### ISSUE TITLE
Exposing messaging API

### ISSUE THREAD

**Issue by jooray** [ACINQ/eclair#1005]
It would be very useful to expose messaging and communication interface through an API. There are many decentralised finance applications built on top of the Lightning Network that would greatly benefit if nodes could exchange other messages than direct payment messages, for example negotiating settlements and parameters of various payment products. Since for communication all that is really needed is node pubkey, communicating using a different layer seems redundant and not very effective.

I propose creating a simple sendMessage, subscribeMessages (for websocket) with encryption and signature verification. This would greatly improve usability of lightning network besides of simple payment use-case.

**Comment by t-bast** [comment]
While I understand the will to re-use the existing peer-to-peer components, this would add a very wide attack surface to nodes. This is one of the reasons bitcoind doesn't offer those capabilities either.
This is a recurring request, but I think we're not ready to invest time into this right now (but maybe in the future that will change).

You can still achieve what you want by using our plugin system to enrich your eclair node, or using our `Peer` components as a library in a separate application.
