### ISSUE TITLE
[API] Get deposit address

### ISSUE THREAD

**Issue by NicolasDorier** [ACINQ/eclair#1006]
The new API does not have a call to get a new deposit address.
This mean that if our client app need this, we need to pass bitcoind parameters to it while eclair already know all of it. Can you add this?

We need this for [btcpay integration](https://github.com/btcpayserver/BTCPayServer.Lightning/) that @Kukks  is working on.

**Comment by t-bast** [comment]
@NicolasDorier @Kukks I think you discussed that with @araspitzu in other threads.
Has this been fixed?

**Comment by NicolasDorier** [comment]
Not really. Not a blocker, but still a pain in the ass to connect to eclair as we need 2 credentials set instead of one.

**Comment by t-bast** [comment]
What you'd need is for us to proxy to the `getnewaddr` bitcoind RPC?
Is it restricted to that API or do you in fact need most of the bitcoind APIs?

**Comment by NicolasDorier** [comment]
@t-bast limited to `getnewaddr`
