### ISSUE TITLE
Can't connect to any Tor node.

### ISSUE THREAD

**Issue by viaj3ro** [ACINQ/eclair#1007]
I can't connect to any Tor node (eclair 0.3, win7 64bit)

If I have an existing channel but the node operator switches over to tor, the channel goes offline and can't be brought back online again.

Is there something I can do or any known issue?

**Comment by pm47** [comment]
You can't connect to a tor node if you don't have tor enabled. See the [readme](https://github.com/ACINQ/eclair/blob/master/TOR.md).
