### ISSUE TITLE
No .exe in release

### ISSUE THREAD

**Issue by InternetofTrust** [ACINQ/eclair#1017]
No .exe in release. If the idea is to make this user friendly for average users this is not helping. Not every one is going to compile a .jar in a command line. C'mon guys!

**Comment by sstone** [comment]
You don't need to compile anything, the JAR files that we provide are directly usable on all environments with `java -jar xxxx.jar`. Windows was the exception here, now packaging and running eclair is consistent across all environments.
If you have specific questions and/or issues please contact us on 

Packaging and using Eclair is now consistent across all environments (Windows was the exception here).
If you have specific questions/issues you can ask on https://gitter.im/ACINQ/eclair.

**Comment by InternetofTrust** [comment]
What if I don't want to install a Java environment on my server and have more security holes to worry about? How do I explain to a regular user what an environment with java -jar xxxx.jar is and how to update? This is going to kill a lot of users who are used to GUI installations and updates.

**Comment by sstone** [comment]
> What if I don't want to install a Java environment on my server ...

You MUST install java to run eclair. The exe was just packaging it for you, but it was not a "real" (i.e. native) executable. You've always been running `java -jar xxx`, it was just hidden for Windows users.

**Comment by t-bast** [comment]
If you're really interested in securing your servers, you will have to avoid GUIs anyway...

I suggest having a look at unikernels if you want to go down the server security rabbit hole, but in that case your only chance of running a lightning node as of today would probably be to get the c-lightning source code and adapt it to be able to compile to a unikernel backend.

If you have time to get this to work feel free to share, it would be a really cool project for the lightning community!

**Comment by wdey** [comment]
After all, see https://github.com/ACINQ/eclair/issues/1024
Anyone successful in creating a .exe ? by means of "java -jar xxxx.jar" ??
