### ISSUE TITLE
maxHtlcValueInFlightMsat being parsed as signed long

### ISSUE THREAD

**Issue by cdecker** [ACINQ/eclair#103]
According to the specification, `max_htlc_value_in_flight_msat` is an unsigned 8 byte integer. While testing against c-Lightning, which sets that value to 0xFFFFFFFFFFFFFFFF, eclair parses this as -1, i.e., as a signed int64. This currently kills the opening of a channel unless the other end is manually set to a lower limit.

**Comment by Christewart** [comment]
If ACINQ is interested in types to represent C number types please check out this: https://github.com/bitcoin-s/bitcoin-s-core/blob/master/src/main/scala/org/bitcoins/core/number/NumberType.scala

Hopefully that can help avoid things like this in the future

**Comment by pm47** [comment]
Thanks @Christewart, we'll take a look at it!

We were aware of this issue and have been kicking the can down the road until now...
