### ISSUE TITLE
Double deposit amount appears in wallet 

### ISSUE THREAD

**Issue by sticker592** [ACINQ/eclair#1039]
I deposited .0015 btc and .003 bitcoin is displayed in the wallet. After half an hour the transaction still shows as pending with 0 confirmations despite having 3 confirmations on the block chain. 
When I open a channel it offers to subtract the fee from .003 so I assume the transaction will fail.
version 0.4.6, I just activated the logs so there are none to include. 
After wasting fees to send money out and back into the wallet, the total amount displayed was corrected.

**Comment by pm47** [comment]
Should probably have tried "reset wallet cache".

NB: [Eclair Mobile has its own github repo](https://github.com/ACINQ/eclair-mobile), this is for Eclair desktop/server.
