### ISSUE TITLE
Recommend JDK 11 isn't available anymore from jdk.java.net

### ISSUE THREAD

**Issue by 0xB10C** [ACINQ/eclair#1049]
The README in line 61 (https://github.com/ACINQ/eclair/blame/master/README.md#61) recommends to use OpenJDK 11.

> To run Eclair, you first need to install Java, we recommend that you use OpenJDK 11.

However the linked jdk.java.net site says:

> The JDK 11 Early Access Program has concluded. Please visit Java SE Downloads for production ready builds.
>
> Older releases, which do not include the most up to date security vulnerability fixes and are no longer recommended for use in production, remain available in the OpenJDK Archive.

**Comment by mautematico** [comment]
https://jdk.java.net/archive/

**Comment by sstone** [comment]
Eclair is written in Scala, which constrains which JDK version users should install. Scala/JDK compatibility is better since JDK11, and is better documented now.  
Eclair is now compatible with JDK17 (since version 0.8.0), and will run on JDK21 once we upgrade to Scala 2.13.12.
