### ISSUE TITLE
Include `feesPaid` in `GetSentInfo` output

### ISSUE THREAD

**Issue by btcontract** [ACINQ/eclair#1060]
**Issue**
Currently when successful outgoing payment is announced via websocket as `PaymentSent` it has `feesPaid` field, but when it is obtained via `GetSentInfo` API call there is no `feesPaid` in a returned list of payment attempts.

**Expected behavior**
`feesPaid` should also be present in `GetSentInfo` output.

**Comment by t-bast** [comment]
Closed by #1130
