### ISSUE TITLE
Remove incorrect_payment_amount error type

### ISSUE THREAD

**Issue by s-tikhomirov** [ACINQ/eclair#1076]
BOLT 4 defines the error types ([failure messages](https://github.com/lightningnetwork/lightning-rfc/blob/master/04-onion-routing.md#failure-messages)) and contains a note (probably referring to [this paper](https://eprint.iacr.org/2019/328)):

> Originally PERM|16 (incorrect_payment_amount) was used to differentiate incorrect final amount from unknown payment hash. Sadly, sending this response allows for probing attacks whereby a node which receives an HTLC for forwarding can check guesses as to its final destination by sending payments with the same hash but much lower values to potential destinations and check the response.

Eclair does not actually use the `incorrect_payment_amount` error code (as far as I can tell). The behavior which enables probing attacks has been changed in [this commit](https://github.com/ACINQ/eclair/commit/ccdd42305e46153783b9074c67545e03daed932b). But the `incorrect_payment_amount` error type remains defined in `FailureMessage.scala` ([line 53](https://github.com/ACINQ/eclair/blob/master/eclair-core/src/main/scala/fr/acinq/eclair/wire/FailureMessage.scala#L53)).

Would it make sense to remove this error type altogether, as they [did](https://github.com/ElementsProject/lightning/pull/2519) in c-lightning?

**Comment by t-bast** [comment]
Thanks for spotting this!

We are waiting for this PR (https://github.com/lightningnetwork/lightning-rfc/pull/608) to be merged in the spec, at which point we will do a clean-up pass on the errors in `FailureMessage.scala`.

I'm not sure we can remove it entirely like c-lightning did, depending on how it's removed it might break backwards-compatibility with older nodes.

**Comment by t-bast** [comment]
Closing this as we do need to keep the type defined for backwards-compatibility (eclair will not use this error code but we allow old nodes to send it).
