### ISSUE TITLE
Building eclair with graalvm native image

### ISSUE THREAD

**Issue by Christewart** [ACINQ/eclair#1085]
Hi all,

Graalvm has a ahead of time compiler (AOTC) that allows you to create native binaries for jars. I would like to attempt to use this for bitcoin-s and the testing suites we have to reduce test time. I've attempted to build the eclair-node with the graalvm native image and am running into a few issues. I thought I would file an issue here asking for official support for this

Here is my branch

https://github.com/Christewart/eclair/tree/native-image-build

Here is some issues i have open o the graal repo https://github.com/oracle/graal/issues/1513

This is some what unrelated, but there is _allegedly_ support for compiling native iOS code with graal as well. https://gluonhq.com/java-on-ios-for-real/

**Comment by sstone** [comment]
Hi Chris,
Thanks, It looks interesting. I suspect that your main pb is startup time, and it may be caused by capsule which we use to package eclair (I guess it may also cause issue with GraalVM ?). I guess that packaging the app as a traditional fat jar (which has its share of issues) or as a directory with a `lib` subdir that includes all dependencies could make it start much quicker too

**Comment by Christewart** [comment]
Graal compiles a native binary, which circumvents the JVM startup time together. 

You can read this blog post for an example of how the native image reduced netty startup time by 90%. This does come at a cost for production applications, but  for testing applications it seems like a no brainer to me.

https://medium.com/graalvm/instant-netty-startup-using-graalvm-native-image-generation-ed6f14ff7692

Another project adopting it is Spring, which is a notoriously heavy weight project: 

https://github.com/spring-projects/spring-framework/wiki/GraalVM-native-image-support#graalvm

The payoff: 


> GraalVM native image allows to compile Spring applications to native executable with very fast startup (less than 100ms) with low memory consumption (usually 5x less than its regular JVM equivalent) at the price of lower throughput and various limitations. Reflection and dynamic proxies are supported but need to be configured manually or via dedicated support. It also allows to produce small container images.

Again, it isn't a silver bullet. But it would be a great option to have IMO.
