### ISSUE TITLE
"Message not delivered" probably causing flakiness in LN payments between eclair nodes

### ISSUE THREAD

**Issue by darwin** [ACINQ/eclair#1098]
In [simverse](https://github.com/darwin/simverse) I have a test suite which exercises simple LN payment in these scenarios:
- bitcoind+2 eclair nodes (direct payment alice-bob)
- bitcoind+3 eclair nodes (indirect payment alice-charlie-bob)

The second scenario started to be flaky (failing most of the time). I noticed that when this happens there is logged a message like "Message ... from Actor[...] to Actor[...] was not delivered..."

```
alice_1      | 2019-08-16 13:27:40,990 INFO  f.a.eclair.router.Router  - finding a route 027a9b56fc656011601cc1a64740dcc2a953e18ca998c3f473b113a5dcae8c1404->03b95bf9ad11766b9859e24ac8b7eb8f23a8d5c45c887e31718eaa0f564be9ca2d with assistedChannels= ignoreNodes= ignoreChannels= excludedChannels=
alice_1      | 2019-08-16 13:27:40,993 INFO  f.a.eclair.router.Router  - finding a route with randomize=true params=RouteParams(true,MilliSatoshi(21000),0.03,6,1008,Some(WeightRatios(0.15,0.35,0.5)))
alice_1      | 2019-08-16 13:27:41,075 INFO  a.a.DeadLetterActorRef  - Message [fr.acinq.eclair.payment.PaymentLifecycle$PaymentFailed] from Actor[akka://eclair-node/user/$m/payment-initiator/$a#528843153] to Actor[akka://eclair-node/deadLetters] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
```

This used to work and the breakage is [quite recent](https://github.com/darwin/simverse/commits/health-check) (in last 10 days). I wanted to bisect for exact commit causing this but the situation got complicated a bit and I wasn't able to identify it precisely due to other changes like 4929febbd11ebad6ae20caed4b161db44dfd263d).

Any hints what could be causing this and potential fixed would be appreciated. Thanks.

**Comment by darwin** [comment]
With git bisect I was able to pin-point the commit causing this to 4929febbd11ebad6ae20caed4b161db44dfd263d (this is expected because that was the only commit in last ~11 days).

The trick on my side was to make bisect work across that change and keep backward compatibility:
https://github.com/darwin/simverse/commit/349b0cb75a82890f284aedcf8f6632bfd19aa4f2

**Comment by sstone** [comment]
Our automated integration tests (which are run on every commit on master) include indirect payment tests, this is also something we test manually on lot and we have not seen this problem. Can you please provide more info, ideally a description of what the test does (for example setup an A- > B ->C network) and full logs for A B and C ? 
Also, can you run the same test manually i.e step by step using our API  (it may have been cause by an API change) ?

**Comment by darwin** [comment]
I understand that my description is not good enough for you to reproduce it. I posted it more as a warning that something fishy might be going on in 4929febbd11ebad6ae20caed4b161db44dfd263d.

Example logs of A, B and C can be seen here[1] (I tail last 300 lines of each docker container). 

Please note the wall of stack traces above[1]. That is from polling of your `findroutetonode` api call to detect route availability[3][4] before I try to make the payment. 

I was able to reproduce similar situation on my dev machine manually executing the same commands as the test would, but not waiting for `findroutetonode`, if I do it fast enough, then I get failed status which is probably expected:

```
> alice getsentinfo --id=cd31f01e-39d3-4bd7-abb1-209d057efb78
[
  {
    "id": "cd31f01e-39d3-4bd7-abb1-209d057efb78",
    "paymentHash": "84c1fb0631358290b75c9254d77018da6ed3d909969ccefbcfbbff418e367dd3",
    "amount": 1000000000,
    "createdAt": 1566342171854,
    "completedAt": 1566342171891,
    "status": "FAILED"
  }
]
```

Just a wild guess, maybe there is a non-zero time window between `findroutetonode` reporting success but `payinvoice` failing?

This looks like a timing issue. I will investigate this further on my side by adding more diagnostics printing into my failing test.

[1] https://travis-ci.org/darwin/simverse/builds/574216651#L10601
[2] https://travis-ci.org/darwin/simverse/builds/574216651#L10280
[3] https://github.com/darwin/simverse/blob/master/toolbox/_toolbox_lib.sh#L225-L233
[4] https://github.com/darwin/simverse/blob/master/toolbox/get_route#L26

**Comment by araspitzu** [comment]
Maybe it's irrelevant for your test but when you use `findroutetonode` you can't be sure the payment will go through. That API is only performing path-finding on the local view of the network, the response is a route that can potentially accommodate the payment but there is no guarantee it will.

**Comment by darwin** [comment]
Ok. My approach is fragile. But I don't know a good way how to effectively wait for LN network to be ready to successfully execute my test payment.

Anyways. The test suite started to passing again. At least I have new diagnostics code in place for case this happened again in the future. Also I bumped maxAttempts to 100.

Thanks for all your input. Closing.
