### ISSUE TITLE
no secp256k1 in java.library.path

### ISSUE THREAD

**Issue by deafboy** [ACINQ/eclair#110]
I got the following error in the console while running eclair-node_2.11-0.2-alpha4-c85823f-capsule-fat.jar under Ubuntu 16.04:

> UnsatisfiedLinkError: java.lang.UnsatisfiedLinkError: no secp256k1 in java.library.path

Logfile says:

> 2017-07-21 16:22:44,302 INFO  akka.event.slf4j.Slf4jLogger  - Slf4jLogger started
> 2017-07-21 16:22:44,318 INFO  fr.acinq.eclair.Setup  - hello!
> 2017-07-21 16:22:44,318 INFO  fr.acinq.eclair.Setup  - version=0.2-alpha4 commit=c85823f5b462c2e57070e16d384d8ecac995c4cf
> 2017-07-21 16:22:44,323 INFO  fr.acinq.eclair.Setup  - initializing secure random generator
> 2017-07-21 16:22:45,833 WARN  akka.actor.ActorSystemImpl akka.actor.ActorSystemImpl(default) - Illegal response header: Illegal 'date' header: Invalid input 'P', expected IMF-fixdate, asctime-date or '0' (line 1, column 1): Pi, 21 júl 2017 14:22:45 GMT
> ^
> 2017-07-21 16:22:45,912 INFO  fr.acinq.eclair.Setup  - using chain=test chainHash=000000000933ea01ad0ee984209779baaec3ced90fa3f408719526f8d77f4943
> 2017-07-21 16:22:46,027 WARN  akka.actor.ActorSystemImpl akka.actor.ActorSystemImpl(default) - Illegal response header: Illegal 'date' header: Invalid input 'P', expected IMF-fixdate, asctime-date or '0' (line 1, column 1): Pi, 21 júl 2017 14:22:46 GMT
> ^
> 2017-07-21 16:22:46,029 INFO  fr.acinq.eclair.Setup  - finaladdress=mfiwi3ixwRQrDyntBnx4h7JH7jeJaVrmhW
> 2017-07-21 16:22:46,362 INFO  fr.acinq.eclair.Setup  - nodeid=031d34ff8985eea856262506976e9d5c069de06dd901f8d97157787c202d490171 alias=eclair
> 2017-07-21 16:22:46,370 INFO  fr.acinq.eclair.Setup  - initial feeratePerKw=10000
> 2017-07-21 16:22:46,402 INFO  fr.acinq.eclair.router.Router akka://default/user/$f/router - current status channels=0 nodes=0 updates=0
> 2017-07-21 16:22:46,404 INFO  fr.acinq.eclair.io.Server akka://default/user/$i/server - bound on /0:0:0:0:0:0:0:0:9735
> 2017-07-21 16:22:47,427 INFO  f.a.eclair.blockchain.zmq.ZMQActor akka://default/user/$a/zmq - connected to tcp://127.0.0.1:29000
> 
> 

No gui is visible at all.

**Comment by sstone** [comment]
eclair is based on our bitcoin-lib library, which will use libsecp256k1 if it can be loaded, and fall back to spongy-castle if not, so this warning is normal, it just means that libsecp256k1 was not found. 

eclair-node is a headless node meant to be used on servers through its API and does not include a gui, for a nice desktop GUI you can use eclair-node-javafx instead.

Thanks!

**Comment by pm47** [comment]
@deafboy I have attached the eclair-node-javafx jar to the [last release](https://github.com/ACINQ/eclair/releases/tag/v0.2-alpha4).

**Comment by deafboy** [comment]
Thanks for an explanation and for publishing the jfx release!
Since I use openjdk, I built the jfx jar myself and it's working fine.

**Comment by pm47** [comment]
Reopening the issue, this log output will be fixed in a later version of bitcoin-lib (see ACINQ/bitcoin-lib/pull/10), and dependency then needs to be updated in eclair.
