### ISSUE TITLE
Method not found while struggling with params in RPC JSON

### ISSUE THREAD

**Issue by rem0g** [ACINQ/eclair#111]
I'm really excited to test LN with Eclair, I've already setup channel between eclair wallet and eclair node. But when trying to create an request for payment via JSON RPC because i'm doing this everything via terminal; i'm getting "Method not found" as return.

I'm using the following commands: 
curl --data-binary '{"jsonrpc":"2.0", "id": "0", "method": "receive", "params": ["5000"]}'\
 -H 'content-type:application/json'\
 http://localhost:8081

I tried ["5000"], [{"5000"}], [{"amountMsat","5000"}], and so on. Still getting the same "method not found" message.

Hope the issue is clear and thank you for your time already.

**Comment by pm47** [comment]
Try with a description, like this:
```shell
curl localhost:8080 -X POST -H "Content-Type: application/json" -d '{  "method": "receive", "params" : [ 5000000, "a coffee" ] }'
```
Note that amount is in millisatoshis

**Comment by rem0g** [comment]
Thank you very much, it works now and the payment is done with eclair mobile wallet. 

Maybe the documentation should be updated with "description" as extra param, because there is only the amount as param described.

**Comment by pm47** [comment]
Yup that's a bug! Feel free to submit a pull request 😛
