### ISSUE TITLE
Eclair-cli outdated

### ISSUE THREAD

**Issue by rem0g** [ACINQ/eclair#112]
I noticed the Eclair-CLI is outdated, for example the node doesnt accept POST header anymore and requires only application/json content-type. 

The methods should be adjusted too. 

https://github.com/ACINQ/eclair/blob/master/eclair-core/eclair-cli

**Comment by pm47** [comment]
You are right, `eclair-cli` definitely needs a serious refreshing!

I am working on it currently, [here is something you can use](https://gist.github.com/pm47/3fd94c4c34391bad8457a419fbb27c56) in the meantime (very rough still).

**Comment by rem0g** [comment]
Looks great! I'll definitely use that!

**Comment by pm47** [comment]
Note that the script needs `jq`, you shouldn't have no trouble installing it from your favorite package manager
