### ISSUE TITLE
Expand certain API calls to also accept lists

### ISSUE THREAD

**Issue by STAWKEYE** [ACINQ/eclair#1136]
Specifically requesting that API call "UpdateRelayFee" optionally accept a list of channel ID's instead of being limited to a single channelID. (Much like SendToRoute accepts a list of nodeIDs)

It would be nice to update every channel you have at once if you decide to increase/decrease your fees in the future. There may be other API calls that could benefit from an optional list input as well - I haven't run through them all.

**Comment by pvyhnal-generalbytes** [comment]
For us it would be useful to call GetReceivedInfo with a list of invoices / payment hashes to check the status of all pending invoices at one call. (or is there a better way of being notified about incoming payments?)

**Comment by t-bast** [comment]
I believe you can use the websocket to be notified of every payment event. Would that solution potentially work for you?

**Comment by t-bast** [comment]
Fixed by #1440
