### ISSUE TITLE
Android Eclair Wallet wrecked by a malformed incoming transaction

### ISSUE THREAD

**Issue by artlav** [ACINQ/eclair#116]
Eclair Wallet, version 0.1.4. 

I sent some coins to the P2SH wallet it showed, and sent the change to the same hash but formatted as P2PKH (totally not a bug in my own code. totally...). This got the wallet confused - it counted both outputs as being sent to it, however the second one is unspendable. TXID in question: 72f7106927e1d38cbdc8ffd7e9c2b3ef4a28fb4672eafad0dddf6ac5cd0965d7

The bad part is that now it can't send anything anywhere or open a channel - apparently all transactions being sent out by the wallet try to use the malformed output, and the "open in explorer": returns a "transaction not found" error.

While this is a rather unnatural thing to happen in regular use, it does present a critical attack vector where someone can disable your wallet by a malformed transaction, and with no way to recover your private keys (at least for now only, i hope) this means you are locked out of your funds.

**Comment by pm47** [comment]
Interesting! So you are saying there might be a bug in the hastily modified segwit-enabled version of bitcoinj that we are using as onchain wallet? How surprising!

@sstone is currently on vacation but I'll ask him to take a look at it when he comes back

Cheers

**Comment by sstone** [comment]
It is indeed a bug in my bitcoinj mods that has been identified and fixed, a updated app will be released soon (I'll update this issue). Thanks!

**Comment by dpad85** [comment]
Fixed in the 0.1.5 release of eclair wallet.
