### ISSUE TITLE
Should eclair exit on SQL Disk errors?

### ISSUE THREAD

**Issue by n1bor** [ACINQ/eclair#1171]
Got a disk write error. But eclair just carried on. I think it would be more useful to exit. As this is a dangerous state to be in - and ensures any monitoring picks up the issue.

Agree?

 org.sqlite.SQLiteException: [SQLITE_IOERR]  Some kind of disk I/O error occurred (disk I/O error)
        at org.sqlite.core.DB.newSQLException(DB.java:941)
        at org.sqlite.core.DB.newSQLException(DB.java:953)
        at org.sqlite.core.DB.execute(DB.java:857)
        at org.sqlite.core.DB.executeUpdate(DB.java:895)
        at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:102)
        at fr.acinq.eclair.db.sqlite.SqliteChannelsDb$$anonfun$removeChannel$1.apply(SqliteChannelsDb.scala:75)
        at fr.acinq.eclair.db.sqlite.SqliteChannelsDb$$anonfun$removeChannel$1.apply(SqliteChannelsDb.scala:73)
        at fr.acinq.eclair.db.sqlite.SqliteUtils$.using(SqliteUtils.scala:38)
        at fr.acinq.eclair.db.sqlite.SqliteChannelsDb.removeChannel(SqliteChannelsDb.scala:73)
        at fr.acinq.eclair.channel.Channel$$anonfun$19.applyOrElse(Channel.scala:1381)
        at fr.acinq.eclair.channel.Channel$$anonfun$19.applyOrElse(Channel.scala:1376)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)

**Comment by pm47** [comment]
Can you provide more logs right before and after this error?

**Comment by n1bor** [comment]
Nothing after the message..
The below was before.

And repeated a LOT before I realised there was an issue.
File is on EFS on AWS and a reboot fixed it.

Although my node is now in a mess - as my eclair balance is much higher than it should be!
So need to trawl through the channels to see what is going on.

Other odd thing was after the restart I had over 1m requests in the queue to bitcoind which seemed odd.


17:00:07.020 INFO  akka://eclair-node/user/$k/switchboard/peer-022565c24c0498f18f0688f57b5985d2f0c20ce2efc9a99d38e888d6f13016063d/$a fr.acinq.eclair.channel.Channel - deleting database record for channelId=1df45ac1bf725217acdd26f57c48429ae8f2a98469f98879c0c9c65c68b39356
17:00:07.034 ERROR akka://eclair-node/user/$k/switchboard/peer-022565c24c0498f18f0688f57b5985d2f0c20ce2efc9a99d38e888d6f13016063d/$a fr.acinq.eclair.channel.Channel - [SQLITE_IOERR]  Some kind of disk I/O error occurred (disk I/O error) while processing msg=String in state=CLOSED

**Comment by n1bor** [comment]
Was a number of channels that I guess are now in a mess:

akka://eclair-node/user/$k/switchboard/peer-022565c24c0498f18f0688f57b5985d2f0c20ce2efc9a99d38e888d6f13016063d/$a
akka://eclair-node/user/$k/switchboard/peer-02513e59cd20bd31bd4c47f6af1be5760c26f6fa9446f648c7a73e17ff7ab6d32f/$a
akka://eclair-node/user/$k/switchboard/peer-025f0a47fb2614dddaeda50cf0f18bf08811139a7647bcd5c2ccef1ffb2ad98224/$a
akka://eclair-node/user/$k/switchboard/peer-02913d84886059292845f870c5229f103dd8d7d71d7e9fc6fd52f75a40486d2187/$b
akka://eclair-node/user/$k/switchboard/peer-0295c903b3e9d22b968b9482fd71e60186f2591d582c3f86e988a8ffce57f97684/$a
akka://eclair-node/user/$k/switchboard/peer-02b2b65a42a4cf1d14bf4860018e8ff83ae25e942e11929b6b1d543006d2c0d5d7/$a

akka://eclair-node/user/$k/switchboard/peer-02e4a1968460bcc48b26fc2ac4ed16a6e156360a639e5d1b2737bf72cab41e9334/$a
akka://eclair-node/user/$k/switchboard/peer-0322ea550e3949e31e07790bb97648e266326d0cb533dc2504c0d098377da6c410/$b
akka://eclair-node/user/$k/switchboard/peer-03cf8a476d7f99f47962e085178e17f4b19f452f11902f415abc367a4834af53ac/$a
akka://eclair-node/user/$k/switchboard/peer-03ee22ea9e228157e9d03700c37e968791a5b2b26f20f3110716bc2161604f88cf/$a

**Comment by t-bast** [comment]
Please send us whatever data you're able to collect during your investigation, this is definitely something we need to handle more gracefully.
The channels should go offline when we receive unexpected exceptions such as this one (so I hope your channels state isn't too bad), but we probably need to test this E2E more thoroughly.
We are also adding a monitoring infrastructure which should make it easy to define alerts when channels are going offline.

**Comment by n1bor** [comment]
Arh - I have 82 channels in ERR_INFORMATION_LEAK.
looks like when I restarted server SQLITE has rolled back a long way to before the error or something...

As in grafana it thinks my capacity suddenly increased...

I have backups of eclair.sql every 15mins - so I just need to trawl through them to understand what happened.

To get a channel into ERR_INFORMATION_LEAK I thought I just had to have the wrong commitment id. So if I transmitted the commitment tx it would not be the latest but and old one?

**Comment by n1bor** [comment]
1st one in ERR_INFORMATION_LEAK I can see was forced closed by the other side and I have the money back in my btc wallet. And looking in usablebalances this counts ERR_INFORMATION_LEAK as canSend - which is not actually the case in this situation.

Do you have a tool to dump the local_channels table to JSON? If not guess I will be writing one!

Also I would think in this situation eclair should have seen the spend - as must have move the output to the btc wallet but has not closed the channel?

I need to look at a pre-restart wallet to see if the restart caused the issues or was broken before then...

**Comment by t-bast** [comment]
> Do you have a tool to dump the local_channels table to JSON? If not guess I will be writing one!

I don't think we do...but you can easily use the eclair code (or even the test code) to read and extract what you want from those tables.

> Also I would think in this situation eclair should have seen the spend

Yes we should have detected it, but depending on how bad information was lost in the DB it might interfere :(

**Comment by pm47** [comment]
> File is on EFS on AWS

So your `eclair.sqlite` was on a network file system? I'm not sure what consistency guarantees NFS offers, but it seems like asking for trouble for a file that is written to constantly. If you had a backup every 15 min (which is good practice), why not keep `eclair.sqlite` locally? That would be much more reliable.

> Do you have a tool to dump the local_channels table to JSON? If not guess I will be writing one!

You can use the `channels` API call, it pretty much does that.

Did you have any channel open with our node? It would be interesting to see what it looked like from our side.

**Comment by n1bor** [comment]
I have a lot of channels stuck in closing.
I think what happened was that they got closed as the database started having issues.
But we could not write the localCommitPublished.claimMainDelayedOutputTx to the db. But was published fine.
Now when I have restarted there is a slightly different tx in the db to the one I can see in the blockchain. Only difference is the fee.
But obviously these are now stuck in CLOSING forever.

**Comment by n1bor** [comment]
Definitely think that Eclair should exit on these errors rather than carry on without writing data to the database.
e.g. if disk filled up, or filesystem became read-only or disk controller died.

At least if eclair dies only one channel is missing data rather than a large number.
Also more likely to have monitoring of the running process than sql error deep in a log file.

**Comment by pm47** [comment]
> I have a lot of channels stuck in closing.
I think what happened was that they got closed as the database started having issues.
But we could not write the localCommitPublished.claimMainDelayedOutputTx to the db. But was published fine.
Now when I have restarted there is a slightly different tx in the db to the one I can see in the blockchain. Only difference is the fee.
But obviously these are now stuck in CLOSING forever.

Can you provide logs and channel data (preferably filtered for a single channel if possible).

> Definitely think that Eclair should exit on these errors rather than carry on without writing data to the database.

Maybe, but that's a tradeoff. What if your counterparty tries to cheat while you are offline?

**Comment by n1bor** [comment]
Sorry - I lost all the useful logs. But seems that Eclair just could not write and I think it closed most of the channels but really not sure (other than an I not missing to much btc other than expected fees etc..).

But think if there are disk errors on sql then eclair should go into some sort of watch only mode? As at the moment it will relay - but not save the next commitment id to the database. So on startup danger of publishing old commitment - which is actually worse than going off-line as you are almost certain to either lose funds or upset someone.

In the end I have closed everything and started again - as as channels came online they kept going to ERR_INFORMATION_LEAK state - that I assume means the peer has a later commitment?

**Comment by t-bast** [comment]
Since there are advantages and drawbacks to both options, I think a better solution is to build good enough alerting on your node. Then you can choose how to act on that alerting.

I'm closing this issue as it's become stale.
