### ISSUE TITLE
Eclair wallet does not recognize mainnet addresses as mainnet

### ISSUE THREAD

**Issue by artlav** [ACINQ/eclair#118]
If you try to send money from the testnet Eclair wallet to a mainnet, it would happily accept it and generate a transaction using the hash of that address, essentially sending coins to the testnet equivalent of the mainnet address.

This have caused some confusion on at least one occasion: https://www.reddit.com/r/Bitcoin/comments/6pnbwc/im_using_the_lighning_network_enabled_eclair/dkqni2z/

In general, it's a good idea to check for such things - many people won't be able to recognize what happened and how to fix it.

**Comment by dpad85** [comment]
Fixed in the 0.1.5 release of eclair wallet. Thanks!
