### ISSUE TITLE
Type fee rates info

### ISSUE THREAD

**Issue by pm47** [ACINQ/eclair#1188]
Fee rates are currently implicitly calculated in satoshis (see files below), they should probably be typed.

https://github.com/ACINQ/eclair/blob/fbdb369e822113cfb6c1a87cc9fa464854e7f066/eclair-core/src/main/scala/fr/acinq/eclair/package.scala#L66-L111

https://github.com/ACINQ/eclair/blob/fbdb369e822113cfb6c1a87cc9fa464854e7f066/eclair-core/src/main/scala/fr/acinq/eclair/blockchain/fee/FeeEstimator.scala#L19-L25

**Comment by DariusParvin** [comment]
Note that there's a typo in the comments above ```val MinimumFeeratePerKw = 253```:
It should be ```(3 + weight) / 4```, 
not ```(3 * weight) / 4```
