### ISSUE TITLE
Strange name and logic for `ChannelsDb.addOrUpdateHtlcInfo`

### ISSUE THREAD

**Issue by btcontract** [ACINQ/eclair#1233]
there's `INSERT OR IGNORE` in https://github.com/ACINQ/eclair/blob/master/eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteChannelsDb.scala#L105 but `htlc_infos` table has no unique fields so it has no effect.

As far as I understand we need to allow duplicates in `(channelId, commitmentNumber)` tuple because `commitmentNumber` may be local or remote? In that case method seems to be doing things right but `IGNORE` is superfluous.

Also `addOrUpdateHtlcInfo` seems to be a misleading method name because it adds or ignores (only adds in practice).

**Comment by btcontract** [comment]
Also while at it, I don't understand why a foreign key is needed in `htlc_infos` table. Perhaps it's a remnant of times when channel was actually getting deleted from db instead of `SET closed=1` so cascade delete could be triggered?

**Comment by t-bast** [comment]
You're totally right, this name of the method was misleading, I'm fixing that.
Thanks for looking at this code and reporting this ;)
Regarding the foreign key I think it doesn't hurt to keep it, you don't want to be adding HTLCs before you added the channel...
