### ISSUE TITLE
Confused about eclair.conf

### ISSUE THREAD

**Issue by KevinKelbie** [ACINQ/eclair#125]
I have a Bitcoin node setup and an Eclair LN node but I cannot get another one to run. I know I need to change the ports in eclair.conf but I cannot seem to find that files. Inside the directory I am running the eclair node from only contains 

- db file
- eclair.log
- seed.dat

Am I looking in the wrong place?

Edit: I am on OSX 10.10.5

**Comment by pm47** [comment]
You are looking at the right place, but `eclair.conf` is not created by default, you need to do it yourself. Bitcoin core has the same behavior with `bitcoin.conf`.

You will want to set eg `eclair.server.port=9731` and `eclair.api.port=8081`. All default values are listed [here](https://github.com/ACINQ/eclair/blob/master/eclair-core/src/main/resources/reference.conf).

**Comment by KevinKelbie** [comment]
Thanks! I just re-read the README and somehow completely missed the create a file named eclair.conf in eclair's home directory "create a file named eclair.conf in eclair's home directory" sorry about that.

Great project you guys are working on btw. Good work!

**Comment by pm47** [comment]
Hmm, but you are right, there is nothing about creating the file, and that should be made explicit! Where did you find that sentence?

**Comment by KevinKelbie** [comment]
https://github.com/ACINQ/eclair/blob/v0.2-alpha1/README.md#configuring-eclair
in **Configuring Eclair**

> If you want to change configuration parameters, create a file named eclair.conf in eclair's home directory.

maybe it shouldn't be `home directory` because home implies that there is only one (in my opinion).

**Comment by pm47** [comment]
Ok, this was in an older version (we currently are at [0.2-alpha4](https://github.com/ACINQ/eclair/releases)) and somehow it has been lost in the battle.

Please leave the issue open, we need to fix this.
