### ISSUE TITLE
Error messages ought to be selectable for copy/paste

### ISSUE THREAD

**Issue by dscotese** [ACINQ/eclair#1255]
![image](https://user-images.githubusercontent.com/1767796/70865551-c2b98800-1f13-11ea-84e6-5bbb9aae8f78.png)

When Eclair pops up a message box like this one, it should be possible for the user to select the text of the message and copy it.  This was not the case with the message above.  If this is an aspect of the underlying Java environment, please let me know so I can report it as a JVM bug.

The message above was produced with a file called eclair-node-gui-0.3.1-6906ecb.jar on a Windows 10 machine running JDK 11.0.3.0.

**Comment by t-bast** [comment]
Closing this issue as the demo UI has been deprecated in [v0.4](https://github.com/ACINQ/eclair/releases/tag/v0.4).
PRs to improve the demo UI are still accepted, but we won't track any feature requests.
