### ISSUE TITLE
No prompt to ask which channel to use for payment

### ISSUE THREAD

**Issue by artiomchi** [ACINQ/eclair#130]
I set up Eclair on my phone, did a test transaction, and that works well so far. I then created a second channel, and made a second transaction. 

What I noticed was that at no point was I asked which of the two active channels do I want to use. It just automatically assumed I want to use the last one.

Could the payment screen get a new field asking which channel do I want to use, if multiple are available?

On the and note, I think channel labels could come in handy as well

**Comment by paulperegud** [comment]
It does not make much sense to ask user which channel should be used. If anything this is bad UX. 

It will be much better if channels were chosen automatically according to some heuristic (e.g. use channel that creates shorter path, pick channel in such way that it will balance out funds, etc).

**Comment by artiomchi** [comment]
Hmm.. I'm not familiar with Lightning yet, as I just tried it, so maybe I'm understanding it wrong..

What if someone wanted to keep different transactions separate.. Or manage several channels for different kind of spending (for any reason).. Or is that not really a realistic usecase?

**Comment by paulperegud** [comment]
Channels are building blocks of LN. Channels directly connected to you define maximum amount you can send without receiving and maximum amount you can receive without sending. From point of view of the rest of the network they are there to route other people's payments. By depleting channel you impair both your own ability to use it and network's ability to route payments through your node. I don't think manual management of those channels is desirable. Its both bad UX and bad decision in regards of health of network.

**Comment by pm47** [comment]
Agree with @paulperegud, I don't see the benefit for the user. In fact what we are trying to do is abstract away this kind of technical stuff. You don't get to choose what network links to use when you visit a web page right?

That being said, we will certainly add some custom "constraints" to the route calculation in the future, but it would be more in the likes of : "min x hops" or "max y fee".

**Comment by artiomchi** [comment]
@paulperegud I wouldn't say that's bad UX at all - I'm coming from using various Bitcoin wallets, and when you want to process the payment, the wallet won't just randomly pick a wallet and just take the money from there. It will give you the choice of which wallet to use, either on the payment screen, or by selecting a wallet/address in advance.

The network health is of course a separate issue, and I leave those decisions to the devs. Maybe from that point of view manual channel management is not a great idea.

Then again, from a pure user perspective - to start using Lightning, I have to take some funds from my main (BTC) wallet, and send them to a *channel*, or multiple *channels*. At this point they're no longer in my wallet, so I'm suddenly lacking those funds. So the ability to at least see those channels is crucial imo. Furthermore, if I only opened two 50 mBTC channels, that means I still can't make a 100 mBTC transaction, is that right? So as a regular user, knowing that I have > 100 mBTC in my *channels* doesn't mean I can actually spend them in one go, which would be confusing :) (ofc maybe channels can work in the same way as BTC transactions with multiple in and out channels, in which case this point is less relevant)

Besides, might there not be advanced users out there, who would still want to be able to see/manage the channels themselves? I'm just asking

**Comment by btcontract** [comment]
If I may, this is just too low level. It's like manually choosing which outputs to use when sending a btc tx: some people want it but majority has no idea what utxo even is. Perhaps there is a place for this feature somewhere but not in a consumer oriented mobile wallet.

**Comment by artiomchi** [comment]
Riiight.. I've just seen [this video](https://youtu.be/v2Gz6d-xaVU), which explained how Lightning works in a very simple way.. Now I see why there's no point in picking a sending channel! 

With that in mind, I just have one question to understand how eclair works currently.. The way it was explained in the video, when you open a channel, it's opened between two parties. So who are the parties in eclair? Is eclair backend(?) acting as a second party in the channel?

**Comment by pm47** [comment]
You can open a channel with whoever you want, just provide its URI in the form `nodeid@ip:port`. In eclair wallet (on android), there is also an additionnal 'autoconnect' option which currently defaults to one of our test nodes. When [BOLT 10](https://github.com/lightningnetwork/lightning-rfc/blob/master/10-dns-bootstrap.md) is implemented we will be able to offer a real random connect option.

For that kind of question, next time please use our [gitter](https://gitter.im/ACINQ/eclair), you will get a faster answer and tickets are reserved for bugs.

I am closing this ticket since the initial issue is resolved.

Cheers!
