### ISSUE TITLE
Feature request: Use getzmqnotifications for the ZMQ addresses

### ISSUE THREAD

**Issue by Thoragh** [ACINQ/eclair#1314]
I think it would be nice if eclair used the getzmqnotifications RPC method in bitcoin to get the ZMQ addresses. It would mean users has less things to write in the `eclair.conf` file.

**Comment by t-bast** [comment]
Interesting, that's something that could be tried. This is quite a crucial part of the application so that change would need to be thoroughly tested.
We're open to external contributions if you want to do that!

**Comment by pm47** [comment]
Really like the idea.

**Comment by sstone** [comment]
What are the limitations of using this rpc call ?

- What does it return ? Is it just whatever is configured in bitcoin.conf or is it smarter (as in: don't return something when it there was a zmq error)
- How does it work when the bitcoin node is not on the same machine as the LN node and is accessed through its IP address ?
- How does it work when the bitcoin node is not on the same machine and is accessed with SSH and port forwarding ? (this is a very common setup for testing and afaik the recommended way of accessing remote bitcoin node)

**Comment by t-bast** [comment]
@Thoragh could you help answer sstone's questions?

**Comment by Thoragh** [comment]
>     * What does it return ? Is it just whatever is configured in bitcoin.conf or is it smarter (as in: don't return something when it there was a zmq error)
The rpc will only return something it could successfully bind all addresses. The addresses are returned in the same way they are writen in bitcoin.conf.
>     * How does it work when the bitcoin node is not on the same machine as the LN node and is accessed through its IP address ?
If the the address in bitcoin.conf was set to for example tcp://192.168.0.123:29000 and the machines are in the same network it should work. If 0.0.0.0 was used it will not work.
>     * How does it work when the bitcoin node is not on the same machine and is accessed with SSH and port forwarding ? (this is a very common setup for testing and afaik the recommended way of accessing remote bitcoin node)
If the ports are the same for example `ssh -L 29000:127.0.0.1:29000 user@host` it should work I think.

There are cases where using the rpc call wont work so the current zmqblock and zmqtx config options need to stay. The default fallback should in my opinion be to use the rpc call if the user has not specified the zmq addresses.

**Comment by t-bast** [comment]
What's the status of this?
To be honest I think the additional code required for this is not worth the effort, especially since the fallback needs to stay.

**Comment by t-bast** [comment]
Closing this issue. Since the fallback will always be needed, I don't think this would be that much of an improvement considering the extra code it adds.
