### ISSUE TITLE
Feature request: dedicated fees for balanced, saturated and depleted channels

### ISSUE THREAD

**Issue by viaj3ro** [ACINQ/eclair#1328]
It would be very helpful to have an option to set dedicated fees for channels depending on the available balance.

standard settings could be something like:

saturated (>70%): 0.1%
balanced (30-70%): 0.2%
depleted (<30%): 0.4%

any chance something like this could get implemented?

**Comment by araspitzu** [comment]
It's a nice idea but i'm not sure if it belongs to eclair, it sounds more like a local node policy. Also this could be implemented by an external script although i know this sounds like passing the buck :) , we can check if there is interest in having dynamic fee policies from other users, and this would cover your feature too.

**Comment by viaj3ro** [comment]
well, it would help the network operate more smoothly. if you need to write your own script, almost nobody will do it. If nodes offer a simple solution to set things up via the config and the config comes with reasonable standard settings already, almost everyone will have it and we all have a better lightning experience :)

The numbers I chose in the parent post is a rough estimate of what I consider the minimum fees to operate a routing node in the current environment without losing money.

**Comment by araspitzu** [comment]
Closing this since the feature is now implemented as a plugin by https://github.com/araspitzu/eclair-plugin-dynamicfees
