### ISSUE TITLE
eclair error -5

### ISSUE THREAD

**Issue by jarnonestor** [ACINQ/eclair#1335]
Hello to all

I have this error on eclair v 0.3.3: error no such mempool transaction. blockchain transactions are still in process of idexed. use gettransaction for wallet transaction. code -5.

I had created a node but had problems and I reinstalled the bitcoin core wallet, how can I get out of it? I have funds on the new wallet . thank you

**Comment by t-bast** [comment]
Your Bitcoin core is still indexing transactions.
You need to wait for Bitcoin to have indexed the blockchain before you can launch eclair.
