### ISSUE TITLE
Can't send a payment when request contains no amount

### ISSUE THREAD

**Issue by btcontract** [ACINQ/eclair#134]
As far as I understand there should be a possibility to specify a custom amount to be paid which does not necessarily equals the one specified in payment request (can be up to 2x higher according to spec). 

Currently there's no way to do that in Eclair. And also payment requests without amount can't be processed at all.

**Comment by pm47** [comment]
Yes, you are right this is currently explicitely rejected by the API. Our implementation of payment requests is fully BOLT11 compliant though, and does support an empty amount, so it should be fairly easy to add.

Without looking into it too much, I think we just need an additional optional parameter here (Service.scala):
``` scala
case JsonRPCBody(_, _, "send", JString(paymentRequest) :: Nil) =>
                  for {
                    req <- Future(PaymentRequest.read(paymentRequest))
                    res <- (paymentInitiator ? SendPayment(req.amount.getOrElse(throw new RuntimeException("request without amounts are not supported")).amount, req.paymentHash, req.nodeId)).mapTo[PaymentResult]
                  } yield res
```

PR welcome!
