### ISSUE TITLE
Timeouts on channel opening with Tor activated

### ISSUE THREAD

**Issue by Sosthene00** [ACINQ/eclair#1343]
I encountered many timeouts when trying to open channels. I suspect it has something to do with the fact that both Eclair and bitcoind are running over Tor and that I might have messed up something with the conf.

- It seems that I have no trouble connecting with most nodes, at least I tried a couple of "big" nodes and it connects without issue.
- but I have issues opening channels, it seems it will timeout most of the time.
- At first this was my conf file, with ip binding and Socks5 activated : 
```
eclair.chain=mainnet
eclair.bitcoind.rpcport=8332
eclair.bitcoind.rpcuser=#####
eclair.bitcoind.rpcpassword="######################"
eclair.api.enabled=true
eclair.api.password="###############"
eclair.tor.enabled=true
eclair.tor.auth="password"
eclair.tor.password="####################"
eclair.server.binding-ip="127.0.0.1"
eclair.socks5.enabled=true
eclair.socks5.use-for-ipv4 = true
eclair.socks5.use-for-ipv6 = true
eclair.socks5.use-for-tor = true
```
Then I commented out those lines : 
```
#eclair.server.binding-ip="127.0.0.1"
#eclair.socks5.enabled=true 
```
and I succeeded opening a channel. But then I tried opening another one (with Acinq node), and it timed out again.

eclair is the latest release 0.3.3, downloaded from here
bitcoind is 0.19.0.1
Tor version 0.3.5.8
Linux 4.15.0-48-generic x86_64

Here is my bitcoin.conf : 
```
txindex=1
server=1
listenonion=1
proxy=127.0.0.1:9050
bind=127.0.0.1
onlynet=onion
torpassword=<password>
maxconnections=16
minrelaytxfee=0.000001
zmqpubrawblock=tcp://127.0.0.1:29000
zmqpubrawtx=tcp://127.0.0.1:29000
addresstype=bech32
daemon=1
rpcauth=<user>:<password>
```
I'm writing a guide in french for people that want to run their full node, and I want to add Eclair as an alternative to LND, so I'd like to get Tor conf right so to not to induce other people in error !

**Comment by Sosthene00** [comment]
Ok I tried with another node and opened a channel succesfully, but I seem to be totally stuck with Acinq's node. Might be totally unrelated to Eclair idk

**Comment by t-bast** [comment]
Can you share some logs? You can filter "WARN" and "ERR" logs, that should tell us what went wrong.

**Comment by Sosthene00** [comment]
Hi, sorry I thought I already answered, I tried a couple of days later and everything worked, so I guess I was having some network issue unrelated to Éclair.
Thanks !
