### ISSUE TITLE
For more security spongycastle -> bouncycastle

### ISSUE THREAD

**Issue by Neustradamus** [ACINQ/eclair#1375]
For more security, can you change old spongycastle (based on old bouncycastle) to bouncycastle?
- https://www.bouncycastle.org/
- https://www.bouncycastle.org/releasenotes.html
- http://www.bouncycastle.org/latest_releases.html
- https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=bouncy%20castle
- https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=bouncycastle
- https://www.cvedetails.com/vulnerability-list/vendor_id-7637/Bouncycastle.html

**Comment by t-bast** [comment]
Thanks for reporting that, I'll have to do some digging, but I believe we needed spongycastle for the android support.
Do you know if that new version of bouncycastle would work on android?
Note that we're only using it for hmac, sha256 and chacha20. Anything related to those in the latest releases?

**Comment by Neustradamus** [comment]
@t-bast: Thanks for your comment!
Currently Bouncy Castle last version is 1.65 and Spongy Castle last version is 1.58.
Spongy Castle is a fork of Bouncy Castle.
Please look previous links :)

Since several years, a lot of projects have already moved from Spongy Castle to Bouncy Castle because the project is dead.

You can see discussion "34" in https://github.com/rtyley/spongycastle/issues.

**Comment by sstone** [comment]
Yes, we needed to use spongycastle on Android. We're not supporting old versions of Android anymore so it may be possible to switch to BouncyCastle but it is not that obvious even when you look at https://github.com/rtyley/spongycastle/issues/34. 

> Since several years, a lot of projects have already moved from Spongy Castle to Bouncy Castle

Do you have a list of Android projects that moved from SC to BC ?

**Comment by Neustradamus** [comment]
@sstone, @t-bast: Some applications have been noted in the issues.

And a little search here:
- https://github.com/search?q=spongycastle+bouncycastle&type=Commits

**Comment by Neustradamus** [comment]
@Any news?

**Comment by t-bast** [comment]
The mobile apps are moving to a new lightning engine in Kotlin, once that's complete we'll be able to update eclair to not depend on spongycastle anymore.

**Comment by Neustradamus** [comment]
@t-bast: Good job, thanks!

At the same time, can you update to 1.69?
