### ISSUE TITLE
btcsuite/btcd equivalent ZeroMQ configuration

### ISSUE THREAD

**Issue by fjrojasgarcia** [ACINQ/eclair#138]
I'm trying to connect **Eclair** to a **btcd testnet** instance, but I can't find the equivalent configuration for zeromq.

* In the Eclair README there is a minimal bitcoin.conf recommendation;
```
zmqpubrawblock=tcp://127.0.0.1:29000
zmqpubrawtx=tcp://127.0.0.1:29000
```

* And in the reference.conf of Eclair there is an entry like this;
`zmq = "tcp://127.0.0.1:29000"`

It's my bad or currently **Eclair** is not compatible with _Bitcoin Go_ implementation **btcd**?

**Comment by sstone** [comment]
we cannot use btcd (yet ?) because AFAIK it does not implement zeromq notifications.

**Comment by pm47** [comment]
@fjrojasgarcia I think this can be closed? We don't plan to support btcd at the moment.
