### ISSUE TITLE
./eclair-node.sh  fatal error: No such mempool transaction. Blockchain transactions are still in the process of being indexed. Use gettransaction for wallet transactions. (code: -5)

### ISSUE THREAD

**Issue by johnblanc** [ACINQ/eclair#1384]
That's what I get in the terminal after trying to run it on Debian.
The bitcoin core is fully synced and up to date, it's latest version 0.19.1
Eclair is latest as well 0.34

here is bitcoin.conf

> server=1
> rpcuser=user
> rpcpassword=pass
> rpcport=8332
> rpcallowip=127.0.0.1
> txindex=1
> 
> rpcport=8332
> 
> zmqpubrawblock=tcp://127.0.0.1:29000
> 
> zmqpubrawtx=tcp://127.0.0.1:29000
> 
> addresstype=p2sh-segwit
> 
> deprecatedrpc=signrawtransaction

here is eclair.conf

> eclair.chain=mainnet
> 
> eclair.node-alias=”node-alias”
> 
> eclair.bitcoind.rpcport=8332
> 
> eclair.bitcoind.rpcuser=user
> 
> eclair.bitcoind.rpcpassword=pass
> 
> #eclair.bitcoind.zmq="tcp://127.0.0.1:29000"
> 
> #eclair.server.public-ips = [“xxx.xxx.xx.x”]
> 
> eclair.node-color=ffffff
> 
> 
> 
> eclair.bitcoind.zmqblock="tcp://127.0.0.1:29000"
> eclair.bitcoind.zmqtx="tcp://127.0.0.1:29000"

**Comment by t-bast** [comment]
Your Bitcoin core node is still indexing transactions.
You need to wait for Bitcoin to have indexed the blockchain before you can launch eclair.
See https://github.com/ACINQ/eclair/issues/1263 for more details.

**Comment by johnblanc** [comment]
I would have thought but bitcoin core was fully up to date, synced and indexed.
However, I just tried running it again after leaving bitcoin core running for the night and now it just hangs after executing ./eclair-node.sh with no output in the terminal.

In pre 0.34 releases i see there was GUI file and now it's eclair-cli and eclair-node so I suppose eclair-node.sh is the one that is supposed to bring up the GUI if it's run successfully?

**Comment by t-bast** [comment]
> I would have thought but bitcoin core was fully up to date, synced and indexed.

The error message we displayed is coming from Bitcoin Core, so it looks like it wasn't completely done with indexing yet. Please make sure you've correctly configured `txindex=1` at the right place as explaining in the issue I linked.

> In pre 0.34 releases i see there was GUI file and now it's eclair-cli and eclair-node so I suppose eclair-node.sh is the one that is supposed to bring up the GUI if it's run successfully?

We didn't release a GUI update in 0.3.4, when you run `eclair-node.sh` you're running your eclair node without a GUI. If you don't see any output in the terminal your node is running correctly, you need to check the `eclair.log` file to see the activity.

See [this discussion](https://gitter.im/ACINQ/eclair?at=5e96e53ea412254f2185faec) for details on why the GUI wasn't included this time.

**Comment by johnblanc** [comment]
That's unfortunate! Having GUI out of the box was the sole reason I went with Eclair. Now I see that i've missed it for just 1 version. I'm not experienced enough to build it myself from the source as pointed in the link. Can I use the GUI from the previous release with the 0.34 node?

**Comment by t-bast** [comment]
You can use the 0.3.3 version that has a GUI, until we release a new version with GUI.

**Comment by johnblanc** [comment]
When would that be?

**Comment by johnblanc** [comment]
When?

**Comment by sstone** [comment]
It was added to [eclair 0.3.4](https://github.com/ACINQ/eclair/releases/tag/v0.3.4) last week.
