### ISSUE TITLE
Re-enable strict compiler parameters

### ISSUE THREAD

**Issue by pm47** [ACINQ/eclair#1393]
They were relaxed in https://github.com/ACINQ/eclair/pull/1390 for better compatibility with the android branch.

**Comment by pm47** [comment]
Starting from scala 2.13.2 we can re-enable fatal warnings while ignoring deprecation errors: https://alexn.org/blog/2020/05/26/scala-fatal-warnings.html.

Remember that we are stuck in 2.13.1 for now because of #1394.

**Comment by t-bast** [comment]
Fixed by #1885
