### ISSUE TITLE
Encrypted Wallet doesn't work 

### ISSUE THREAD

**Issue by jhysum** [ACINQ/eclair#140]
I've opened up lightning and connected it to my core. My friend also did the same but with his encrypted wallet. I try to open a channel to him and it's just stuck forever. I can't even close the connection anymore.

**Comment by sstone** [comment]
Can you please be a bit more specific: 

- which version of eclair are you using ? 
- which version of bitcoin core ? 
- are you on regtest or testnet ? 

Can you share the bitcoin and eclair configuration files ? 
Is there anything relevant in the logs ?

**Comment by pm47** [comment]
I am assuming this issue might be due to using a forked version of eclair on an unsupported blockchain (see #141)?

We will reassess if OP provides more info. Thanks!

**Comment by thetaj** [comment]
Hi guys! I need some help with the same problem. I am using core 0.16.0 and windows version of Eclair beta 2. I can open the software no problem, but I cannot seem to open a channel even though I have btc in my wallet. 

The error I get is code: -13 
Error: Please enter the wallet passphrase with walletpassphrase first

**Comment by macdasi** [comment]
1. I managed to operate eclair with passphrase but the way to do it was not by code or config : 
I just typed the command "walletpassphrase [my bitcoin passphrase] 60" so in 60 sec I am able to open the channel but I don't know about sending payments

**Comment by d4amenace** [comment]
@macdasi Did anyone figure this out?  I am having the same problem with eclair using bitcoin core on windows 0.16.  Do I need to enter it into the config file?  How should it be written?

**Comment by sstone** [comment]
@d4amenace please ask support questions on [gitter](https://gitter.im/ACINQ/eclair) instead. When bitcoind's wallet is protected with a passphrase it is up to the user to unlock it with `bitcoin-cli  walletpassphrase` before it can be used by eclair or any other app that uses rpc to communicate with bitcoind.

**Comment by patrykcc** [comment]
just open debug window in btc wallet type "walletpassphrase [your wallet password] 60" and then open eclair channel in 60s

**Comment by macdasi** [comment]
I assume that you will need to enter passphrase for each payment as well.
