### ISSUE TITLE
eclair-node.sh shebang broken

### ISSUE THREAD

**Issue by ysangkok** [ACINQ/eclair#1416]
The shebang does not appear in the first line.

This means e.g. that eclair-node.sh can't be executed without specifying the interpreter on zsh.

If I try this is what I get:
`
/eclair-node.sh: 92: Syntax error: redirection unexpected`

Tested on the release of version 0.4.

**Comment by t-bast** [comment]
@araspitzu do you know if this is expected? These scripts come from the maven packager, right?

**Comment by araspitzu** [comment]
The scripts come from [sbt-native-packager](https://www.scala-sbt.org/sbt-native-packager) and they expect to be run by the bash interpreter (although other shells work too), @ysangkok have you tried launching it with bash?
```
bash ./eclair-node.sh
```

**Comment by ysangkok** [comment]
Yeah, I tried that and I get a Future timeout error (Probably because I am using Java 8). So I think using bash explicitly helps. But the shebang should be fixed.

**Comment by t-bast** [comment]
Fixed by #1423
