### ISSUE TITLE
The shebang is misplaced in eclair-node.sh

### ISSUE THREAD

**Issue by rorp** [ACINQ/eclair#1422]
In eclair-node.sh v0.4 `#!/usr/bin/env bash` is not in the first line. That means that it gets executed with a default shell. The problem is that in some systems the default shell is not `bash`, so the script fails with syntax errors, like:
```
eclair-node.sh: 92: eclair-node.sh: Syntax error: redirection unexpected
```

**Comment by t-bast** [comment]
Did it work with 0.3.4? I'm surprised we're getting such reports only for 0.4 as the script didn't change at all.

**Comment by araspitzu** [comment]
I confirm the shebang is misplaced and should have been in the first line, it's not supposed to be a big deal (most OSs can deal with it) but since we have a few user reporting malfunctions i think we should fix it.
