### ISSUE TITLE
Feature request: API call to update relay fees for bulk or all channels

### ISSUE THREAD

**Issue by viaj3ro** [ACINQ/eclair#1432]
Would it be possible to change `UpdateRelayFee` such that the fee can be changed for more than one channel at once via providing a list of short and/or long channel IDs?

Due to the constantly changing on-chain fees it would also be very helpful to have another API call to simply update relay fees for all channels in one go.

**Comment by t-bast** [comment]
That sounds reasonable, I'll find some time this week to work on it.

**Comment by viaj3ro** [comment]
awesome, thanks!

**Comment by viaj3ro** [comment]
so thanks to @araspitzu I now have a command to adjust fees for all channels:

´eclair-cli -a localhost:8080 -p APIpassword channels | jq '.[] | .channelId' | sed -e 's/^/--channelId=/' | xargs -L 1 ./eclair-core/eclair-cli -a localhost:8080 -p APIpassword updaterelayfee --feeBaseMsat=100 --feeProportionalMillionths=500´

So at least for me, the first option (to adjust fees for a list of channels) is much more important. That being said, a simple API call to adjust fees for all channels is still very useful. Probably for many users, not just me.

**Comment by t-bast** [comment]
Great, that unblocks you until we release a new version! I'm currently updating the API to support this, it's not too complicated, should have a PR ready by tomorrow.

**Comment by viaj3ro** [comment]
Would it be complicated to also add an API call to update all channels in one go? I assume the eclair-cli script from https://github.com/ACINQ/eclair/issues/1432#issuecomment-634734587 will most likely stop working at one point as has happened to this one: https://github.com/ACINQ/eclair/wiki/Usage#example-5-compute-your-total-balance-across-all-channels

**Comment by t-bast** [comment]
I think it would be bad design as it doesn't compose well and has many edge cases.
But achieving this result is easy with the existing APIs.
You can first use the `channels` command to select all the `channelId`s that are in `NORMAL` state (it doesn't make sense to try to update channels that are offline, syncing or closing, you must filter them out).
Then you use the `updaterelayfee` API with the new `--channelIds` parameter to update them all in one step.

I'll fix the wiki example for the total balance, thanks for pointing it out.

**Comment by viaj3ro** [comment]
ok. Might make sense to include the script from https://github.com/ACINQ/eclair/issues/1432#issuecomment-634734587 in the wiki. I`m probably not the only one finding it quite helpful
