### ISSUE TITLE
Configuration values that are stored as maps in configuration files are merged, not overwritten.

### ISSUE THREAD

**Issue by sstone** [ACINQ/eclair#1434]
`Features` are represented as a map in our configuration files, which means that the corresponding configuration object defined in `application.conf` does not overwrite the "base" definition found in `reference.conf`, as it would if it was a string or number, but is merged with it (see https://github.com/lightbend/config/blob/c17d58e09af11f9e2a9ddae2eccca18f5f0f01f6/HOCON.md#duplicate-keys-and-object-merging).

With the following configuration files:
```
reference.conf:
  features {
    initial_routing_sync = optional
    option_data_loss_protect = optional
    gossip_queries = optional
    gossip_queries_ex = optional
    var_onion_optin = optional
  }

application.conf:
  features {
    option_data_loss_protect = mandatory
    var_onion_optin = optional
    payment_secret = optional
    basic_mpp = optional
  }
```

The final configuration, as read by the application, will be equivalent to:
```
  features {
    initial_routing_sync = optional
    option_data_loss_protect = mandatory
    gossip_queries = optional
    gossip_queries_ex = optional
    var_onion_optin = optional
    payment_secret = optional
    basic_mpp = optional
  }
```

There are several potential fixes:

- configuration keys that are represented by maps could be removed from eclair-core's `reference.conf` file, so there's nothing to merge with.
- a `null` value could be inserted in `application,.conf` to discard values defined in `reference.conf`:
```
application.conf:

  features : null
  features {
    option_data_loss_protect = mandatory
    var_onion_optin = optional
    payment_secret = optional
    basic_mpp = optional
  }
``` 
- or we could use an another representation for map-like fields such as `Features`

**Comment by t-bast** [comment]
Fixed by #1435
