### ISSUE TITLE
Custom electrum server as a Hidden Service not working

### ISSUE THREAD

**Issue by gustavonalle** [ACINQ/eclair#1448]
As described in the subject.
My custom electrum service is listening on a hidden Tor service at port 50001. I am connecting to Eclair using Orbot VPN

**Comment by t-bast** [comment]
That's not nearly enough information to do any kind of troubleshooting.
First of all, are you talking about eclair or eclair-mobile?
Eclair doesn't support connecting to electrum, only bitcoin core.
Eclair-mobile can connect to Electrum though, if that's where you have an issue you need to provide more details about what you put in the configuration.

**Comment by gustavonalle** [comment]
sorry, wrong project, will move it to mobile
