### ISSUE TITLE
On-chain list transactions API

### ISSUE THREAD

**Issue by ShahanaFarooqui** [ACINQ/eclair#1459]
In order to offer better on-chain insights and features to the user, we request to add on-chain list transactions API. This is good to have as an API. [LND](https://api.lightning.community/#v1-transactions) already provides it but [C-Lightning-REST](https://github.com/Ride-The-Lightning/c-lightning-REST/issues/39) has an open issue and will be introducing it soon.

Request Params:
start height
end height 

Response:
block hash on which the transaction is included
transaction hash
date/time of the transaction
block height
number of confirmations
total fees
amount
destination addresses

Sample UI designs:
![image](https://user-images.githubusercontent.com/23240721/84718473-a8a24600-af46-11ea-8da6-356b207b68b9.png)

![image](https://user-images.githubusercontent.com/23240721/84718612-05056580-af47-11ea-8b18-2f154abcaf31.png)

**Comment by t-bast** [comment]
`bitcoind` doesn't offer filtering transactions by `start_height` / `end_height` (see [listtransactions](https://bitcoincore.org/en/doc/0.20.0/rpc/wallet/listtransactions/)).
It only offers pagination using `count` and `skip`, going downwards from the latest transactions.

We have two possibilities:

- we expose filtering only by `count` and `skip` like `bitcoind` does: simplest for us, is this something that could work for the UI side?
- we try to match given `start` / `end` height by dichotomy making calls to `bitcoind`: this is likely going to be somewhat inefficient

What do you prefer?

**Comment by ShahanaFarooqui** [comment]
Hi @t-bast no preference, whatever works or is simpler for you.
Thanks
