### ISSUE TITLE
parseinvoice API throws error for empty invoice generated by CLightning

### ISSUE THREAD

**Issue by ShahanaFarooqui** [ACINQ/eclair#1478]
parseinvoice works fine with empty invoice generated by LND but throws error `The form field 'invoice' was malformed:\\nrequirement failed: amount is not valid` for Clightining's empty invoice.

Successful response from LND's empty Invoice:
{
	"prefix": "lntb",
	"timestamp": 1593632106,
	"nodeId": "02fad37ef58f76c1a5f802d198a07da5a8e55620b9ffbcbdc316fc8c9e9eac02cb",
	"serialized": "lntb1p00eet2pp5hd8s2u9nh8a0vu23rmmvqwp9eewfu54ks22rhjf2fqjxtx03zuqqdzg23jhxarfdenjq3trd3skju3q2pshjmt9de68xgrhd96xsgz9d4c8g7fqf9h8vmmfvdjjqveqcqzpgxqy9gcqsp565fye2jp5tdny2le9azgkylcuj8ghc282g5we6ympj5kula2zn0q9qy9qsqyzmupljnqyzlexk6wfh5aqs587c288005ksszuxxz6dyvyl952hqwuvvm0wquy3zjjzcrv95w24jaqh7cpewnmgjnggxwd0azd4qqespj8saqr",
	"description": "Testing Eclair Payments with Empty Invoice 3 ",
	"paymentHash": "bb4f0570b3b9faf671511ef6c03825ce5c9e52b682943bc92a48246599f11700",
	"expiry": 172800,
	"minFinalCltvExpiry": 40
}

Error while parsing Clightning's empty Invoice:
{
	"name": "StatusCodeError",
	"statusCode": 400,
	"message": "400 - {\"error\":\"The form field 'invoice' was malformed:\\nrequirement failed: amount is not valid\"}",
	"error": {
		"error": "The form field 'invoice' was malformed:\nrequirement failed: amount is not valid"
	},
	"options": {
		"url": "http://localhost:9090/parseinvoice",
		"rejectUnauthorized": false,
		"json": true,
		"form": {
			"invoice": "lntb01p00eezgpp5zprrgpmr8wugjhrpnnwqfc0u3suuvju6z2f7wgk9xm2sv95k90eqdpc23jhxarfdenjqetdwp68jgrfdemx76trv5sxvun0d5sy2cmvv95hygp3xqyjw5qcqp2sp56q5kq5gvftylckzlwppzj994qxvtj8kcwysdjucjltfpycxekcusrzjqg9ncduwavcnd98jqtd98mecucuxf4rrc4fh24u9ke766ftrlmn3jx48jcqqpqsqqqqqqqqpqqqqqzsqqc9qy9qsqvkz059mh3q5ghtcz2343vd4440mpr6dlmfeuv8rlgn3vhssxzk2jwap33lawq8p9s46r9s5pcszvvn7g0a025rj4jq0p5wcdnsljw6sqg6rruu"
		},
		"headers": {},
		"method": "POST",
		"qs": {},
		"simple": true,
		"resolveWithFullResponse": false,
		"transform2xxOnly": false
	},
	"response": {
		"statusCode": 400,
		"body": {
			"error": "The form field 'invoice' was malformed:\nrequirement failed: amount is not valid"
		},
		"headers": {
			"access-control-allow-headers": "Content-Type, Authorization",
			"access-control-allow-methods": "POST",
			"cache-control": "public, no-store, max-age=0",
			"server": "akka-http/10.0.11",
			"date": "Wed, 01 Jul 2020 19:46:25 GMT",
			"connection": "close",
			"content-type": "application/json",
			"content-length": "100"
		},
		"request": {
			"uri": {
				"protocol": "http:",
				"slashes": true,
				"auth": null,
				"host": "localhost:9090",
				"port": "9090",
				"hostname": "localhost",
				"hash": null,
				"search": null,
				"query": null,
				"pathname": "/parseinvoice",
				"path": "/parseinvoice",
				"href": "http://localhost:9090/parseinvoice"
			},
			"method": "POST",
			"headers": {
				"content-type": "application/x-www-form-urlencoded",
				"accept": "application/json",
				"content-length": 403
			}
		}
	}
}

**Comment by t-bast** [comment]
Thanks for reporting this!
It looks like c-lightning is not including the amount multiplier, which is fine but we don't handle well. I'll fix that.
Note that https://lndecode.com/ doesn't handle it well either, maybe lnd has the same parsing issue?

**Comment by t-bast** [comment]
NB though that ideally, c-lightning should not include a `0` amount but should instead completely omit it (which is what lnd and eclair do for amountless invoices).
