### ISSUE TITLE
Add `signmessage` and `verifymessage` APIs

### ISSUE THREAD

**Issue by t-bast** [ACINQ/eclair#1496]
It can be useful to sign arbitrary messages with the key associated with our `node_id` (to prove ownership of a node).
It can be done implicitly by generating an invoice, but it shouldn't be much work to have an explicit way of doing it.

We should provide an interface similar to lnd, see:

- https://api.lightning.community/#signmessage
- https://api.lightning.community/#verifymessage

We will probably differ on the encoding to keep it simple and avoid adding new dependencies.
The message should probably be a base64 encoding of raw bytes, and the signature a raw 64-byte signature in hex format (or base64?), so the response would look something like:

```json
{
    "nodeId": "03af0ed6052cf28d670665549bc86f4b721c9fdb309d40c58f5811f63966e005d0",
    "message": "base64 encoding of a raw message",
    "signature": "64 bytes signature, hex-encoded"
}
```

**Comment by dkrm0** [comment]
I think the signature should be in hex format. It's more common for this type of data.

**Comment by t-bast** [comment]
Yeah I agree, let's do base64 for the message and hex for the signature
