### ISSUE TITLE
Initial routing sync is executed after reconnect despite `localFeatures = 00`

### ISSUE THREAD

**Issue by btcontract** [ACINQ/eclair#150]
Node `A` has `localFeatures = 00`, node `B` has `localFeatures = 08`.
Restarting `B` makes it send full current routing state to `A` after re-connection.
In turn, restarting `A` has no such effect (`B` does not send a full current routing state after re-connection).

**Comment by sstone** [comment]
We broadcast routing info every 10 seconds (it would be a different setting on mainnet) which makes it look like it was broadcast on reconnection but it's not the case. You can change this setting by adding the following line to eclair.conf:

```
eclair.router-broadcast-interval = 45 seconds
```

and see how B behaves upon reconnection.

**Comment by btcontract** [comment]
Thanks for explanations. It looks like node `B` does respect `A`'s `localFeatures = 00` but on restart `B` gets full routing state from `C` and updates it's `rebroadcast` collection which then gets re-sent to `A` within 10 seconds. 

This effectively cancels `localFeatures = 00` which may be undesired for, say, lite phone clients but I guess this won't be changed until the whole routing gossip mechanism is revised in v1.1?

**Comment by pm47** [comment]
Yes, I think this is more a spec issue than an implementation issue, and the discussion would be best had there. There is even a related PR: https://github.com/lightningnetwork/lightning-rfc/pull/218 (as you expected this is scheduled for v1.1).
