### ISSUE TITLE
Small typo in code comments for amount conversion

### ISSUE THREAD

**Issue by dxts** [ACINQ/eclair#1502]
Just a small issue in the code comments :)

Typo in amount conversions comments.
[Line 464 and 477](https://github.com/ACINQ/eclair/blob/master/eclair-core/src/main/scala/fr/acinq/eclair/payment/PaymentRequest.scala#L464)

```// 1 pico-bitcoin == 0.1 milli-satoshis```

**Comment by t-bast** [comment]
Good catch, thanks!
