### ISSUE TITLE
Feature request: Open channel with specific relay and base fee setting

### ISSUE THREAD

**Issue by viaj3ro** [ACINQ/eclair#1507]
for some peers (like LOOP) it is necessary to open channels with a vastly higher fee than the regular one due to the one way flow characteristics of the liquidity and in order to not have them fully exhausted right away. 

Therefor it would be very helpful if channels could be opened with a specific fee setting overwriting the global setting in the config.

**Comment by pm47** [comment]
Have you tried the `fundingFeerateSatByte`? See
https://acinq.github.io/eclair/#open

**Comment by viaj3ro** [comment]
yes, in fact I have. But unless I'm missing something, this only allows for setting a specific fee for the funding TX.

I guess my title is not clear enough. What I want to do, is open a channel in such a way that it has a specific relay and base fee setting other than the global setting from the config. Otherwise some channels just get exhausted right away upon opening and the only work around is to have a very high global fee setting and then manually adjust it down for every new channel.

**Comment by pm47** [comment]
Ha, gotcha.

> Otherwise some channels just get exhausted right away upon opening

Really? How often does that happen?

**Comment by viaj3ro** [comment]
well, for channels to LOOP it happens every single time. Some other highly active nodes, it happens but less frequently. 

so far this bug hast usually saved me:
https://github.com/ACINQ/eclair/issues/1444
https://github.com/lightningnetwork/lnd/issues/4368

but since recently it doesn't seem to do it's "job" reliably anymore.

There are actually quite a few actively managed routing nodes that do use a super high global fee setting like 1% to circumvent the issue. But arguably this makes matter worse since the fee for every channel has to be readjusted manually or programmatically after opening. So far my channels

**Comment by viaj3ro** [comment]
I mean it doesn't happen instantly but a few hours after channel opening it can happen within minutes: [https://i.imgur.com/NIasnci.png](url)

**Comment by viaj3ro** [comment]
Awesome! Thanks a lot! Looking forward to using this once it's merged!
