### ISSUE TITLE
ListInvoices should return separate requested and received amounts

### ISSUE THREAD

**Issue by ShahanaFarooqui** [ACINQ/eclair#1511]
Currently, only settled invoices return received amount otherwise it is either null or missing. We have to call getinvoice API in order to get the requested amount value for expired invoices.

It will be great if we can get the requested and received amount as different fields in the list invoices API itself.

**Comment by t-bast** [comment]
Can you detail a bit more?

In all cases, our invoice APIs (`getinvoice`, `listinvoices` and `listpendinginvoices`) only return the Bolt 11 invoice and never return any information about what has been received. I don't understand what you mean by `only settled invoices return received amount`.

What's the UX flow you're trying to fix? That will help figure out the API we need to tweak/add to address this best.

**Comment by ShahanaFarooqui** [comment]
Details: Currently, we are showing the amount and settled amount as two separate fields for LND's invoices. We want to mimic the same functionality for C-Lightning and Eclair. However, we are only getting a single `amount` field from Ecliar's API where it is unclear if the field is request amount or settled amount. For example, listInvoices API will return the amount value for an empty invoice as well, with the settled amount value. 

Overall, it will be great if we can get two amount fields with first being the amount which was passed while creating the invoice and another being the amount which was paid at the time of invoice settlement.
createinvoice => amountMsat | Amount in millisatoshi for this invoice
payinvoice => amountMsat | Amount to pay if the invoice does not have one

UX flow: https://github.com/Ride-The-Lightning/RTL/issues/402
Sample invoice responses from different implementations:
- Eclair empty invoice:
   - settled
      - amount: 123
   - unsettled
     - amount: undefined

- Eclair non-empty invoice:
  - settled
     - amount: 600
  - unsettled
    - amount: undefined
 
- LND empty invoice:
  - settled
    - amt_paid_sat: "150"
    - value_msat: "0"
  - unsettled
    - amt_paid_sat: "0"
    - value_msat: "0"

- LND non-empty invoice:
  - settled
    - amt_paid_sat: "2100"
    - value: "2100"
  - unsettled
    - amt_paid_sat: "0"
    - value_msat: "349550000"

- CLightning empty invoice:
  - settled
    - msatoshi: undefined
    - msatoshi_received: 6500
  - unsettled
    - msatoshi: 0
    - msatoshi_received: undefined

- CLightning non-empty invoice:
  - settled
    - msatoshi: 100000
    - msatoshi_received: 100000
  - unsettled
    - msatoshi: 100000
    - msatoshi_received: undefined

**Comment by t-bast** [comment]
Got it, that makes sense. I think the current APIs have everything you need already.

All the invoice APIs (`getinvoice`, `listinvoices`, `listpendinginvoices`) only return the Bolt 11 invoice data.
But you can pipe the payment hash to the `getreceivedinfo` API that will return you detailed information about the status of the payment.

Would that work for you?

**Comment by ShahanaFarooqui** [comment]
@t-bast Thanks for the suggestion. Will use getreceivedinfo API at our end.
