### ISSUE TITLE
Early payment failures are not reflected in `getsentinfo`

### ISSUE THREAD

**Issue by t-bast** [ACINQ/eclair#1512]
When payments fail before a `PaymentLifecycle` FSM is instantiated, nothing is logged in the DB.
This is confusing for users that send payments through the API/CLI.

In particular, for MPP payments for which we can't find a route, nothing will be written to the DB, whereas non-MPP payments that don't find a route will have an entry in the DB.

**Comment by fiatjaf** [comment]
Perhaps just returning a routing error to the original `payinvoice` call instead of a payment id would be enough. Or even just making it more clear in the documentation that when `getsentinfo` is blank that means the payment wasn't even tried.
