### ISSUE TITLE
support for lnurl-pay is missing

### ISSUE THREAD

**Issue by ChuckNorrison** [ACINQ/eclair#1522]
Iam testing static qr code solution with lnurl within my LNBits installation. 

On Eclair Andoird Wallet, the lnurl string format seems to be not supported.

Here is an example of a LNURL which can be used on ZAP Android and Lightning Labs Android App:

> LNURL1DP68GURN8GHJ7MRFVA58GMNFDENHWCTVDDJHYTNYW43KKERWWVHX7UN89AKXUATJD3CZ7CTSDYHHVVF0D3H82UNV9UCSLETSVY

Will eclair support those lnurl's in the future to pay on static QR codes?

**Comment by dpad85** [comment]
Eclair mobile will support LNURL, the code for LNURL-withdraw/auth already exists for Phoenix and needs to be ported to Eclair mobile.

Closing this issue because it's not on the correct repository. Could you create it on https://github.com/ACINQ/eclair-mobile instead?
