### ISSUE TITLE
Some of eclair's log output ought to go to stdout

### ISSUE THREAD

**Issue by dscotese** [ACINQ/eclair#1546]
It may be the case that because eclair is started by a batch file on Windows, it CANNOT send output to the console window in which it's starting.  Otherwise, it would make sense for some log level to default to output to that window.

Version eclair-node-0.3.4-24aa710 never produces any output to my console.  The log shows ERROR entries and WARN entries.  It would be nice to see them show up in the console.

**Comment by t-bast** [comment]
It's just a matter of configuring your logs.
See our wiki: https://github.com/ACINQ/eclair/wiki/Logging
You can configure a console logger very easily.
