### ISSUE TITLE
Error using JAVA_OPS in Docker

### ISSUE THREAD

**Issue by brmdbr** [ACINQ/eclair#1560]
I have trouble running the latest Eclair from Docker (acinq/eclair:release-0.4.1). Issue is using the JAVA_OPTS parameters. v3.3 release seems to work. Using the official docker images.

It throws the following error: /bin/sh: 1: -Xmx256m: not found. But when I remove that line it throws an error on the next line withing the JAVA_OPS block.

This is when I try to run the Docker image with docker-compose up.

This is the part of the docker-compose:

```
eclair:
image: acinq/eclair:release-0.4.1
container_name: eclair
stop_signal: SIGINT
env_file: .env
environment:
PUBLIC_HOST: ${BW_ROOTURL}
JAVA_OPTS: |
-Xmx256m
-Declair.printToConsole
-Declair.headless
-Declair.chain=${BITCOIN_NETWORK}
-Declair.server.binding-ip=0.0.0.0
-Declair.server.public-ips.0=${BW_ROOTURL}
-Declair.server.port=9735
-Declair.api.enabled=true
-Declair.api.binding-ip=0.0.0.0
-Declair.api.port=${LIGHTNING_PORT}
-Declair.node-alias=test
-Declair.api.password=${LIGHTNING_PASS}
-Declair.bitcoind.host=bitcoind
-Declair.bitcoind.rpcport=${BITCOIN_RPCPORT}
-Declair.bitcoind.rpcuser=${BITCOIN_RPCUSERNAME}
-Declair.bitcoind.rpcpassword=${BITCOIN_RPCPASSWORD}
-Declair.bitcoind.zmqblock=tcp://bitcoind:28332
-Declair.bitcoind.zmqtx=tcp://bitcoind:28333
expose:
  - "9735" # server port
  - "${LIGHTNING_PORT}" # api port
volumes:
  - "bitcoin_datadir:/etc/bitcoin"
  - "eclair_datadir:/data"
depends_on:
  - bitcoind
restart: unless-stopped
```

@araspitzu Is this related to your changes to the Dockerfile?

**Comment by dkrm0** [comment]
This [line](https://github.com/ACINQ/eclair/blob/master/Dockerfile#L66) seems to be the problem. The `JAVA_OPTS` variable is expanded and the first word of it is considered to be the command to run.

**Comment by brmdbr** [comment]
> This [line](https://github.com/ACINQ/eclair/blob/master/Dockerfile#L66) seems to be the problem. The `JAVA_OPTS` variable is expanded and the first word of it is considered to be the command to run.

I think so too but, I'm not sure what the fix is. Got an idea?

**Comment by t-bast** [comment]
Maybe switching the order of `bash` and `$JAVA_OPTS` does the trick? @dkrm0 can you try fixing this today, so that we include it in the 0.4.2 release?

**Comment by dkrm0** [comment]
@t-bast I'm on it

**Comment by brmdbr** [comment]
Awesome guys thanks a lot! Is this image available in Dockerhub now?

**Comment by dkrm0** [comment]
We will release the v0.4.2 today so the Dockerhub image will be available shortly after.

**Comment by brmdbr** [comment]
Great, thanks @dkrm0!
