### ISSUE TITLE
Tor instructions for Windows

### ISSUE THREAD

**Issue by dscotese** [ACINQ/eclair#1592]
I followed the instructions at https://github.com/ACINQ/eclair/blob/37c222dce1b6c57685804cea5200d1f8b3620f41/docs/Tor.md
Running eclair-cli in Windows command prompts does nothing. Running it in a bash shell (installed by the "Windows Subsystem for Linux" works, so I tried `eclair-cli getinfo` and entered my password.  It does NOT show a tor hidden service.

Relevant entries from my eclair.conf file:
````
	eclair.tor.enabled = true
	eclair.tor.auth = safecookie
	# eclair.tor.password = ""      # Needed if you set auth to password
```
... and from my torrc file:
```
SOCKSPort 9050
ControlPort 9051
HashedControlPassword 16:[REDACTED]
ExitPolicy reject *:* # don't change this unless you really know what you are doing
```
I realized that the Tor Browser Bundle may be insufficient for the task, so I went to get the "Expert Bundle" but there is no such thing available at https://www.torproject.org/download/download.html.

**Comment by t-bast** [comment]
> Running eclair-cli in Windows command prompts does nothing. 

What do you mean by "does nothing"? I'm pretty sure it's correctly running, have you tried looking at your log file or doing an `eclair-cli getinfo` to verify whether it's running or not?

If you run eclair in WSL, it's not running on windows, it's running in a linux sub-system, so it's expected that the windows Tor instructions won't work.

**Comment by dscotese** [comment]
Sorry, not nothing.  It doesn't recognize the file as an executable, as you can see below.  I don't think I changed the extension, but perhaps that's what I tried when it did "nothing" It's the cli, and I didn't give it any input.  

```
C:\Users\dscot\Downloads\eclair-node-0.3.4-24aa710\bin>eclair-cli
'eclair-cli' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\dscot\Downloads\eclair-node-0.3.4-24aa710\bin>dir
 Volume in drive C is OS
 Volume Serial Number is 3AF4-2583

 Directory of C:\Users\dscot\Downloads\eclair-node-0.3.4-24aa710\bin

04/12/2020  02:28 PM    <DIR>          .
04/12/2020  02:28 PM    <DIR>          ..
04/12/2020  02:28 PM             3,909 eclair-cli
04/12/2020  02:28 PM             6,342 eclair-node.bat
04/12/2020  02:28 PM            10,941 eclair-node.sh
               3 File(s)         21,192 bytes
               2 Dir(s)  262,221,946,880 bytes free
```
I expected the output to be the same as it is in bash:
```
dscotese@DESKTOP-13S57FH:/mnt/c/Users/dscot/Downloads/eclair-node-0.3.4-24aa710/bin$ ./eclair-cli
==============================
Command line client for eclair
==============================
...
```

**Comment by t-bast** [comment]
I'm noticing you're using eclair 0.3.4, which is obsolete (we are at eclair 0.4.2).
Did you try running the latest version?
I don't have a windows machine so I can't help you much there.

**Comment by dscotese** [comment]
The Readme doesn't explicitly say that upgrading from 0.3.4 to 0.4.2 is safe.  Each of the steps is explicitly represented as safe.  Is this something that needs to be tested?  I can imagine that I try it, it works fine, but the fact is that it isn't safe in particular situations.  However, you might know that it is safe to go from 0.3.4 to 0.4.2 directly.  

Thanks for pointing out my node's age!

**Comment by t-bast** [comment]
Closing this, issue, upgrading should not be a problem.
Please re-open if it creates issues.
