### ISSUE TITLE
Overwriting from 4.0 with 4.1 appears to fail.

### ISSUE THREAD

**Issue by dscotese** [ACINQ/eclair#1619]
1. I downloaded the version 4.1 zip file and overwrote the contents of my eclair folder (from which I have been running my node successfully) with the contents of the zip file.
2. I ran the eclair.bat file.
3. I used a bash window to run `ecliar-cli getinfo`

I expected it to report that it was running `  "version": "0.4.1-e5fb281",`

It reported that it was still running `  "version": "0.4-69c538e",`

I tracked this down to an assumption in eclair.bat that `dir /b` in Windows command prompt will list files putting xyz.4.jar before xyz.4.1.jar, and that's not true.  The result is that `APP_ENTRYPOINT` is set to the version 4.0 jar instead of the 4.1 jar.  If we continue using the convention of leaving the .0 off of the initial major version, this will happen for every upgrade done similar to mine.  I am about to make a pull request for an update to the batch file which orders the `eclair-node*` files by their timestamp, under the assumption that the latest `eclair-node*.jar` file will be the one with the highest version number.

**Comment by t-bast** [comment]
Fixed with eclair 0.5.0.
