### ISSUE TITLE
[Feature request] Cooperative closure with unreliable peers

### ISSUE THREAD

**Issue by viaj3ro** [ACINQ/eclair#1623]
I have lots of channels from unreliable peers that I wish to close but are reluctant to force close. 1ml shows that they come online every once in a while but it is next to impossible to manually time a closure when that happens.

It would be very helpful and also save a lot of money for everyone if there was a way to close a channel to an unreliable and mostly offline peer such that it is only marked for closure but the actual closure happens once the peer becomes responsive again and a cooperative closure can be negotiated.

So ideally there would be an API call for a cooperative closure that is send out as soon as the peer comes online again.

**Comment by t-bast** [comment]
This is fixed by #1768.
Once more peers support this on the network you'll be able to close with more reliable fees.
