### ISSUE TITLE
Add a metric for unconfirmed bitcoin balance

### ISSUE THREAD

**Issue by pm47** [ACINQ/eclair#1635]
The more we optimize for lower feerates,  the more we will have to take unconfirmed transactions into account.

**Comment by t-bast** [comment]
But isn't it already what #1609 did?

**Comment by pm47** [comment]
Not exactly, I'm looking at `getunconfirmedbalance`, something like:

```scala
val BitcoinUnconfirmedBalance = Kamon.gauge("bitcoin.unconfirmedbalance", "Bitcoin unconfirmed balance (mBTC)")
```

**Comment by t-bast** [comment]
I think that's https://github.com/ACINQ/eclair/blob/ade17ecb725ff40429f2d51972e59e99ec2336ef/eclair-core/src/main/scala/fr/acinq/eclair/blockchain/Monitoring.scala#L28 with `status=unconfirmed`.

**Comment by t-bast** [comment]
Everything is now available in the `BitcoinBalance` metric with specific tags.
