### ISSUE TITLE
`ClaimDelayedOutputTx` amount may be negative

### ISSUE THREAD

**Issue by btcontract** [ACINQ/eclair#164]
An HTLC may have a borderline amount which will be sufficient for `HtlcTimeoutTx/HtlcSuccessTx` to be part of a local commit but respected `ClaimHtlcTimeoutTx/ClaimHtlcSuccessTx` amounts will be so small that applying fees to them would render their output values negative or below dust levels. 

This will result in a dangling utxo which is created by 1st tier tx but is unable to be spent by a 2nd tier tx in a case of uncooperative local commit spend. 

Perhaps this can be improved using two additional checks:

1. When creating a `ClaimHtlcTimeoutTx/ClaimHtlcSuccessTx`, if tx `output.value - fee < dust`, then fee might be set to something like `output.value / 2`?

2. In `claimCurrentLocalCommitTxOutputs`, if 2nd tier tx `output.value <= dust`, then spend neighter that 2nd tier nor related 1st tier tx. HTLC output will thus be unused and blockchain won't be burdened with a useless tx.

**Comment by pm47** [comment]
Hi Anton,

I'm not sure how that can happen given that:
- `htlcTimeoutWeight` > `claimHtlcSuccessWeight`
- `htlcSuccessWeight` > `claimHtlcTimeoutWeight`

What am I missing?

**Comment by pm47** [comment]
Example, with:
- outgoing htlc `amount_msat`=1205
- `dust_limit`=542
- `feeratePerKw`=10000

The corresponding output of the commitment tx is 1205.
The corresponding output of the `HtlcTimeoutTx` is 542 (=`dust_limit`).
The corresponding output of the `ClaimHtlcSuccessTx` is 635 (greater than the output of `HtlcTimeoutTx`).

**Comment by btcontract** [comment]
Damn, sorry, I've completely messed up a terminology here. What I've meant is that `ClaimDelayedOutputTx` may have a negative amount, NOT  `ClaimHtlcTimeoutTx` or `ClaimHtlcSuccessTx`, they are completely unrelated to this issue.

Here's a live example:
`A` sends an outgoing HTLC of `25000` SAT
`dust_limit = 542`
`feeratePerKw=10000`

`B` disconnects when HTLC is cross-signed, `A` decides to close a channel uncooperatively, here's an output of `generateTx` method in `channel/Helpers.scala`:

```
tx generation success: desc=main-delayed-output txid=41159ba0ac8ef463aa00601dfdece449908e0ca6976216890e2f61dfd78ec819 amount=964282 tx=020000000001019eeccb069facda1875ac27ccd2ab701f155d609f7a05ec5d1390d19db98c4cc801000000009000000001bab60e00000000001976a914a3c33ba6c51df554f8e976b837f5d2656bb9f74988ac034830450221009eb4bb5c517667aa3afa4486a4b689219c3c16c19518dc9d6603a7cadc124c890220409285a41d87e82831021e1197b6a0c196b8fd3576e07a57db12fc32cab9d6fe01004d6321024234066757c7d43f4c873c21012af6efd4e87add6fe24f4807bfe416268dc82667029000b2752103841407300fa84d6caa1a475c74854d98499a3d28c475ecf9660cff62865dc62168ac00000000
tx generation success: desc=htlc-timeout txid=2932377dc31395d2abafe54ebf24f2461322fc3faf25f6c6dbc697382d8e4623 amount=10257 tx=020000000001019eeccb069facda1875ac27ccd2ab701f155d609f7a05ec5d1390d19db98c4cc8000000000000000000011128000000000000220020a7e90a5577493aa359a73d01a73a5ae00d850b43719e751b0e42068f893c936e0500483045022100942ed3aef7fab41476218b6dce5ef175c53c925d626455d07dde6f1f0f3873c70220697ab81616726627ea73877e78ba9e8c1640b24be3a8c9a905b7a11d8df0546b0147304402205e73b0bdb5bca5ec3c14bf9756722b70e6efb339672753759447465822e53403022045ca0f4de22db45c399f38f8a13874aea127e2fbabd7fe14bfd6fac525a6bd9a01008576a9141f66540a70aec7f3a25296ff4a3f1b320d27f50b8763ac6721036f5157cee2d1db61117d9d2832af7f95267171839eeb58eb77112ee7855ebab97c820120876475527c2103c07a22e78f7c91fa715694f7b11a2a172c050e1105f544f327da76486dcad17552ae67a9143e94b54edba28beebdc1c66e00e6a12d58408b9088ac6868f7570000
tx generation success: desc=claim-delayed-output txid=a64e769e715e1e8d5d4fc367833e9cb0015a58a52400b1a75487218be4c3d152 amount=-461 tx=0200000000010123468e2d3897c6dbc6f625af3ffc221346f224bf4ee5afabd29513c37d3732290000000000900000000133feffffffffffff1976a914a3c33ba6c51df554f8e976b837f5d2656bb9f74988ac0347304402204ac885fd3ded5b65953609aab3639e09e46d1fe199f8155a63fff2f2ed08be190220425935b18bb8555b37b041127fa570356eb3362d1abb3dc66331138bac11c5d301004d6321024234066757c7d43f4c873c21012af6efd4e87add6fe24f4807bfe416268dc82667029000b2752103841407300fa84d6caa1a475c74854d98499a3d28c475ecf9660cff62865dc62168ac00000000
```

`claim-delayed-output` has an amount of `-461` SAT

**Comment by pm47** [comment]
Gotcha. I opted for a simpler solution, more consistent with the current logic for [trimmed outputs](https://github.com/lightningnetwork/lightning-rfc/blob/master/03-transactions.md#trimmed-outputs).
