### ISSUE TITLE
First interrupted HTLC leads to state de-synchronization and eventual channel closing

### ISSUE THREAD

**Issue by btcontract** [ACINQ/eclair#165]
How to reproduce:

1. Create a new channel between `A` and `B`

2. Send an `A` -> `B` HTLC and disconnect `B`, more precisely:
- `A` -> `B`: `UpdateAddHtlc`
- `A` -> `B`: `CommitSig`
- `B` disconnectes without receiving a `CommitSig`

3. On reconnect `B` expects `commitments.remoteNextHtlcId == 0` but `A`'s `localNextHtlcId == 1` so the next `A`'s outgoing HTLC will cause `UnexpectedHtlcId` from `B`

This seems to be happening because of a special `if/else` case in channel reestablishment code:

```scala
case Event(channelReestablish: ChannelReestablish, d: DATA_NORMAL) =>

      val commitments1 = if (channelReestablish.nextLocalCommitmentNumber == 1 && d.commitments.localCommit.index == 0) {
        // no new commitment was exchanged after NORMAL state was reached
        log.info(s"re-sending fundingLocked")
        val nextPerCommitmentPoint = Generators.perCommitPoint(d.commitments.localParams.shaSeed, 1)
        val fundingLocked = FundingLocked(d.commitments.channelId, nextPerCommitmentPoint)
        forwarder ! fundingLocked
        d.commitments
      } else {
        handleSync(channelReestablish, d)
      }
```

It does not take into account that node `A` may already have a first locally signed HTLC which needs `handleSync` to be executed on `A`'s side anyway.

**Comment by pm47** [comment]
Good catch! 

When receiving `B`'s `ChannelReestablish`, `A` should make sure that it didn't have an inflight signature.

Something like that should fix it (additional condition in the `if/else`):

```scala
case Event(channelReestablish: ChannelReestablish, d: DATA_NORMAL) =>

      val commitments1 = if (channelReestablish.nextLocalCommitmentNumber == 1 && d.commitments.localCommit.index == 0 && d.commitments.remoteNextCommitInfo.isRight) {
        // no new commitment was exchanged after NORMAL state was reached
        log.info(s"re-sending fundingLocked")
        val nextPerCommitmentPoint = Generators.perCommitPoint(d.commitments.localParams.shaSeed, 1)
        val fundingLocked = FundingLocked(d.commitments.channelId, nextPerCommitmentPoint)
        forwarder ! fundingLocked
        d.commitments
      } else {
        handleSync(channelReestablish, d)
      }
```

**Comment by btcontract** [comment]
Yes, it does fix an issue.
