### ISSUE TITLE
Upgrade from 0.3.0 to 0.5.0 on Windows 10

### ISSUE THREAD

**Issue by wdey** [ACINQ/eclair#1663]
I run version 0.3.0 on Windows 10, by means of

java -jar eclair-node-gui-0.3-a5debcd.jar command.

What is the proper way to upgrade to 0.5.0 ? where can I find the proper jar file

**Comment by t-bast** [comment]
We changed the packaging to run via a script: https://github.com/ACINQ/eclair/wiki/Run
Note that the GUI has been deprecated in release 0.4: https://github.com/ACINQ/eclair/releases/tag/v0.4
You can instead use https://github.com/Ride-The-Lightning/RTL if you want a GUI.
