### ISSUE TITLE
Eclair wont run

### ISSUE THREAD

**Issue by crippercrisp** [ACINQ/eclair#1670]
Am I supposed to run eclair from eclaire-node.bat? when i run it, a cmd prompt opens with nothing on it and then it closes out on its own.

**Comment by t-bast** [comment]
See https://github.com/ACINQ/eclair/wiki/Run
You need to locate your `eclair.log` file to figure out what's wrong.

**Comment by crippercrisp** [comment]
> 
> 
> See https://github.com/ACINQ/eclair/wiki/Run
> You need to locate your `eclair.log` file to figure out what's wrong.

this is what it says
`2021-01-15 12:19:46,682 ERROR fr.acinq.eclair.Boot - fatal error: C:\Users\-----\.eclair\eclair.conf: 6: Expecting end of input or a comma, got ':' (if you intended ':' to be part of a key or string value, try enclosing the key or value in double quotes, or you may be able to rename the file .properties rather than .conf)com.typesafe.config.ConfigException$Parse: C:\Users\-----\.eclair\eclair.conf: 6: Expecting end of input or a comma, got ':' (if you intended ':' to be part of a key or string value, try enclosing the key or value in double quotes, or you may be able to rename the file .properties rather than .conf)`

**Comment by t-bast** [comment]
That error seems clear enough: your `eclair.conf` is invalid.
Please fix it and work your way through the simple configuration errors before opening an issue.
