### ISSUE TITLE
Return underlying state when in `OFFLINE` and `SYNCING`

### ISSUE THREAD

**Issue by pm47** [ACINQ/eclair#1676]
There is an ambiguity because the state is sometimes really a combination of state + data.

We should probably return `OFFLINE_X`, `SYNCING_X`, with `X`=`WAIT_FOR_FUNDING_CONFIRMED`, `NORMAL`, etc.

**Comment by t-bast** [comment]
We tried this in #2225 but it created more problems than it solved...shall we keep that issue or is this a dead-end?

**Comment by t-bast** [comment]
Closing for now, we can re-open later if we feel it's necessary.
