### ISSUE TITLE
UnreadableWalletException after remote uncooperative close with in-flight outgoing HTLC when using bitcoinj 0.15-rc4

### ISSUE THREAD

**Issue by btcontract** [ACINQ/eclair#171]
`A` sends an HTLC to `B`, after HTLC is cross-signed `A` disconnects and then `B` closes a channel uncooperatively while `A` is not connected, `B` also spends it's `HtlcSuccessTx` immediately.

`A` listens to blockchain events all this time and gets `B`'s spent commit, reacts by broadcasting it's `ClaimP2WPKHOutputTx` and `ClaimHtlcTimeoutTx` for in-flight HTLC (even though it has 6 blocks of CLTV timeout), then gets `B`'s `HtlcSuccessTx` and extracts a preimage.

The problem is remote spent commit tx does not get confirmations in `A`'s wallet and as a consequence `A`'s `ClaimP2WPKHOutputTx` and `ClaimHtlcTimeoutTx` don't get confirmations either. Moreover, once 6 blocks of CLTV timeout pass, restarting a wallet causes the following exception: 

```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.reflect.InvocationTargetException
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    ... 1 more
Caused by: org.bitcoinj.wallet.UnreadableWalletException: Could not connect 1d10acc39ef37c9b217bc7ce14365a1201fbefc67417acb29465fe17d55b82d2 to 455d8e8a80156e3afc16c81cdbcbdfda70c2ab93da90eda58fb0f6cbf2943f29
    at org.bitcoinj.wallet.WalletProtobufSerializer.connectTransactionOutputs(WalletProtobufSerializer.java:756)
    at org.bitcoinj.wallet.WalletProtobufSerializer.readWallet(WalletProtobufSerializer.java:543)
    at org.bitcoinj.wallet.WalletProtobufSerializer.readWallet(WalletProtobufSerializer.java:470)
...
```

A combination of the following events seems to trigger such a behavior:

1. `A` sees remote commit spent, it is unconfirmed
2. `A` broadcasts `ClaimHtlcTimeoutTx` immediately
3. `A` gets `B`'s `HtlcSuccessTx` (so there are now two txs which attempt to spend the same utxo present in a wallet: `A`'s CLTV delayed `ClaimHtlcTimeoutTx` and `B`'s `HtlcSuccessTx`)

None of this happens if remote commit gets at least 1 confirmation before `A`'s `ClaimHtlcTimeoutTx` is broadcasted (I've delayed spending `HtlcSuccessTx` on `B`'s side to achieve this), presumably because `B`'s `HtlcSuccessTx` gets confirmed in a same block with commit tx so `A`'s later attempt to spend a `ClaimHtlcTimeoutTx` gets rejected right away.

**Comment by pm47** [comment]
We have been recently chasing a bug that may be the same as the one you are observing.

Just to be sure, which branch are you on? `master` or `wip-android`?

**Comment by btcontract** [comment]
This happens in my lite wallet but I'm using bitcoinj 0.15-rc4 which is also currently used `wip-android` http://search.maven.org/#artifactdetails%7Cfr.acinq%7Cbitcoinj-core%7C0.15-rc4%7Cjar

**Comment by btcontract** [comment]
Think I probably should test the same scenario in `wip-android`, my first impression was this is something related to bitcoinj, but it may be not! I'll do the the testing on `wip-android` and report how it goes there.

**Comment by pm47** [comment]
I am almost certain it is related to bitcoinj, but if you can reproduce with `wip-android` that's even better!

**Comment by btcontract** [comment]
OK this has something to do with my wallet rather than bitcoinj, `eclair-master` with `spv = true` works fine in similar scenario. Currently looking for reason in my app but this issue can be disregarded I guess. Sorry for bothering!

**Comment by btcontract** [comment]
Well, after further testing it turns out the bug is present in both `eclair-master` and in my wallet. It does not manifest itself in `eclair-master` because `PublishAsap` in `SpvWatcher` postpones CLTV tx broadcasting until timeout is gone and spent commit tx already has a few confirmations by that time, which eliminates the bug.

I think this is still a real problem and just postponing a CLTV tx won't always solve it on mainnet. The reason is `SpvWatcher` only looks at current chain height but not at number of confirmations a spent commit tx has so it may happen such that even after 6 blocks commit tx still has no confirmations and CLTV it broadcasted which would currently corrupt a wallet.

**Comment by pm47** [comment]
Just to be sure, you are saying that bitcoinj will blindly accept any transaction that we give it through `broadcastTransaction` (even timelocked ones), and it writes it to its wallet?

**Comment by btcontract** [comment]
Yes, a timelocked tx is accepted and saved in a wallet, it has zero confirmations and a PENDING status, should be re-broadcasted again when timeout is cleared or else will stay this way forever.

**Comment by btcontract** [comment]
Just in case, made a much more detailed description of what is going on when this happens: https://github.com/btcontract/bitcoinj/issues/1

**Comment by pm47** [comment]
Bitcoinj has been deprecated in favor of Electrum starting from 875dc04d3904d44e7bb10bc30d53434f1d81e9a6.
