### ISSUE TITLE
updaterelayfee API call returning incorrect return types

### ISSUE THREAD

**Issue by n1bor** [ACINQ/eclair#1711]
successful api call to updaterelayfee returned:

```{"d740bb72f539047eabfdc6c3485640f0c3871260918f98b89e40e2d9e65d1cac":{"cmd":{"replyTo":null,"feeBase":50000,"feeProportionalMillionths":2500},"channelId":"d740bb72f539047eabfdc6c3485640f0c3871260918f98b89e40e2d9e65d1cac"}}```

was expecting:

```{"d740bb72f539047eabfdc6c3485640f0c3871260918f98b89e40e2d9e65d1cac":"ok"}```

according to the docs:
https://acinq.github.io/eclair/#updaterelayfee

Happens on master latest as of 26th Feb 2021.

Errors seem to return as expected:

```{  "f0d23268832c74ff805a5844fb47dbfb480042bc530a4b14011c68a0109f483b": "cannot execute command=updaterelayfee in state=CLOSING" }```

**Comment by t-bast** [comment]
Yes, we now return the whole command when it's successful.
We will update the documentation.

**Comment by t-bast** [comment]
The API documentation is now fixed.
