### ISSUE TITLE
Number of HTLCs in `CommitmentSpec` in `sendAdd` and `receiveAdd` methods

### ISSUE THREAD

**Issue by btcontract** [ACINQ/eclair#175]
Currently, when doing checks in `sendAdd` on HTLC sender side and `receiveAdd` on receiver side, a number of respected `commitments1.remoteCommit.spec.htlcs.size` and `commitments1.localCommit.spec.htlcs.size` sometimes differ, is this an expected behavior?

This happens when nodes `A` and `B` constantly send a lot of HTLCs to each other. 

In lnwallet/Eclair case this often becomes severe and leads to channel close when lnwallet arrives at negative `val missing = reduced.toRemoteMsat / 1000 - commitments1.localParams.channelReserveSatoshis - fees` while Ecliair thinks it's still positive.

In Eclair/Eclair case HTLC number disparities also appear sometimes which yields different `missing` values. But a channel close did not yet happen because so far a `missing` value on sender side has been strictly equal or lower than on receiver side.

**Comment by pm47** [comment]
This is obviously not an expected behaviour. Any chance you can write a test that reproduces this issue? That would save us time.

> In Eclair/Eclair case HTLC number disparities also appear sometimes which yields different missing values.

What do you mean by yielding different `missing` values?

**Comment by btcontract** [comment]
I'm not sure if I can write a test. That specific test language is still unfamiliar to me, but I'll try!

Here's what I mean by different `missing` values, a complete example:

The network setup is as follows: `A` <-> `B` <-> `C`
`A` constantly sends `7000` SAT HTLCs to `C`, it is programmed to send new HTLC once an old one is fullfilled + new HTLC every 10 seconds, so the amount oh HTLCs in-flight slowly increases over time.
In turn `C` constantly sends `25000` SAT HTCLs to `B`

Output of `C`'s `sendAdd`:

```scala
val reduced = CommitmentSpec.reduce(commitments1.remoteCommit.spec, commitments1.remoteChanges.acked, commitments1.localChanges.proposed)
...
val missing = reduced.toRemoteMsat / 1000 - commitments1.remoteParams.channelReserveSatoshis - fees
...
log.info(s"send: amountMsat = ${add.amountMsat}, leftSatoshis = $missing, " +
      s"reserveSatoshis = ${commitments1.remoteParams.channelReserveSatoshis}, feesSatoshis = $fees, " +
      s"HTLCs in-flight: ${commitments1.remoteCommit.spec.htlcs.size}")
```

```
send: amountMsat = 25000000, leftSatoshis = 3083358, reserveSatoshis = 100000, feesSatoshis = 0, HTLCs in-flight: 6
send: amountMsat = 25000000, leftSatoshis = 3065358, reserveSatoshis = 100000, feesSatoshis = 0, HTLCs in-flight: 6
send: amountMsat = 25000000, leftSatoshis = 3040358, reserveSatoshis = 100000, feesSatoshis = 0, HTLCs in-flight: 7
send: amountMsat = 25000000, leftSatoshis = 3022358, reserveSatoshis = 100000, feesSatoshis = 0, HTLCs in-flight: 6
```

Output of corresponding `B`'s 'receiveAdd':

```scala
val reduced = CommitmentSpec.reduce(commitments1.localCommit.spec, commitments1.localChanges.acked, commitments1.remoteChanges.proposed)
...
val missing = reduced.toRemoteMsat / 1000 - commitments1.localParams.channelReserveSatoshis - fees
...
log.info(s"receive: amountMsat = ${add.amountMsat}, leftSatoshis = $missing, " +
        s"reserveSatoshis = ${commitments1.localParams.channelReserveSatoshis}, feesSatoshis = $fees, " +
        s"HTLCs in-flight: ${commitments1.localCommit.spec.htlcs.size}")
```

```
receive: amountMsat = 25000000, leftSatoshis = 3083358, reserveSatoshis = 100000, feesSatoshis = 0, HTLCs in-flight: 6
receive: amountMsat = 25000000, leftSatoshis = 3065358, reserveSatoshis = 100000, feesSatoshis = 0, HTLCs in-flight: 6
receive: amountMsat = 25000000, leftSatoshis = 3047358, reserveSatoshis = 100000, feesSatoshis = 0, HTLCs in-flight: 6
receive: amountMsat = 25000000, leftSatoshis = 3022358, reserveSatoshis = 100000, feesSatoshis = 0, HTLCs in-flight: 6
```
There's a disparity in line 3 and `missing` difference of `3040358` - `3047358` is exactly `7000` SAT, an amount of one of `A` -> `C` in-flight HTLCs I presume.

**Comment by pm47** [comment]
I am not sure I understand still...

In your first message you wrote:
> But a channel close did not yet happen because so far a missing value on sender side has been strictly equal or lower than on receiver side.

If eclair does not close the channel, it means that both parties agree at all time on the current number of htlcs because otherwise the commitment signature wouldn't match, right?

**Comment by btcontract** [comment]
Indeed. This little fact has been escaping me until now. But this stuff is not made up, it's a real output I've taken from two Eclair instances. I'll do some further testing with this info taken into account.

**Comment by btcontract** [comment]
Changing this code in method `sendAdd`:

```scala
val reduced = CommitmentSpec.reduce(commitments1.remoteCommit.spec, commitments1.remoteChanges.acked, commitments1.localChanges.proposed)
```

to this one:

```scala
val nextSpec = commitments1.remoteNextCommitInfo.left.toOption.map(_.nextRemoteCommit.spec).getOrElse(commitments1.remoteCommit.spec)
val reduced = CommitmentSpec.reduce(nextSpec, commitments1.remoteChanges.acked, commitments1.localChanges.proposed)
```

Solves all the problems described above. Output in `sendAdd`/`receiveAdd` becomes exactly the same both in Ecliar/Eclair and lnwallet/Eclair cases and no more channel closings in lnwallet/Eclair case.

**Comment by pm47** [comment]
Great find! We should totally base our estimates on the last sig we sent, event if we didn't yet receive the revocation, because messages are ordered.

I'll add a test that reproduces this. Thanks!
