### ISSUE TITLE
Eclair Mobile qr display/read problems

### ISSUE THREAD

**Issue by d4amenace** [ACINQ/eclair#1756]
I am currently developing a merchant app that uses inexpensive low quality 2megapixel cameras to capture images. C-lightning works well with eclair so until our custom client app is completed we were going to suggest using eclair mobile wallet. There is a problem though, the qr codes the app creates are difficult for low qual cameras to read. This problem is occuring with eclair mobile wallet codes and they clearly "look" different in your app. Who would I need to direct this issue to?

Eclair Mobile 0.4.13

**Comment by t-bast** [comment]
This is not an `eclair` issue, please open in [eclair-mobile](https://github.com/ACINQ/eclair-mobile) or [phoenix](https://github.com/ACINQ/phoenix)
