### ISSUE TITLE
A place to find plugins

### ISSUE THREAD

**Issue by btcontract** [ACINQ/eclair#1761]
Eclair now has at least these 3 plugins:

- https://github.com/btcontract/plugin-hosted-channels
- https://github.com/btcontract/plugin-chainswap
- https://github.com/engenegr/eclair-alarmbot-plugin

I think it's about time to create some place where Eclair plugins could be listed for easier discovery.

**Comment by t-bast** [comment]
You can simply add those to the `Plugins` section of the `README`?

**Comment by btcontract** [comment]
Seems like a good start, I'll do that.
