### ISSUE TITLE
config switch eclair.on-chain-fees.min-feerate doesn't work

### ISSUE THREAD

**Issue by viaj3ro** [ACINQ/eclair#1779]
the `eclair.on-chain-fees.min-feerate` setting keeps getting ignored. Even for my own claim main tx.

Imho this setting should always be used as the absolute minimum and never be ignored. No matter which kind of onchain tx (besides funding).

**Comment by t-bast** [comment]
Well, it should work. Are you sure you restarted your node after changing the config value, and the transaction you're seeing was created after that (and not a retransmit)?

**Comment by viaj3ro** [comment]
the transaction in question was this one: https://blockstream.info/nojs/tx/2855083c5f3b137ddd036ec80de6b7b18136eafd9982ee78f6e2630f9ead50c4

if claim main transactions are not created shortly after channel failure, I'm sure my node was already running with at least 8 s/b `min-feerate`

**Comment by t-bast** [comment]
Claim main is created immediately when the channel fails, that explains what you're seeing (all transactions that can be created when the channel fails are created immediately to ensure there's no risk they're "missed" later).

This will change in the future with more dynamic fees and RBF logic, but that's the behavior right now.

**Comment by viaj3ro** [comment]
ok, in that case I'm only 95% sure that my node was already running with 8 s/b `min-feerate` 
Will wait and see if my memory is just playing tricks on me or if future transactions meet the `min-feerate` value
