### ISSUE TITLE
Include support for Windows 10

### ISSUE THREAD

**Issue by seangrant82** [ACINQ/eclair#1782]
Issue: 
Previous versions used to have a Windows Installer but the most current releases only support Linux. 

Documentation indicates Windows support but there is no installer in Releases

**Comment by t-bast** [comment]
The documentation explains how to run `eclair` on windows: https://github.com/ACINQ/eclair/wiki/Run

Maybe you're talking about the GUI instead? It's been deprecated a long time ago: https://github.com/ACINQ/eclair/releases/tag/v0.4

You may want to have a look at https://github.com/Ride-The-Lightning/RTL if you want a GUI to plug into your node.
