### ISSUE TITLE
`DefaultDirectedGraph` can't find all available routes

### ISSUE THREAD

**Issue by btcontract** [ACINQ/eclair#179]
Eclair currently uses `DefaultDirectedGraph` which has a restriction of single edge between two vertexes so on a topology like this:
```
       ->
A -> B -> C
       ->
```
there are three possible routes but `DefaultDirectedGraph` will only find one. Changing `DefaultDirectedGraph` to `DirectedMultigraph` results in all possible routes being found.

**Comment by btcontract** [comment]
Aha, now I see the way Eclair works makes this limitation irrelevant.

**Comment by pm47** [comment]
I was pretty sure about it but wanted to check later. Good to know though!
