### ISSUE TITLE
BlockchainWatchdog doesn't work independently

### ISSUE THREAD

**Issue by engenegr** [ACINQ/eclair#1803]
I open this issue because of suggestion made by Anton.

The issue revealed as a result of other problems https://github.com/ACINQ/eclair/issues/1789.

In particular, I noticed that when ZMQ actor stops receiving blocks, BlockchainWatchdog also stops working and counting how many blocks node missed with regard to explorers.

**Comment by t-bast** [comment]
Yes you're right, I noticed that as well, we should have a timer that ticks if no block is found and verifies the secondary blockchain sources.
