### ISSUE TITLE
Add description_hash in createinvoice

### ISSUE THREAD

**Issue by engenegr** [ACINQ/eclair#1816]
Please add `description_hash` in `createinvoice` and in serialized invoice bolt11 as well.

I need it for LNURL-pay support.

Or just say if it is unacceptable/not needed.

**Comment by t-bast** [comment]
It sounds reasonable to me.
It shouldn't be too hard, it's a somewhat simple change in https://github.com/ACINQ/eclair/blob/master/eclair-node/src/main/scala/fr/acinq/eclair/api/handlers/Invoice.scala

> and in serialized invoice bolt11 as well.

A small clarification for implementers: this field should be added to the JSON serialization returned by the API (https://github.com/ACINQ/eclair/blob/9a20aade0a00f6ef4ad01247e34bbc4cbe4101cd/eclair-node/src/main/scala/fr/acinq/eclair/api/serde/JsonSerializers.scala#L284).

**Comment by btcontract** [comment]
Unless someone works on this already I'll do it next week.
