### ISSUE TITLE
Channel with small balance produces closing transactions without outputs

### ISSUE THREAD

**Issue by btcontract** [ACINQ/eclair#182]
It's currently possible to create a channel with capacity large enough to make a first commit tx but too small to make a valid closing tx. 

An example is balance of `8000 SAT` with `feeRatePerKw = 10000` for which Eclair produced a first remote commit tx with a `760 SAT` output and later a mutual closing tx which has no outputs.

One negative effect of this is a channel with such a balance stays in `CLOSING` state forever.  This happens in both cooperative and uncooperative close cases.

**Comment by pm47** [comment]
We should probably set a min capacity for channels.

I think we should add a recommendation about that in the spec.

**Comment by btcontract** [comment]
This seems to be a complex issue as this state may pop up in different phases and at different times.
My current approach is:

- when creating a channel: set a min capacity barrier (current fee per kb * 3)
- when receiving a `FundingSigned`: abort a channel if the first local commit tx outputs sum < dust
- when receiving a new `CommitSig`: close a channel unilaterally if new local commit tx outputs sum < dust
- when receiving a new `ClosingSigned`: close a channel unilaterally if new closing tx outputs sum < dust
- on uncooperative close: filter out every tier1-2 tx whose outputs sum < dust, treat channel as `CLOSED` if tier1-2 tx set is empty.

All the checks are done via modified `checkSpendable` method:

```scala

def checkSpendable[T <: TransactionWithInputInfo](txWithInputInfo: => T) = Try {
    val check = Map(txWithInputInfo.tx.txIn.head.outPoint -> txWithInputInfo.input.txOut)
    val totalOutputValue = txWithInputInfo.tx.txOut.map(_.amount).sum

    if (totalOutputValue < LNParams.dustLimit) throw new Exception("Dusty amount detected")
    Transaction.correctlySpends(txWithInputInfo.tx, check, STANDARD_SCRIPT_VERIFY_FLAGS)
    txWithInputInfo
  }.toOption
```

**Comment by btcontract** [comment]
Actually, irregardless of how good my solution is, checking for `txWithInputInfo.tx.txOut.isEmpty || txWithInputInfo.tx.txOut.exists(_.amount < LNParams.dustLimit)` would be better than summation.

**Comment by pm47** [comment]
Addressed at the spec level in https://github.com/lightningnetwork/lightning-rfc/pull/389.

**Comment by pm47** [comment]
Was this fixed with 5afd9fa0352a290335fbe93dedb12533a650362b?

**Comment by pm47** [comment]
@btcontract ping

**Comment by btcontract** [comment]
I can't reproduce this and get these outputs:

```
$ curl 127.0.0.1:8081 --user "eclair-cli:pass" -X POST -H "Contnt-Type: application/json" -d '{ "method": "open", "params": ["0218bc75cba78d378d864a0f41d4ccd67eb1eaa829464d37706702003069c003f8", 10000, 0, 150, 1] }'
{
  "result" : null,
  "error" : {
    "code" : 400,
    "message" : "command failed: peer sent error: 'channelReserveSatoshis too high: reserve=546 fundingRatio=0.0546 maxFundingRatio=0.05'"
  },
  "id" : "eclair-node"
}

$ curl 127.0.0.1:8081 --user "eclair-cli:pass" -X POST -H "Contnt-Type: application/json" -d '{ "method": "open", "params": ["0218bc75cba78d378d864a0f41d4ccd67eb1eaa829464d37706702003069c003f8", 11000, 0, 150, 1] }'
{
  "result" : null,
  "error" : {
    "code" : 400,
    "message" : "command failed: peer sent error: 'can't pay the fee: missingSatoshis=22126 reserveSatoshis=546 feesSatoshis=32580'"
  },
  "id" : "eclair-node"
```

**Comment by btcontract** [comment]
I can't reproduce this and get these outputs:

```
$ curl 127.0.0.1:8081 --user "eclair-cli:pass" -X POST -H "Contnt-Type: application/json" -d '{ "method": "open", "params": ["0218bc75cba78d378d864a0f41d4ccd67eb1eaa829464d37706702003069c003f8", 10000, 0, 150, 1] }'
{
  "result" : null,
  "error" : {
    "code" : 400,
    "message" : "command failed: peer sent error: 'channelReserveSatoshis too high: reserve=546 fundingRatio=0.0546 maxFundingRatio=0.05'"
  },
  "id" : "eclair-node"
}

$ curl 127.0.0.1:8081 --user "eclair-cli:pass" -X POST -H "Contnt-Type: application/json" -d '{ "method": "open", "params": ["0218bc75cba78d378d864a0f41d4ccd67eb1eaa829464d37706702003069c003f8", 11000, 0, 150, 1] }'
{
  "result" : null,
  "error" : {
    "code" : 400,
    "message" : "command failed: peer sent error: 'can't pay the fee: missingSatoshis=22126 reserveSatoshis=546 feesSatoshis=32580'"
  },
  "id" : "eclair-node"
```

**Comment by pm47** [comment]
So I guess this can be closed?

**Comment by btcontract** [comment]
Yes, I think so.
