### ISSUE TITLE
Useless condition

### ISSUE THREAD

**Issue by btcontract** [ACINQ/eclair#1820]
This condition does not make sense and produces the same thing in both cases: https://github.com/ACINQ/eclair/blob/76894bd2e1cba226d618ffd28aa38f5da4228f97/eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala#L1690-L1692
Can be reduced to 

```scala
// we start a new round of negotiation
goto(NEGOTIATING) sending d.localShutdow
```

Opening an inssue in case it's a bug of some kind.

**Comment by btcontract** [comment]
Yes, indeed I'm wrong here, it seemed to me an empty list is being merged, not appended. Well, what boosted my confidence is all current tests still pass when this code is removed.

**Comment by t-bast** [comment]
It could be worth a test, but it's not a critical piece of the channel logic, that's probably why it wasn't explicitly tested.
