### ISSUE TITLE
Location of plugin-resources

### ISSUE THREAD

**Issue by engenegr** [ACINQ/eclair#1830]
Currently Eclair looks for `plugin-resources` directory from inside the directory `run-eclair` was invoked.

Is it possible for node to look for plugin configs relatively to `.eclair` dir or `eclair.conf`?

**Comment by btcontract** [comment]
A bit to clarify here: `plugin-resources` is a directory I've started using when I realized that my HC plugin needs a config file of its own and also other file stuff (such as icon image). So I've decided to introduce a `./plugin-resources/<plugin-name>/` approach which is used in HC plugin and now in alarm bot plugin. 

I guess if this makes sense then at some point these approaches need to be solidified on some "plugin best practices" section or something like that.

**Comment by engenegr** [comment]
Thank you very much @btcontract. I didn't realize this is only hosted-channels thing and did the same in Telegram warnings bot just because it is convenient to have separate config.
