### ISSUE TITLE
Channel does not receive `CurrentBlockCount` events after restart

### ISSUE THREAD

**Issue by btcontract** [ACINQ/eclair#187]
Currently a channel only subscribes to `CurrentBlockCount` once on receiving a `FundingLocked` message in `WAIT_FOR_FUNDING_LOCKED` state. 

It does not re-enter this state after application restart and does not get `CurrentBlockCount` ever again which prevents node from closing a channel unilaterally if there are outdated outgoing HTLCs.

**Comment by pm47** [comment]
Indeed, we should put it back at the `SYNCING`->`NORMAL` and `SYNCING`->`SHUTDOWN` transitions.

The same holds true for `CurrentFeerate`...

**Comment by pm47** [comment]
You're right, the channel needs to subscribe *before* reaching `OFFLINE` state, when its next state would be `NORMAL` or `SHUTDOWN`.

**Comment by pm47** [comment]
I've actually opted for a more basic solution (see https://github.com/ACINQ/eclair/pull/195/commits/80249f476f2dfe36dce923f992a65f81f24e95d6), let's try to keep things simple!
