### ISSUE TITLE
Document /getsentinfo response 

### ISSUE THREAD

**Issue by pvyhnal-generalbytes** [ACINQ/eclair#1873]
I'm having some trouble finding what possible values could be returned in `/getsentinfo` `status.type` field. So far I got `failed`, `sent`, `pending`

https://acinq.github.io/eclair/#getsentinfo

I haven't managed to find that in source code either

thank you

**Comment by t-bast** [comment]
You can find the `sealed trait`s here:

- https://github.com/ACINQ/eclair/blob/95fffe348cbd42da70731fbf76f5cae48a97b678/eclair-core/src/main/scala/fr/acinq/eclair/db/PaymentsDb.scala#L105
- https://github.com/ACINQ/eclair/blob/95fffe348cbd42da70731fbf76f5cae48a97b678/eclair-core/src/main/scala/fr/acinq/eclair/db/PaymentsDb.scala#L153

If you'd like to help make the documentation better, please open a PR on the `slate-doc` branch (you just need to update the `index.html.md` file).

**Comment by pvyhnal-generalbytes** [comment]
Happy to help. I found this but not knowing scala I didn't know where is the "type" string value taken from?
```
    "status": {
      "type": "sent",
```

**Comment by t-bast** [comment]
The possible values are all the child types that `extend` this `trait`.
The string values are simply the names of the child types, lower-cased.

**Comment by pvyhnal-generalbytes** [comment]
I'm probably running an older version and in `getsentinfo` I'm getting `sent` but in the current version it will change to `succeeded`, right?

**Comment by t-bast** [comment]
Good catch, we are in fact manually translating those to strings here: https://github.com/ACINQ/eclair/blob/547d7e700f05960c0f52a79819a94686af186d96/eclair-core/src/main/scala/fr/acinq/eclair/json/JsonSerializers.scala#L354

That should give you the list of possible values!

**Comment by pvyhnal-generalbytes** [comment]
great, thanks

**Comment by t-bast** [comment]
Fix by #1877
