### ISSUE TITLE
Why are 2 confirmations necessary to create a lightning channel?

### ISSUE THREAD

**Issue by fresheneesz** [ACINQ/eclair#189]

**Comment by sstone** [comment]
LN channels are based:
- on a funding tx that is published to the blockchain and will be used for as long as the channel is open 
- and commitment txs which spend the funding tx, are not published (but are publishable) and which are updated whenever a payment is made.

If the funding tx is reorged away (or double spent) it all becomes very messy, and 2 confirmations was chosen, on testnet, as a compromise to get users started as quickly as possible without seeing their channels inexplicably go away too often. On mainnet (which is much more predictable) it would probably be 3 or 4 instead. This is also why we wait for 6 more confirmations before we announce channels.

For general questions/support about eclair we'd rather have users go to https://gitter.im/ACINQ/eclair. But this could also have been a good question for #lighting-dev.

Thanks!

**Comment by pm47** [comment]
I think this question has been answered? See also `minimum_depth` description in [BOLT 2](minimum_depth)
