### ISSUE TITLE
Graceful stop and DB unlock

### ISSUE THREAD

**Issue by engenegr** [ACINQ/eclair#1896]
I have sometimes
```
2021-08-06 13:06:42,501 ERROR f.a.e.d.p.PgUtils - cannot obtain lock on the database 
```
even when I do `kill -SIGTERM` which means that process should be stopped gracefully.

Isn't there any way to close connections to Postrgre so the node could be restarted immediately?

**Comment by pm47** [comment]
Yes, this is annoying. As a short term workaround you can delete the lock line in the database: `DELETE FROM lease` after stopping eclair. But only do this if you are sure there is no other instance running.

I have been thinking on a way to achieve this properly, with a shutdown hook that would explicitly release the lock. It's not trivial if we want to be safe.
