### ISSUE TITLE
Probing Acinq node using BOS give me errors

### ISSUE THREAD

**Issue by DutchHornet** [ACINQ/eclair#1913]
Using BOS to probe ACINQ gives me an error, I tested probing to other nodes and it worked fine.
err:
  - 503
  - UnexpectedErrorWhenPayingViaRoute
  -
    err:
      message: 2 UNKNOWN: cannot marshall failure *lnwire.InvalidOnionPayload
      stack:
        - Error: 2 UNKNOWN: cannot marshall failure *lnwire.InvalidOnionPayload
        -     at Object.callErrorFromStatus (/app/node_modules/lightning/node_mod
        -     at Object.onReceiveStatus (/app/node_modules/lightning/node_modules
        -     at Object.onReceiveStatus (/app/node_modules/lightning/node_modules
        -     at Object.onReceiveStatus (/app/node_modules/lightning/node_modules
        -     at /app/node_modules/lightning/node_modules/@grpc/grpc-js/build/src
        -     at processTicksAndRejections (node:internal/process/task_queues:78:

 -->
 A successful probe.

 Everytime I try and no matter what the amount I try to probe.

Umbrel through SSH

 My node name is Dutch.Hornet.

 $ bos probe 03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f 100000

checking_for_path_to: ACINQ 03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f

evaluating:
  - 696037x2219x7 ★ ★ ★ ☆
  - BCash_Is_Trash 0298f6074a454a1f5345cb2a7c6f9fce206cd0bf675d177cdbf0ca7508dd28852f. Fee rate: 0.00% (6)
  - 638565x749x0
  - CoinGate 0242a4ae0c5bef18048fbecf995094b74bfb0f7391418d71ed394784373f41e4f3. Fee rate: 0.00% (11)
  - 608428x1470x1

failure: TemporaryChannelFailure at 608428x1470x1 from CoinGate

evaluating:
  - 696037x2219x7 ★ ★ ★ ★
  - BCash_Is_Trash 0298f6074a454a1f5345cb2a7c6f9fce206cd0bf675d177cdbf0ca7508dd28852f. Fee rate: 0.01% (101)
  - 693896x1492x0
  - Vajrapani 03093c3867e6b11193c26caa446880319db7d122f8629ed9052965bccd356c24f4. Fee rate: 0.00% (1)
  - 693764x2472x1

failure: TemporaryChannelFailure at 693764x2472x1 from Vajrapani

evaluating:
  - 696037x2219x7 ★ ★ ★ ☆
  - BCash_Is_Trash 0298f6074a454a1f5345cb2a7c6f9fce206cd0bf675d177cdbf0ca7508dd28852f. Fee rate: 0.01% (68)
  - 694620x1468x1
  - MicelioMadrid 029b81d1aaf177fa00c1c5796360163bfa98ee4d5d0daa54c6f510d9e237f376e9. Fee rate: 0.01% (92)
  - 689394x1254x1

failure: TemporaryChannelFailure at 689394x1254x1 from MicelioMadrid

evaluating:
  - 696037x2219x7 ★ ★ ★ ☆
  - BCash_Is_Trash 0298f6074a454a1f5345cb2a7c6f9fce206cd0bf675d177cdbf0ca7508dd28852f. Fee rate: 0.00% (3)
  - 694741x1864x1
  - BRIDGE.LN 034b60f2348249534d72df4fc72b6169e577043f259a8402596153900c7a1d57a7. Fee rate: 0.01% (60)
  - 693769x2297x1

failure: TemporaryChannelFailure at 693769x2297x1 from BRIDGE.LN

evaluating:
  - 696037x2219x7 ★ ★ ★ ☆
  - BCash_Is_Trash 0298f6074a454a1f5345cb2a7c6f9fce206cd0bf675d177cdbf0ca7508dd28852f. Fee rate: 0.01% (101)
  - 693873x3069x0
  - Breez 031015a7839468a3c266d662d5bb21ea4cea24226936e2864a7ca4f2c3939836e0. Fee rate: 0.00% (11)
  - 693252x1060x0

failure: TemporaryChannelFailure at 693252x1060x0 from Breez

evaluating:
  - 692889x2203x0 ★ ★ ★ ☆
  - Carbon 029bbbb1dcb3a2bea9ddb7312be2569b212a3a8de03cd6278456316f294948d6b9. Fee rate: 0.00% (0)
  - 692936x1821x1
  - wildverick 034dd644c5b06f0e5845cd483bc8fc39ac3f4c85c7a73d83854324a3cd15a9ca81. Fee rate: 0.01% (100)
  - 693963x939x1

err:
  - 503
  - UnexpectedErrorWhenPayingViaRoute
  -
    err:
      message: 2 UNKNOWN: cannot marshall failure *lnwire.InvalidOnionPayload
      stack:
        - Error: 2 UNKNOWN: cannot marshall failure *lnwire.InvalidOnionPayload
        -     at Object.callErrorFromStatus (/app/node_modules/lightning/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
        -     at Object.onReceiveStatus (/app/node_modules/lightning/node_modules/@grpc/grpc-js/build/src/client.js:179:52)
        -     at Object.onReceiveStatus (/app/node_modules/lightning/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)
        -     at Object.onReceiveStatus (/app/node_modules/lightning/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
        -     at /app/node_modules/lightning/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78
        -     at processTicksAndRejections (node:internal/process/task_queues:78:11)

**Comment by t-bast** [comment]
A probe is by definition an invalid payment, but your probes are way too invalid: they don't even contain a `payment_secret`, which is why they're rejected with that error.

The spec (very) recently made `payment_secret` mandatory (see https://github.com/lightningnetwork/lightning-rfc/pull/887) so you should fix your probing code if you expect this to work.

**Comment by t-bast** [comment]
Closing this issue as it should instead be an issue on the probing code (which should send a `payment_secret` in the onion).

**Comment by alexbosworth** [comment]
Users can either update to lnd 0.13.1 or bos 10.7.9 to address this
