### ISSUE TITLE
Add cancelinvoice API 

### ISSUE THREAD

**Issue by Kukks** [ACINQ/eclair#1916]
A cancel invoice API would be great to be able to reject payments to invoices you no longer want paid.

**Comment by t-bast** [comment]
This is a duplicate of #1510

**Comment by btcontract** [comment]
I'm not sure it's a duplicate, what's desired here is to delete a not yet expired invoice.

**Comment by t-bast** [comment]
IMO a future `deleteinvoice` RPC should allow deleting non-expired invoices as well. The only case where it should reject the delete request is if the invoice has been paid.
