### ISSUE TITLE
Walletname bug

### ISSUE THREAD

**Issue by engenegr** [ACINQ/eclair#1933]
Hard to determine if it is Core's fault or Eclairs.

If wallet file stored somewhere not in `~/.bitcoin`, Eclair will fail.

Because Core Api will return 
```
  "walletname": "/path/to/wallet",
```

Eclair could parse string and take only `wallet` from it.

**Comment by t-bast** [comment]
This is weird, if what Bitcoin Core returns as `walletname` isn't what they accept in the wallet name field when we call them, I'd say it should be a bug on their side.

**Comment by engenegr** [comment]
@t-bast at some point I understand why Core returns full path. Because it is specified in config file. Maybe I could provide the same path in Eclair but it looks not cool.

**Comment by t-bast** [comment]
I'm not completely sure what you're proposing there.
Can you be more precise and detail exactly the setup, what part fails and how (logs)?

**Comment by engenegr** [comment]
I say that Eclair does not start if Core loaded wallet not from `.bitcoin` directory.
Obviously because it returns "/path/to/wallet" wallet name when Eclair requests Core at startup and expects "wallet".

**Comment by t-bast** [comment]
> Core loaded wallet not from .bitcoin directory.

Please detail that: how exactly did you create the wallet in Bitcoin Core and load it?

> because it returns "/path/to/wallet" wallet name

Same, please detail what returns that? What value have you put in your `eclair.conf`?

**Comment by engenegr** [comment]
bitcoin.conf
`wallet=/mnt/hdd/blockchain/eclair`
wallet loads automatically in this case.
eclair.conf
`eclair.bitcoind.wallet="eclair"`
Node doesn't start.

**Comment by t-bast** [comment]
If you call `bitcoind`'s `listwallets` RPC, is the wallet name they return `eclair` or `/mnt/hdd/blockchain/eclair`?
If it's `/mnt/hdd/blockchain/eclair`, have you tried setting this in `eclair.bitcoind.wallet`?

**Comment by engenegr** [comment]
No I didn't tried setting `/mnt/hdd/blockchain/eclair` in eclair.
I was in hurry to return node back online and just copied wallet inside `.bitcoin`.

**Comment by t-bast** [comment]
If that's what `bitcoind` uses as wallet name, then I think that's what you should put in `eclair.conf`.
If it works, there's no bug, it would be expected behavior.
If for some reason it doesn't work let me know, and we'll see if there are parsing issues on the eclair side that could explain.

**Comment by engenegr** [comment]
Okay. I understand this is non-issue for you. 
So I just try to memorize it as UX quirk.
