### ISSUE TITLE
API fails too much, no errors in the logs

### ISSUE THREAD

**Issue by fiatjaf** [ACINQ/eclair#1938]
I'm running an app (https://t.me/lntxbot) that uses the Eclair API. Eclair logs are filtered to only show ERROR events, and they show nothing, but my app have very frequent errors in which Éclair's API is just not online. The same app is listening to the Éclair websocket and it gets disconnected at the same time the API calls fail.

It is not consistent, it works, works, fails, fails, works and so on.

I'm running the latest `master` on Linux, openjdk 11, with a remote bitcoind.

Other information:

- I have the impression that these errors have started yesterday when I started running `master` because I wanted to use the zmq block hashes and not the zmq with full blocks.
- The logs also show errors from the "watchdog" that I don't remember seeing before yesterday. blockcypher fails all the time and outputs HTML to the logs for a Cloudflare antispam captcha, logs says bitcoinheaders is disabled, blockstream.info often times out, say the logs. I don't know if these things are related.

**Comment by t-bast** [comment]
> blockcypher fails all the time and outputs HTML to the logs for a Cloudflare antispam captcha, logs says bitcoinheaders is disabled

Are you using Tor? It looks like you're triggering the code from that PR: https://github.com/ACINQ/eclair/pull/1907
The PR added documentation about `blockcypher` being flaky over Tor and instructions on how to disable it.
That is very likely orthogonal to potential API issues though.

> my app have very frequent errors in which Éclair's API is just not online.

You'll need to be more accurate than that if you want us to be able to troubleshoot something.
Please try to get a better understanding of the issue and share the results in this issue.

**Comment by fiatjaf** [comment]
I think the issue was lack of memory in my server that was somehow causing Eclair to restart or the API to just hang until a timeout, sorry.
