### ISSUE TITLE
Eclair can't parse payment requests that have the "lightning://" prefix

### ISSUE THREAD

**Issue by fresheneesz** [ACINQ/eclair#196]
When pasting in a payment request that starts with "lighting://" (eg a request from [lightning labs' lightning app](https://github.com/lightninglabs/lightning-app) ), using "Paste a payment ...", it fails to read it correctly.  If I remove the prefix, it reads it correctly.

**Comment by dpad85** [comment]
The `lightning://` prefix is not standard yet but eclair wallet should be able to understand it and read the payment request.

This is fixed in the latest version (0.1.6) of eclair wallet that is deployed today.

**Comment by fresheneesz** [comment]
@dpad85 Can this please be reopened? I have the same error I originally reported but I'm using v0.2.2

**Comment by dpad85** [comment]
Well the issue was fixed for eclair-wallet 😄 It's confusing because we use the same repo for two different projects.

Yet it's true that eclair desktop gui should trim the prefix.

**Comment by dpad85** [comment]
I won't reopen this issue, let's use this one: https://github.com/ACINQ/eclair/issues/317

**Comment by fresheneesz** [comment]
@dpad85 Oh I didn't realize there are two projects using this same repository. But my problem is in fact on the mobile version 0.2.2 (not desktop).
