### ISSUE TITLE
Payment Failure with FinalIncorrectCltvExpiry when sending to lightning lab's lightning app

### ISSUE THREAD

**Issue by fresheneesz** [ACINQ/eclair#197]
I'm not sure if this is an issue on Eclair's end or on the other end, but I thought I'd bring it up here. It seems like this issue has been discussed here: https://github.com/cdecker/lightning-integration/issues/3

**Comment by sstone** [comment]
It was a "spec" issue that is being resolved, all implementations (eclair,lnd,lightingd) should be interoperable very soon (I'll update this issue).

**Comment by pm47** [comment]
Closed with 02683dfb430ed7bfb409557d2923b11e671971bd
