### ISSUE TITLE
SendToRoute doesn't return any useful info

### ISSUE THREAD

**Issue by viaj3ro** [ACINQ/eclair#1970]
It only returns `PaymentID` and `ParentID`. IIRC it used to return success or failure with useful information about failure reason.
Why was this changed? Should be changed back IMHO.

Now I have to query `GetSendInfo` which does return failures but does NOT return if the  payment actually went through. So all I get is all the recent failures but if the last attempt was a success I can only find out if I manually compare before and after channel balances.

**Comment by t-bast** [comment]
> IIRC it used to return success or failure with useful information about failure reason.

That must have been a really long time ago (many years), as the internal logic makes it very hard to do that (we would need to block until the payment completes before returning a response).

In particular, MPP happened and the `sendtoroute` API is a good way to do MPP "manually" (with the splitting done by a plugin), but that requires the API to return instantly with the corresponding payment IDs.

> Now I have to query GetSendInfo which does return failures but does NOT return if the payment actually went through.

I'm suspecting you're not providing the right ID. Please see the wiki page: https://github.com/ACINQ/eclair/wiki/Multipart-Payments
It will return something in both success and failure cases.

**Comment by viaj3ro** [comment]
It might have been the GUI back in the day that actually returned success/failure, not the API. Which ID do I have to provide? I thought all I can provide is the payment hash?

**Comment by viaj3ro** [comment]
It might have been the GUI back in the day that actually returned success/failure, not the API. Which ID do I have to provide? I thought all I can provide is the payment hash?

EDIT: I tried with the ID and same result. Only reports failures even though the last attempt succeeded.

Since just providing the payment hash returns all results (which only show failures, this is not surprising)

I double checked again and RTL shows the payment hash of the successful attempt and when I feed it to `getsendinfo` it only returns failures
