### ISSUE TITLE
Improve `updaterelayfee` JSON response 

### ISSUE THREAD

**Issue by t-bast** [ACINQ/eclair#1995]
Using `updaterelayfee` with eclair v0.6.2 returns the following:

```json
{
  "4881ea3050bd0d82a571db79984a4c1c432eb77a7349b1afac6198b92d740cca": "RES_SUCCESS(CMD_UPDATE_RELAY_FEE(null,10 msat,150,None),4881ea3050bd0d82a571db79984a4c1c432eb77a7349b1afac6198b92d740cca) (of class fr.acinq.eclair.channel.RES_SUCCESS)"
}
```

We should instead return something like:

```json
{
  "4881ea3050bd0d82a571db79984a4c1c432eb77a7349b1afac6198b92d740cca": {
    "feeBase": 10,
    "feeProportionalMillionths": 150
  }
}
```

Or in case of error:

```json
{
  "4881ea3050bd0d82a571db79984a4c1c432eb77a7349b1afac6198b92d740cca": "error message"
}
```

If possible, we should probably also fix #2001 at the same time.

**Comment by pm47** [comment]
I noticed those issues while working on the serializers and left it for later...

https://github.com/ACINQ/eclair/blob/master/eclair-core/src/main/scala/fr/acinq/eclair/json/JsonSerializers.scala#L178-L181

**Comment by n1bor** [comment]
+1 was just about to raise the issue!

**Comment by t-bast** [comment]
> Also with these APIs a simple common "result":"ok" or similar for all calls would make life easier for users (in addition to the detailed info).

Good idea. I'd rather use a boolean than a string though (e.g. `"success": true`).
