### ISSUE TITLE
Improve accuracy of `updateRelayFee` error reporting.

### ISSUE THREAD

**Issue by dscotese** [ACINQ/eclair#2001]
Submitting channelIDs causes the misleading error 
```
The form field 'nodeIds' was malformed:
list must be either json-encoded or comma separated
```

Since the list was comma-delimited sometimes and json-encoded sometimes, I would expect Eclair to return the error message
```
The form field 'nodeIds' was malformed:
the list contained malformed nodeIds.
```
To make it really helpful, it could suggest that the user may have passed channelIds instead of nodeIDs..

To reproduce the issue, pass channelIDs to updateRelayFee instead of nodeIDs, but ensure that the form field is a comma-separated or json-encoded list.

This was in Eclair v 0.6.2 on Windows 10 with 
```
openjdk 11.0.6 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)
```

**Comment by t-bast** [comment]
Fixed by #2047
