### ISSUE TITLE
Multiple failures when sending a payment from Eclair

### ISSUE THREAD

**Issue by btcontract** [ACINQ/eclair#2050]
@ncrashed tried to send a payment from his Eclair to SBW and was getting various (quite bizarre) failures.

Payer `nodeId` is `034a7b1ac1239ff2ac8438ce0a7ade1048514b77d4322f514e96918e6c13944861`.

SBW has two direct channels to payer node, also one private HC to `Motherbase`, another private HC to node `02cd1b7bc418fac2dc99f0ba350d60fa6c45fde5ab6017ee14df6425df485fb1dd` (SATM), so 4 channels in total.

The following routes with confirmed enough capacity exist:

- `payer` -> SBW (direct channel 1)
- `payer` -> SBW (direct channel 2)
- `payer` -> `Motherbase` -> SBW (HC 1)
- `payer` -> `SATM` -> SBW (HC 2)

First apparent issue is that if user produces an SBW invoice which contains a single direct channel hint then Eclair fails a payment with "route not found", `getsentinfo`: [eclair.getsentinfo.withhint.txt](https://github.com/ACINQ/eclair/files/7476715/eclair.getsentinfo.withhint.txt).

Second set of issues is when trying to pay to SBW invoice with all 4 channel hints: 
- direct channels are still not used.
- sending through `LNTXBOT` node has "a disconnection occurred with the first hop" which is related to other issue we have.
- `Motherbase` often replies with `UpdateFailMalformedHtlc`.

`getsentinfo`: [eclair.getsentinfo.txt](https://github.com/ACINQ/eclair/files/7476838/eclair.getsentinfo.txt)

Payer runs vanilla `0.6.2`.

**Comment by t-bast** [comment]
Don't you think it's just a side-effect of https://github.com/ACINQ/eclair/issues/2048?
Where channels are removed from the graph because of frequent disconnects and thus path-finding fails to find a route (because the channels aren't in the graph anymore)?

**Comment by btcontract** [comment]
User reports connection issues only with `LNTXBOT` node while connections to `SATM`, `Motherbase` and direct BLW channels are stable. Also I don't think connection issues can explain `UpdateFailMalformedHtlc` from Motherbase (which I do see in my logs).

**Comment by btcontract** [comment]
Another thing to add is that small payments work fine (which somewhat reminds `LNTXBOT` case where small payments also do work).

**Comment by t-bast** [comment]
All the errors I see still seem related though:

- channel 11249764x14542197x18712 is currently unavailable -> this channel is probably offline (connection issue)
- a disconnection occurred with the first hop -> connection issue
- channel 649417x2162x1 is currently unavailable -> this channel is probably offline (connection issue)
- first hop returned an UpdateFailMalformedHtlc message -> do you have logs from the side that sent `UpdateFailMalformedHtlc`? I'm very curious about this one, I don't see how an `eclair -> eclair` scenario could trigger these

Thanks for reporting this, I think there's definitely something fishy going on that we need to fix asap.

**Comment by NCrashed** [comment]
I indeed see some connection flickering for some channels like nicehash or lntxbot. Connection is stable for 100 peers and 6-10 peers are problematic with rapid online/offline status switching. But, mentioned short channel ids are not direct channels to me.

The `UpdateFailMalformedHtlc` message arrived from Eclair node where the HC is actually hosted.

**Comment by btcontract** [comment]
After inspecting logs more closely it turned out `UpdateFailMalformedHtlc` actually comes from SBW which we'll investigate separately.

**Comment by t-bast** [comment]
Closing this issue, as the investigation showed that this was either:

- the `UpdateFailMalformedHtlc` issue (on BLW side)
- a too low `ping-timeout`
- a too low fee budget
