### ISSUE TITLE
Documentation seems to indicate safecookie bitcoind auth excludes RPC.

### ISSUE THREAD

**Issue by dscotese** [ACINQ/eclair#2074]
At https://github.com/ACINQ/eclair/blob/master/docs/Configure.md#bitcoin-core-cookie-authentication the instructions state
```To use safecookie authentication, you need to remove rpcpassword=*** and rpcuser=*** from your bitcoin.conf and...```
 but this means that no other program that is using the Bitcoin RPC will be able to continue using it.

This instruction may be in place because Eclair does not support using a bitcoind that is also answering RPC calls unless Eclair itself is making RPC calls.  However, it makes more sense that this is a documentation oversight.

If bitcoind can only be used by other RPC clients when Eclair uses it that way, the documentation should explain that rather than leaving it to be inferred.  If RPC calls to bitcoind don't cause problems while Eclair uses safecookie authentication, the instruction should be revised.

**Comment by t-bast** [comment]
> However, it makes more sense that this is a documentation oversight.

No, that is intentional. The only goal of safe cookies is to avoid exposing a user/password API. So if other applications have to keep using user/password, it doesn't make sense to use safe cookies with eclair, just keep using user/password with eclair as well.

> If bitcoind can only be used by other RPC clients when Eclair uses it that way, the documentation should explain that rather than leaving it to be inferred.

Please open a PR to clarify if that was unclear to you.

**Comment by Thoragh** [comment]
Having `rpcpassword=***` and `rpcuser=***` in `bitcoin.conf` disables safecookie in Bitcoin Core so it need to be removed to use safecookie.
