### ISSUE TITLE
Automatically delete old expired invoices

### ISSUE THREAD

**Issue by fiatjaf** [ACINQ/eclair#2078]
Maybe I have too many invoices?

```
sqlite> select count(*) from received_payments;                                                                                                                                      
48508
sqlite> select count(*) from received_payments where received_at is null;
30772
```

Can I delete these? I'm not interested in keeping expired invoices in the database and would also be glad to get rid of successfully paid invoices from months ago.

**Comment by t-bast** [comment]
You can use the new `deleteinvoice` API: https://github.com/ACINQ/eclair/pull/1984

We also discussed in the past automatically deleting unpaid invoices that have expired, it shouldn't be hard to do, we even tagged this with "good first issue" but nobody picked it up.

**Comment by fiatjaf** [comment]
Can I delete it directly on the SQLite database?

**Comment by t-bast** [comment]
Yes you can, if you check that the invoice is expired and unpaid you're safe.
