### ISSUE TITLE
[Bug] SendToRoute doesn't allow to send via private channels

### ISSUE THREAD

**Issue by viaj3ro** [ACINQ/eclair#2081]
Trying to use the `SendToRoute` API to send via a private channel throws this error: 

```
router error: The sequence of channels provided cannot be used to build a route to the target node
```

**Comment by t-bast** [comment]
Indeed, the faulty line is here: https://github.com/ACINQ/eclair/blob/9792c725c777d18d538e16d55ac89a847ba8beef/eclair-core/src/main/scala/fr/acinq/eclair/router/RouteCalculation.scala#L72

We look only into the public channels map, we should also look into the private channels.
