### ISSUE TITLE
Add sendcustommessage and subscribecustommessage apis

### ISSUE THREAD

**Issue by benthecarman** [ACINQ/eclair#2088]
lnd and clightning both have the ability through the rpc to send and receive custom onion messages. It would be great to get the same functionality with eclair.

**Comment by t-bast** [comment]
#2061 already added the ability to send onion messages. It is then trivial to add an event to the websocket whenever we receive an onion message (we already emit an event, we just need to pipe it to the websocket).

**Comment by benthecarman** [comment]
Oh I see, it just hasn't been released yet
