### ISSUE TITLE
Unclear arguments to parse in the conf file

### ISSUE THREAD

**Issue by dinnerisserved** [ACINQ/eclair#209]
Inside application.conf the example is: 

```
eclair {

  chain = "test"
  spv = false // experimental!! do not use

  server {
    public-ips = [] // external ips, will be announced on the network
    binding-ip = "0.0.0.0"
    port = 9735
  }
  api {
    binding-ip = "127.0.0.1"
    port = 8080
  }
  bitcoind {
    host = "localhost"
    rpcport = 18332
    rpcuser = "testing123yo"
    rpcpassword = "DF02jfqw!fdovwmwe923CASDF"
    zmq = "tcp://127.0.0.1:29000"
  }
```

What parameters can go into "`chain`"? It says "`test`" right now, but what is the equivalent of live and testnet? Is it `live` and `testnet`? 

Also, what is the format in the eclair.conf file? 

`eclair.server.port=xxx`
`eclair.server.port="xxx"`
Or something third? 

It is also unclear if it only works with BitcoinD or also with Bitcoin-qt

**Comment by pm47** [comment]
> What parameters can go into "chain"? It says "test" right now, but what is the equivalent of live and testnet? Is it live and testnet?

"test" for testnet, "regtest" for regtest, no live option for now. Good point, this needs to be better documented.

> Also, what is the format in the eclair.conf file?
> eclair.server.port=xxx
> eclair.server.port="xxx"
> Or something third?

Either works, use quoted strings if you need special characters. Full ref [here](https://github.com/lightbend/config/blob/master/HOCON.md).

> It is also unclear if it only works with BitcoinD or also with Bitcoin-qt

Eclair works with both.

**Comment by dinnerisserved** [comment]
I see that case Block.LivenetGenesisBlock.hash => "lnbc"

val chainHash = chain match {

In [https://github.com/ACINQ/eclair/blob/93739eb3f17f5e13b9f967ebf483071a68e9ac78/eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala](url) is referencing testnet and regtest. Can we put live chain in the params and start running Eclair on live net? 

It is impossible to do any testing without live net, as testnet is not reliable. Is there a live Eclair version elsewhere we can use?

**Comment by dpad85** [comment]
> It is impossible to do any testing without live net, as testnet is not reliable.

If you want to test in a controlled environment you should probably use regtest.

> Can we put live chain in the params

It is currently not supported (on purpose), you would have to change the code.
