### ISSUE TITLE
Compatibility issue with latest master and RTL

### ISSUE THREAD

**Issue by viaj3ro** [ACINQ/eclair#2098]
I've updated to the latest master in order to have this issue patched: https://github.com/ACINQ/eclair/pull/2082

Unfortunately there seems to be a compatibility issue with RTL now. 

RTL can't retrieve the date of routed payments and aliases of incoming and outgoing node anymore. Missing Aliases could be an RTL issue. Missing date apparently not.
![image](https://user-images.githubusercontent.com/42124006/145612292-cb8f70f3-5bc4-4ddf-bb50-5a5ea534756e.png)

There seem to be some breaking changes between 0.6.2 and the latest master. Are they intentional? Will they stay as they are until the next official release?

**Comment by t-bast** [comment]
I guess you're thinking about the timestamp changes from this PR: https://github.com/ACINQ/eclair/pull/1990
They are indeed intentional, as they remove an inconsistency where API callers wouldn't know what format was used for timestamps, now it's been made explicit.
