### ISSUE TITLE
Error: bitcoind should be synchronized (initialblockdownload=true)

### ISSUE THREAD

**Issue by leffw** [ACINQ/eclair#2105]
## Error: bitcoind should be synchronized (initialblockdownload=true)

I am having this error running Eclair as RegTest.

```fatal error: assertion failed: bitcoind should be synchronized (initialblockdownload=true)```

### Configuration of Bitcoin.conf

```
# Daemon Options
server=1
# Network Options
regtest=1
# RPC Options
[regtest]
rpcuser=""
rpcpassword=""
txindex=1

# ZMQ Options
zmqpubrawblock=tcp://127.0.0.1:28332
zmqpubrawtx=tcp://127.0.0.1:28333
```

### Configuration of Eclair.
```
eclair {
    datadir = ${user.home}"/.eclair"
    chain = "regtest"
    
    bitcoind {
      host ="127.0.0.1"
      rpcport = 18443
      rpcuser = "root"
      rpcpassword = "root"
      zmqblock = "tcp://127.0.0.1:28332"
      zmqtx = "tcp://127.0.0.1:28333"
    }
}
```

**Comment by t-bast** [comment]
You need to generate some blocks on regtest, otherwise `bitcoind` considers itself as being the process of IBD, and you can't run a lightning node with a bitcoin node that hasn't finished IBD.

**Comment by t-bast** [comment]
Just run `bitcoin-cli generatetoaddress 150 <address>` and you'll be fine.
See https://github.com/t-bast/lightning-cfg/ for some helper scripts.
