### ISSUE TITLE
signmessage returns 65-byte signature in unknown format

### ISSUE THREAD

**Issue by Kixunil** [ACINQ/eclair#2121]
**Summary**
When using `signmessage` a 65-byte (130-hex digits) signature is returned but #1496 says it should be 64 bytes.

**Expected behavior**
`signmessage` returns 64-byte signature

**Actual behavior**

`signmessage` returned 65-byte signature, seems to be prefixed by constant `1f`
It also seems to be in some undocumented format since it can not be verified by `libsecp256k1` (I'm using the Rust crate).
Is the hash algorithm sha256?

**Steps to reproduce**

1. use `signmessage` API with any message
2. observe the `sigature` field of returned Json
Eclair version: 0.6.2

**Environment**

Linux, ARM64 openjdk 11.0.9

**Comment by Kixunil** [comment]
Looked into the code and figured it out. It's double sha256 the message is prefixed with `Lightning Signed Message:` and the signature is prefixed with recovery ID.
So I guess this is mostly documentation issue now (unless it was wrong to include recovery ID).

One more unfortunate thing is it's not even documented in bolts. Even signatures used in the protocol are underdocumented.

**Comment by t-bast** [comment]
> One more unfortunate thing is it's not even documented in bolts. Even signatures used in the protocol are underdocumented.

I completely agree with you on that.
The history of this feature was that lnd added the ability to sign and verify messages from your lightning node.
Users started to rely on this and build apps on top, and asked other implementations to support it, so c-lightning and eclair reverse-engineered what lnd did and implemented the same thing for compatibility's sake.

I don't think it should be in the BOLTs, but this really deserves a BLIP, for the sake of having a public specification.
If you have time to write that BLIP it would be helpful to everyone (similar to what has been done for keysend)!

**Comment by Kixunil** [comment]
Decided to draft the bLIP, please take a look. :)

**Comment by t-bast** [comment]
Closing this issue, fixed by https://github.com/lightning/blips/pull/8

**Comment by Kixunil** [comment]
May be still useful to reference blip 8 in the Eclair doc once it's merged.

**Comment by t-bast** [comment]
Sure, we can even open a PR on eclair to do that right now, right?
Can you open such PR?
I'll update the [eclair API doc](https://acinq.github.io/eclair/#introduction) once the blip is merged.

**Comment by Kixunil** [comment]
Wanted to open but can't find where the docs moved.

**Comment by t-bast** [comment]
I'll handle updating the API doc, it's not very intuitive (https://github.com/ACINQ/eclair/blob/master/BUILD.md#build-the-api-documentation).

I meant that it could be useful in the eclair _code_ to add a comment linking to the BLIP, and that's a PR you could do to add it where you think it makes sense (where you actually looked at the code to figure out why it didn't behave as you expected).

**Comment by Kixunil** [comment]
Ah, I looked at the API first and at the code only after opening the issue I looked at #1499 and figured it out. I find documenting the API the most important but I could imagine it being useful somewhere around https://github.com/ACINQ/eclair/pull/1499/files#diff-fb4a2d874e067b9c19c6eccf5b120756c786a68bc960151d6f867cb929991b20R410

**Comment by t-bast** [comment]
Gotcha, if you think documenting the code isn't very important let's skip it.
I'll update the API doc next time I change it (I tend to batch updates to the API doc and test APIs before I publish), it's been added to my todo-list.
