### ISSUE TITLE
Node URI format for QR scanner

### ISSUE THREAD

**Issue by btcontract** [ACINQ/eclair#218]
Eclair wallet allows to scan a node URI to open a channel, what is the format of that URI? Asking because want to be compatible with Eclair wallet on this detail.

**Comment by dpad85** [comment]
Hi Anton, Eclair wallet requires a node URI to match this regex:

```java
// <node_pubkey>@<host>:<ip>
([a-fA-F0-9]{66})@([a-zA-Z0-9:\\.\\-_]+):([0-9]+)
```

**Comment by btcontract** [comment]
No optional prefixes like `lightning://` or similar?

**Comment by pm47** [comment]
The URI is only for payment requests (see [BOLT 11](https://github.com/lightningnetwork/lightning-rfc/blob/master/11-payment-encoding.md#encoding-overview)) and should be `lightning:`, not `lightning://`.

**Comment by btcontract** [comment]
Got it, thanks.
