### ISSUE TITLE
Is endurance ok?

### ISSUE THREAD

**Issue by btcontract** [ACINQ/eclair#224]
Neither Eclair for Android nor LN wallet can establish a channel with it as of today. It is online but just does nothing after sending it's `Init`. Routing payments to starblocks also does not work with `UnknownNextPeer` returned by my Eclair instance.

**Comment by pm47** [comment]
We have updated our nodes to the latest version of the spec (with htlc-key), this is a breaking change.

Note: please use gitter for that kind of issues.

**Comment by btcontract** [comment]
got it
