### ISSUE TITLE
I got this error: "chainHash mismatch"

### ISSUE THREAD

**Issue by 9kek** [ACINQ/eclair#225]
Hi, i tried to run eclair on windows, using the .exe installer.
I also installed Bitcoin core v0.15.1 and run it in regtest mode using the bitcoin.conf file in the README.md file. I also mined some blocks in regtest mode.
But when i try to run eclair i get a "chainHash mismatch" error. Here is the complete message: https://i.imgur.com/XOoRB3i.jpg
Any suggestion on how to fix it?

**Comment by pm47** [comment]
eclair uses testnet by default, and your bitcoin core is configured for regtest.

In your [configuration file](https://github.com/ACINQ/eclair#configuration-file) set:
```
eclair.chain=regtest
```

Please leave the issue open, current README is misleading we need to fix that.

**Comment by 9kek** [comment]
i'm using windows, i didn't find a eclair.conf in the Eclair directory (C:\Users\<username>\AppData\Local\Eclair). I tried to make a new text file with the string "eclair.chain=regtest" in that directory, but i still get the same error.

**Comment by pm47** [comment]
Default datadir should be C:\Users\<username>\.eclair

Le 22 nov. 2017 23:14, "9kek" <notifications@github.com> a écrit :

i'm using windows, i didn't find a eclair.conf in the Eclair directory
(C:\Users<username>\AppData\Local\Eclair). I tried to make a new text file
with the string "eclair.chain=regtest" in that directory, but i still get
the same error.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/ACINQ/eclair/issues/225#issuecomment-346487291>, or mute
the thread

**Comment by 9kek** [comment]
Ok, now it's working, thanks for you help.
I'll leave the issue open for now, as you asked.

**Comment by pm47** [comment]
Note that if you are using the latest released version, it is pretty old.
We are shipping a new one in the coming days.

**Comment by 9kek** [comment]
I'll try also the new one when it will be avaible.

I have another question: is it possible to run 2 or more instances of eclair on the same computer? How?

**Comment by dpad85** [comment]
Yes, you can run as many instances of eclair as you like on the same machine. The catch is that each Eclair node requires its own `datadir` and these instances must listen on different ports.

The README explains [how to do it on command line](https://github.com/ACINQ/eclair#java-environment-variables) but it's kinda hidden and we need to rework it 😄

**Comment by 9kek** [comment]
I found how to setup different ports, and i managed to open different instances (using the same folder and deleting the seed .dat after opening one, lol). How can i specify the datadir folder?
Btw, in this configuration i can open channels beetween the different instance, but when trying to send coins it says it can't find route.

Also, i have additional questions:
- i've read here https://github.com/ACINQ/eclair/blob/master/eclair-core/src/main/resources/reference.conf there is experimental support for electrum, but if i set it, it seems that eclair simply ignores it and continues to search for bitcoind. I think support for electrum would be very useful (it permits to try lightning in testnet without dowloading the entire testnet blockchain)
- a question not specific about eclair: isn't it possible to send arbitrary amount of coins to a lightning user? seems it's all based on "payment request", but i think also sending arbitrary amounts would be useful

**Comment by pm47** [comment]
> it seems that eclair simply ignores it and continues to search for bitcoind

You are looking at the latest reference.conf, but are using an older release (Electrum support was added very recently). Just wait for the next release, or build yourself from master (it is really easy see BUILD.md).

> isn't it possible to send arbitrary amount of coins to a lightning user?

No, you need a payment request. This is not an eclair limitation, but due to how Lightning works.

**Comment by 9kek** [comment]
I see, so i'll wait for the next release to use it with electrum.

Yes i know it's not a eclair limitation, but i think it can be uncomfortable in some cases. For example a site that accepts donation of any amount. Yes, it is possible to create a web form that generates coustum payment request, but it's a little uncomfortable

**Comment by 9kek** [comment]
For example using bitcoin you can say "send the amount you want to my address X", it's easier.
Hope that will be some workaround to this in the future (ex. sending a "request of payment request", and the receiver can choose to automatically accept these requests)

**Comment by btcontract** [comment]
is it not technically possible to issue a payment request without an exact amount specified which essentially means "pay whatever you want"?

**Comment by pm47** [comment]
Yes it is possible, amount is optional. This [test vector](https://github.com/lightningnetwork/lightning-rfc/blob/master/11-payment-encoding.md#please-make-a-donation-of-any-amount-using-payment_hash-0001020304050607080900010203040506070809000102030405060708090102-to-me-03e7156ae33b0a208d0744199163177e909e80176e55d97a2f221ede0f934dd9ad) gives an example for a donation use case.

**Comment by 9kek** [comment]
Ok, so it is possible, good news. Will it be implemented also in the gui in future? At the moment if i don't write an amount, i get a "Amount must be numeric" error.

**Comment by 9kek** [comment]
Sorry if I reopen this but I have a problem.
I unistalled the old version (alpha5), I downloaded and installed the new version (alpha6) and made a simple eclair.conf with only this string:
watcher-type = "electrum"
I opened electrum in testnet mode and then run eclair, but i got the error "could not connect to bitcoin core using JSON-RPC". How to fix it? I want eclair to work with electrum, not with bitcoin core.

**Comment by pm47** [comment]
Please do not reuse old tickets for a different issue.

Also please use our [gitter](https://gitter.im/ACINQ/eclair) when you have questions of that kind.

That said, the configuration you are looking for is `eclair.watcher-type = "electrum"`.

Thanks!
