### ISSUE TITLE
`TemporaryNodeFailure` instead of `TemporaryChannelFailure`

### ISSUE THREAD

**Issue by btcontract** [ACINQ/eclair#227]
Happens in `master`, setup is as follows:

`A` - 1 channel -> `B` - 1 channel -> `C` - 2 channels -> `D`

When sending `A -> D` payments, `C` fails a payment with `TemporaryNodeFailure` once it's first `C -> D` channel gets exhausted. A more correct response would be `TemporaryChannelFailure` since `C -> D` still has a second channel which could be used.  

`TemporaryNodeFailure` causes `C` to be excluded from further route search which eventually fails a payment while it could be routed if `TemporaryChannelFailure` were to be received by `A`.

Just in case, older Eclair instances compiled from https://github.com/ACINQ/eclair/commit/5becef6fc61ccd2a826bed4709eff964c33cf3ef correctly return `TemporaryChannelFailure` in similar situation.

**Comment by pm47** [comment]
Looks like a regression caused by f71f3da027e9358d36c27c463060b0cabc22499d, looking into it...

**Comment by pm47** [comment]
Anton this commit should fix the regression, can you check?

**Comment by btcontract** [comment]
Yes, `C` responds with `TemporaryChannelFailure` now. Thanks for fixing it this fast!
