### ISSUE TITLE
Possible bug in RoutingHeuristics.normalize

### ISSUE THREAD

**Issue by barrybecker4** [ACINQ/eclair#2295]
While I was adding some tests for RoutingHeuristics.normalize I noticed something that doesn't seem right. 

If you normalize a value that == max, then you get `1.0` as the result.
If you normalize a value that is > max. then you get `0.99999` as the result.
If you normalize a value that is epsilon less than max, then you get a value between 0.99999 and 1.0 as the result.

I don't think that this is expected. According to the comment, the result should be in (0, 1) - meaning that 0 and 1 should be excluded. Yet, when value is max, you can get 1.

I think that maybe the intended implementation should be 

```
def normalize(value: Double, min: Double, max: Double): Double = {
  val extent = max - min
  val clampedValue = Math.min(Math.max(min, value), max)
  val normalized = (clampedValue - min) / extent
  Math.min(Math.max(0.00001D, normalized), 0.99999D)
}
```
or perhaps
```
def normalize(value: Double, min: Double, max: Double): Double = {
  val extent = max - min
  val clampedValue = Math.min(Math.max(min, value), max)
  0.00001D + 0.99998D * (clampedValue - min) / extent
}
```
The first way will give the same values as before in most cases, but clamp the result to [0.00001, 0.99999]
The second way scales the normalized value into [0.00001, 0.99999]. An advantage of this second approach is that values very close to the min and max will always be different.

Which is better?
Should I make a PR for this change?

**Comment by thomash-acinq** [comment]
You're right, the current implementation does not do what it claims to do. That's not a problem in practice because we don't rely on the fact that 0 and 1 are not possible return values. It would still be nice to fix it thought.

**Comment by barrybecker4** [comment]
I think the second approach is more correct because it avoids 0 and 1 while still returning different values near the extremes.
