### ISSUE TITLE
Dockerfile does not build for arm64

### ISSUE THREAD

**Issue by chrisguida** [ACINQ/eclair#2298]
`docker build .` inside the main repo dir fails with this error, on my M1 Mac. It also fails similarly in a cross-platform build using docker buildx:

```
% docker build .
[+] Building 1.4s (4/4) FINISHED                                                                                                                                                                            
 => [internal] load build definition from Dockerfile                                                                                                                                                   0.0s
 => => transferring dockerfile: 3.06kB                                                                                                                                                                 0.0s
 => [internal] load .dockerignore                                                                                                                                                                      0.0s
 => => transferring context: 99B                                                                                                                                                                       0.0s
 => ERROR [internal] load metadata for docker.io/adoptopenjdk/openjdk11:jdk-11.0.3_7-alpine                                                                                                            1.4s
 => CANCELED [internal] load metadata for docker.io/library/openjdk:11.0.4-jre-slim                                                                                                                    1.4s
------
 > [internal] load metadata for docker.io/adoptopenjdk/openjdk11:jdk-11.0.3_7-alpine:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: no match for platform in manifest sha256:012ff3a1fd9c9237b14f7522307f8f64a19da0f3db37015b3456dafa69a29c0e: not found
```

It appears that the openjdk alpine base image does not compile for arm64. I tried cloning [the openjdk-docker repo](https://github.com/AdoptOpenJDK/openjdk-docker) and building with `./build_all.sh` but that fails as well, with this error:

```
 % ./build_all.sh 
Snyk authentication token not set, skipping snyk analysis
Total reclaimed space: 0B
Total reclaimed space: 0B
==========================================================================================
                                                                                          
  14:27:19 :    Building Docker Images for Version 8 hotspot jdk build  
                                                                                          
==========================================================================================
Snyk authentication token not set, skipping snyk analysis
ERROR: Unsupported arch:arm64, Exiting
###############################################################

ERROR: Docker Build for Version 8 hotspot jdk failed.

###############################################################

WARNING: Pushing to AdoptOpenJDK repo on hub.docker.com
WARNING: If you did not intend this, quit now. (Sleep 5)
```

Eclair's docker image should build for arm64. This includes platforms such as MacOS and Raspberry Pi. I am attempting to pacakge Eclair for [EmbassyOS](https://github.com/Start9Labs/embassy-os), but that will not be possible until Eclair builds for arm64.

See above.

See above.

Cloned from this repo, git commit hash 9610fe30e308af64fd30d0953ccf2eb0da69b67a.

MacOS with an M1 (arm64) processor. Also linux, in a cross-platform build to arm64 for raspberry pi (`DOCKER_CLI_EXPERIMENTAL=enabled docker buildx build --platform=linux/arm64 -o type=docker,dest=image.tar .`)

Please fix this, as Eclair would be a great addition to the EmbassyOS marketplace :)

See above for error messages.

**Comment by sstone** [comment]
We do support linux arm64 (but not macos M1 yet), but yes this does not seem related. I won't be able to try this for a few days but can you try either updating the base image or specifying an arm64 platform when you build the image (I think there is an option for that)

**Comment by chrisguida** [comment]
@sstone you can specify a target platform when you use `docker buildx`, as I did here:

`DOCKER_CLI_EXPERIMENTAL=enabled docker buildx build --platform=linux/arm64 -o type=docker,dest=image.tar .`

I believe this should automatically request the arm64 version of the image, but I may be wrong.

The problem appears to be that there *is* no arm64 version of the base image.

I did notice [adoptopenjdk's "deprecation notice"](https://hub.docker.com/_/adoptopenjdk), which points the user to a [new official dockerhub repo](https://hub.docker.com/_/eclipse-temurin/). However a quick search of said repo for "11-alpine" only reveals a [single image with a single supported architecture for alpine (amd64)](https://hub.docker.com/_/eclipse-temurin/?tab=tags&page=1&name=11-alpine).

However, if the eclair Dockerfile could be adapted to debian rather than alpine, it looks like there's a [debian image](https://hub.docker.com/layers/eclipse-temurin/library/eclipse-temurin/11-jdk-jammy/images/sha256-2c22f55fda06c413474bc0b04b30917eb5bfcaa46d239dcd99d55ead5b28712d?context=explore) in the same dockerhub repo.

**Comment by chrisguida** [comment]
Ok sweet, that was easy: https://github.com/ACINQ/eclair/pull/2304

Turns out adapting to debian was a one-liner :)
