### ISSUE TITLE
Feature request: Create new function to ban channels for a defined time

### ISSUE THREAD

**Issue by DerEwige** [ACINQ/eclair#2364]
Currently (if enabled) channels get banned for a fixed duration if they fail a payment.
If you use a plugin to monitor all payment you might find some bad channels that fail all the time and want them black listed for longer.
The whole process to black list channels and automatically reinstating them is already there.
It is just not possible to manually call this and define a custom duration for the black list.

Allowing this would give plugins much better control over payment routes.
Also it would remove the need to pass long list of exclude channels to rout find commands.

Currently I have 1500 channels on my black list and have to pass them to each and every find route command.

**Comment by t-bast** [comment]
> Currently (if enabled) channels get banned for a fixed duration if they fail a payment.

We are in the process of changing that, as this behavior doesn't work well for nodes making many payments of various sizes.
We're instead moving to statistical remote balance estimation.

> The whole process to black list channels and automatically reinstating them is already there.
It is just not possible to manually call this and define a custom duration for the black list.

Agreed, that's something that could make sense.
But you're incorrect when you say that it's not possible to manually call this.
You simply have to send a `ExcludeChannel` message directly to the router from your plugin.
Then you decide when to send a `LiftChannelExclusion` message to the router after some duration that you decide.
All of this is already available to plugins today, no changes to `eclair` are needed.

**Comment by DerEwige** [comment]
Ok thanks a lot, will look into it.
Still having a bit of a problem finding my way around in Scala

**Comment by t-bast** [comment]
> Still having a bit of a problem finding my way around in Scala

Yeah, Scala does require time to learn, but it's worth it, once you get used to it it's really easy to navigate the codebase.

**Comment by DerEwige** [comment]
I've look into sending an ExcludeChannel message to the router.
But when I look at the code here [Router.scala](https://github.com/ACINQ/eclair/blob/v0.7.0/eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala )
It looks like it will it automatically schedule an LiftChannelExclusion after the default time

      case Event(ExcludeChannel(desc@ChannelDesc(shortChannelId, nodeId, _)), d) =>
        val banDuration = nodeParams.routerConf.channelExcludeDuration
        log.info("excluding shortChannelId={} from nodeId={} for duration={}", shortChannelId, nodeId, banDuration)
        context.system.scheduler.scheduleOnce(banDuration, self, LiftChannelExclusion(desc))
        stay() using d.copy(excludedChannels = d.excludedChannels + desc)
        
Or am I missing something?

**Comment by t-bast** [comment]
Good catch, indeed! But it's very straightforward to modify `ExcludeChannel` with a flag to make it permanent.

**Comment by DerEwige** [comment]
Actually I thought about adding a new Class ExcludeChannelWithDuration that has one more argument (the duration)
And then just banns the node for the given Duration or for ever if Duration is Zero.

**Comment by t-bast** [comment]
This is a trivial change and shouldn't be contentious, so I went ahead and implemented it in #2368, you can try it with your plugin.

**Comment by DerEwige** [comment]
Great. looking at your code. I understand now how options work in Scala now.
Man, I wished Java had this feature.

I already programmed and tested my own version with the plugin. But used a different Event class.
So it would not mess with any of your code base.

To add the duration as option, keeps backwards compatibility without the need of a new event.
Very nice.
