### ISSUE TITLE
Possible flaky issue opening channel to LND nodes 

### ISSUE THREAD

**Issue by dannydeezy** [ACINQ/eclair#2391]
I run an LND node on version `0.15.0-beta` and lately have had two separate node operators running Eclair `0.7` mention that their requests to open a channel with me were timing out. Others are able to open a channel to me just fine. One of the operators was able to open after waiting a day and retrying.

I'm wondering if some flaky incompatibility could have been introduced in Eclair `0.7`, or LND `0.15.0-beta`. I'm happy to do some investigation into both code bases, hoping somebody could give me some pointers on which direction to look in the Eclair codebase.

Apologies I don't have more info on the issue. I will try to get some logs from the other node operators.

**Comment by t-bast** [comment]
Sorry, but this isn't actionable at all...can you ask those eclair node operators to share the logs of the failed attempt(s)? Without that there isn't much we can do.

**Comment by DerEwige** [comment]
Hey @t-bast one of them is me.

I've attached 2 logs (already filtered)
The “bad” log is from an attempt that failed.
I tried more than a dozen times and always just got a timeout.
Tried to set channel type manually, fee rate, etc. Nothing worked always just no response.

Then suddenly it just worked without anything changed on my or his end.

The “god” log is from an attempt that worked like a day later.


[deezy.io.god.log](https://github.com/ACINQ/eclair/files/9402277/deezy.io.god.log)
[deezy.io.bad.log](https://github.com/ACINQ/eclair/files/9402278/deezy.io.bad.log)

**Comment by t-bast** [comment]
Thanks for the logs @DerEwige, it shows that the issue doesn't seem to be on the eclair side.

In the good case, eclair sends `open_channel` and receives `accept_channel`, and everything works fine.
In the bad case, eclair sends `open_channel` but then lnd never responds, so eclair cannot do anything else than wait and eventually timeout.

So you'll need to figure out why lnd doesn't respond to the `open_channel` message. The operator of the lnd node will have to look at their logs to see if they can figure out what happens, or ask for help from the lnd team to understand why lnd goes silent.

**Comment by dannydeezy** [comment]
thank you @t-bast will continue and follow-up on the LND side

**Comment by t-bast** [comment]
@dannydeezy were you able to get data from the lnd side? Meanwhile I'll close this issue as the current status indicates that this isn't an error in `eclair`, feel free to re-open if the lnd data indicates otherwise.

**Comment by Crypt-iQ** [comment]
Hi I believe this is because 0.7 eclair nodes used trampoline payment feature bits 50/51. So when they connect to LND nodes, the 0.15.1 LND nodes will interpret bit 51 as zero-conf, which requires scid-alias. The older eclair nodes don't have scid-alias set, so LND will fail the init handshake since zero-conf requires scid-alias to be set.

for ref: https://github.com/lightningnetwork/lnd/issues/6880

**Comment by Crypt-iQ** [comment]
Sorry I misread the OP.
