### ISSUE TITLE
No channel announcements are published for channels to a specific node, even though the channel is public.

### ISSUE THREAD

**Issue by DerEwige** [ACINQ/eclair#2420]
Eclair Version: (version=0.7.0 commit=a804905)

My node: [https://amboss.space/node/023631624e30ef7bcb2887e600da8e59608a093718bc40d35b7a57145a0f3db9af](https://amboss.space/node/023631624e30ef7bcb2887e600da8e59608a093718bc40d35b7a57145a0f3db9af)
Peer: [https://amboss.space/node/037172d2110c4148d6ed0c2790ec8be948458022425dced6794fede834be92af36](https://amboss.space/node/037172d2110c4148d6ed0c2790ec8be948458022425dced6794fede834be92af36)
Channel: [754056x2117x0.channel.log](https://github.com/ACINQ/eclair/files/9574355/754056x2117x0.channel.log)

I had this issue in the past already. When I open a channel to this peer, my node does not send out any announcements for this channel.

Even stranger, if I pass this shortChannelId into one of the API endpoints I get an error that the channel does not exist.
`java.lang.IllegalArgumentException: unknown channel: 754056x2117x0`
 (I guess the Node looks into the announcements and does not check the local channels for that)

What is even stranger, alle channels I opened after this channel, do also not get announced.

This issue happens every time I open a channel to this particular peer.

**Comment by t-bast** [comment]
Can you check in your logs whether your peer correctly sends you their `announcement_signatures`? If they don't, this is a bug on their side and we cannot do anything, without their signatures we simply cannot publish a `channel_announcement`.

**Comment by DerEwige** [comment]
@t-bast 

Here is the log of my node filtered by the peer NodeID from the moment the channel was opened: [754056x2117x0.channel.log](https://github.com/ACINQ/eclair/files/9574470/754056x2117x0.channel.log)

I dont see an `announcement_signature` in there.

But this should not affect channels to other nodes opened after this channel right?

**Comment by t-bast** [comment]
> I dont see an announcement_signature in there.

Me neither, so that's what I suspected, you're not receiving your peer's `announcement_signatures`, so your node cannot do anything about it...

> But this should not affect channels to other nodes opened after this channel right?

No, this should be completely independent. If other nodes aren't announced, this is probably for the same reason (not receiving `announcement_signatures`).

I only see two possibilities:

1. Your peer isn't sending `announcement_signatures`: it's a bug on their side, we cannot do anything about it
2. Your peer is sending `announcement_signatures` but it's somehow lost (cannot be parsed or doesn't use the right `channel_id`)

I would be surprised if (2) was the reason, I don't see why this would break suddenly.
The best course of action is to get in touch with your peers and ask them to check their logs to see if they're sending `announcement_signatures` or not. My bet is that some implementation out there has a regression and doesn't send them...

**Comment by DerEwige** [comment]
One of the channels I opened after the "problem" channel, is to a node I already had a channel before that worked without issues.
Now it is not working. 

I have currently 2 channels opend after the "problem" channel and both now sow the same behaviour as the problem channel.
I don't see why the node that worked for weeks before the "problem" channel should suddently not work anymore.

**Comment by DerEwige** [comment]
@t-bast 
I am going to do the following:

1.) I will wait till the "problem" channel is 26 hours old 
(I have a suspicion that the node is holding back it’s first announcement for 24 hours, based on past channel opening announcements)

2.) If after 26 hours the channel is still stuck. I will close it

3.) I will wait 2 more hours after that to see if the other 2 channels are now getting announced.

4.) If the 2 channels are still not getting announced I will close and reopen them.


I will let you know of the results

**Comment by t-bast** [comment]
It seems like there is a bug in the latest release of lnd that exactly matches this behavior: https://github.com/lightningnetwork/lnd/issues/6882

So this is a known bug on their side, they seem to have a patch ready but we'll need to wait for users to apply that patch.

**Comment by DerEwige** [comment]
@t-bast 
This indeed explains the "problem" channel with the node where it always happens

But it does not fully explain why the other channels I opend to nodes that did not show that behaviour in the past also show this issue.

I suspect a 2nd bug at work on eclair side.
That when eclair goes through the chanels to check it get's stuck at that channel without announcment_signature and does not check later channels.

In about 4 hours I can give you information if the other nodes started working once I closed the "problem" channel

**Comment by t-bast** [comment]
> But it does not fully explain why the other channels I opend to nodes that did not show that behaviour in the past also show this issue.

It does explain it if they simply upgraded their lnd software to the latest version.

> That when eclair goes through the chanels to check it get's stuck at that channel without announcment_signature and does not check later channels.

With the way the code works, I really don't think that's possible.
Every channel is its own actor, fully independent of other channels.
When you have multiple channels with the same node, the fact that it's the same node doesn't have any impact.

To be honest I'm almost certain this is only linked to the lnd bug, but let me know if you find something.

**Comment by DerEwige** [comment]
@t-bast 
looks like you are right
I've managed to contact one of the other 2 nodes showing the problem and the owner confirms he is running LND 0.15.1-beta
