### ISSUE TITLE
Delay considering a channel closed when seeing an on-chain spend

### ISSUE THREAD

**Issue by t-bast** [ACINQ/eclair#2437]
See https://github.com/lightning/bolts/pull/1004

This is something we should do whenever possible, as it will be necessary for splicing to have most of the network delay when they consider a channel closed (to allow a new `channel_update` to come in to notify that the channel was actually just spliced, not closed).

This isn't trivial to do, because we don't have any way of tracking that state yet. We may need to add a new list in `Router.Data` to track channels that have been spent on chain and are waiting to be either removed or for which we will receive a `channel_update` with a new funding outpoint (when it was a splice, not a close).

**Comment by remyers** [comment]
Fixed by #2936
