### ISSUE TITLE
Sending `ChannelUpdate` for a non-public channel

### ISSUE THREAD

**Issue by btcontract** [ACINQ/eclair#244]
Currently Eclair won't send a `ChannelUpdate` to a peer which opens a non-public channel so peer can't use it to accept incoming payments. This is unfortunate since in my understanding most phone clients better have a non-public channels since they won't be routing payments anyway and also node graph could be trimmed enormously by doing this.

If this is fine I could try to implement sending `ChannelUpdate`'s, too, it seems to be an easy task.

I understand this is not urgent since at start phone wallets won't be able to receive payments anyway but at least this could be tried on testnet.

**Comment by pm47** [comment]
Good catch, I'm actually working on this as part of #230.

**Comment by pm47** [comment]
Fixed in commit f47ea72369c7bb9d01986ce9dbba00e37b83197d.

**Comment by btcontract** [comment]
It does not seem to work, neither for public non for private channels.
Eclair does send a `ChannelUpdate` to `Relayer` on `WAIT_FOR_FUNDING_LOCKED` -> `NORMAL` in
https://github.com/ACINQ/eclair/blob/master/eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala#L440 

but If I get it right by looking at `Relayer.scala` code, `relayer ! initialChannelUpdate` will just update it's channels map but won't actually send an update.

**Comment by pm47** [comment]
Can you try with 6ad115c17af29b9e0e811955819a9a7975d2e860? Remote should receive a `channel_update` after 6 blocks, even for private channels.

**Comment by btcontract** [comment]
it works fine now
