### ISSUE TITLE
Add API to delete unpaid expired invoices

### ISSUE THREAD

**Issue by ShahanaFarooqui** [ACINQ/eclair#2449]
Currently we do not have any option to delete unpaid expired invoices. 

With growing number of records, it is becoming time consuming to fetch all invoices. However, we can save some time by deleting unpaid & already expired invoices from the node.

**Comment by t-bast** [comment]
This has already been fixed in February: https://github.com/ACINQ/eclair/pull/2174
This is available in [eclair v0.7.0](https://github.com/ACINQ/eclair/blob/master/docs/release-notes/eclair-v0.7.0.md).
There is a `deleteinvoice` API available, and they can automatically be cleaned up if you configure your node accordingly.

**Comment by ShahanaFarooqui** [comment]
Deleting invoices in thousands via this API call can be very time consuming. First I have to fetch all invoices, filter out unpaid expired invoices and then call this API for each invoice separately. 

An API to delete all expired unpaid invoices in a single call will be much cleaner and efficient way for us to delete them in bulk.

**Comment by t-bast** [comment]
But why do you need that in the first place since eclair automatically cleans up those expired invoices at a configurable interval? This will always be more efficient that doing it through an API...

See #2174

**Comment by ShahanaFarooqui** [comment]
@t-bast That is perfect, exactly what we needed. Thank you. 

Do you have an official link on how to configure the interval? Is this a correct [link](https://github.com/ACINQ/eclair/pull/2210/files) to share?

**Comment by t-bast** [comment]
My first comment was wrong, this wasn't included in eclair's 0.7.0 release, my bad! This isn't yet in any of the released versions of eclair, but we should make a release soon :tm: that will include it, along with documentation on how to properly configure this.

Meanwhile, for users that use the `master` branch, the pending release notes explains how to set this: https://github.com/ACINQ/eclair/blob/master/docs/release-notes/eclair-vnext.md#expired-incoming-invoices-now-purged-if-unpaid
