### ISSUE TITLE
Add some blockchain.fee tests and minor refactoring

### ISSUE THREAD

**Issue by barrybecker4** [ACINQ/eclair#2453]
As part of my learning and getting familiar with the codebase I would like to add some additional feerate tests and perhaps do some minor refactoring. I asked some preliminary questions in [this discussion](https://github.com/ACINQ/eclair/discussions/2446).

To keep the scope very small, here is what I propose in my initial change:
- Use case classes for the feerate classes because they are immutable.
- Add a test to BitcoinCoreFeeProviderSpec to verify that an error with the correct message occurs when we try to get fee rates when no fee rate is found.
- Add a test spec for ConstantFeeProvider where none currently exists.

**Comment by barrybecker4** [comment]
One thing that I noticed while testing is that `feePerBlock(0)` for [FeeratesPerKB](https://github.com/ACINQ/eclair/blob/06ead3cf28c299825e87bc579f0b0d3146891462/eclair-core/src/main/scala/fr/acinq/eclair/blockchain/fee/FeeProvider.scala#L112) returns an incorrect value. It returns `blocks_6` instead of either an error or `mempoolMinFee`. Would it be better to add `require(target > 0)` to feePerBlock or return membpooMinFee if target <= 0? I suspect that having a target <= 0 doesn't make sense, so probably the require is better.

**Comment by t-bast** [comment]
Fixed by #2454
