### ISSUE TITLE
Expired invoices are filtered out from list invoices with v0.8.0

### ISSUE THREAD

**Issue by ShahanaFarooqui** [ACINQ/eclair#2530]
Previously `listinvoices` used to respond with all available invoices in the node. But with v0.8.0, all expired invoices are being filtered out from the list.

Were expired invoices deleted, filtered by design or is it a bug?

**Comment by t-bast** [comment]
Isn't it just because the invoice purger ran and removed the invoices from the DB? You can disable it if you want to keep those around in the DB: https://github.com/ACINQ/eclair/blob/master/docs/release-notes/eclair-v0.8.0.md#expired-incoming-invoices-now-purged-if-unpaid
