### ISSUE TITLE
N/A USD amount after app restart

### ISSUE THREAD

**Issue by btcontract** [ACINQ/eclair#259]
Select amounts to be displayed in USD, restart an app, it's all N/A

![screenshot_2017-12-07-07-28-27-951_fr acinq eclair wallet](https://user-images.githubusercontent.com/9870980/33700235-aeaf76e6-db20-11e7-911e-5d8e0cf727ec.png)

**Comment by dpad85** [comment]
Thanks Anton, this can happen when the exchange API responds a bit slowly, the application does not handle this case well and the display falls back to `N/A`. Will fix!

If you click on the balance in the top section, this will refresh the display with - hopefully - the current fiat value.

**Comment by dpad85** [comment]
The last known exchange rates are now persisted in the phone and the app will at least display a readable data for the fiat value of bitcoin amounts. This will be available in the next release (0.2.3)

However this may confuse the user if the bitcoin price varied a lot which makes the last known exchange rate obsolete and for some reason the app can not fetch the latest price from the API.

This seems like a reasonable compromise.

**Comment by dpad85** [comment]
Available in the released version 0.2.3
