### ISSUE TITLE
"Capacity is not valid" when trying to fund a channel using SAT as unit

### ISSUE THREAD

**Issue by btcontract** [ACINQ/eclair#260]
10,000,000 SAT yields a warning while the same amount entered as 100 mBTC passes
![screenshot from 2017-12-07 09-54-13](https://user-images.githubusercontent.com/9870980/33704472-4488b038-db35-11e7-885a-7dc87e9a823d.png)

**Comment by dpad85** [comment]
There was a mismatch between hardcoded units labels, #261 fixes this
Thanks!
