### ISSUE TITLE
Closing channels in Switchboard Init can cause issues due to long running deletes on htlc_infos table.

### ISSUE THREAD

**Issue by n1bor** [ACINQ/eclair#2610]
This table ends up with 100's millions of rows in it (billions??). And channels can have 400k++ rows each.

When channels close deleting all these rows in one go takes many minutes. So I think it hung my node effectively for 30++mins.

And if your node has been down for a while - hours - due to issues - the node gets stuck waiting on these deletes.
This really confused me for a while - did multiple restarts/changed DB RDS size etc....... vacuumed / analyzed etc....

It has now cleared the backlog of deletes and is working fine again.

I am wondering if this delete of the rows in htlc_info should be done as a background task rather than inline.

So remove this section:
https://github.com/ACINQ/eclair/blob/master/eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgChannelsDb.scala#L210

and instead run a maintainer thread that ran:
delete from local.htlc_infos WHERE channel_id not in (select channel_id from local.channels where is_closed=FALSE) limit 10000
every few minutes or something.

**Comment by rorp** [comment]
That makes perfect sense. Just running `select count(*) from htlc_infos where channel_id=?` can take minutes on 400k rows. And in this case the `delete` statement from `PgChannelsDb` creates a huge transaction, that could potentially hurt the performance of  whole Postgres DB server.

**Comment by n1bor** [comment]
I think this is the line that caused me issues:
https://github.com/ACINQ/eclair/blob/a52a10a0404cf908d352315a7a49348ca80847cc/eclair-core/src/main/scala/fr/acinq/eclair/io/Switchboard.scala#L54

Problem is that then it looks like there is some start-up issue - as logs look odd - not the normal peer connections etc...

Solution was just to be patient for all the deletes to run. But am sure it was over 15mins I had to wait.
