### ISSUE TITLE
Eclair mobile wallet UI

### ISSUE THREAD

**Issue by Sgt-Miller** [ACINQ/eclair#263]
1. Its really hard to know that there is a text box for channel capacity in the "open a new lightning channel" box. The user has to click on a particular tiny spot to activate the text box. 
I would say when the user requests to open a channel(autoconnect, scan or paste) and gets to the "open a new lightning channel" box, the text box is automatically selected and the keypad automatically pops up. 
Another reddit user said the same.
2. Is there a way to open the eclair app automatically when I click on a LN payment request on a website?
3. Go to the third tab "Lightning Channels".
     Click the + button
     Now you changed your mind and you don't want to open a channel, so you click on the 
    whitespace on the left to close the option list (paste, scan autoconnect).
But that list doesn't go. Make it so that if I click anywhere else, the list goes off.

**Comment by dpad85** [comment]
1. Yes, it's a good idea, will do!

2. Yes, the app opens uri starting with the `lightning:` and `bitcoin:` schemes

In a website you would have:
````html
<a href="lightning:lntb17u1pdzjfsrpp53sele9yl60lj2jc7l4xgnzremtm9ppwe5056v6axeplx68pqj0uqdpzxysy2umswfjhxum0yppk76twypgxzmnwvyyr26ucueg2vsp8ssslxt224k9myygclk8vsv29wy54rey4eu2eh37aqvpgxza05mqkjyeca5g33e6l3488h5t7mjgqqqpxn62q9gc3sqn5f5e6" target="_blank">Open with your wallet</a>
```

There is an button like this at the bottom of starblock's order pages

3. It's a good idea, thanks! Btw, if you click on the `+` button (which by now has become an `x`) it does just that but I guess this is not really obvious 😄 

Thanks for your feedback 👍

**Comment by dpad85** [comment]
Last release of eclair wallet (0.2.2) fixes 1).
