### ISSUE TITLE
Eclair stopped routing payments

### ISSUE THREAD

**Issue by evd0kim** [ACINQ/eclair#2645]
### What behaviour did you expect? 

I expected that I can send payments through public Eclair node. The node itself routes payments from external network it is unable to route payments from closest peers.

### What was the actual behaviour? 

Payments fail instantly (in case the channel is Hosted channel) or after a while in case the channel is unannounced channel opened with SBW wallet, or another non-public Eclair node. Payment sizes from 1000 to 100 000 sats. Public node has plenty of liquidity for such payment. Tested directions WOS, LN.TIPS, SBW-> Public Eclair -> Private Eclair. 

### How reliably can you reproduce the issue, what are the steps to do so? 

Payments do not go anywhere since a while ago. Systemic issue. I created alternative channel in SBW with Blixt node and it works. I removed Hosted channel plugin and it didn't help routing payments from real unannounced channel.

### What version of Eclair are you using, where did you get it (website, self-compiled, etc)? 

Tested versions: `0.7.0-patch-disconnect-cad88bf` and `0.7.1-SNAPSHOT-64211f1`. Both versions expose the same behavior. 

### What environment are you observing the error on (OS, JDK version)? 

Routing node runs on Debian, OpenJDK. Private Eclair runs on Fedora, OpenJDK. SBW -- Android.

### Any extra information that might be useful in the debugging process. 

No extra information. No errors, no warnings in logs.

Debug info from SBW:
- Local failure: no-routes-found

Config:
https://pastebin.com/MX42kmU2

**Comment by evd0kim** [comment]
Complete reset of the graph helped with restoring node routing capabilities for unannounced and hosted channels.

**Comment by rorp** [comment]
Prolly it makes sense to add an RPC call to purge the network database.

**Comment by evd0kim** [comment]
I am thinking now if Eclair supplied wrong data to SBW and Valet so Valet is unable to make payments still because it updates graph rarely.

**Comment by t-bast** [comment]
I'm not sure I understand your setup correctly, there isn't enough information to troubleshoot this.
Can you provide the output of the `channels` API from the `Eclair Routing Node`?
That will let us see what channels are actually available, with their exact balance, and the associated node IDs.

> I have one key question with regard to this information: why there may be a node 031015a7839468a3c266d662d5bb21ea4cea24226936e2864a7ca4f2c3939836e0 which has no direct channels with either sender or public Eclair node (router)?

How do you actually make that (failed) payment?

That could be the issue: this routing information is usually taken from the invoice, and tells the sender that they can reach the recipient by going through a private channel from node `031015a7839468a3c266d662d5bb21ea4cea24226936e2864a7ca4f2c3939836e0`. But if the sender cannot reach node `031015a7839468a3c266d662d5bb21ea4cea24226936e2864a7ca4f2c3939836e0`, it is expected that it results in a `route not found` error.

**Comment by evd0kim** [comment]
> there isn't enough information to troubleshoot this.

Exactly. That was the issue: the node stopped routing without any errors or warnings whatsoever. 

What worked:

1. All network tables were dropped.
2. No changes of the channels fees were done anymore
2. After a while, SBW started re-syncing and resumed sending payments. Some days later Valet started sending payments through Eclair node. Also after re-syncing graph.
