### ISSUE TITLE
[Mobile Wallet] Assume default port as 9735

### ISSUE THREAD

**Issue by Sgt-Miller** [ACINQ/eclair#265]
Scanning/pasting a node URI without a port number results in an error. In these cases, just assume the default port number to be 9735.
Services such as yalls.org , htlc.me etc all have the default port number so they didn't bother to specify the port number.
So when the user scans/pastes 
02a35187c5a71676da4930d93faaf30f6d5e19e3bbe8f3ead400b898967e1dc475@45.77.115.33
The wallet should assume it is 
02a35187c5a71676da4930d93faaf30f6d5e19e3bbe8f3ead400b898967e1dc475@45.77.115.33:9735

**Comment by dpad85** [comment]
Thanks for this proposal!
It will be included in the next release of eclair wallet, with `9735 `as the default port.

**Comment by dpad85** [comment]
Should not have closed it since the release is not available yet. Expected release version: `0.2.1`

**Comment by dpad85** [comment]
Fixed and released in `0.2.2`
