### ISSUE TITLE
[Mobile Wallet] - Error messages

### ISSUE THREAD

**Issue by Sgt-Miller** [ACINQ/eclair#266]
I'm not a programmer, so if this is not the correct place for this, please do say so. I'm not very familiar with github.
1. Show a message called : Node doesn't exist
I scanned a URI of a node which doesn't actually exist(I changed the ip of a node to something random).
The status goes from wait_for_channel_accept to closed, and then it goes away. For newbies like us a error message saying "node not found" would be user friendly.
2. Show a message for : Path not found after some timeout
I scanned a payment request for a service but its still stuck in pending. I didn't have a direct channel with them.
What happens to this payment? After a path is found, lets say hours later, because I opened a channel with them, will this payment go through? Or should I pay again?
3. Where are the log files on android stored? I tried to open the wallet this morning but It got stuck on this screen( https://my.mixtape.moe/knqqvp.png ) and then it closed. It works fine now, though so I'll try to post the log if I know where the log file is stored.
4. What does this mean? Is this an issue on the receiving side? ( https://my.mixtape.moe/lrbwek.png ) 
5. While scanning a payment request, having a newline or space at the end of the payment request results in "payment failed". It should be possible to remove trailing white spaces automatically in the app? 

Btw, I've had so many successful transactions. I have enough testnet_drinks and testnet_food to last an year. I have refilled my testnet_phonebalance so many times. I'm really liking this app!

**Comment by dpad85** [comment]
5) issue has been fixed, and the fix will be available in the next version (0.2.3)

**Comment by tfestate** [comment]
Hi - I downloaded the mobile wallet from google play and sent 1.1 tbtc to it a few hours ago. it doesn't appear that the wallet is downloading the block headers from an electrum server. data storage stays at 376KB. i'm connected, am able to use my electrum wallet with no problem

i double checked the receive address and checked the tx id on the blockchain...many confirmations.

any ideas what is should do to get the wallet synced so i can try out lightning sends? 

thanks...looking forward to trying this out.
