### ISSUE TITLE
Need a way to check for the payment of an invoice/payment request that has been issued

### ISSUE THREAD

**Issue by ghanavati27** [ACINQ/eclair#270]
Thank you for your great program.
I installed Eclair v0.2-alpha6 on my windows server 2012R2 and program working very well.
I want integrate it with my test site  but how Eclair node will notify us when we receive a payment in channels ?
We need to something like walletnotify or ZeroMQ in Bitcoin-qt for receiving messages from Eclair node.

**Comment by ghanavati27** [comment]
or same as this http://api.lightning.community/#subscribeinvoices

**Comment by AndySchroder** [comment]
I too would like this feature. I think your issue title is very poor and not very specific though. Can you edit it to say "Need a way to check for the payment of an invoice/payment request that has been issued"? I don't seem to have the authority to edit your issue title.

**Comment by ghanavati27** [comment]
@AndySchroder Done. Thank you

**Comment by ghanavati27** [comment]
Implemented APIs in LND are very usefully.
But Eclair still is not.
I using LND node : see it http://88.99.209.230

**Comment by AndySchroder** [comment]
It looks like your wiki page is not updated to include this. I'm wondering if the wiki page should be deleted and just keep everything in the readme file so that there is only one place for updates to be listed?

**Comment by AndySchroder** [comment]
Any way to return the value paid instead of true or false? For the case where you provide a payment request without a specific amount, there doesn't seem to be a way to know how much they actually paid.
