### ISSUE TITLE
Restore from seed

### ISSUE THREAD

**Issue by rodasmith** [ACINQ/eclair#271]
It looks like there isn't a way to restore an eclair wallet from the 12-word seed yet. After resetting the app data to upgrade to the latest release, my upgraded eclair testnet wallet generated a new 12-word seed. There should be an option to input an old seed upon a fresh install.

**Comment by dpad85** [comment]
This is indeed a important yet missing feature!

**Comment by prugi** [comment]
Thanks YOu sorry for not answering fone but im at the meeting ( and will be all day longg : (  ) Could You pleasee guild me ( beginner ) to straight things up?

**Comment by prugi** [comment]
really big Thanks for Your band eng help me.  even if my feature with ac/ec
will gone ( as You Can see my english is poor and my knowleagge aboutt ico/
cryp/ programist is worse than eneglish 😄im v very thankfull

11 gru 2017 11:04 "Dominique" <notifications@github.com> napisał(a):

**Comment by dpad85** [comment]
Next release (0.2.4) will provide this feature.

**Comment by dpad85** [comment]
0.2.4 is now available. From now on, with a clean application data, you have the option to import a mnemonics when starting the application.
