### ISSUE TITLE
Many channels will not close..

### ISSUE THREAD

**Issue by n1bor** [ACINQ/eclair#2714]
Am on version 8

I have a large number of channels that I can't close. (I can force close - but would rather not due to obvious cost implications).

When looking at the channel JSON from API I can see.

state==NORMAL
localShutdown section is present with a channelID and scriptPubKey but rest is empty.

I can see in the logs I sent a:
Shutdown(channelID,,ByteVector(23 bytes,scriptPubKey,TlvStream(List(),List()))

Where channelID and scriptPubKey match what I can see in the localShutdown section of the JSON.

I can not see a reply from the other Node following the publish of the Shutdown message.

Any ideas what is wrong? I tried a restart of the Node but this does not help.
This is an example channel that seems stuck.
https://mempool.space/lightning/channel/851097866285744128

**Comment by thomash-acinq** [comment]
It looks like most of your channels are marked as disabled by your peers which means that they think you're offline. You should try to debug this connectivity issue first, they probably haven't received the shutdown message.

**Comment by n1bor** [comment]
After restart - I can see the:
OUT msg=ChannelReestablish(
IN msg=ChannelReestablish(
OUT msg=Shutdown(

And the ChannelReestablish messages look as expected - channel ID matches and Commitment/Revocation numbers make sense.

Will give it a few days - maybe they will reconnect and then reset the state to a working one. Else I will trawl through the list to try to find someone on the other side I can talk to!

**Comment by t-bast** [comment]
If your peer doesn't answer your `shutdown` message with their own `shutdown` message, there is nothing you can do.
Mutual close can only progress if your peer responds with a `shutdown` message, if they don't, you can't make any progress.
They're likely using an old version of lnd, which actually didn't support mutual closing in many cases.
