### ISSUE TITLE
Option to show bits

### ISSUE THREAD

**Issue by rodasmith** [ACINQ/eclair#272]
It would be nice to have "bits" as an option for the bitcoin unit to display.

1 bit == 1 microbitcoin (1E-6) == 0.00000100 bitcoin == 100 satoshi

Recommend to add "bit" display option: Preferences / Bitcoin unit / "bit (100 satoshi, 0.00000100 bitcoin)"

(Low priority issue, pretty easy to implement.)

**Comment by dpad85** [comment]
It seems there is still some debate about this. Let's wait for the BIP: https://github.com/jimmysong/bips/blob/unit-bias/bip-unit-bias.mediawiki

**Comment by dpad85** [comment]
Added to the next release (0.2.3)

**Comment by btcontract** [comment]
FWIW I've decided to go with Satoshi, Finney (FIN which is 10,000 SAT) and BTC (10,000 FIN) and nothing else. There's a nice logic of x10,000 multiplier in each denomination.

**Comment by rodasmith** [comment]
There's now a BIP: https://github.com/bitcoin/bips/blob/master/bip-0176.mediawiki

**Comment by dpad85** [comment]
Bits unit is now available in the released version 0.2.3
