### ISSUE TITLE
eclair sets fix description "Donation" for all received keysend payments instead of message from sender

### ISSUE THREAD

**Issue by DerEwige** [ACINQ/eclair#2724]
version=0.9.0 commit=623f7e4

When eclair receives a keysend it generates a fake matching invoice to be stored in payments.received.
This invoice always gets a generic description "Donation" insted of the message sent by the sender.

keysend is used for more than just sending sats to a peer.
It is used to chat with peers or even to trigger commands, etc.

it should be possible to see this messages from the keysend sender so we can parse them in plugins and interact with our peers.

**Comment by DerEwige** [comment]
I just realised this is more a missing feature then a bug:

eclair only implementent PushPayment but not Basic Messages

https://github.com/alexbosworth/keysend_protocols

**Comment by t-bast** [comment]
I don't think we plan on supporting that at the moment. Keysend was always a somewhat hacky temporary feature, so we only implement what is inside the [blip](https://github.com/lightning/blips/blob/master/blip-0003.md). Our goal is not to support messages through payments, we introduced onion messages for that and Bolt 12 will provide cleaner ways of paying for that kind of scenarios.
