### ISSUE TITLE
Connection broken after open channel

### ISSUE THREAD

**Issue by xbukorg** [ACINQ/eclair#2729]
Hi,

When I add new TOR peer in RTL 0.14.0 for Eclair 0.9.0 for some nodes happen that connection is disconnected after opening channel.

Error:
[8/25/2023, 7:49:50 AM] ERROR: Peers => connection failed to d7kak4gpnbamm3b4ufq
54aatgm3alhx3jwmu6kyy2bgjaauinkipz3id.onion:9735: {"statusCode":500,"message":"C
onnect Peer Error","error":"connection failed to d7kak4gpnbamm3b4ufq54aatgm3alhx
3jwmu6kyy2bgjaauinkipz3id.onion:9735"}

I observed it behavior for more different nodes but not for all.

**Comment by t-bast** [comment]
I'm not sure what eclair would have to do with that? This seems to be an error that your peers return, we cannot do anything here, I believe it's your peers who have something to fix.
