### ISSUE TITLE
How make eclair forget about a channel?

### ISSUE THREAD

**Issue by DerEwige** [ACINQ/eclair#2763]
version: eclair 0.9

I’ve opened a channel, but then realized I’ve mistyped the channel size by factor 10.
So instead of waiting for the open and then closing it again, I’ve double spent my input to myself.
The self-payment got mined and now the channel can never open.

But eclair is still was still waiting for the opening TX.
I tried the force close command in the hope, that that would help eclair forget the channel.

There are no funds at risk.
The BTC are already back in my wallet.

The only problem is, that eclair waits for a channel, that can never open and shows a false balance.

**Comment by t-bast** [comment]
This should be automatically handled when the node restarts: eclair will fetch the status of the funding tx and will check whether it is double-spent or not. Once it detects that it has been double-spent, the channel will automatically move to the `CLOSED` state.

**Comment by DerEwige** [comment]
Unfortunately, I was a bit inpatient and tried the forceclose command before restarting the node.
So now the channel is stuck in forceclosng as the force close transaction can not be broadcasted as the input is invalid.

**Comment by t-bast** [comment]
Right, in that case eclair won't watch for double-spends. You can simply delete that channel from the `local.channels` table directly in the DB to clean-up that state, that won't have any side-effect since that channel was never confirmed.

**Comment by DerEwige** [comment]
thanks.
I was expecting that anwer, but just wanted to make sure before deleeting anything from the database

**Comment by DerEwige** [comment]
worked like a charm
