### ISSUE TITLE
Not posible to add routing hints, when creating invoice

### ISSUE THREAD

**Issue by DerEwige** [ACINQ/eclair#2802]
if you run an eclair node with only private channels, you can currently not receive any payments.

Eclair's `createinvoice `does not offer to add any routing hints which is needed to receive payments on private channels

**Comment by t-bast** [comment]
That's correct, we never added those hooks! There will be a similar issue for offers, where it's unclear yet who will be responsible for choosing the blinded paths.

**Comment by DerEwige** [comment]
Thanks, that looks good to me.
Will test when I have time
