### ISSUE TITLE
Please release an .apk file and/or the source code for your mobile wallet

### ISSUE THREAD

**Issue by AndySchroder** [ACINQ/eclair#286]
Android play is a centralized app distribution system. Why use that for a decentralized financial network?

**Comment by pm47** [comment]
Well, we do use github (not just git) for development, which is a centralized website too, but it serves a purpose right? ;-)

Android play is nice for not-too technical users. But we certainly should also release raw apks for those who prefer that. It will be much easier when we open source the android app and it has a dedicated github repo, but for now it is a little bit clunky.

@dpad85 can you please upload the latest apk somewhere and put a link in the readme?

**Comment by AndySchroder** [comment]
I don't have a problem with you distributing your wallet on android play. My issue is three fold:

1. Android play is currently the only source of it.

2. Android play requires users to log in to their website in order to allow downloads. This forces the users' downloads to be tracked. It also forces the users to have android play app installed on their phone, in order to do the download.

3. Android play bullies people into updating apps. Yes, you can opt out, but sometimes they ask you multiple times per day to do updates on there. This is not a good model for tools that make financial transactions. Updating software should be very intentional, and voluntary, especially financial software. People should be able to completely opt out of the android play distribution model if they wish to do so.


Github is a single source, but the difference is that you can download everything from Github without an account. You only need an account to post (contribute) to Github. Github is also a pull system.

**Comment by dpad85** [comment]
You can find a link to the latest APK in the [Wiki home page](https://github.com/ACINQ/eclair/wiki).

The APK itself is hosted on our servers.
