### ISSUE TITLE
All payments do not show up under the Activity tab of the GUI

### ISSUE THREAD

**Issue by AndySchroder** [ACINQ/eclair#288]
If I send lightning payments, many of the payments do not show up under the Activity tab of the GUI. I know that they were sent because the channel balance is much lower than the channel capacity minus the total that is actually shown under the activity tab.

How can I troubleshoot why this may be happening?

**Comment by dpad85** [comment]
If you have restarted your node between your payments, the activity history has been wiped out. That might be the reason why you find a discrepancy between the channel balance and the total in the activity tab. Can you check on this?

**Comment by AndySchroder** [comment]
It's possible that it was after a restart and I didn't realize it. I will try to pay more attention from now on. I'd like to have the activity persist over restarts, but I guess that is more of an enhancement request than a bug. Since I don't have any more troubleshooting information, I guess it's up to you to decide if you want to keep this issue open or close it.

**Comment by dpad85** [comment]
Closing this because I could not reproduce this issue.
