### ISSUE TITLE
Prevent sending payments when Electrum is not synchronized

### ISSUE THREAD

**Issue by pm47** [ACINQ/eclair#293]
Currently if the electrum server eclair is connected to isn't synchronized with the current blockchain height, eclair will use an expiry in the past when making a payment, which will lead to the counterparty force-closing the channel.

We should at least make a basic check on the header timestamp.

**Comment by dpad85** [comment]
A fix for this issue will be available in the next release (0.2.4).

**Comment by dpad85** [comment]
0.2.4 is now available and fixes this issue.
