### ISSUE TITLE
Open Lightning Channel closes unexpectedly

### ISSUE THREAD

**Issue by PRabahy** [ACINQ/eclair#297]
Steps to reproduce:

1. Change preferences to Bitcoin unit =  Bitcoin
2. Click Green Plus
3. Click AUTOCONNECT
4. Press "." (The decimal button) I was trying to open a .25 BTC channel.

Actual behavior:

The dialog disappears

Expected behavior:

It would allow me to type in .25.

**Comment by PRabahy** [comment]
If I type the number first, then move the cursor, and then add the decimal, it doesn't close the dialog, but it displays "Channel capacity must be between 1 and 167 mBTC" (not respecting my default preference).

**Comment by dpad85** [comment]
Good catch, `.25` should be a valid input, a leading 0 should not be required. Or if not, at least this input should fail gracefully -- which is not the case.

The error label should also take into account the user's preferences.

**Comment by dpad85** [comment]
Both issues are fixed in the next version (0.2.3).

**Comment by dpad85** [comment]
Available in the released version 0.2.3
