### ISSUE TITLE
AUTOCONNECT seems to always connect to the same node

### ISSUE THREAD

**Issue by PRabahy** [ACINQ/eclair#298]
I clicked AUTOCONNECT several times. I now see 3 channels as "WAIT_FOR_FUNDING_CONFIRMED" with 03933884aa...

There is one additional one that is "CLOSING (uncooperative)", but I'm pretty sure I did that by clicking "CLOSE CHANNEL"

I expected autoconnect to make several connections to different nodes in the network so that it would be more robust to any one node being down.

**Comment by dpad85** [comment]
Yes, for now the autoconnect option always connects to this one hard-coded node because we are sure this one works 😄 

If you want to connect to another node the best way would be to go to https://explorer.acinq.co, select one node in the network and scan its QR code

**Comment by PRabahy** [comment]
Is there any advantage to having the multiple channels open to the same node? If not, I would have expected some sort of warning "A channel to this node is already established/establishing".

**Comment by pm47** [comment]
Yes there is, eg an existing channel is almost exhausted (or you want to increase the capacity of a channel to a particular node), and you don't want any downtime so you open a 2nd one in parallel so that eclair can transparently switch from one to the other once the first one is closed.

**Comment by fresheneesz** [comment]
@pm47 
> Yes there is, eg an existing channel is almost exhausted

No, that's not a good reason. There is no good reason to open up multiple channels with the same node. If your channel is near exhaustion, you should send more bitcoins into that channel rather than opening a new channel.

**Comment by pm47** [comment]
> No, that's not a good reason. There is no good reason to open up multiple channels with the same node.

Please refrain from making such definitive statements, we are trying to keep this space as friendly as possible.

> If your channel is near exhaustion, you should send more bitcoins into that channel rather than opening a new channel.

I believe you may be referring to the splice in/out feature, which won't make it in spec 1.0. Besides this wouldn't allow changing channel parameters without a downtime (those defined in `open` or `accept` messages for example).

LN spec has been designed to explicitely permit channel multiplexing; while this might sound like an advanced feature it adds a level of flexibility. That said we could certainly add a user preference for restricting a channel per peer.

**Comment by dpad85** [comment]
Closing this issue because after v0.3+ the autoconnect button has been removed from eclair-wallet, and replaced by a `random node` that will use BOLT 10 (https://github.com/lightningnetwork/lightning-rfc/blob/master/10-dns-bootstrap.md).
