### ISSUE TITLE
SCAN A NODE URI appears to fail silently

### ISSUE THREAD

**Issue by PRabahy** [ACINQ/eclair#299]
I found a node that looked interesting on https://explorer.acinq.co/#/ (physically close to me), and tried to connect to it in eclair. I clicked SCAN A NODE URI, scanned the QR code, picked the amount (100 mBTC), then clicked OK. It ended up bringing me back to the Lightning Channels page, but I don't see any new channels listed.

**Comment by PRabahy** [comment]
I just tried it again and this time it gave me a toast, "Failed to open channel:connection failed". I guess the code is in there, but it wasn't getting triggered 100% of the time.

**Comment by dpad85** [comment]
Indeed there was an issue where the toast would not always appear when the channel fails to open. It has been fixed. The fix is not released yet, it will be available in the next version.

Thank you!

**Comment by PRabahy** [comment]
I don't think a toast feels like the right kind of notification for this. Toast automatically disappear. If I click OK, and the dialog disappears, I expect that it worked successfully (even if I'm not looking at my phone as I do it). I would expect an error like this to require the user to click "OK" or similar.

**Comment by dpad85** [comment]
The silent fail issue was fixed by the 0.2.3 release.

Using a `Toast` is not perfect but it is good enough for now.
