### ISSUE TITLE
Allow cooperative close before `min_depth`

### ISSUE THREAD

**Issue by PRabahy** [ACINQ/eclair#300]
I was playing around with the app, and started making a channel. Before it could get established, I force closed it. Now that it has been established, I think (from what I have read) it would be faster/cheaper to close it cooperatively, but when I click on the channel, the "Close Channel" option is gone.

Feel free to close this issue if I am wrong on the basic premise that it is faster/cheaper to close it cooperatively.

**Comment by pm47** [comment]
You are right that a cooperative close is cheaper.

We don't currently support a mutual close before the funding tx has reached a minimum depth (default 2 blocks on testnet), but that's a legitimate request. I've opened an issue in the specs https://github.com/lightningnetwork/lightning-rfc/issues/335.

**Comment by t-bast** [comment]
This issue should have been fixed by #358 
Feel free to re-open if that wasn't the case.
