### ISSUE TITLE
"Open a new Lightning Channel" dialog closes unexpectedly

### ISSUE THREAD

**Issue by eightywon** [ACINQ/eclair#308]
Testnet wallet 2.2.2 on Pixel running Android 8.0.0

Steps to recreate:
- start creating a channel by any of the three methods
- when the soft keyboard appears to enter the channel capacity, enter a period as the first character
- dialog closes unexpectedly

I'd switched to Bitcoin as the "Bitcoin unit" in Preferences so I was trying to enter ".00167" to meet the channel capacity limit.

Entering "0.00167" works as expected. 

Thank you! It's great to be able to test Lightning Network.

**Comment by eightywon** [comment]
*0.167

**Comment by dpad85** [comment]
Thanks for your feedback!

This issue has already been reported in #297
