### ISSUE TITLE
It is not choosing the cheapest route

### ISSUE THREAD

**Issue by Sgt-Miller** [ACINQ/eclair#310]
A wants to send to B
Path#1 A->C->B ,fees charged = x sat
Path#2 A->D->E->B , total fees charged = y sat
where y is less than x       
Expected : Choose A->D->E->B
What happened : It chose A->C->B

`eclair.conf` of C
eclair.chain="regtest"
eclair.server.port=9737
eclair.api.port=8082
eclair.node-color=49daaa
fee-base-msat = 10000
fee-proportional-millionths = 100 // fee charged per transferred satoshi in millionths of a satoshi (100 = 0.1%)

`eclair.conf` of D
eclair.chain="regtest"
eclair.server.port=9738
eclair.api.port=8083
eclair.node-color=49daaa
fee-base-msat = 1
fee-proportional-millionths = 1 // fee charged per transferred satoshi in millionths of a satoshi (100 = 0.1%)

`eclair.conf` of E
eclair.chain="regtest"   
eclair.server.port=9739   
eclair.api.port=8084   
eclair.node-color=49daaa   
fee-base-msat = 1   
fee-proportional-millionths = 1 // fee charged per transferred satoshi in millionths of a satoshi (100 = 0.1%)

**Comment by Sgt-Miller** [comment]
Ok, A wants to send to B.

Through C
For 1mbtc, fee = 20,000 mSAT
For 2mbtc, fee = 30,000 mSAT

Through D
For 1mbtc, fee = 20,000 mSAT
For 2mbtc, fee = 30,000 mSAT

So, eventhough fee-base-msat and fee-proportional-millionths of D was changed to much lower,
it still charges the same as C
So issue seems to be the fee is not checked in the eclair.conf file?

**Comment by pm47** [comment]
Indeed, current implementation chooses shortest path, not cheapest path. This opens way to vulnerability and needs to be improved.
