### ISSUE TITLE
[Mobile] Channel closed unexpectedly on app launch

### ISSUE THREAD

**Issue by fresheneesz** [ACINQ/eclair#313]
I opened eclair just now and then went to my home screen without doing anything in the app. I then got a notification that my channel had begun closing uncooperatively from *my* side (details say the close is "local"). It's disconcerting that my channel could close automatically without me initiating it.

Also the notification doesn't do anything when i tap it - I'd expect it to bring me into the app at least.

**Comment by dpad85** [comment]
Moved this issue to the eclair-wallet repo.
