### ISSUE TITLE
Use same default units

### ISSUE THREAD

**Issue by Sgt-Miller** [ACINQ/eclair#314]
[Eclair desktop wallet, regtest with Bitcoin Core]
Currently,              
In open channel capacity : mBTC(default) 
In push amount : msat  (unit can't be changed)
In receive payment : mBTC(default)
In send payment : msat - (unit can't be changed)(this field is used when amount: in human readable part of payment request isn't there)     
Using the same default for all fields could be more intuitive.

**Comment by Sgt-Miller** [comment]
In Activity tab, Amount and fees paid are in msat. Here its okay, because user doesn't type anything here. Maybe amount could have the same default used elsewhere(say mBTC).  And fees are tiny so the currently used default unit msat is the best.

**Comment by dpad85** [comment]
It's something that should have been done ages ago do but I have not found the time yet!

Added on the TODO list 👍

**Comment by AndySchroder** [comment]
In addition to making the default input units consistent, please also make the units of error messages for maximum amounts (channel funding size and payment size) use the same units as are selected in that dialogue box where the error is displayed.
