### ISSUE TITLE
Not recognizing payment invoice if it has lightning: prefix

### ISSUE THREAD

**Issue by Sgt-Miller** [ACINQ/eclair#317]
[Eclair desktop, bitcoin core regtest]
If I paste     
`lightning:lntb500u1pdrea67pp5n7suxpcj8kjtv50cnn63q0kek5xcmvnx9de4magur7ak6a0fz62sdqqa3a2c29rt5jkfanzeq8redwxjqucfr4y7kwv3k3vlkh69dq43gfp9df4pxd30l0dw93hnl7fvpf6jm3wptq0hwe7sp6cvmvvtqfvc2sq6hm382`
I get : Could not read this payment request.     
If I paste without the lightning prefix, it sends it.           
What should happen: It should recognize the lightning: prefix

**Comment by fresheneesz** [comment]
This was reported as fixed here: https://github.com/ACINQ/eclair/issues/196 but its clearly not fixed.
