### ISSUE TITLE
.5 is invalid but 0.5 is valid

### ISSUE THREAD

**Issue by Sgt-Miller** [ACINQ/eclair#318]
[Desktop eclair]
In the following text boxes,    
open channel ->  capacity
receive payment -> optional amount to recieve 
Entering amount as `.5` is invalid but `0.5` is valid.   
(Units are divisible in that case because the unit was mBTC)  
What should happen : .5 should be recognized as 0.5       

Also a question : Should tiny issues like this be reported in Github or in Gitter chat?

**Comment by PRabahy** [comment]
Sounds related to https://github.com/ACINQ/eclair/issues/297
