### ISSUE TITLE
Error for opening channel doesn't respect units setting

### ISSUE THREAD

**Issue by fresheneesz** [ACINQ/eclair#325]
When opening a channel with too few bitcoins, the warning reads "Channel capacity must between 1 and 167 mBTC" even tho my setting is to use satoshi.

**Comment by dpad85** [comment]
This issue is mentioned in #297

It's fixed in the next release (0.2.3)

**Comment by fresheneesz** [comment]
Cool, in that case I'll close this. Thanks!
