### ISSUE TITLE
README Bitcoin Core sample config connects to regtest instead of testnet

### ISSUE THREAD

**Issue by rstmsn** [ACINQ/eclair#326]
The README provides a minimal config file for Bitcoin Core. This demo conf connects to regtest, instead of testnet:

`regtest=1
server=1
rpcuser=XXX
rpcpassword=XXX
txindex=1
zmqpubrawblock=tcp://127.0.0.1:29000
zmqpubrawtx=tcp://127.0.0.1:29000`

Suggest:

`testnet=1
regtest=0
server=1
rpcuser=XXX
rpcpassword=XXX
txindex=1
zmqpubrawblock=tcp://127.0.0.1:29000
zmqpubrawtx=tcp://127.0.0.1:29000`

**Comment by pm47** [comment]
Fixed with 81977479137618afd1d43309baa6c11081654f97, thanks!
