### ISSUE TITLE
[Mobile] Error "Click here for details" button is difficult to press

### ISSUE THREAD

**Issue by fresheneesz** [ACINQ/eclair#328]
When I receive a payment failed error, there's a button labeled "Click here for details" - half the time when I try to press it, it closes the whole "Payment Failed" view instead of opening the details. Perhaps have two buttons, one for showing details and one for closing the view (rather than closing the view if anything other than that "show details" button is tapped).

**Comment by dpad85** [comment]
A fix will be available in the next release (0.2.4).

**Comment by dpad85** [comment]
0.2.4 is now available.
