### ISSUE TITLE
[Mobile] Improve error message: "RemoteFailure TemporaryNodeFailure"

### ISSUE THREAD

**Issue by fresheneesz** [ACINQ/eclair#329]
"TemporaryNodeFailure" means nothing to a user. We need an error message here that tells the user why their payment attempt failed that's descriptive enough for a user to take corrective action. Does TemporaryNodeFailure mean that the sum of available channel balance for all their routes doesn't have enough to make the payment happen? Does it mean that all routes have a channel is temporarily offline? Or does it mean something else? 

The user needs to know if its a problem they can solve, and if so how to solve it. Does the user have to send a higher fee? Do they have to create another channel for better LN connectivity? Should they blame some of their currently connected channels for lack of connectivity and close those channels out in favor of channels with better uptime? 

Generic error messages like "TemporaryNodeFailure" aren't good enough.

**Comment by dpad85** [comment]
The fix for this issue will be available in the next release (0.2.4).

see https://github.com/ACINQ/eclair/pull/431

**Comment by dpad85** [comment]
0.2.4 is now available and fixes this issue.
