### ISSUE TITLE
[Mobile] AmountBelowMinimum

### ISSUE THREAD

**Issue by fresheneesz** [ACINQ/eclair#330]
I tried to sent a 1 satoshi payment and got this. Why is there a minimum amount at all? The fee market for channels should eliminate any need for exceeding a minimum amount, right?

**Comment by pm47** [comment]
The `htlc_minimum_msat` is defined in the specs ([BOLT 2](https://github.com/lightningnetwork/lightning-rfc/blob/master/02-peer-protocol.md#the-open_channel-message)). It is not something particular to eclair.

To be honest I'm not sure of the rationale for this. Relaying payments incur costs (e.g. CPU/storage) but as you point out, fees should take care of that (except for the last node in the route).

Best place to discuss this is on the `lightning-dev` irc channel.

**Comment by AndySchroder** [comment]
The link that you provided just says that one can define `htlc_minimum_msat`, but it doesn't say that minimum is a certain amount. Eclair seems to be enforcing a 10 satoshi minimum though. Am I missing something?

**Comment by AndySchroder** [comment]
Actually, there is a way to set eclair.htlc-minimum-msat = 1000 in the config file, but it doesn't seem to work.
