### ISSUE TITLE
Show payment failure in the send dialog

### ISSUE THREAD

**Issue by Sjors** [ACINQ/eclair#334]
For some reason paying for my blockachino's almost always fails. The error message can be easy to miss if you have multiple monitors.

<img width="468" alt="schermafbeelding 2017-12-24 om 15 19 11" src="https://user-images.githubusercontent.com/10217/34327164-d1584ac4-e8bd-11e7-99e1-643844ee182a.png">

<img width="434" alt="schermafbeelding 2017-12-24 om 15 20 25" src="https://user-images.githubusercontent.com/10217/34327169-fa83a9fc-e8bd-11e7-8403-0fbebdedbf81.png">

I think it's better to display a spinner on the send button while it's in progress and show the error on the send dialog itself.

In addition it would be nice to get more actionable advice.

**Comment by Sgt-Miller** [comment]
Which OS is that? In Lubuntu I rarely get that notification. Instead I get a permanent white box white box in that area which goes only when I close all instances of eclair.

**Comment by Sjors** [comment]
OSX

**Comment by t-bast** [comment]
Closing this issue as the demo UI has been deprecated in [v0.4](https://github.com/ACINQ/eclair/releases/tag/v0.4).
PRs to improve the demo UI are still accepted, but we won't track any feature requests.
