### ISSUE TITLE
Channel closed and funds lost

### ISSUE THREAD

**Issue by starrymoonlight** [ACINQ/eclair#336]
I was using yalls.org to test and it worked, but the next day i came back and tried to make a payment, and it said that the LN connection not available and to wait a few blocks. After that didn't work, i closed the channel uncooperatively. That resulted in me losing all the funds in the channel.

**Comment by starrymoonlight** [comment]
I opened a new channel and was able to get it to work yesterday, but I just tried again. Now this second channel is failing. When I scan the QR code and click pay, I get "Payment failed". When I click to see the cause, it tells me, "RemoveFailure", "FinalIncorrectCtvExpiry".

**Comment by pm47** [comment]
Hi
> After that didn't work, i closed the channel uncooperatively. That resulted in me losing all the funds in the channel.

Note that when you initiate an unilateral close, funds are returned with a delay (typically 1 day). Can you confirm that you still haven't got the funds back? If so, can you provide a channel id or transaction id?

Thanks

**Comment by starrymoonlight** [comment]
Now I'm getting a message that says, "Breaking changes! Last update was not backward compatible." and that i need to update. I'll try to see if I can get it re-installed. Either way, even if it would have gone through, I think it's a usability issue. There should be some indication that my coins are still around. As it is, my balance just went down by 167 mbtc. If that had happened on the mainnet, I would have been very worried unless there was some sort of clear indication that this money would be around in a day or so.

**Comment by starrymoonlight** [comment]
Unfortunately, I don't think I can access the program anymore because I uninstalled and re-installed and it is still giving me this same message.

**Comment by pm47** [comment]
> There should be some indication that my coins are still around.

Agreed, that's pretty scary, we need to figure something out for that.

> Unfortunately, I don't think I can access the program anymore because I uninstalled and re-installed and it is still giving me this same message.

What do you mean? Are you enable to start eclair event after uninstalling and reinstalling?

**Comment by starrymoonlight** [comment]
That is correct. When I uninstall and reinstall, I still get "Breaking changes!" Eclair Wallet is still in alpha....

**Comment by pm47** [comment]
I'm closing this as issue is old and there have been many changes since then. Please reopen if necessary.
