### ISSUE TITLE
How to determine the IP address and TCP port of existing channels?

### ISSUE THREAD

**Issue by AndySchroder** [ACINQ/eclair#337]
How to determine the IP address and TCP port of existing channels? I can't seem to find a way to do this in the GUI or the API.

**Comment by moneystore** [comment]
Try this https://explorer.acinq.co/#/

**Comment by pm47** [comment]
Example with `eclair-cli` (which calls the API), starting from a channel id:

First you retrieve the remote node id for this channel:
```bash
./eclair-cli channel e7cfa490c6c92a24f7c3ada9504a447cb10fe68658b762d2601b6fd6a673364c
{
  "nodeid": "035b55e3e08538afeef6ff9804e3830293eec1c4a6a9570f1e96a478dad1c86fed",
  "channelId": "e7cfa490c6c92a24f7c3ada9504a447cb10fe68658b762d2601b6fd6a673364c",
  "state": "NORMAL",
  "balanceMsat": 12870900000,
  "capacitySat": 15000000
}
```

Then you get peer information for this node id:
```bash
./eclair-cli peers | jq '.[] | select(.nodeId | contains("035b55e3e08538afeef6ff9804e3830293eec1c4a6a9570f1e96a478dad1c86fed"))'
{
  "nodeId": "035b55e3e08538afeef6ff9804e3830293eec1c4a6a9570f1e96a478dad1c86fed",
  "state": "CONNECTED",
  "address": "34.248.76.24:9735",
  "channels": 3
}
```

Second call is a little bit clunky, and will only give you the address when you initiated the connection. But what you are asking seems very specific and I don't think we should do more than that for now.
