### ISSUE TITLE
Allow binding of the API to multiple IP addresses

### ISSUE THREAD

**Issue by AndySchroder** [ACINQ/eclair#338]
eclair.api.binding-ip defaults to 127.0.0.1 . Many uses of the API could be from remote computers. The machine hosting the API can have multiple IP addresses, and those IP addresses can change, such as when DHCP is used. Is there any way to specify multiple IP addresses, and/or all IP addresses on the machine?

**Comment by bobsmith30332** [comment]
Did you try 0.0.0.0

**Comment by pm47** [comment]
@bobsmith30332 gave the correct answer, we actually bind to 0.0.0.0 for the main TCP server, but the API is sensitive and should not be exposed publicly, that's why it is bound to a loopback address by default.
