### ISSUE TITLE
[Mobile] RouteNotFound on every transaction attempt

### ISSUE THREAD

**Issue by Jawknee-88** [ACINQ/eclair#340]
Using 0.2.3 of the Android app. I have a payment channel open using the autoconnect feature. Attempted sending many payments to Starblocks and Y'alls but on every occasion I get a RouteNotFound error. 

I closed the channel successfully but when I try to open a new channel via autoconnect I now receive "failed to open channel: connection failed to endurance.acinq.co/34.250.234.192:9735"

I've also tried to connect other custom nodes but either get an error similar to the above, or the new channel is listed in the app for a brief period with zero funds and a status of "closing".

**Comment by Jawknee-88** [comment]
Ok. Once disconnecting from my home wifi and switching to 4G I am now able to set up channels with any node. My wifi was connected normally to the internet at the time so perhaps my router is blocking certain ports? I'll do some investigation.

Even on 4G however, I'm still seeing all transactions fail. As well as RouteNotFound I'm now also getting TemporaryChannelFailure.

**Comment by Akkowicz** [comment]
On Linux with UFW(firewall) enabled my transactions aren't going through, however after disabling UFW everything is working fine on Y'alls, transactions are instantaneous, however I haven't achieved any success trying to pay for coffee on Starblocks, maybe it's node is offline?

I've tried with Android Eclair app and the same thing happened - Y'alls is working just fine, but Starblocks throws RouteNotFound. 

I'm going to supply logs when I return home.

**Comment by Akkowicz** [comment]
Managed to reproduce the issue on my laptop, here are two failed Starblocks transactions from desktop GUI client, firewall disabled.
[eclair.log](https://github.com/ACINQ/eclair/files/1585782/eclair.log)
It's seems that it's problem with Starblocks node connection.

**Comment by Jawknee-88** [comment]
I think you're right. Starblocks transactions and creating channels are now working with and without wifi.
