### ISSUE TITLE
Route not found (x attempts) - trying to buy me a Satoccinamon Dolce Latte.

### ISSUE THREAD

**Issue by kjellberg** [ACINQ/eclair#349]
I do currently have 8 local channels, All nodes (404) and All channels (1343) but I can't buy me a coffee at https://starblocks.acinq.co/ because of "no route found". What am I doing wrong?

 I don't know how, but it worked once, but stopped working again.

Log file says:
`cannot parse returned error: channelUpdate/signature: cannot acquire 512 bits from a vector that contains 16 bits`

Thanks!

**Comment by kjellberg** [comment]
Solved it by opening a channel with the endurance node. It works. Amazing!

**Comment by Sgt-Miller** [comment]
Can confirm, it sometimes goes through and sometimes doesn't. Seems like an issue with their endurance node.

**Comment by fringd** [comment]
Had a similar issue buying a story on y'all's.org today. I tried again and it went through. Are we displaying the wrong code or is there temporarily not enough bandwidth on some intermediary. If wrong code, who is sending the wrong code initially?

**Comment by pm47** [comment]
@kjellberg which nodes do you have a channel open to ?

**Comment by fringd** [comment]
I have a single channel open to 03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134 I noticed that the first time it fails the fee is 0 sat. Second time it's 10 sat and it works

**Comment by halfik** [comment]
Have same issue with lastest android realease (using android 6.0)

**Comment by pm47** [comment]
Thanks, we're able to reproduce and are investigating

**Comment by pm47** [comment]
This was fixed with #366.
