### ISSUE TITLE
Opening a second channel with lightning-c causes that and the previously existing channel to be closed

### ISSUE THREAD

**Issue by Sgt-Miller** [ACINQ/eclair#351]
Bitcoin Core Regtest
lightning c is port 9735    
eclair is port 9736
I opened a channel from Eclair to lightning-c. Everything as expected.     
Then I opened another channel from Eclair to lightning-c. It appeared on the screen, quickly    disappeared, and the already existing channel changed to state CLOSING(was NORMAL before).    
I think this is the relevant portion from the log file     
`2017-12-29 19:12:46,529 ERROR fr.acinq.eclair.io.Peer akka://default/user/$h/switchboard/peer-036251ca580411bb71e4497805b72677ebea26bd6ebb08c157dcd5f04c3970bdca  - connection-level error, failing all channels! reason=Peer sent unknown message 32 (WIRE_OPEN_CHANNEL)`        
[eclair.log](https://github.com/ACINQ/eclair/files/1593200/eclair.log)

**Comment by Sgt-Miller** [comment]
More info : 
The issue seems to be that eclair is ok with having multiple channels between two peers, but c-lightning is not. 
While trying to connect from c-lightning, it gives a message "Peer already channel normal D".  
While trying to connect from eclair, the first channel gets closed too.

**Comment by Sgt-Miller** [comment]
From lightning-c terminal
I think this is the relevant part?
`lightningd(10651):jcon fd 15: Failing: channel ALL: Peer sent unknown message 32 (WIRE_OPEN_CHANNEL)
lightningd(10651):jcon fd 15: Closing (Bad file descriptor)`      

[lightningc.txt](https://github.com/ACINQ/eclair/files/1593420/lightningc.txt)

**Comment by sstone** [comment]
I don't think that lightning-c supports multiple channels to the same peer yet, you should probably open an issue with them too.

**Comment by sstone** [comment]
Closing because it is a limitation of lightning-c.
