### ISSUE TITLE
Long delay at "Reading the invoice, please wait"

### ISSUE THREAD

**Issue by Xeroxcoin** [ACINQ/eclair#356]
I'm using Eclair on Android, trying to pay starblocks.  I received a recent upgrade that required wiping the app data, which went fine.  Now when I scan the invoice there is a > 1 minute pause before I have the option to pay.  If I press the Back button, Android says Eclair is unresponsive.  Behind the dialog ("Reading the invoice, please wait"), I see the transaction list clear, then repopulate.  Finally the dialog appears to press "Pay".  After pressing that, I get "Reading the invoice" again.  Finally I get to press "Pay" again and it goes through.  Not sure how else to help with debugging this.

**Comment by dpad85** [comment]
Moved this issue to the eclair-wallet repo.
