### ISSUE TITLE
Possible Memory Leak

### ISSUE THREAD

**Issue by drmoore718** [ACINQ/eclair#357]
Leaving Eclair open for several days, I notice a steady climb in its memory usage.

I have 14 channels open, connected to Bitcoin core testnet.

Here is the usage after ~3 days
![image](https://user-images.githubusercontent.com/7050199/34507030-29e1409e-efe7-11e7-970d-025ce28c8392.png)

Windows 10 
v0.2-alpha8

**Comment by pm47** [comment]
Indeed, current memory management is very naive and eclair consumes far more memory than it should; on top of that there are at least a few memory leaks which makes it even worse.

I've been working on this lately, expect improvements in the next release.

Thanks for reporting!
