### ISSUE TITLE
Failure to route a payment

### ISSUE THREAD

**Issue by btcontract** [ACINQ/eclair#359]
Setup is as follows: 
`node1 (phone)` 
-> `nonpublic channel, shortChanId: 1382554508069175296`  -> 
`node2: 03dc39d7f43720c2c0f86778dfd2a77049fa4a44b4f0a8afb62f3921567de41375` 
-> `public channel, shortChanId: 1380824976283467777` -> 
`node3: endurance`
-> `nonpublic channel, shortChanId: 1382538015402491905` -> 
`node4 (phone)`

Public channel `1380824976283467777` has a following balance:

```
"remoteCommit" : {
          "index" : 196,
          "spec" : {
            "htlcs" : [ ],
            "feeratePerKw" : 53760,
            "toLocalMsat" : 2679597910,
            "toRemoteMsat" : 13320402090
          },
          "txid" : "d454b2b5d2230860183f35f321b5c53c5852daeec3b3349b5bee01921f7b1360",
          "remotePerCommitmentPoint" : "0317b5ed26fdce7138fd3e6a2d9a4441ae0f38ce7f44ab226ba68b6d658d461dfd"
        }
```

When trying to send a `100,000 SAT` HTLC from `node1` to `node4`, `endurance` first replies with `TemporaryChannelFailure` despite `1380824976283467777` clearly having enough balance to route a payment, and on next retry it replies with `TemporaryNodeFailure` related to `endurance`.

Also: smaller payments of `10,000 SAT` are routed successfully via these channels.

**Comment by btcontract** [comment]
I was just able to send a `100,000 SAT` from `node1` to `node4` but was unable to send `100,000 SAT` back from `node4` to `node1`, error messages are the same.

**Comment by rileyjalexander** [comment]
Forgive me if I am understanding incorrectly, but I know on my android version of Eclair, it says a known current limitation is payments are OUTBOUND ONLY. Meaning you can pay with LN, but not receive/forward payments (at least on the android version of eclair)
