### ISSUE TITLE
[Desktop] Display how long a channel has been in its current state

### ISSUE THREAD

**Issue by PRabahy** [ACINQ/eclair#362]
I have several channels that are currently offline. It would be very nice to know how long they have been in that state. If it has been offline for several days, I can assume that the other person was just testing lightning and I will force close the channel. If they have only been offline for a few hours, they are probably just working on their computer, or they turn it off at night.

**Comment by t-bast** [comment]
Closing this issue as the demo UI has been deprecated in [v0.4](https://github.com/ACINQ/eclair/releases/tag/v0.4).
PRs to improve the demo UI are still accepted, but we won't track any feature requests.
