### ISSUE TITLE
[mobile] Payment failed, route not found to Starblocks

### ISSUE THREAD

**Issue by timjrobinson** [ACINQ/eclair#364]
I last used the eclair wallet about 2 weeks ago, I setup channels with the automatic node, my home server and a few other random nodes I found via block explorer. Payments with Starblocks all worked fine. 

Today I tried paying for a coffee on Starblocks and got a "route not found error". I went to the channels page and setup a new automatic channel, and then immediately tried to pay for that same transaction again, this 2nd time it worked correctly. I'm not sure if initializing that new channel did anything (as it's still in WAITING_FOR_FUNDING_CONFIRMED state), I presume it didn't and the app was just having a temporary glitch 

Error screenshot and my open channels are attached as images.
![screenshot_20180108-113319](https://user-images.githubusercontent.com/525534/34667222-663c7f24-f468-11e7-9f66-31370db23c5a.jpg)
![screenshot_20180108-114006](https://user-images.githubusercontent.com/525534/34667421-2ad3eb60-f469-11e7-9a26-652bee88bd0b.jpg)

**Comment by dpad85** [comment]
What version of eclair wallet are you using ? (you can find it in the about page)

**Comment by timjrobinson** [comment]
Version 0.2.3

**Comment by pm47** [comment]
It doesn't look like a bug to me, it is perfectly possible that there were no available routes to starblocks at that time.

As a matter of fact, 2 weeks ago we have intentionally let some channels depleted in order to track down an issue between eclair/lnd.

Can you reproduce this? If not, please close, thanks!
