### ISSUE TITLE
make checkpayment RPC method return a non-binary result

### ISSUE THREAD

**Issue by AndySchroder** [ACINQ/eclair#369]
The checkpayment RPC method returns True or False. For the case where you provide a payment request without a specific amount, there doesn't seem to be a way to know how much they actually paid. Please make the checkpayment method return the value that was paid, in msat (an integer).

**Comment by AndySchroder** [comment]
So, it looks like the highest level reference for this is here: https://github.com/ACINQ/eclair/blob/master/eclair-core/src/main/scala/fr/acinq/eclair/api/Service.scala#L241

And then the next lower level reference is here: https://github.com/ACINQ/eclair/blob/master/eclair-core/src/main/scala/fr/acinq/eclair/payment/LocalPaymentHandler.scala#L48

However, I'm struggling what to do from there.

**Comment by AndySchroder** [comment]
Also, it might be useful to bundle in this feature request the ability to return the payment_hash (if querying with the paymentRequest) or paymentRequest (if querying with the payment_hash) and timestamp (for both query types).

**Comment by t-bast** [comment]
This has been fixed, you can now use the `sentinfo` RPC to get all details.
