### ISSUE TITLE
Alphanumeric QRs are not supported

### ISSUE THREAD

**Issue by btcontract** [ACINQ/eclair#375]
An alphanumeric QR has a payment request in upper case and Eclair mobile currently fails to process it, exaple QR:

![photo_2018-01-17_11-06-46](https://user-images.githubusercontent.com/9870980/35034351-86d12720-fb76-11e7-8b0b-454c900599ac.jpg)

Form BIP 173:

> Decoders MUST NOT accept strings where some characters are uppercase and some are lowercase (such strings are referred to as mixed case strings).

>For presentation, lowercase is usually preferable, but inside QR codes uppercase SHOULD be used, as those permit the use of alphanumeric mode, which is 45% more compact than the normal byte mode. 

Just in case, a regex I use to match both uppercase and lowercase:  
`"(?i)(lightning:)?([a-zA-Z0-9]+)\\W*".r`

**Comment by dpad85** [comment]
The fix will be available in the next release (0.2.4)

**Comment by dpad85** [comment]
0.2.4 is now available and fixes this issue.
