### ISSUE TITLE
We don't check for expired htlcs in next remote commitment

### ISSUE THREAD

**Issue by btcontract** [ACINQ/eclair#376]
In theory if a node along the payment route accepts an HTLC and does nothing it's channel should be soon broken and original payment sender should get a payment failed (or fulfilled). In practice this is not always the case and depends on how exactly a buggy or malicious node behaves.

In the following setup:
`A (sender)` -> `B` -> `C (malicious receiver)`

If:
`B` -> `C`: `UpdateAddHtlc`
`B` -> `C`: `CommitSig`
`C` -> `B`: `Revocation`
`C` -> `B`: `CommitSig`
`C` does nothing after this
then everything works fine: `B` breaks a channel with `C` in 9 blocks and fails `A`'s payment, leaving it's channel intact.

But if:
`B` -> `C`: `UpdateAddHtlc`
`B` -> `C`: `CommitSig`
`C` does nothing after this
then `B` does not break `B` -> `C` channel and `A` -> `B` channel gets broken instead after HTLC fully expires, initiated by `A`.

**Comment by pm47** [comment]
Good catch!

In the following test we should also check their remote next commit when it exists:
https://github.com/ACINQ/eclair/blob/1db673a631e5c7ad2c70a9a86c8689da6609be38/eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala#L48-L50
