### ISSUE TITLE
Some expired payments don't get failed on sender's side

### ISSUE THREAD

**Issue by btcontract** [ACINQ/eclair#377]
Setup is as follows: `A (sender)` -> `B` -> `C (malicious receiver)`

Scenario 1:
1. `A` sends an HTLC of `1,000,000 SAT` to `C`
2. `C` accepts an HTLC and does nothing
3. 9 blocks pass, `B` breaks `B` -> `C` channel and fails `A`'s HTLC

Scenario 2:
1. `A` sends an HTLC of `1,000 SAT` to `C`
2. `C` accepts an HTLC and does nothing
3. 9 blocks pass, `B` breaks `B` -> `C` channel but does not fail `A`'s HTLC
4. 144 more blocks pass and `A` initiates an uncooperative closing because of expired HTLC

It seems like this depends on HTLC amount and `B` does not fail HTLC which get filtered out of commit tx.

**Comment by pm47** [comment]
I don't have an explanation right off the bat. Do reproduce this all the time?

**Comment by btcontract** [comment]
Yes, it does. Just tried this on https://github.com/ACINQ/eclair/pull/390 once again and `1000000 SAT` is constantly getting failed (if sender is online) while `1000 SAT` is constantly not getting failed.

**Comment by btcontract** [comment]
I think it has to do with this region: https://github.com/ACINQ/eclair/blob/master/eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala#L1044-L1094

`relayer` never gets `Status.Failure` for small payments because it involves checking a spent tx which does not have a small payment output. This explains `1,000,000 SAT` gets failed but `1,000 SAT` does not.

**Comment by pm47** [comment]
Closed by 1aea664.
