### ISSUE TITLE
Expired payment don't get failed if sender is offline at expiration time

### ISSUE THREAD

**Issue by btcontract** [ACINQ/eclair#378]
Setup is as follows: `A (sender)` -> `B` -> `C (malicious receiver)`

Scenario 1:
1. `A` sends an HTLC of `1,000,000 SAT` to `C`
2. `C` accepts an HTLC and does nothing
3. `A` stays online
4. 9 blocks pass, `B` breaks `B -> C` channel and fails `A`'s HTLC

Scenario 2:
1. `A` sends an HTLC of `1,000,000 SAT` to `C`
2. `C` accepts an HTLC and does nothing
3. `A` goes offline
4. 9 blocks pass, `B` breaks `B -> C` channel
5. `A` becomes online but `B` does not fail `A`'s HTLC
6. 144 more blocks pass and `A` initiates an uncooperative closing because of expired HTLC

**Comment by pm47** [comment]
Yes, we should do the equivalent of #183, but for failed payments. I'm on it.
