### ISSUE TITLE
Eclair roadmap and developmental status

### ISSUE THREAD

**Issue by curiosity81** [ACINQ/eclair#380]
Hello,

This is not a code issue, but I think similarly important:

**Where do I find information about the developmental status of Eclair?**

**What of the protocol is already implemented and tested well, what is still missing?**

**How far is Eclair from working on the main net?**

**If you have node running on testnet, will it be possible to simply switch to mainnet, when Eclair is ripe?**

**Where do I find such information?**

One such document or webpage containing this information would be nice. And please, NOT optimized for a tablet or in form of a video, a simple Readme.md would be enough. 

Moreover, what about sha256-hashes for the precompiled jar-files? As well as corresponding signatures from the developers or the project?

In the moment, I write a tutorial for installing an Eclair-node on a linux machine:

https://bitcointalk.org/index.php?topic=2778084.0

However, it is not clear to me, what to expect from Eclair in future.

Thanks.

Regards
cu

**Comment by curiosity81** [comment]
Hello,

another question. Is there a way to make test payments? As far as I understand LN, someone has to request a payment. Right?

Can someone request a payment for testing? Please leave a corresponding comment here or in the given bitcointalk-thread.

Moreover, concerning my previous question: What happens if I opened a channel and then shutdown the corresponding node? There are so many questions which should be covered in some document!

Regards
cu

**Comment by alex-georgiou** [comment]
@curiosity81 Hi, I'm new to all this but I believe you can generate payment requests at https://starblocks.acinq.co

**Comment by curiosity81** [comment]
Hi alex,

This was quick :-). Thank you. I will try that.

Best
cu

**Comment by curiosity81** [comment]
The default Eclair-port is 9735, right?

Now there are nodes in the network, that are shown on the map with all infos: alias, color, pubkey, ip, port. But connection fails. The FAQ at https://explorer.acinq.co says, that this might be due to wrongly configured port(s) or port forwarding.

I close all ports by default. That is, I disabled port forwarding. If the above is true, then others cannot connect to my node. But I can connect to those nodes with open port 9735. If everyone disables port 9735, then there is no network possible since no one accepts connections. If only a small number of nodes accept connections, then this leads to a centralized network with a small number of hubs.

So again my question, do I have to open port 9735 to be able to accept others to establish a channel with me. Are there other ports which must be accessible?

Thanks in advance
cu

**Comment by pm47** [comment]
@curiosity81 please don't mix several unrelated topics on the same thread, that doesn't make the lives of maintainers any easier.

Also this is not a general support forum but an issue tracker. For this kind of questions, please go to our https://gitter.im/ACINQ/eclair, you'll have faster answers and it creates less overhead.

That said:

> The default Eclair-port is 9735, right?

that is the default standard LN port yes

> If everyone disables port 9735, then there is no network possible since no one accepts connections.

correct

> do I have to open port 9735 to be able to accept others to establish a channel with me. Are there other ports which must be accessible?

Yes you have to open 9735 (only this one) for others to connect to you.

There is nothing specific to Lightning about all this, the same exact thing applies to the main bitcoin network. Again, gitter is a better place for this. Thanks!

**Comment by curiosity81** [comment]
Thanks for the quick answer again. And I am sorry for the inconvenience. I was not aware of this gitter-channel.

But I have to stress again, that all those informations are distributed somewhere in the net or are missing at all. In the moment I am collecting the relevant things for my Eclair-tutorial which I hope might reduce the trouble in future.

Best
cu

**Comment by pm47** [comment]
No worries.

The [Lightning Network Megathread](https://www.reddit.com/r/Bitcoin/comments/7pwna9/lightning_network_megathread/) on reddit compiles a lot of information and resources on Lightning, you should take a look at it.

**Comment by pm47** [comment]
> Where do I find information about the developmental status of Eclair?

This repository is the place to go. Don't expect regular high level status update for now, because things are still under heavy development and that would cause us too much overhead. We will do that when things settle down. In the meantime, just taking a look at current issues/PR/discussions will give you an idea of what we are currently doing. Last release notes also give valuable info.

> What of the protocol is already implemented and tested well, what is still missing?

Eclair is fully BOLT compliant, and there is a somewhat decent test coverage. See next point for what's missing.

> How far is Eclair from working on the main net?

We are tracking bugs and corner cases that regularly appear on testnet, and generally work towards making the software more robust and production ready. Sometimes it require changes in the db format, which would be very annoying on mainnet. We also want to provide basic recovery tools so that users can recover at least part of their funds when/if things go south.

> If you have node running on testnet, will it be possible to simply switch to mainnet, when Eclair is ripe?

Getting to know eclair on testnet will definitely help setting up a mainnet node faster. We highly recommend trying testnet first and not rush for mainnet.
