### ISSUE TITLE
Opening and closing a channel before it's confirmed gets it hanging

### ISSUE THREAD

**Issue by felipequintella** [ACINQ/eclair#384]
Opening and then imediatelly closing a channel leaves it hanging at "CLOSING" indefinetely.

**Comment by pm47** [comment]
A little more details would be helpful:
- are you using eclair desktop or mobile? which version?
- what do you call indefinitely? is that minutes, hours or days?

**Comment by felipequintella** [comment]
Eclair desktop, v0.2-alpha8.
But it closed after 2 days hanging :)
You can close this issue, I guess I was a bit unpacient?

**Comment by pm47** [comment]
Unilateral close have a 144 blocks timeout for refunds by default, so this is the expected behavior. It's always better/cheaper/faster to mutual close.

We have a pending feature request for allowing early mutual closing (right after opening and before funding tx confirms).

Thanks!
