### ISSUE TITLE
fatal error: Futures timed out after [10 seconds]

### ISSUE THREAD

**Issue by AdvancedStyle** [ACINQ/eclair#387]
When running java -jar eclair-node-0.2-alpha8-8edb2a4.jar

I get error: `fatal error: Futures timed out after [10 seconds]`

What does it mean?

**Comment by AdvancedStyle** [comment]
Oh seems to be from running bitcoind on mainnet and not eclair.

Is it possible to run eclair on mainnet, when i set config: eclair.chain=livenet

fatal error: only regtest and testnet are supported for now

**Comment by pm47** [comment]
We neither support nor recommend running mainnet for now. Source code as-is won't work with mainnet on purpose.

We are working hard towards this, please be patient thanks!
