### ISSUE TITLE
Reading the invoice, please wait STUCKED

### ISSUE THREAD

**Issue by ianzkie** [ACINQ/eclair#389]
Stucked at reading the invoice please wait...

**Comment by dpad85** [comment]
Can you give your phone model and your version of android? Also, can you give me the invoice you are trying to scan? Thanks!

**Comment by ianzkie** [comment]
SM-G900F
Android 5.0
I'm trying to scan invoices on Starblocks

**Comment by dpad85** [comment]
Moved this issue to the eclair-wallet repo.
