### ISSUE TITLE
Payments stuck on "pending"

### ISSUE THREAD

**Issue by raindogdance** [ACINQ/eclair#392]
Eclair Version 0.2.3
Android 8.0.0

![sfaml1k](https://user-images.githubusercontent.com/35657440/35235024-e6942e14-ff9a-11e7-86ad-4a5af0eab797.jpg)

**Comment by dpad85** [comment]
The fix for this issue will be available in the next release (0.2.4).

**Comment by dpad85** [comment]
0.2.4 is now available and fixes this issue.
