### ISSUE TITLE
Some special characters from payment request are displayed wrong in Eclair mobile

### ISSUE THREAD

**Issue by btcontract** [ACINQ/eclair#398]
Some encoded special characters, such as apostrophe, are not properly displayed in Eclair mobile, for example:

![photo_2018-01-23_17-45-08](https://user-images.githubusercontent.com/9870980/35285319-b8f2b478-0065-11e8-9ce3-a6dfda643de9.jpg)  

Similar payment request in another app:

![photo_2018-01-23_17-45-11](https://user-images.githubusercontent.com/9870980/35285359-d76a9b46-0065-11e8-94f8-61541428a4cb.jpg)

**Comment by verretor** [comment]
It seems the Android app is escaping HTML which is good for security in my opinion although a bit ugly.

**Comment by btcontract** [comment]
@verretor is this relevant inside of Android app? A far as I know escaping is done to prevent javascript execution on websites.

**Comment by verretor** [comment]
Could be SQL injection. Eclair uses SQLite.

There are some characters that cause problems in some very specific situations. Imagine your app uses UTF-8 encoding and accepts 2 byte characters such as 뼢 but your database has an encoding that only accepts 1 byte characters.
뼢 is 0xbf22 (2 byte) but when translated into 1 byte, it becomes:
0xbf 0x22 = ¿"

Notice the double quote. That's just one of many examples and it requires a lot of tests to make sure it is really safe.

I think it's better to be too careful than not enough but that's just my opinion.

**Comment by dpad85** [comment]
@btcontract By chance did you keep the payment request with the `Elaine's Idle Mind` description ? I can't reproduce this issue, even with some exotic characters.

**Comment by btcontract** [comment]
no, sorry, it's been a long time.

**Comment by dpad85** [comment]
Moved this issue to the eclair-wallet repo.
