### ISSUE TITLE
Display a proper error message in case of TCP bind failure

### ISSUE THREAD

**Issue by pl48415** [ACINQ/eclair#399]
When I try to run latest eclair on FreeBSD 11 it just won't start. I am using openjdk8. Here is log from ~/.eclair/eclair.log:
`2018-01-23 17:06:02,837 INFO  fr.acinq.eclair.Setup   - version=0.2-alpha9 commit=951bcc4750602c2eba1998c24bcad3714f24b6ef
2018-01-23 17:06:02,878 INFO  org.bitcoin.Secp256k1Context   - couldn't find secp256k1 library, defaulting to spongycastle
2018-01-23 17:06:03,311 ERROR fr.acinq.eclair.Boot$   - fatal error: null
`
I have experienced the same error on alpha8 also.
My openjdk version:
`openjdk version "1.8.0_152"
OpenJDK Runtime Environment (build 1.8.0_152-b16)
OpenJDK 64-Bit Server VM (build 25.152-b16, mixed mode)`

**Comment by dpad85** [comment]
Are you trying to run `eclair-node-gui`? The GUI requires JavaFX and it looks like it does not come automatically with OpenJDK. Not sure there is a package for FreeBSD.

You can try to run eclair without a GUI with the `eclair-node` JAR, or with `-Declair.headless` option

**Comment by pl48415** [comment]
I was running headless version(eclair-node-0.2-alpha9-951bcc4.jar)

**Comment by pl48415** [comment]
Found the problem, lnd was running in the background and it used the same port that eclair uses. It would be nice to have an error message for that.

**Comment by dpad85** [comment]
There is an error message for that scenario, it is not displayed and that's a bug. Thanks for the reporting, I reopen this issue.
