### ISSUE TITLE
running Bitcoin Core but eclair says not...

### ISSUE THREAD

**Issue by nybe** [ACINQ/eclair#406]
I've set up bitcoin.conf and eclair.conf with the minimum requirements but I cannot connect... keep getting this error screen:
<img width="390" alt="screen shot 2018-01-24 at 10 47 43 am" src="https://user-images.githubusercontent.com/4483720/35350896-2d1d7430-00f4-11e8-8e64-9ae7f3c95e34.png">

**Comment by nybe** [comment]
Bitcoin Core is open and running in testnet mode

**Comment by sstone** [comment]
This is not a support forum, we'd like to restrict github to technical issues only. Please use https://gitter.im/ACINQ/eclair instead. Thanks!
