### ISSUE TITLE
RPC become unresponsive, CPU consumes 100%

### ISSUE THREAD

**Issue by gdassori** [ACINQ/eclair#408]
OS :Ubuntu 16.04 @ Virtualbox w/ JRE 1.8 and Oracle JDK 8.

After a while eclair-node is up, with ~50 channels open (but already happened previously on another installation with ~20 peers) the RPC become unresponsive, plenty of timeouts, and the CPU usage turn to a fixed 100% (8 hours up now and won't change).

Reload eclair with the same sqlite file won't help.
I have 66 peers in my sqlite file. 

In both cases, the sqlite size is around 3.2MB

Neither the "help" RPC won't respond, the whole daemon is stuck.

Nothing into the logs but the usual INFO entries.

**Comment by pm47** [comment]
Hm, we don't see that kind stability issues on nodes with a much higher load. How much RAM does your vm have? Maybe you don't have enough and your garbage collector is struggling?

**Comment by gdassori** [comment]
The VM have 2gb of RAM and the java process is consuming 33%, the swapfile is neither hit. 
There's only Eclair in the VM, the bitcoind is elsewhere.

I can send you all the files (sqlite files, seed.dat and wallet.dat of the bitcoin node), if they help in the debug process.

Forgot to mention, I automated the channels opening with a small script I wrote, so an important amount of 'peers' calls is made, along with 'open' to interested peers, right before the problem appears.

**Comment by pm47** [comment]
> The VM have 2gb of RAM and the java process is consuming 33%, the swapfile is neither hit.
There's only Eclair in the VM, the bitcoind is elsewhere.

Yeah but the JVM will only allocate a portion of this space and not go over it, so it can run out of memory without your OS noticing. Maybe try running eclair with e.g. `java -Xmx1G -jar eclair[...].jar`?

If you open a lot of connections, try setting `eclair.local-features=00`, it will prevent eclair from asking every peer to download the whole routing table, which could amount to a lot of data if you are connecting to a lot of peers.

**Comment by gdassori** [comment]
Increasing the max allocated memory to 1G didn't helped, same with 2G.

So I shut down the VM and restarted it with 6GB, and set the max memory usage for java to 5G and the issue was mitigated, but not fixed. I still have some lag on the RPC, and the CPU usage is still 100%.
Disabling the routing table download from every peer as you suggested, instead, fixed the issue definitely, and without the need to increase the memory amount.

Question now is, how this setting affect the path discovery, and if not relevant, what are the consequencies of disabling peer downloads?

Thanks!

**Comment by pm47** [comment]
> Question now is, how this setting affect the path discovery, and if not relevant, what are the consequencies of disabling peer downloads?

If you only have an incomplete view of the routing table, this affects your ability to find paths when you make payments. But you can still relay payments even with no routing table at all.

Anyway this is obviously something that needs fixing and has been addressed in #421 and #422.

**Comment by YaroslavYrm** [comment]
Same for me on beta 5. `eclair.local-features=00` worked as well.
