### ISSUE TITLE
`eclair-cli` fails to parse timeout errors

### ISSUE THREAD

**Issue by Stadicus** [ACINQ/eclair#414]
When the Eclair API fails to connect to a node, the error message is not parsed correctly.

    bitcoin@RaspiBolt:~ $ eclair-cli allnodes
    parse error: Invalid numeric literal at line 1, column 4

    bitcoin@RaspiBolt:~ $ curl --user eclair-cli:PW_REMOVED --silent --show-error -X POST -H "Content-Type: application/json" -d '{ "method": "allnodes", "params" : [""] }' http://localhost:8080
    The server was not able to produce a timely response to your request.
    Please try again in a short while!bitcoin@RaspiBolt:~ $

Please note the missing line break at the end of the API answer. The command line prompt is attached directly to the reply (see image).
![eclair 1 - output eclair-cli](https://user-images.githubusercontent.com/19550140/35476111-d85c5f56-03aa-11e8-9bd2-7053d9633621.png)

The same error also occurs with the "send" method when the connection to the selected nodeId fails.

**Comment by pm47** [comment]
I would say that the bug isn't in the client but in the server: all error messages should have the same (json) format, but this one hasn't.

**Comment by Stadicus** [comment]
Yes, makes sense. It's confusing, though, especially with an timeout error like this.

**Comment by gregtronel** [comment]
Wonder if it's trying to parse the node_alias and bumps into encoding issues with non-utf8 chars

**Comment by gregtronel** [comment]
I have the following line in eclair.log:
INFO  f.a.e.Setup$$anonfun$bootstrap$4$$anonfun$apply$14$$anon$1   - API call failed with cause=exception decoding Hex string: invalid characters encountered in Hex string

**Comment by pm47** [comment]
@gregtronel that seems unrelated, can you paste the eclair-cli command line you are using? Thanks

**Comment by donnielrt** [comment]
@pm47 I'm getting the same error, I've tried the following on eclair alpha 10:

`eclair-cli send <invoice>`, and also directly via curl:

`curl --user eclair-cli:<pwd> --silent --sh application/json" -d '{ "method": "send", "params" : ["<invoice>"] }' http://localhost:8080`

In my log, I see what attempts to be an attempt to find a route:

<pre>
2018-02-17 16:01:46,983 INFO  f.a.eclair.payment.PaymentLifecycle akka://default/user/$j/payment-initiator/$e  - route found: attempt=1/5 route=03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134->03dde213194e58f9c0d042d4b2a2582bda332969a95caaaff9d1c7e0c7395a05c4->039cc950286a8fa99218283d1adc2456e0d5e81be558da77dd6e85ba9a1fff5ad3 channels=133d7600004c0001->138f5c00004a0000->1391570000250000
</pre>

but curl responds with a timeout, `The server was not able to produce a timely response to your request.`
