### ISSUE TITLE
Cannot acquire 512 bits from a vector that contains 0 bits

### ISSUE THREAD

**Issue by cryptobabel** [ACINQ/eclair#419]
Running alpha9 on Windows7 and having trouble with both getting the installer to load the config file(appreciate thoughts here) and the following error: 

2018-01-29 00:25:15,638 WARN  f.a.eclair.payment.PaymentLifecycle akka://default/user/$k/payment-initiator/$f  - cannot parse returned error: channelUpdate/signature: cannot acquire 512 bits from a vector that contains 0 bits
2018-01-29 00:25:15,638 WARN  f.a.eclair.payment.PaymentLifecycle akka://default/user/$k/payment-initiator/$f  - too many failed attempts, failing the payment

**Comment by pm47** [comment]
Hi, 

> 2018-01-29 00:25:15,638 WARN f.a.eclair.payment.PaymentLifecycle akka://default/user/$k/payment-initiator/$f - cannot parse returned error: channelUpdate/signature: cannot acquire 512 bits from a vector that contains 0 bits

Alpha9 fixed a bug related to encoding of error messages (#366), so it is possible that the node you are connected to still has the bug, which creates parsing error.

> 2018-01-29 00:25:15,638 WARN f.a.eclair.payment.PaymentLifecycle akka://default/user/$k/payment-initiator/$f - too many failed attempts, failing the payment

This just means that your payment failed, because eclair couldn't find a working route. This isn't a bug in itself.

How many channels do you have? Which nodes are you connected to?

**Comment by cryptobabel** [comment]
I tried it with several different configurations with the same results. Everything from 1 node to 10+. I usually try to connect to the more stables ones like starblocks, yalls etc. I was able to make a payment to yalls and starblocks a couple days ago with the android app using auto connect but havn't been able to since and never on the desktop client. I'll give it another run this evening. I had to completely remove the android app as it began hanging and draining the battery and made phone unusable. Those funds/channels etc are stuck in the ether I assume. A reinstall solved having a dead phone though.

**Comment by cryptobabel** [comment]
I was able to get a single direct connection to the yalls peer and made a payment. Can't find other routes out of there though. Things seem a bit less flaky than past night or two. I want to look in to see how initial peer is chosen and how errors are handled around that. I would have assumed it would have tried another channel on fail. It had to have been from pulling in bad peers during majority of tests.
