### ISSUE TITLE
When i open channel between eclair and c-lightning i found still state OPENINGD

### ISSUE THREAD

**Issue by parmax** [ACINQ/eclair#425]
I use eclair mobile wallet on android and c-lightning on ubuntu.
When i open channel from eclair mobile wallet to c-lightning i have switch state from wait_for_accept_channel to closed

When i open channel from c-lightning to eclair node 03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134@34.250.234.192:9735
i found still state OPENINGD

**Comment by sstone** [comment]
Which version (or commit) of c-lightning are you using ? In both cases there should be something in the c-lightning logs (for example eclair and c-lightning could disagree on network fees so much that c-lightning does not want the channel to be opened). c-lightning and eclair (at recent commits) should be compatible and there are c-lightning nodes connected to 0393388.....

**Comment by parmax** [comment]
I connect to 0393388... successful
`lightning-cli connect 03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134 34.250.234.192:9735`
But not have connection in listpeers command output

**Comment by parmax** [comment]
After try dev-ping command
`lightning-cli dev-ping 03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134 10 10`
I have listpeers command result
`                 { "state" : "GOSSIPING", "id" : "03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134", "netaddr" :
                        [ "34.250.234.192:9735" ], "connected" : true, "owner" : "lightning_gossipd" } ] }`

When i funding channel command
`lightning-cli fundchannel 03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134 100000` 
it is still very-very long time.

**Comment by pm47** [comment]
Pretty sure this was fixed with the improved routing sync.
