### ISSUE TITLE
Eclair 0.2alpha-1 uses 100% CPU and becomes unresponsive shortly after launch

### ISSUE THREAD

**Issue by robzon** [ACINQ/eclair#43]
$ uname -a
Linux ubuntu 4.4.0-36-generic #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

$ jre1.8.0_121/bin/java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

[eclair.log.gz](https://github.com/ACINQ/eclair/files/866337/eclair.log.gz)

**Comment by pm47** [comment]
Congratulations you found a bug!

You seem to have set `eclair.bitcoind.network=testnet`, what happens with `eclair.bitcoind.network=test`?

**Comment by robzon** [comment]
Always happy to break something :^)

The good news is changing the setting to `test` seems to fix the issue!

Back to my playground...

**Comment by pm47** [comment]
Yeah we don't handle well unexpected value for bitcoind parameters.

You might want to use regtest for easier testing, but please carry on breaking things :-)
