### ISSUE TITLE
`addwitnessaddress` deprecated in Bitcoin core 0.16

### ISSUE THREAD

**Issue by btcdanny** [ACINQ/eclair#432]
I have compiled Bitcoin core 0.16 when testing the eclair.log contains the following warning when another node attempts to open a channel with my node. The channel fails to open, I will build 0.15.1 and update if that solves my channel opening issues.

`WARN  akka.actor.OneForOneStrategy akka://default/user/$h/switchboard/peer-03d8deca0f0c85ec75f300a0c646944555bd5bf3c9fdf775503351d3ade3e16350  - addwitnessaddress is deprecated and will $
Projects should transition to using the address_type argument of getnewaddress, or option -addresstype=[bech32|p2sh-segwit] instead.
 (code: -32)`

**Comment by btcdanny** [comment]
I can confirm the issues are resolved when running Bitcoin Core 0.15.1

**Comment by sstone** [comment]
For now, If you build and use bitcoin core 0.16 (which has not been released yet) you need to add the `deprecatedrpc=addwitnessaddress` option (either in your bitcoin.conf file or on the command line you use to start it), and use `addresstype=p2sh-segwit` (which will be the default in 0.16). Then you won't have to worry about setting change addresses manually.
