### ISSUE TITLE
wallet does not seem to be downloading block headers from an electrum server--cannot sync

### ISSUE THREAD

**Issue by tfestate** [ACINQ/eclair#433]
Hi - I downloaded the mobile wallet from google play and sent 1.1 tbtc to it a few hours ago. it doesn't appear that the wallet is downloading the block headers from an electrum server. data storage stays at 376KB. i'm connected, am able to use my electrum wallet with no problem

i double checked the receive address and checked the tx id on the blockchain...many confirmations.

any ideas what I should do to get the wallet synced so i can open a channel and try out lightning sends?

thanks...looking forward to trying this out.

**Comment by tfestate** [comment]
Thanks very much  for replying. Sorry about posting twice.  -r

**Comment by pm47** [comment]
I was able to confirm that one of the test electrum servers was having issues recently.
