### ISSUE TITLE
Not Broadcasting Public IP

### ISSUE THREAD

**Issue by chsados** [ACINQ/eclair#438]
I have successfully gotten my node connected to a few channels, but for some reason I am not broadcasting my public IP according to https://explorer.acinq.co/#/n/0299ec4b40e55044f5c578512f6fa7161a7e1bc6d2638335a304c6f8607d2444aa.    Is there something I am missing in my eclair.conf file?

```
eclair.node-alias="SNIP"
eclair.node-color=68f442
eclair.api.enabled=true
eclair.api.password="SNIP"
eclair.bitcoind.rpcuser="SNIP"
eclair.bitcoind.rpcpassword="SNIP"
eclair.server.port=9735
```

**Comment by pm47** [comment]
You need to tell eclair what your public ip is by adding this to your configuration file:
```
eclair.server.public-ips.0=a.b.c.d
```

**Comment by chsados** [comment]
thank you

**Comment by pm47** [comment]
It is intentional because you may have multiple ips.

Works that way:

```
eclair.server.public-ips.0=a.b.c.d
eclair.server.public-ips.1=e.f.g.h
eclair.server.public-ips.2=i.j.k.l
```

Full syntax guide can be found [here](https://github.com/lightbend/config/blob/master/HOCON.md)
