### ISSUE TITLE
Bitcoin tx locked after opening channel --> insufficient funds error

### ISSUE THREAD

**Issue by Stadicus** [ACINQ/eclair#442]
I had this issue already several times but could reproduce it. Also, several readers of my [Beginner's Guide](https://medium.com/@stadicus/noobs-guide-to-%EF%B8%8F-lightning%EF%B8%8F-on-a-raspberry-pi-f0ab7525586e) had issues with this.

**Scenario**
Bitcoin Core wallet is newly set up, encrypted and empty. It is funded on testnet, and the whole balance is sent to a new `p2sh-of-p2wpkh` address, as outlined in the readme.
The first channels can be opened, but at some point in time (not sure when), new channels fail due to insufficient funds.

* channel status: `WAIT_FOR_ACCEPT_CHANNEL`
* after some time the channel is closed and even the peer is dropped, see eclair.log: 
  * `wallet returned error: fr.acinq.eclair.blockchain.bitcoind.rpc.JsonRPCError: Insufficient funds (code: -4)`
  * `shutting down`
  * `channel closed`
  * `that was the last open channel, closing the connection`

**Analysis**
However, `bitcoin-cli getbalance` shows sufficient funds. But `bitcoin-cli listunspent` gives me only a change address, nothing of significance. With `bitcoin-cli listlockunspent` I see, that the [tx 5768...](https://testnet.smartbit.com.au/tx/576822372211c3771f7025fec55b77fd7dcc3dc3ac2b068de365bf6933cc9dbc) is locked for some reason.

Here are the transactions up to that point (one channel opened for 0.1 tBTC), with the locked tx 5768... (and thus a locked utxo in 2MuBi...)

Start --> [2MwLc](https://testnet.smartbit.com.au/address/2MwLcQSQeisedL9YScA3BcgtvSh9pVmSuL2) --[[tx 5768](https://testnet.smartbit.com.au/tx/576822372211c3771f7025fec55b77fd7dcc3dc3ac2b068de365bf6933cc9dbc)]--> [2MuBi](https://testnet.smartbit.com.au/address/2MuBi9ajDLC94KfpFsCivmG7gUZUYZAG4Kc) --> ... etc.

**Solution**
`$ bitcoin-cli lockunspent true "[{\"txid\":\"576822372211c3771f7025fec55b77fd7dcc3dc3ac2b068de365bf6933cc9dbc\",\"vout\":1}]"`

After manually unlocking the [tx 5768]..., I can open the next channel (0.2 tBTC). The tx 5768... is listed as locked again, but that shouldn't be a problem, as all utxo have been spent. And after that, I can open a new channel for 0.3 tBTC, and the [tx bd79] is also locked.

The transactions after opening the next channels:

Start --> [2MwLc](https://testnet.smartbit.com.au/address/2MwLcQSQeisedL9YScA3BcgtvSh9pVmSuL2) --[[tx 5768](https://testnet.smartbit.com.au/tx/576822372211c3771f7025fec55b77fd7dcc3dc3ac2b068de365bf6933cc9dbc)]--> [2MuBi](https://testnet.smartbit.com.au/address/2MuBi9ajDLC94KfpFsCivmG7gUZUYZAG4Kc) --[[tx bd79](https://testnet.smartbit.com.au/tx/bd7952c9ec34ce114dbd50ef10e0671f03cc3b35f8158a03e781f5172db57be3)]--> [2NDDW](https://testnet.smartbit.com.au/address/2NDDW7gstVgWqveiR9DP6neTnxBd8FuRMiu) --> ...

Why could it be that the initial [tx 5768] was locked? I never sent transactions manually from this wallet after funding the p2sh-of-p2wpkh address.

Feel free to close this issue if you think it's not relevant. But maybe there is something to it?

**Comment by pm47** [comment]
eclair puts locks on utxos, in order to be able to fund multiple channels concurrently (this is needed because during the opening negotiation, we need to know the txid of the funding tx before publishing it).

It is possible that in some cases we forgot to remove the lock.

> However, bitcoin-cli getbalance shows sufficient funds. But bitcoin-cli listunspent gives me only a change address, nothing of significance. With bitcoin-cli listlockunspent I see, that the tx 5768... is locked for some reason.

At that point what are the statuses of all existing channels?

**Comment by Stadicus** [comment]
This is the current output:

```javascript
bitcoin@RaspiBolt:~ $ bitcoin-cli getbalance
2.11914514
bitcoin@RaspiBolt:~ $ bitcoin-cli listunspent
[
  {
    "txid": "18294103e157e915c255e2cb115f7f6b3161f9dc87050ed56b9f76827ee3bd5e",
    "vout": 0,
    "address": "2N9K89VY7QUAsd3NP4ZCVUg4QmnGWUm6SYU",
    "account": "",
    "redeemScript": "001404f39ea4bb7ce42877b72e37f5748b870893bdb2",
    "scriptPubKey": "a914b03ecce5884b2699dd3d49a9edb51a41b40cb36787",
    "amount": 0.00973888,
    "confirmations": 22257,
    "spendable": true,
    "solvable": true,
    "safe": true
  },
  {
    "txid": "3dc0aea9d2e95db1d65dffbaca308ddd76f6573bd3fae5e85e7276990aae8970",
    "vout": 0,
    "address": "2N5NE3kgAAVCxRhUkVfhirC6tvRGkqNHq1N",
    "account": "",
    "redeemScript": "0014a7cacec61d3d316f308d1038ae4cec400b3d7a2e",
    "scriptPubKey": "a91484f478988d00c0e1a0bd8befd0e7e552cb2ace0987",
    "amount": 2.10940626,
    "confirmations": 76,
    "spendable": true,
    "solvable": true,
    "safe": true
  }
]
bitcoin@RaspiBolt:~ $ bitcoin-cli listlockunspent
[
  {
    "txid": "576822372211c3771f7025fec55b77fd7dcc3dc3ac2b068de365bf6933cc9dbc",
    "vout": 1
  },
  {
    "txid": "bd7952c9ec34ce114dbd50ef10e0671f03cc3b35f8158a03e781f5172db57be3",
    "vout": 0
  }
]
bitcoin@RaspiBolt:~ $ eclair-cli channels
[
  {
    "nodeId": "03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134",
    "channelId": "bc9dcc3369bf65e38d062bacc33dcc7dfd775bc5fe25701f77c3112237226857",
    "state": "NORMAL"
  },
  {
    "nodeId": "03172377a939b21aadab64943ac82fc54a6600db48812dec9046c78abd78f5a0a2",
    "channelId": "7089ae0a9976725ee8e5fad33b57f676dd8d30cabaff5dd6b15de9d2a9aec03c",
    "state": "NORMAL"
  },
  {
    "nodeId": "02eba4a726c20c4fcc5a7291181f65dd389951b944dc48a0aec07b13d7c772de57",
    "channelId": "e37bb52d17f581e7038a15f8353bcc031f67e010ef50bd4d11ce34ecc95279bc",
    "state": "NORMAL"
  },
  {
    "nodeId": "0312b3f83b4beb8e9ecd05d0e3302d03ffa93ecaf10ed0a72a5f5cd2a62d1528f2",
    "channelId": "7f1519bbd687bc49f99ed612e9c6b049855a759381ed5a5ea434e88beb1e161a",
    "state": "NORMAL"
  },
  {
    "nodeId": "025e194297fdd776e46b795039cbfdd933505ea7bf0aba3da0d4338d0a05381e75",
    "channelId": "5fa23237820257aea69a88af5c8f9ed75b805a5ea3731931db5bfe7e9addbd35",
    "state": "OFFLINE"
  },
  {
    "nodeId": "03c8e50e2281d8ae4471c0a9ce7727d8c3e581143a6b00fc9a402ea03b05cd030c",
    "channelId": "183e5f0fdad789bec7078f11f8da529c7019fe1349b83cbe35bd1a5222a57330",
    "state": "OFFLINE"
  },
  {
    "nodeId": "03e38d5fabd53c15f0d3bc37c2e5d332dad8cf34cb4332035bdcfbc71a246c1675",
    "channelId": "344c34d36b13dd7137470cd8c5aa55d880f5241abccdf4101f64e0506a3a75d5",
    "state": "OFFLINE"
  }
]
```

**Comment by pm47** [comment]
Hmmm, that's weird: `576822372211c3771f7025fec55b77fd7dcc3dc3ac2b068de365bf6933cc9dbc:1` isn't in your utxo set and still show up as locked :confused:

**Comment by Stadicus** [comment]
This is the one tx I manually unlocked, then was able to open the second channel. Right after that, the tx was locked again.

**Comment by Stadicus** [comment]
The first attemped gave an error by the counterparty:
```
2018-02-17 11:30:25,007 ERROR fr.acinq.eclair.channel.Channel akka://default/user/$h/switchboard/peer-0372e8c16b4b3576dcc429d73418f48b33e59f04e77098673e2b040502ab307e37/$b 5cbe24c8351e24b51c5e403e7aefcc30845c9ee7d6ca946865679b960f67a36c - peer sent error: ascii='n/a' bin=02
2018-02-17 11:30:35,019 INFO  fr.acinq.eclair.channel.Channel akka://default/user/$h/switchboard/peer-0372e8c16b4b3576dcc429d73418f48b33e59f04e77098673e2b040502ab307e37/$b 5cbe24c8351e24b51c5e403e7aefcc30845c9ee7d6ca946865679b960f67a36c - shutting down
```

The second attempt worked just fine:
```javascript
bitcoin@RaspiBolt:~ $ eclair-cli channel "8248c1d78de0796fd7e050c5653dbd6ffd05a59814a68f386df4fefea8bb2fb9"
{
  "nodeId": "03a78e6e6aa86108769d97a065f501982f5a9eda80fe8acd1089edfe21d6dd91f3",
  "shortChannelId": null,
  "channelId": "8248c1d78de0796fd7e050c5653dbd6ffd05a59814a68f386df4fefea8bb2fb9",
  "state": "WAIT_FOR_FUNDING_CONFIRMED",
  "balanceMsat": 4000000000,
  "capacitySat": 4000000
}
```

This is the new locked tx state:
```javascript
bitcoin@RaspiBolt:~ $ bitcoin-cli listunspent
[
  {
    "txid": "18294103e157e915c255e2cb115f7f6b3161f9dc87050ed56b9f76827ee3bd5e",
    "vout": 0,
    "address": "2N9K89VY7QUAsd3NP4ZCVUg4QmnGWUm6SYU",
    "account": "",
    "redeemScript": "001404f39ea4bb7ce42877b72e37f5748b870893bdb2",
    "scriptPubKey": "a914b03ecce5884b2699dd3d49a9edb51a41b40cb36787",
    "amount": 0.00973888,
    "confirmations": 22271,
    "spendable": true,
    "solvable": true,
    "safe": true
  },
  {
    "txid": "b82fbba8fefef46d388fa61498a505fd6fbd3d65c550e0d76f79e08dd7c14882",
    "vout": 0,
    "address": "2MyJXkKvcDjLCCgHmbXffvsjdT2AYrjPUra",
    "account": "",
    "redeemScript": "00148f197e927e44201c5d23e82ff98b17df03e321d8",
    "scriptPubKey": "a9144270d3cdccaef629c5783de9a710897d0ad07d7f87",
    "amount": 2.06940447,
    "confirmations": 1,
    "spendable": true,
    "solvable": true,
    "safe": true
  }
]

bitcoin@RaspiBolt:~ $ bitcoin-cli listlockunspent
[
  {
    "txid": "3dc0aea9d2e95db1d65dffbaca308ddd76f6573bd3fae5e85e7276990aae8970",
    "vout": 0
  },
  {
    "txid": "576822372211c3771f7025fec55b77fd7dcc3dc3ac2b068de365bf6933cc9dbc",
    "vout": 1
  },
  {
    "txid": "bd7952c9ec34ce114dbd50ef10e0671f03cc3b35f8158a03e781f5172db57be3",
    "vout": 0
  }
]
```

**Comment by Stadicus** [comment]
Do you want me to close this issue, as it could be resolved manually? Or is it under investigation?

**Comment by pm47** [comment]
I'm not able to reproduce or find a problem with the information you provided. I guess let's close and reopen if the issue reappears.
