### ISSUE TITLE
android testnet wallet: address changes between executions of the app

### ISSUE THREAD

**Issue by rchikhi** [ACINQ/eclair#445]
Hi,

If I force-close/open the app around 3-4 times, it ends up switching to a different bitcoin address. (Therefore I cannot access the funds in the original address)

The app cycles between those 2 addresses. Is this a known issue?

Android app: Eclair Wallet Testnet
Phone: Samsung S7

**Comment by dpad85** [comment]
Hi,

To access the testnet blockchain, eclair mobile uses electrum servers. We configured only two and one of them has been desynchronized for a few weeks now, or is following a fork.

By closing/opening the app you're switching from one server to another and I guess that's the reason why you are switching to different bitcoin addresses, and your original funds can not be accessed.

You can check the eclair mobile block count by opening the `Network Overview` menu. These days the current testnet height should be something like `1,283,XXX`. If you get a lower block count, you're connected to a desynchronized electrum server. In this case the only workaround for now is to restart the app.

**Comment by rchikhi** [comment]
Oh that makes sense!
Yes I checked that the height is lower when I have the other address. 
Perhaps let the other users know?

**Comment by dpad85** [comment]
The fix for this issue will be available in the next release (0.2.4).

**Comment by dpad85** [comment]
0.2.4 is now available and fixes this issue.
