### ISSUE TITLE
Error starting using electrum as watcher

### ISSUE THREAD

**Issue by vitorbgs** [ACINQ/eclair#446]
When I use 
eclair.watcher-type = "electrum"
in eclair.conf I get the error 
"error electrum wallet requires a seed to set up"
on startup of eclair. 

Electrum is running on testnet, segwit wallet.

**Comment by dpad85** [comment]
the `electrum` watcher is not supported for desktop node, this is specific to mobile nodes. In any way, even if it worked, it would use an embedded electrum node, not the one you've installed on your machine. 

You must use the `bitcoind` watcher.

**Comment by mautematico** [comment]
Has this since changed?
