### ISSUE TITLE
Push amount unit improvement

### ISSUE THREAD

**Issue by vitorbgs** [ACINQ/eclair#448]
It would be more easy to calculate the opening of a channel if push amount could be in other units and not only in msat, just like you can set up in bitcoin, satoshi or milibitcoin in the channel capacity.

**Comment by dscotese** [comment]
When you open a channel, you set the push amount and the UI says "(msat)" but this seems to be wrong. At least in English, as I understand it, msat could mean thousandths of satoshi or millionths, or possibly, thousands (which should be ksat), but what it's really asking for is satoshis, according to the transactions themselves. So "(msat)" should be changed to "(satoshis)". Right?

**Comment by t-bast** [comment]
`msat` is milli-satoshi in Bitcoin/LN jargon.
Are you still experiencing an incoherency between what is being pushed and what you expect @dscotese?

**Comment by t-bast** [comment]
Closing this issue as the demo UI has been deprecated in [v0.4](https://github.com/ACINQ/eclair/releases/tag/v0.4).
PRs to improve the demo UI are still accepted, but we won't track any feature requests.
