### ISSUE TITLE
Serious delays when interacting with Eclair node

### ISSUE THREAD

**Issue by btcontract** [ACINQ/eclair#454]
Node in question: https://explorer.acinq.co/#/n/03dc39d7f43720c2c0f86778dfd2a77049fa4a44b4f0a8afb62f3921567de41375

It runs Eclair v0.2-alpha10.
Establishing a channel both from it and to it takes a lot of time (typically a couple of minutes to get through `WAIT_FOR_ACCEPT` -> `WAIT_FOR_FUNDING_SIGNED` -> ...).

Sending a payment to `starblocks` through `local node` -> `03dc39d7f43720c2c0f86778dfd2a77049fa4a44b4f0a8afb62f3921567de41375` -> `Endurance` -> `starblocks` sometimes takes minutes (longest seen delay was 15 minutes) with `starblocks` site often (but not always) displaying a payment as fulfilled within seconds.

`$ top` on server shows that `03dc39d7f43720c2c0f86778dfd2a77049fa4a44b4f0a8afb62f3921567de41375` does not take much resources so it does not seem like it's overwhelmed with work:
![screenshot from 2018-02-22 11-07-37](https://user-images.githubusercontent.com/9870980/36529322-b2153488-17c0-11e8-9085-9bf58a5c61a7.png)

UPD: an error message from local Eclair node when trying to send a payment:
> Ask timed out on [Actor[akka://default/user/$k#-1640924068]] after [30000 ms]. Sender[null] sent message of type "fr.acinq.eclair.payment.SendPayment".

UPD2: connecting directly to `Endurance` and sending a payment to `starblocks` has the same delay issues: a payment stayed in-flight for 3 minutes.

**Comment by pm47** [comment]
This is related to routing table sync and will be fixed by #453.

**Comment by pm47** [comment]
#453 has been merged a long time ago, not sure why this hasn't been closed.
