### ISSUE TITLE
Eclair Mobile Wallet - Not receiving testnet coins

### ISSUE THREAD

**Issue by rileyjalexander** [ACINQ/eclair#462]
I tried to fund my eclair wallet for testing purposes with some Testnet Coins. 

Coins were sent to: 2Mxmor3GN4ekw972AGpgUMtEPWzbBigoQtg which is the address that my eclair wallet shows as receive address. 

Coins were sent, now showing 6+ confirmations, yet eclair wallet shows 0 balance. have closed wallet and re-opened, restarted phone. 

So much for testing out anything else in the wallet as the first thing I tried to do had a bug. haha. Any ideas on what to do?

Eclair Version 0.2.3
Android Version 7.0
Samsung Experience Version 8.1
Android Security Patch Level January 1,2018

**Comment by dpad85** [comment]
Hi, thanks for testing out eclair.
Could you check your block count in the Network Overview menu and check that you have something ilke `1,286,XXX`?
It seems that your problem is the same as https://github.com/ACINQ/eclair/issues/433, https://github.com/ACINQ/eclair/issues/445, https://github.com/ACINQ/eclair/issues/434

**Comment by rileyjalexander** [comment]
Hey, so I restarted one more time based on what the other issues you sent me seemed to be suggesting and Voila! Fixed. 

ALTHOUGH, I would not consider that fixed because in more production usage, this would end up with 10,000 bug reports being sent in. haha. 

So I guess the end all answer to fixing this is to have a way for the eclair wallet to see if the Electrum server it is connecting to is out of sync?? And If out of sync, try other server.

**Comment by dpad85** [comment]
Yes, you're absolutely right, this would not be acceptable in production 😄 

The next release will display an 'out of sync' warning to the user if this happens. It would also be nice to have an automatic reconnection to other electrum servers, but that will come a bit later.

**Comment by rileyjalexander** [comment]
In followup to this issue, when you are connected to the BAD Electrum node, balances get way off. Basically it made my regular balance dissapear and says I only have the balance available that is in my channels. See attached transaction page. Do the math and you will see I am missing the majority of funds in my balance. 
![screenshot_20180226-145636](https://user-images.githubusercontent.com/2788144/36700739-940574b0-1b05-11e8-8f33-e0db8d4c386d.png)

**Comment by dpad85** [comment]
The fix for this issue will be available in the next release (0.2.4).

**Comment by dpad85** [comment]
0.2.4 is now available.
