### ISSUE TITLE
Why change LoggingFSM->FSM in commit b91e90783fa229ce8eec4eb924bdfc69b34a7546

### ISSUE THREAD

**Issue by n1bor** [ACINQ/eclair#465]
Before if you changed log level to DEBUG and ran the channel unit tests could see clearly the state transitions in logs:

`22:30:36.310 DEBUG akka://test/user/$$e - transition WAIT_FOR_FUNDING_INTERNAL -> WAIT_FOR_FUNDING_SIGNED
`
I really liked these log messages when walking through the Unit Tests which I find the easiest way to understand the code. And now they are gone!

Was there a good reason for this change?

Or was that unintended as you were expecting FSMDiagnosticActorLogging to do this logging - but it does not.

Can see issue by running this unit test with/without the commit after updating log level to debug.
`mvn test -Dtest=WaitForFundingSignedStateSpec`

Spent ages mucking about with application.conf etc... before realised it was a commit that changed the behavior!

**Comment by pm47** [comment]
The reason is explained in the PR, it's just too expensive: 

> LoggingFSM were great for debugging but they come at a high performance cost so it's time to get rid of them.

You are right that logging state transition is helpful when debugging, but when you need that level of details, just rename the class, it is a drop-in replacement.

**Comment by n1bor** [comment]
OK - makes sense.
Sorry - did not see comment about performance - need to learn how to use github better!
