### ISSUE TITLE
What happens when the IP of the node you have funded a channel to changes?

### ISSUE THREAD

**Issue by AndySchroder** [ACINQ/eclair#471]
So, when opening a channel as a funder, you need the nodeId, host, port, and available funds to fund the channel.

It seems as though the person receiving the incoming connection doesn't care if the IP changes of the person who funded the channel?

As a funder, what happens if the IP of the node you are connecting to changes after the channel has been established? Is there a way to change this if you know what it changed to? Does your node check for a new IP for that nodeId through initial gossip when starting back up eclair? If so, why do you need to specify the host and port when the channel is initially established?

**Comment by pm47** [comment]
> It seems as though the person receiving the incoming connection doesn't care if the IP changes of the person who funded the channel?

Correct.

> As a funder, what happens if the IP of the node you are connecting to changes after the channel has been established? Is there a way to change this if you know what it changed to?

Just open a connection to the new URI, and everything should sort itself out.

> Does your node check for a new IP for that nodeId through initial gossip when starting back up eclair? If so, why do you need to specify the host and port when the channel is initially established?

It doesn't currently, that may be something we add in the future.

**Comment by AndySchroder** [comment]
> Just open a connection to the new URI, and everything should sort it self out.

That works on ubuntu, but I can't seem to figure out how to do that on your android wallet. Even when the IP hasn't changed, I seem to be getting that the channel is offline on android, and I don't know how to force it to try and reconnect.



> It doesn't currently, that may be something we add in the future.

Understood. I can understand why you may and may not wan to do this.

**Comment by deafboy** [comment]
I have a related problem. My internet connection went down this morning so I've switched to a 4G modem with different public IP. All of my channels stayed offline (for hours) until I've manually reconnected to each peer.

**Comment by gr-g** [comment]
Recent versions of lnd support a dynamic IP for the node (option nat=true), which will make it more common in the future to have nodes that frequently change their public IP. Just something to keep in mind...

I think a reasonable approach could be, when a node appears offline, to do a [BOLT #10](https://github.com/lightningnetwork/lightning-rfc/blob/master/10-dns-bootstrap.md) lookup to find out if it has a new address (i.e. issue a DNS query for a name such as r0.n2.<node_id>.lseed.bitcoinstats.com).

It would also be helpful to have the possibility to simply (re-)connect to a node in the android wallet by scanning/copying the node_id without opening a new channel, as mentioned by AndySchroder.

**Comment by t-bast** [comment]
This issue has been fixed by https://github.com/ACINQ/eclair-mobile/pull/130.
Feel free to re-open if you're still experiencing this.
