### ISSUE TITLE
lnbcrt bech HRP for regtest

### ISSUE THREAD

**Issue by NicolasDorier** [ACINQ/eclair#474]
CLightning is now using `lnbcrt` for regtest [see](https://github.com/ElementsProject/lightning/commit/b30fb952e62c4a2d9077dee7af00e6e6b8474685#diff-53092192708008b1de0d997128c58d37L18).

It means that for now eclair can't be tested against clightning on regtest.
Can you update ?

**Comment by sstone** [comment]
Yes, it seems that `bcrt` is now the consensus for regtest bech32 prefix, though I could not find where it was specified (it is not in BIP173 afaict ?). I will update our prefix.
