### ISSUE TITLE
How to use in testnet

### ISSUE THREAD

**Issue by Sgt-Miller** [ACINQ/eclair#49]
I try the regtest it work.   
In testnet my friend is another computer. I in my computer.
We both have testnet3. Can we send to each other? Or is eclair send only locally to computer?
Also is bitfury lightning routing algorithm in eclair?

**Comment by pm47** [comment]
It works exactly the same way, just set the `eclair.bitcoind.network=test` in eclair.conf. In the next version (to be released next week) you won't even have to do that. 

Happy testing!

**Comment by pm47** [comment]
> Also is bitfury lightning routing algorithm in eclair?

No, for now [BOLT 7](https://github.com/lightningnetwork/lightning-rfc/blob/master/07-routing-gossip.md) defines a more simple alternative. Good enough for now!
