### ISSUE TITLE
[Mobile] possible regression, no longer a suggested app to handle LN payment requests

### ISSUE THREAD

**Issue by ric2b** [ACINQ/eclair#494]
Hello,

The new version of eclair no longer shows up as an option on my Android 7.1 phone when I tap an LN payment request link (I tested yalls and starblocks). Instead it now directly opens the [lightning-wallet](lightning-wallet.com) (what a confusing name, by the way, they should change it).

Previous versions of eclair used to show up as one of the two options for opening LN payment requests.

**Comment by pm47** [comment]
@btcontract Anton that's for you ^^

**Comment by dpad85** [comment]
Can you check that lightning-wallet is not set as the default app for opening the lightning payment request? 

You can do that on android 7 by going to the `android settings page > Apps > lightning-wallet` and verify that `open by default` is set to `No default set`. If not, you can clear the defaults, and try to open a payment request again; you should now have the choice between the two apps.

**Comment by ric2b** [comment]
> Can you check that lightning-wallet is not set as the default app for opening lightning payment requests?

Yes, I did check before submitting the issue :)

**Comment by dpad85** [comment]
That's strange, I can reproduce this issue with Chrome only, Firefox works fine, consistently with the application 'open by default' setting.

**Comment by ric2b** [comment]
You're right, it works as expected with Firefox.
The link seems to have the same format on both, maybe Chrome is doing something weird.

**Comment by dpad85** [comment]
A fix will be available in the next mobile version. Chrome is actually a bit more restrictive than Firefox, that's why it would not launch eclair with the `lightning:...` uris. Thanks for reporting the issue!

**Comment by dpad85** [comment]
Moved this issue to eclair-wallet repo.

**Comment by ric2b** [comment]
It is fixed with the latest version, btw, sorry for the delay
