### ISSUE TITLE
[Mobile] Yalls payment requests are now triggering "this is not a valid payment address" when copy pasted.

### ISSUE THREAD

**Issue by ric2b** [ACINQ/eclair#496]
Hello,

I'm trying the new version of eclair on my Android 7.1 phone and due to  #494 I have to copy/paste the payment requests instead of directly taping them. 

I've tried it multiple times already, copy/pasting works fine for starblocks payment requests but fails with "this is not a valid payment address" on yalls.

Scanning the QR code on yalls works fine though, and I'm able to make a payment that way.

**Comment by pm47** [comment]
Hm, I can't reproduce, can you paste the content of the payment request in this issue?

**Comment by ric2b** [comment]
Uh, never-mind.
The clipboard is empty after taping the copy button on Chrome Android.

I tried it with Firefox Android and it does copy th payment request and eclair is then able to make the payment, so I guess this is an issue with Chrome Android.
