### ISSUE TITLE
I requested a payment from lightning-wallet and tried to pay with eclair but didn't work

### ISSUE THREAD

**Issue by bitcoinuser** [ACINQ/eclair#501]
Hi,

Requested a payment from http://lightning-wallet.com/ and tried to pay with eclair but didn't work

Obs. Eclair and lightning-wallet has channels opened with yalls.

Payment request:

lntb1m1pdt92nkrzjqwfn3p9278ttzzpe0e00uhyxhned3j5d9acqak5emwfpflp8z2cngya8l5qqqasqqqqqqfcsqqqqqeqqjqrzjqghsakcdd28pjvswjjdx7f8ag3pv8y96ruu0sdymjthqaektmm8qsyaxgqqqqdqqqyqqqfcsqqqqqeqqjqdqqxqrrsspp5r0753sk0vp78tx7uz94j99dqfdqtyr44z8we3xge5rupvl9xf2jqzmzmjk0mhwyzt4fm5yfdamjq7lumehvvuzap37lkpp4m40u4h85srtuysn4z59cm0zrswajvlxet8txkuwl8kqafdve2x3mkmahfk0cqqz8z6v

![photo5014933905530267609](https://user-images.githubusercontent.com/1178856/37731307-844243e6-2d20-11e8-9b14-1e210b62ee12.jpg)

**Comment by pm47** [comment]
Good catch.

`lightning-wallet` opens private unannounced channels, and includes its channel info (=how to be reached) in the payment request it creates. `eclair wallet` currently only relies on public network info to find routes and doesn't use the hints provided in the request. This is already implemented in eclair-core, so fix is trivial.

**Comment by ric2b** [comment]
So the next version might already be able to do this? That would be awesome! :D

**Comment by dpad85** [comment]
Could you try to pay your payment request with this version:

https://acinq.co/assets/wallet/eclair-wallet-ff845ee.apk

This version is the same as the one deployed on google play, but with a fix so that it can handle the routing hint included in this payment request.

**Comment by bitcoinuser** [comment]
Installed the apk and I could pay a request from ln wallet with eclair wallet. Thanks.

**Comment by ric2b** [comment]
Sorry for the delay, it is indeed working with the latest versions of both :)
