### ISSUE TITLE
After upgrading 0.2.5 app fails to work

### ISSUE THREAD

**Issue by capricornuscipher** [ACINQ/eclair#502]
Upon opening a message is shown "Seed is unreadable. Aborting." No user suggestion is given and no UI is available. After swipe exit and/or Force Stop from Android: still behaves visually the same with same error message.

**Comment by dpad85** [comment]
Did you upgrade from 0.2.4 (released yesterday) to 0.2.5? or from 0.2.3 to 0.2.5?

A data wipe is required when upgrading from 0.2.3 to 0.2.5. When starting the app, a message should be be displayed telling you to clean the application's data, but it seems it was not the case.

Can you tell me if the app starts propertly once you clean the app data?

**Comment by pseudozach** [comment]
I had the same issue when upgrading from a much older version to the 0.2.5 version. After cleaning the app data from android system, app starts OK.

**Comment by capricornuscipher** [comment]
I'm not certain which was the prior version. But clearing all the storage data and importing the HD brainkey seed worked.

**Comment by dpad85** [comment]
Moved this issue to eclair-wallet repo.
