### ISSUE TITLE
node connection issues

### ISSUE THREAD

**Issue by bitcoinbeeman** [ACINQ/eclair#521]
Can someone help me understand why I cannot connect to any node on the lightning network?

Using a mac.

**Comment by sstone** [comment]
We will need more information: which version of eclair, how it is configured, which node you tried to connect to, what type of error you got, eclair debug logs... 
Open/support questions like this are better asked on our [gitter](https://gitter.im/ACINQ/eclair)

**Comment by bitcoinbeeman** [comment]
thanks for link to gitter.  I agree that is a much better place for this issue.
