### ISSUE TITLE
Add compatiblity with bitcoin nodes in bech32 mode

### ISSUE THREAD

**Issue by sstone** [ACINQ/eclair#523]
Right now we ask users to run bitcoin-core with `address-type=p2sh-segwit` and if they don't they will have problems when opening new channels and generating the address that is used to return the funds to when the channel is closed (see #522)

We should support "native segwit" nodes that run with `address-type=bech32`.

**Comment by slivver** [comment]
Hi,

unfortunately I forgot to the the address typ to p2sh-segwit. I now opened channels with a bech32 addresses. When I close channels the funds do not appear in my bitcoin core node.
Is there anything I can do to recover those funds?

**Comment by sstone** [comment]
Eclair does not currently understand bech32 addresses (as in: it will fail to parse them, see #522) and cannot open channels or accept channels when the bitcoin node it is connected to is in bech32 mode. What is in your logs ? how do you see that the funds were transferred to a bech23 address ?

**Comment by slivver** [comment]
Hi sstone,

here is one example. I opened a channel to 
02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432@104.198.32.198:9735.
The funding tx id is 54be5ef7526303f107f782bda147bb6ddb6b9cb0a0c79a82889a715ea52ffb25 and the output is bc1qlwlrmss6f4v59tcpn9k563wuawc6rpk9jpzmm45e8aq8ycxmlj9qncswru, which is a bech32 address. When closing the channel the funds were moved to bc1qmla0483ulukzwd8rvcxkxe0jvnaxkz60qvr7va (TX ID 61d408988060f337103206c6b5a8561763c44432acf55369b490249a3329b178)
My Bitcoin Core node does not recognize this address as it's own.

I uploaded my complete eclair.log here: http://www31.zippyshare.com/v/om8qTNzb/file.html

**Comment by sstone** [comment]
Can you please share you eclair.conf as well ?

**Comment by slivver** [comment]
Yes of corse. Here it is: https://pastebin.com/VmvCAE7A

**Comment by sstone** [comment]
It seems to be a fee estimation problem, unrelated to bech32/base58. The funding tx 54be5ef7526303f107f782bda147bb6ddb6b9cb0a0c79a82889a715ea52ffb25 is spent by the other party's commitment tx 61d408988060f337103206c6b5a8561763c44432acf55369b490249a3329b178. We detect it and spend our output in that tx to return the funds to the node's bitcoin wallet, that's tx 53f9ad89243771efec8f272a66c6a999e2d8c2f5ad695eb00f9dcd3932877d21. But there is a problem with our fee estimator which returns the fee rate to 0 and we end up trying to publish a 0-fee tx that is refused by the local bitcoin node ("cannot publish tx: reason=66: min relay fee not met (code: -26)").

**Comment by sstone** [comment]
I'm trying to find a way to get these tx to be accepted with CPFP, not sure yet if it's possible but I'll update this ticket

**Comment by slivver** [comment]
Thx for your effort. I configured my Bitcoin node to accept 0 fee transactions, but the rest of the network does not accept them. So these transaction never go to the mempool. Without being in the mempool I can't use CPFP, afaik.

Is it somehow possible to let eclair recreate these transactions with a fee?

As this seems to happen to all my closed channels, is there something I can configure in my eclair.conf to prevent this from happening?

**Comment by sstone** [comment]
Yes that's what I am working on. Make sure you keep your eclair data directory and I will give you a procedure that will enable you to recover your funds.
Unfortunately there is nothing in our configuration that you can change, this is a bug in our fee estimator that is fixed in #530

**Comment by sstone** [comment]
Can you contact me at https://gitter.im/ACINQ/eclair ?
