### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by deafboy** [ACINQ/eclair#525]
Are the tests up to date for the beta release? I've always skipped the tests while building testnet releases, but I let them run this time and got a lot of warnings and errors.

Running openjdk8 on Ubuntu 17.04

Here's the final summary:

> [INFO] Results:
> [INFO] 
> [ERROR] Failures: 
> [ERROR]   FuzzySpec>TestkitBaseClass.run:30->TestkitBaseClass.org$scalatest$BeforeAndAfterAll$$super$run:30->TestkitBaseClass.org$scalatest$fixture$FunSuiteLike$$super$run:30->TestkitBaseClass.runTests:30->TestkitBaseClass.runTest:30->TestkitBaseClass.org$scalatest$BeforeAndAfterEach$$super$runTest:30->withFixture:65->TestKit.within:814->TestKit.within:814->TestKit.expectMsgType:814 assertion failed: timeout (3 seconds) during expectMsgClass waiting for class fr.acinq.eclair.blockchain.WatchSpent
> [ERROR]   FuzzySpec>TestkitBaseClass.run:30->TestkitBaseClass.org$scalatest$BeforeAndAfterAll$$super$run:30->TestkitBaseClass.org$scalatest$fixture$FunSuiteLike$$super$run:30->TestkitBaseClass.runTests:30->TestkitBaseClass.runTest:30->TestkitBaseClass.org$scalatest$BeforeAndAfterEach$$super$runTest:30->withFixture:65->TestKit.within:814->TestKit.within:814->TestKit.expectMsgType:814 assertion failed: timeout (3 seconds) during expectMsgClass waiting for class fr.acinq.eclair.blockchain.WatchSpent
> [ERROR]   FuzzySpec>TestkitBaseClass.run:30->TestkitBaseClass.org$scalatest$BeforeAndAfterAll$$super$run:30->TestkitBaseClass.org$scalatest$fixture$FunSuiteLike$$super$run:30->TestkitBaseClass.runTests:30->TestkitBaseClass.runTest:30->TestkitBaseClass.org$scalatest$BeforeAndAfterEach$$super$runTest:30->withFixture:65->TestKit.within:814->TestKit.within:814->TestKit.expectMsgType:814 assertion failed: timeout (3 seconds) during expectMsgClass waiting for class fr.acinq.eclair.blockchain.WatchSpent
> [ERROR]   FuzzySpec>TestkitBaseClass.run:30->TestkitBaseClass.org$scalatest$BeforeAndAfterAll$$super$run:30->TestkitBaseClass.org$scalatest$fixture$FunSuiteLike$$super$run:30->TestkitBaseClass.runTests:30->TestkitBaseClass.runTest:30->TestkitBaseClass.org$scalatest$BeforeAndAfterEach$$super$runTest:30->withFixture:65->TestKit.within:814->TestKit.within:814->TestKit.expectMsgType:814 assertion failed: timeout (3 seconds) during expectMsgClass waiting for class fr.acinq.eclair.blockchain.WatchSpent
> [ERROR]   IntegrationSpec.run:60->org$scalatest$BeforeAndAfterAll$$super$run:60->org$scalatest$FunSuiteLike$$super$run:60->runTests:60->runTest:60->withFixture:60->TestKit.awaitCond:814->TestKit.expectMsgType:814 assertion failed: timeout (5 seconds) during expectMsgClass waiting for interface scala.collection.Iterable
> [ERROR]   IntegrationSpec.run:60->org$scalatest$BeforeAndAfterAll$$super$run:60->org$scalatest$FunSuiteLike$$super$run:60->runTests:60->runTest:60->withFixture:60->TestKit.expectMsgType:814 assertion failed: timeout (3 seconds) during expectMsgClass waiting for class fr.acinq.eclair.wire.UpdateAddHtlc
> [ERROR]   IntegrationSpec.run:60->org$scalatest$BeforeAndAfterAll$$super$run:60->org$scalatest$FunSuiteLike$$super$run:60->runTests:60->runTest:60->withFixture:60->TestKit.expectMsgType:814 assertion failed: timeout (3 seconds) during expectMsgClass waiting for class fr.acinq.eclair.wire.UpdateAddHtlc
> [ERROR]   IntegrationSpec.run:60->org$scalatest$BeforeAndAfterAll$$super$run:60->org$scalatest$FunSuiteLike$$super$run:60->runTests:60->runTest:60->withFixture:60->TestKit.expectMsgType:814 assertion failed: timeout (3 seconds) during expectMsgClass waiting for class fr.acinq.eclair.wire.UpdateAddHtlc
> [ERROR]   IntegrationSpec.run:60->org$scalatest$BeforeAndAfterAll$$super$run:60->org$scalatest$FunSuiteLike$$super$run:60->runTests:60->runTest:60->withFixture:60->TestKit.expectMsgType:814 assertion failed: timeout (3 seconds) during expectMsgClass waiting for class fr.acinq.eclair.wire.UpdateAddHtlc
> [ERROR]   IntegrationSpec.run:60->org$scalatest$BeforeAndAfterAll$$super$run:60->org$scalatest$FunSuiteLike$$super$run:60->runTests:60->runTest:60->withFixture:60->TestKit.expectMsgType:814 assertion failed: timeout (3 seconds) during expectMsgClass waiting for class fr.acinq.eclair.wire.UpdateAddHtlc
> [ERROR]   IntegrationSpec.run:60->org$scalatest$BeforeAndAfterAll$$super$run:60->org$scalatest$FunSuiteLike$$super$run:60->runTests:60->runTest:60->withFixture:60->TestKit.expectMsgType:814 assertion failed: timeout (3 seconds) during expectMsgClass waiting for class fr.acinq.eclair.payment.PaymentLifecycle$PaymentFailed
> [ERROR]   IntegrationSpec.run:60->org$scalatest$BeforeAndAfterAll$$super$run:60->org$scalatest$FunSuiteLike$$super$run:60->runTests:60->runTest:60->withFixture:60->TestKit.expectMsgType:814 assertion failed: timeout (3 seconds) during expectMsgClass waiting for class fr.acinq.eclair.payment.PaymentLifecycle$PaymentSucceeded
> [ERROR]   IntegrationSpec.run:60->org$scalatest$BeforeAndAfterAll$$super$run:60->org$scalatest$FunSuiteLike$$super$run:60->runTests:60->runTest:60->withFixture:60->TestKit.expectMsgType:814 assertion failed: timeout (3 seconds) during expectMsgClass waiting for class fr.acinq.eclair.payment.PaymentLifecycle$PaymentFailed
> [ERROR]   IntegrationSpec.run:60->org$scalatest$BeforeAndAfterAll$$super$run:60->org$scalatest$FunSuiteLike$$super$run:60->runTests:60->runTest:60->withFixture:60->TestKit.expectMsgType:814 assertion failed: timeout (3 seconds) during expectMsgClass waiting for class fr.acinq.eclair.payment.PaymentLifecycle$PaymentFailed
> [ERROR]   IntegrationSpec.run:60->org$scalatest$BeforeAndAfterAll$$super$run:60->org$scalatest$FunSuiteLike$$super$run:60->runTests:60->runTest:60->withFixture:60->TestKit.expectMsgType:814 assertion failed: timeout (3 seconds) during expectMsgClass waiting for class fr.acinq.eclair.payment.PaymentLifecycle$PaymentSucceeded
> [ERROR]   IntegrationSpec.run:60->org$scalatest$BeforeAndAfterAll$$super$run:60->org$scalatest$FunSuiteLike$$super$run:60->runTests:60->runTest:60->withFixture:60->TestKit.expectMsgType:814 assertion failed: timeout (3 seconds) during expectMsgClass waiting for class fr.acinq.eclair.payment.PaymentLifecycle$PaymentSucceeded
> [INFO] 
> [ERROR] Tests run: 490, Failures: 16, Errors: 0, Skipped: 3

**Comment by pm47** [comment]
> Are the tests up to date for the beta release?

[Of course they are](https://travis-ci.org/ACINQ/eclair/builds/359526669), not only for the tags but for every single commit on master (look for the green ticks in the [commit history](https://github.com/ACINQ/eclair/commits/master)). Tests must pass for a PR to be merged into master.

> I've always skipped the tests while building testnet releases, but I let them run this time and got a lot of warnings and errors.

Seeing warning and errors is normal during tests, as we are testing error conditions. The two tests that are failing here (FuzzySpec and IntegrationSpec) are more resource intensive than the others (in the latter we actually spawn a bitcoin core and ~10 instances of eclair), so depending on how powerful your box is, you might need to tweak timeouts (with eg `akka.test.timefactor`).

**Comment by pm47** [comment]
Note that you can also re-run these tests individually with e.g.  `mvn test -Dtest=FuzzySpec`.

**Comment by deafboy** [comment]
I decided to go #YOLO on this and skip the tests, but you've pointed me at the right direction so I'm closing this.
