### ISSUE TITLE
Mainnet - Pay problems - channel is currently unavailable

### ISSUE THREAD

**Issue by boehla** [ACINQ/eclair#527]
I have opened an channel to blockstream node and now I want to pay to different payment request. But on most of requests I get an error : "channel xxxx is currently unavailable.

Only payment to blockstream shop was possible.

For example:

> A reddit user request:
> lnbc5550n1pdtajlgpp5u8dmnq0n6scdddg46js3q8xatnz87catrm7prfrfhene7vmlnf0qdqqcqzysnkz66r8sqp02jajykx05yd7xvlvr5u2vpszx075mr9du8p2akwkx250gemhjspy5p6udzwwfqls2aujzdzn608rk4jjdl8kxw7p94rsprr4nem
> Error: 1 attempts: - (remote) channel 7df0e0005ba is currently unavailable
> Fulllog: https://pastebin.com/1cznMdkT

> http://bight.nl/:
> lnbc10u1pdt7t97pp5v6ymtu4xkvn8hf36q4khxls5eshsrukrpz0sdr6asxm9xqnu3vcqdq8w3jhxaqcqpglc9nqmxekj6a8vmm2q3g3p7suyy83eujkvvjqqxf5mc9hjv75wg8ay9hw55cwcp662l4gd4uxx7c3mkvs5vue0f0gdqcntrdw8h9jycq9hfpe8
> Fulllog: https://pastebin.com/1wc8Dca2

> https://lnmainnet.gaben.win/ donate:
> lnbc10u1pdt7tndpp5ry4r50wnvnywc6u4qxhfradd3fuqqqs92ru608w6stypxj2qwnnqdq6f38zq3tcwpkx7un9wgs9g6tswvcqzys7j7l7hsz9kccl5ev4jyg9tuqzd7eg3rl2qj48sa950klv96234t8led2q9lu4yyjjgel9wfl7v233ywzlys68zvg0gfcnap8n07mlkqp0xn0yt
> https://pastebin.com/u3fK4V8D

Can I do something to resolve this problems?

My specs:
- Windows 10 (Home pc + portforwarding)
- Bitcoin Core 16.0
- eclair-node-gui-0.2-beta1-c39ce69.jar

C:\Users\server\.eclair\eclair.conf:
```
elcair.server.public-ips=["84.115.253.70"]
eclair.server.port=9735
eclair.node-alias=WälderNode
eclair.node-color=007701
eclair.chain=mainnet
eclair.gui.unit=mbtc
```

bitcoin.conf:
```
dbcache=8096
server=1
rpcuser=foo
rpcpassword=bar
rpcallowip=10.0.0.0/255.0.0.0
rpcport=18332
txindex=1
addresstype=p2sh-segwit
zmqpubrawblock=tcp://127.0.0.1:29000
zmqpubrawtx=tcp://127.0.0.1:29000
```

**Comment by pm47** [comment]
I don't think there is necessarily a problem, and what you are experiencing might be perfecly normal. What happened is that most people opened a channel _to_ the blockstream node, which means that most of the money in these channels are on their side, and that we can't send funds _to_ them _from_ the blockstream node (hence the "channel temporarily unavailable" error).

**Comment by boehla** [comment]
Ok now I have a channel with 020fccc5602053c438b13ebee7aa31a25e9c3803baace5afcecedff8db70543747 (__AY_YILDIZ__) and could donate to http://bight.nl/

Thanks for help
