### ISSUE TITLE
[mobile] Confusing label on channels list

### ISSUE THREAD

**Issue by patestevao** [ACINQ/eclair#534]
Hi, I'm using Eclair 0.2.5 in Android 5.1.

I think the label “With…” that appears on top of each open channel doesn’t deliver a clear message.
Should it display the alias or the address of the node or am I missing something?

Thanks!

Here is a screenshot:
![eclair_21](https://user-images.githubusercontent.com/7728511/38300830-c2c342ac-37f5-11e8-8525-2b04c58e3814.png)

**Comment by dpad85** [comment]
It looks like a bug on android 5, it should display `With <node_id>` but the node id part is cut and you're left with `...`. The fix will be available in the next release. 

Thanks for reporting the issue!

**Comment by patestevao** [comment]
Okay, thank you for answering, @dpad85! Good to know. :)

**Comment by dpad85** [comment]
Moved this issue to eclair-wallet repo.
