### ISSUE TITLE
[mobile] Send button is too subtle

### ISSUE THREAD

**Issue by patestevao** [ACINQ/eclair#535]
Hi, I'm using Eclair 0.2.5 in Android 5.1.

Here is something I noticed.
The send button is one of the most important in this interface and it doesn’t call enough attention to itself.

Maybe the button could be in a brighter background color and/or slightly larger.
Let me know if I can help with some ideas and sketches on this.
Thanks!

For now, here is a screenshot with the button on the screen:
![eclair_18](https://user-images.githubusercontent.com/7728511/38301012-499e25f8-37f6-11e8-9839-540b6c961aad.png)

**Comment by patestevao** [comment]
Hi, thanks for answering. 

Nice to know that the color will be different in the mainnet version. Even so, you guys could consider making the button a different color from the main blue (like the "add" button in the Lightning channels section), it would get more attention that way.

I believe the positioning it's okay, users are used now to the material design standards. And the size might have been just my impression due to the discrete color.

Thanks for letting me know, I'll take a look at the repository when it's available.

**Comment by dpad85** [comment]
Moved this issue to eclair-wallet repo, please follow up in https://github.com/ACINQ/eclair-wallet/issues/33

Thanks!
