### ISSUE TITLE
Cannot open channel: false insuficient funds

### ISSUE THREAD

**Issue by gustavonalle** [ACINQ/eclair#539]
I have  0.00103488 in my BTC wallet with more than 6 confirmations, trying to open a channel with 0.001 and it won't let me due to "insufficient funds"

**Comment by lucaszanella** [comment]
Same here. I have 0.0014... and the minimum to open the channel is 0.001 but it says I can't. More than 6 confirmations.

**Comment by Amiga500** [comment]
Same here..

**Comment by dpad85** [comment]
Hi, thanks for reporting this issue. It's a duplicate of https://github.com/ACINQ/eclair-wallet/issues/6 (on the eclair-wallet github repo). The cause is an overzealous control in the interface.

This issue will be fixed in the next release of eclair wallet.

**Comment by gustavonalle** [comment]
Ok, closing this...
