### ISSUE TITLE
[mobile] Receive lightning payment / create payment request

### ISSUE THREAD

**Issue by xorq** [ACINQ/eclair#540]
Is there a way to receive lightning payments / create payment requests with the mobile version ?
Can't find a way and this is terribly missing... 
HAVE to make this possible!!!...

**Comment by dpad85** [comment]
Hi, this is not possible for now with the mobile version. 
You can find the rationale for this in https://github.com/ACINQ/eclair/issues/302 and https://github.com/ACINQ/eclair-wallet/wiki/FAQ#can-i-receive-payments-with-eclair-wallet-.

Closing this issue because it's a duplicate of #302.
