### ISSUE TITLE
Cannot pay bitrefill with mobile wallet

### ISSUE THREAD

**Issue by gustavonalle** [ACINQ/eclair#541]
I have a channel open with 02ad6fb8d693dc1e4569bcedefadf5f72a931ae027dc0f0c544b34c1c6f3b9a02b but cannot pay bitrefill invoice. It fails with "Unknown error" after having tried 10 times

**Comment by juscamarena** [comment]
It's a liquidity issue, eclair's capacity with bitrefill is all one sided now, well it was a small channel anyway, as well as their channel to yalls too I believe as I still have good capacity incoming from yalls.

You could for now either try opening a channel with bitrefill and/or yalls.

Bitrefill node key: 024a2e265cd66066b78a788ae615acdc84b5b0dec9efac36d7ac87513015eaf6ed@52.16.240.222:9735
yalls: 023668a30d0a27304695df3fb1af55a4fb75153eac34840817cae0e6a57894fd51@34.205.225.56

**Comment by pm47** [comment]
I've added more capacity to bitrefill, what a popular service ;-)

**Comment by gustavonalle** [comment]
Worked now for me, closing this...
