### ISSUE TITLE
Mobile wallet channel goes OFFLINE when remote node is alive

### ISSUE THREAD

**Issue by gustavonalle** [ACINQ/eclair#543]
I had a channel funded with 0.01 BTC opened with 02ad6fb8d693dc1e4569bcedefadf5f72a931ae027dc0f0c544b34c1c6f3b9a.
After a while the channel went OFFLINE and stayed like that, the only action from mynside was to forcibly close the channel hoping that the funds arrive after 144 blocks.

It appears the remote node is reachable and well (it is a highly connected hub on mainnet), so probably something went wrong on my wallet side?

**Comment by dpad85** [comment]
I tried to open a channel with this node (full URI being `02ad6fb8d693dc1e4569bcedefadf5f72a931ae027dc0f0c544b34c1c6f3b9a02b@167.99.50.31:9735`) and I could not connect to it. It seems that this node is not responsive, or very slow.

Note that, even if a node is shown in the various lightning explorer (such as https://lnmainnet.gaben.win/#), it may not be actually reachable at this very moment.

**Comment by gustavonalle** [comment]
Ok, got it. So if the remote node goes down, the only choice is to forcibly close the channel? Or is there a possibility of recovering the state in case it comes online again?

**Comment by dpad85** [comment]
You can simply wait for your peer to come back online, in which case the channel state will move from `OFFLINE` to `NORMAL` (with a few intermediate states). Forcibly close the channel is kind of a last resort option.

**Comment by gustavonalle** [comment]
Got it, thanks. Closing this
