### ISSUE TITLE
Lightning-c sends an "invalid sig" error

### ISSUE THREAD

**Issue by sstone** [ACINQ/eclair#545]
This happened with 02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432 on channel cdf9624c40a28494a41bf9adeddb64b63c7e0ba43598205a3a6fcbd9a0390d54.

A is eclair, B is lightning-c
```
A --- add htlc 1 ----> B
A --- commit sig ----> B
A <----- revack ------ B
A <---- commit sig --- B (includes htlc 1)
A -----  revack  ----> B
A <----- fail 1 ------ B
A ---- add htlc 2 ---> B (same payment hash, amount and expiry as htlc 1)
A ---- commit sig ---> B (includes htlc 1 and 2, with identical signatures)
A <---- commit sig --- B (no htlcs)
A <----- error  ------ B (invalid signature)   
```
I think that it is right to include both htlcs in our last commit sig message (?)
@cdecker what do you think ?

**Comment by cdecker** [comment]
@sstone can you share more info on the channel, not sure what that channel identifier is. I can search for funding transactions, or short_channel_ids :wink:

**Comment by pm47** [comment]
@cdecker here you go:
`fundingTxid`=`540d39a0d9cb6f3a5a209835a40b7e3cb664dbedadf91ba49484a2404c62f9cd`
`shortChannelId`=`7e27b0006270000`

**Comment by cdecker** [comment]
Ok, found the logs, rather a lot to read through, with log-level=debug we really produce a lot of logs.

I uploaded the last 1000 lines of logs regarding that channel here https://gist.github.com/cdecker/48d2b36420cdb847e94eb2d13e514620 and I'm scanning through it for relevant information now.

**Comment by pm47** [comment]
Here is our [log](https://gist.github.com/pm47/2a5ec2810b7289ca02b7ea9340d98ea8), not less verbose as we log all incoming and outgoing channel-related messages

**Comment by pm47** [comment]
@cdecker bug is on our side, we resolve htlcs on `pubkey_script`, which are exactly the same. We shouldn't accept having htlcs with the same `payment_hash` in the same commitment anyway.

**Comment by cdecker** [comment]
Not sure if the spec allows multiple HTLCs with the same `payment_hash` but it might be necessary for the sort of poor-mans-multi-path routing, allowing partial payments dependent on the same `preimage` to split and join along the multi-path. I'd rather not make this harder in the future. Can we disambiguate some other way?

**Comment by pm47** [comment]
We could disambiguate, but allowing several htlcs with the same `payment_hash` in // poses a clear risk for the sender: the receiver can forward only one of them and fulfill all of them, so I don't think we should encourage that.

**Comment by cdecker** [comment]
Well I think it's up to the recipient to wait for the full amount and not release the `preimage` for partial payment. If he releases the `preimage` and I can get it with a partial payment then he's at fault I'd argue because I can prove that the payment happened and that it was acknowledged by the recipient.

**Comment by pm47** [comment]
You're right, it makes sense that way and sender trusts the destination anyway.
