### ISSUE TITLE
Payment Failed - Remote Failure

### ISSUE THREAD

**Issue by pandabit** [ACINQ/eclair#547]
Every time I try to send a payment to yalls I get a 3 attempt(s) remote failure. Any thoughts on how to resolve? 

![screenshot_20180405-110122_2](https://user-images.githubusercontent.com/17555892/38384044-f70a5046-38c2-11e8-8328-3dd9e24e7b18.png)

**Comment by pm47** [comment]
That's a liquidity issue (everybody is trying to pay the same few merchants leading to channels getting unbalanced). We are creating more channels, that should be fixed shortly.

**Comment by pm47** [comment]
Closing this as issue has been resolved
