### ISSUE TITLE
More options for fees - i.e "Cap at 20%"

### ISSUE THREAD

**Issue by CubicEarth** [ACINQ/eclair#548]
The only option currently is to cap fees at 3%, or to not enforce at all.
I am sure that a more sophisticated approach will be developed in time, but until then, it would be good to have an option to allow fees to be up to some higher amount, while still caping them.

Is it possible that an uncapped fee could be more than 100%? For the next few months, people are going to be making many small 'test' payments to try out this new system.  And fees are often higher than 3%. But an 'uncapped' fee seems like it opens up an attack vector.

So perhaps a second toggle button to allow fees up to 20%, or a simple slider to select a fee level?

**Comment by dpad85** [comment]
Are you thinking about Eclair Wallet for this? For eclair node, this value can be changed by the user in `eclair.conf` and I don't think it need a specific UI widget.

For eclair wallet, however, it could certainly be useful.

**Comment by CubicEarth** [comment]
@dpad85 - You are right, I meant that this issue be attached to the Eclair Wallet repo.

Is there a way to 'move' the issue over? Or should I just close it here, and repost it over there?

**Comment by dpad85** [comment]
I'll copy this issue to the eclair-wallet repo, thanks!
