### ISSUE TITLE
i clicked tons of testnet nodes https://explorer.acinq.co/ but it says connectin failed or wait for accept and then closed

### ISSUE THREAD

**Issue by kostia-lev** [ACINQ/eclair#549]
i clicked tons of testnet nodes https://explorer.acinq.co/ but it says connectin failed or wait for accept and then closed

**Comment by pm47** [comment]
That's because a lot of servers advertise an ip address but don't actually open ports. A cool thing would be for the explorer to attempt connecting to these nodes and tell which ones are actually reachable.
