### ISSUE TITLE
Add json serializers for `NodeAddress` type

### ISSUE THREAD

**Issue by pm47** [ACINQ/eclair#565]
This was forgotten in 4db5564adafebabdbdd9939d6295f372bcf13242.

Result should be similar to what we had with `InetSocketAddressSerializer`.

Source of inspiration: https://github.com/ACINQ/eclair/pull/504

**Comment by pm47** [comment]
@gustavonalle want to give it a try?

**Comment by gustavonalle** [comment]
:+1:
