### ISSUE TITLE
LND "Getnodeinfo" fails when targeted at eclair wallet on Android.

### ISSUE THREAD

**Issue by AmazingDroopy** [ACINQ/eclair#566]
Eclair wallet for mainnet version 0.3.1

LND-Node:~ $ lncli listpeers
{
    "peers": [
        {
            "pub_key": "02bec0998480a26c2ca8acd54fa40f5f6b5add698cdf1a7b15afce75844fed5db2",
            "address": "87.126.135.225:64568",
            "bytes_sent": "5416793",
            "bytes_recv": "579",
            "sat_sent": "0",
            "sat_recv": "0",
            "inbound": true,
            "ping_time": "51465"
        },

LND-Node:~ $ lncli getnodeinfo 02bec0998480a26c2ca8acd54fa40f5f6b5add698cdf1a7b15afce75844fed5db2
[lncli] rpc error: code = Unknown desc = unable to find node

**Comment by sstone** [comment]
This is the wrong github repo (this one is for eclair, we have a specific repo for eclair-wallet) . See [eclair wallet FAQ](https://github.com/ACINQ/eclair-wallet/wiki/FAQ#i-dont-see-my-eclair-wallet-node-on-ln-explorers-) for why lnd does not find your mobile node.

**Comment by AmazingDroopy** [comment]
Thanks for the reply and additional info. 

Appreciated.

Richard.
