### ISSUE TITLE
Nodes with high CLTV deltas are not ignored when a route is recomputed

### ISSUE THREAD

**Issue by sstone** [ACINQ/eclair#569]
We have A -> B -> C -> D, C has a CLTV delay that is so high that channel A-> B will not process the payment (`expiry too high`), and we retry but we exclude A->B while in fact we should exclude C->D

**Comment by t-bast** [comment]
Closing this issue; this hasn't turned out to be an issue in practice, as nodes are incentivized to lower their `cltv_expiry_delta` to attract payments.
