### ISSUE TITLE
Can't open channels with an encrypted wallet, even if it's unlocked

### ISSUE THREAD

**Issue by QcMrHyde** [ACINQ/eclair#571]
I've tried Eclair a couple of times but never was able to open a channel but I just found why. It seems that we can't open channels with an encrypted wallet, even if it's unlocked. So I guess that's something that would need to be fixed or at least some feedback to the user should be added. In the end, I recreated a brand new wallet.dat and everything worked correctly.

**Comment by QcMrHyde** [comment]
I've realized that this issue might be due to the fact that my wallet wasn't an HD wallet. I'll close the issue if someone can confirm me that it's the cause of the problem. If so, sorry for opening an issue, but what I said about adding more feedback to the user is still valid.

**Comment by pm47** [comment]
Actually I think you may be running into #567. Try this:
1) `bitcoin-cli lockunspent true` (or restart bitcoin core, this will remove utxo locks)
2) `bitcoin-cli walletpassphrase <passphrase> 60`
3) open a channel

The fact that your wallet is not HD shouldn't play doesn't really matter.

**Comment by QcMrHyde** [comment]
I've reset my old wallet and tried your 3 steps but I keep getting an "Insufficient funds" error with "(funding tx not found in utxo)" in the logs. It's like Eclair can't access the funds on my Bitcoin wallet for some reason. That's why I was thinking this is probably because either my wallet is very old or it's encrypted but that might have nothing to do with it.

**Comment by sstone** [comment]
How old is your very old wallet ? it does not contain p2pkh utxos (otherwise eclair would not start),  so it cannot be very old.  The `funding tx not found in utxo` you see in the log is not related to your issue (it means that a channel in our routing table has been closed and cannot be used anymore).
After you've applied the procedure above, `bitcoin-cli listlockunspent` should return an empty array, and `bitcoin-cli listunspent` shoud show your utxos (most of them should be tagged as spendable and solvable). 
Also, just to be sure, you are using the released version of Bitcoin Core 0.16.0 ?

**Comment by QcMrHyde** [comment]
>How old is your very old wallet ?
I'd say it was created around 2013-2014

>After you've applied the procedure above, bitcoin-cli listlockunspent should return an empty array, and bitcoin-cli listunspent shoud show your utxos (most of them should be tagged as spendable and solvable).
They are and I see the same amount as my available amount in my wallet. I'm starting to wonder if I'm connecting correctly to other nodes, but again, all this is working perfectly if I created a brand new wallet.

**Comment by thetaj** [comment]
Hi guys! I need some help with the same problem. I am using core 0.16.0 and windows version of Eclair beta 2. I can open the software no problem, but I cannot seem to open a channel even though I have btc in my wallet.

The error I get is code: -13
Error: Please enter the wallet passphrase with walletpassphrase first

just posting this here as well 

If anyone can help please!

**Comment by pm47** [comment]
@thetaj this looks like #567 , will be fixed by #579

@QcMrHyde can you try again the steps provided in https://github.com/ACINQ/eclair/issues/571#issuecomment-383370035 and post the log if that fails? Thanks
