### ISSUE TITLE
Feature request: start/stop scripts

### ISSUE THREAD

**Issue by gustavonalle** [ACINQ/eclair#578]
It'd handy to have a shell script (for Linux and MacOS) and a cmd script (Windows) that allows to manage the service lifecycle:

```
./eclair.sh start | stop | status | restart
```

**Comment by n1bor** [comment]
an api call would be good to. killing always worries me!
Although stopping akka systems seems to be a bit of an art...

**Comment by gustavonalle** [comment]
I am using Linux ```systemd``` integration in my production node, it handles nicely start, stop, logs, pids, etc. 
It sends a graceful shutdown during stop, and I can see from the logs that no errors are thrown, so I assume it's fine :)

```
[Unit]
Description=Eclair
After=network.target
After=systemd-user-sessions.service
After=network-online.target

[Service]
User=bitcoin
SyslogIdentifier=Eclair
ExecStart=/usr/local/bin/eclair-node-0.2-SNAPSHOT-f52d167.bin

[Install]
WantedBy=multi-user.target
```

The ```eclair-node-0.2-SNAPSHOT-f52d167.bin``` is a self executing jar that I generated from the node uber jar.

**Comment by t-bast** [comment]
@gustavonalle do you still need this?
If you have time to submit a PR to add this script, that would be great.

**Comment by t-bast** [comment]
Closing this inactive issue. Latest state is that we welcome contributions to the existing script to add this feature.
