### ISSUE TITLE
can not pay to CL node from Eclair android

### ISSUE THREAD

**Issue by FeedTheWeb** [ACINQ/eclair#591]
[testnet]
payments to  CL node fail, and the errormessage is not really helping 

      "unreadable remote failure  a peer on the route failed the payment with a non readable cause "

target node : 
http://51.15.82.171/ln/demo
(using  cltv-final=12   cltv-delta=12 )

What could be the issue here ?

**Comment by pm47** [comment]
> What could be the issue here ?

This is most certainly related related to an interop issue between `eclair` and `lnd`, more precisely a disagreement about whether or not a particular field is to be included in error messages. This is being fixed in `lnd`.

**Comment by FeedTheWeb** [comment]
@molxyz  c-lightning, as mentioned.

**Comment by pm47** [comment]
In your case the destination node doesn't really matter, it's some node in the route that is causing the issue.

**Comment by Roasbeef** [comment]
In any case, `eclair` should be modified to be a bit more robust, in that even if the field isn't there, it should continue path finding attempts.

**Comment by FeedTheWeb** [comment]
![screenshot_20180511-133600](https://user-images.githubusercontent.com/1678423/39922802-2a078ad4-5521-11e8-8d35-e0ec8cc12991.png)
@Roasbeef  it does make multiple attempts. But the issue is that as a user I have no idea what is going on, why it fails, or if there is something I can do about it.
