### ISSUE TITLE
cannot sign when there are no changes while processing msg=CommitSig in state=NORMAL

### ISSUE THREAD

**Issue by n1bor** [ACINQ/eclair#597]
Is this a known issue?

Only thing slightly odd was that the funding became deeply buried whilst channel offline. But seemed to recover when node reconnected. But the got this error and closed channel.

If new issue will spend some time as have good logs.

**Comment by sstone** [comment]
It could be this: https://github.com/lightningnetwork/lnd/issues/1127 (lt's fixed now but could still happen if you're connected to a lnd node that has not been updated)

**Comment by n1bor** [comment]
Do you know if this causes the lnd node to lose funds? Or just they have to wait for the timeout? I assume the later. Just counterpart think I stole them at the moment!

**Comment by n1bor** [comment]
counterparty confirmed that did not lose any funds (just some fees). And that they were on old version of lnd so is the same issue.
Although when investigating issue do think we need a log per channel. As once whole thing scales up going to be very hard to investigate. Also my audit patch was very useful - see https://lightningconductor.net/balances as was very sure my balances were all as expected.
