### ISSUE TITLE
"Make sure that all your UTXOS are segwit UTXOS and not p2pkh" on setup even if all spendable UTXO are P2SH (but watch-only address is not) 

### ISSUE THREAD

**Issue by BobleChinois** [ACINQ/eclair#599]
## Environment
OS : Ubuntu 18.04 LTS
Bitcoin Core Daemon version v0.16.0
Eclair : version=0.2-beta2 commit=75986152631a225cecefb8f54a3d8788b305ee86
## Actions
* Bitcoind is running on mainnet and fully synchronized
* typing "java -jar eclair-node-0.2-beta2-7598615.jar" in linux shell
## Expected behavior
Eclair startup
## Logs
>2018-05-18 11:21:43,958 INFO  fr.acinq.eclair.Setup   - hello!
>2018-05-18 11:21:43,960 INFO  fr.acinq.eclair.Setup   - version=0.2-beta2 >commit=75986152631a225cecefb8f54a3d8788b305ee86
>2018-05-18 11:21:43,960 INFO  fr.acinq.eclair.Setup   - datadir=/home/bitcoin/.eclair
>2018-05-18 11:21:44,087 INFO  org.bitcoin.Secp256k1Context   - couldn't find secp256k1 library, >defaulting to spongycastle
>2018-05-18 11:21:44,594 INFO  fr.acinq.eclair.Setup   - nodeid=024976XXXXXX alias=eclair
>2018-05-18 11:21:44,596 INFO  fr.acinq.eclair.Setup   - using chain=mainnet >chainHash=6fe28cXXXXX
>2018-05-18 11:21:44,596 INFO  fr.acinq.eclair.Setup   - initializing secure random generator
>2018-05-18 11:21:46,687 ERROR fr.acinq.eclair.Boot$   - **fatal error: assertion failed: Make sure >that all your UTXOS are segwit UTXOS and not p2pkh** (check out our README for more details)

## Problem
I checked with a "listunspent" on bitcoin-cli, **I have no UTXO on p2pkh addresses**
**BUT** I do have a watch-only address on this wallet, which is p2pkh
I suspect that on setup Eclair just check with a "listunspent" and actually don't discriminate on the variable "spendable"
I read the [issue#287](https://github.com/ACINQ/eclair/issues/287), wouldn't be a good idea to check if "spendable=true", and not only the addresses ? 
Thanks !

**Comment by sstone** [comment]
Yes, you're right. We'll have a branch with a fix for this very soon.

**Comment by BobleChinois** [comment]
Ok I guess in the meantime I better reindex and stop following the watch only address, or is there another way ?
