### ISSUE TITLE
Could Not Connect to Bitcoin Core using JSON-RPC

### ISSUE THREAD

**Issue by jcbereznay** [ACINQ/eclair#606]
Please be gentle, noob here learning trying to contribute by hosting a mainnet node on Windows 10. I have v0.16.0 (64-bit) Core installed, fully synched, running with server = 1, foo, bar, 8332, etc - all of the recommended conf file settings. When I install eclair, I get the Could Not Connect pop up. I've made changes to eclair.conf, to match the bitcoin.conf settings but to no avail. I realize I don't know what I don't know, can someone please point me to a resource where I can do some reading/investigation to figure this out? Thanks very much. -Chris

**Comment by gustavonalle** [comment]
I'd start looking at the log file (under the user home directory, ```.eclair/eclair.log```). A wild guess here, assuming the config is all correct, maybe there's a firewall blocking the connection?

**Comment by kravens** [comment]
I'm running the same OS and software version, maybe my guide can help you:
https://steemit.com/lightning/@krav/eclair-bitcoin-qt-core-gui-setting-up-a-lightning-network-node

I believe you have to send a transaction to yourself, receiving the bitcoin on a Segwit address (starting with a 3), if you have not done so already! all the Bitcoin Core node funds must be Segwit / P2SH for Eclair to start... and something with a locking script: lockunspent true

**Comment by jcbereznay** [comment]
Thanks so much to you both for your responses. So I think the first sign of a problem in the logfile is this:

_2018-05-21 19:23:29,814 INFO  org.bitcoin.Secp256k1Context   - couldn't find secp256k1 library, defaulting to spongycastle_
2018-05-21 19:23:30,127 INFO  fr.acinq.eclair.Setup   - nodeid=02db01f521d8c1cd9eebc61e01b245a597015a7d12eac975992b3bd852049ac5af alias=eclair
2018-05-21 19:23:30,128 INFO  fr.acinq.eclair.Setup   - using chain=testnet 

Looks like I may be missing a library?

Also, I think I have correctly designated mainnet in the eclair.conf file, below, but the logfile shows testnet (above):

### eclair {

  chain = "mainnet" // "regtest" for regtest, "testnet" for testnet, "mainnet" for mainnet

  server {
    public-ips = ["my IP is here in the actual config file"] // external ips, will be announced on the network
    binding-ip = "0.0.0.0"
    port = 9735
  }

  api {
    enabled = false // disabled by default for security reasons
    binding-ip = "127.0.0.1"
    port = 8080
    password = "" // password for basic auth, must be non empty if json-rpc api is enabled
  }

  watcher-type = "bitcoind" // other *experimental* values include "electrum"

  bitcoind {
    host = "localhost"
    rpcport = 8332
    rpcuser = "foo"
    rpcpassword = "bar"
    zmq = "tcp://127.0.0.1:29000"
  }

  default-feerates { // those are in satoshis per byte
    delay-blocks {
      1 = 210
      2 = 180
      6 = 150
      12 = 110
      36 = 50
      72 = 20
    }
  }
  min-feerate = 1 // minimum feerate in satoshis per byte (same default value as bitcoin core's minimum relay fee)

  eclair.chain=mainnet
  eclair.bitcoind.rpcport=8332
  eclair.bitcoind.rpcuser=foo
  eclair.bitcoind.rpcpassword=bar
  node-alias = "117BillionServed!"
  node-color = "49daaa"
  global-features = ""
  local-features = "0a" // initial_routing_sync + option_data_loss_protect
  channel-flags = 1 // announce channels
  dust-limit-satoshis = 546

  max-htlc-value-in-flight-msat = 1000000000 // 10 mBTC
  htlc-minimum-msat = 1
  max-accepted-htlcs = 30

  reserve-to-funding-ratio = 0.01 // recommended by BOLT #2
  max-reserve-to-funding-ratio = 0.05 // channel reserve can't be more than 5% of the funding amount (recommended: 1%)

  to-remote-delay-blocks = 144 // number of blocks that the other node's to-self outputs must be delayed (144 ~ 1 day)
  max-to-local-delay-blocks = 2000 // maximum number of blocks that we are ready to accept for our own delayed outputs (2000 ~ 2 weeks)
  mindepth-blocks = 3
  expiry-delta-blocks = 144

  fee-base-msat = 1000
  fee-proportional-millionths = 100 // fee charged per transferred satoshi in millionths of a satoshi (100 = 0.01%)

  // maximum local vs remote feerate mismatch; 1.0 means 100%
  // actual check is abs((local feerate - remote fee rate) / (local fee rate + remote fee rate)/2) > fee rate mismatch
  max-feerate-mismatch = 1.5

  // funder will send an UpdateFee message if the difference between current commitment fee and actual current network fee is greater
  // than this ratio.
  update-fee_min-diff-ratio = 0.1

  channel-exclude-duration = 60 seconds // when a temporary channel failure is returned, we exclude the channel from our payment routes for this duration
  router-broadcast-interval = 60 seconds // see BOLT #7

  ping-interval = 30 seconds
  auto-reconnect = true

  payment-handler = "local"
  payment-request-expiry = 1 hour // default expiry for payment requests generated by this node
  max-pending-payment-requests = 10000000
  max-payment-fee = 0.03 // max total fee for outgoing payments, in percentage: sending a payment will not be attempted if the cheapest route found is more expensive than that
}


And then, finally, this:

_2018-05-21 19:23:31,790 ERROR fr.acinq.eclair.gui.FxPreloader   - fr.acinq.eclair.BitcoinRPCConnectionException$: could not connect to bitcoind using json-rpc_

**Comment by gustavonalle** [comment]
> Looks like I may be missing a library?

Nope, this is only a INFO you don't have a native library in your system and it picked another

>  I think I have correctly designated mainnet in the eclair.conf

Where are putting your ```eclair.conf``` file? It should go in the same folder as ```eclair.log```

Also, the config file you pasted looks strange: you have at the beginning:

```
eclair {

    chain = "mainnet" // "regtest" for regtest, "testnet" for testnet, "mainnet" for mainnet
 ```


but further down:

```
eclair.chain=mainnet
```

You should pick either the hierarchical config or the flattened one!

**Comment by jcbereznay** [comment]
Thanks again. The eclair.conf file is indeed located in the directory with the log file. On my particular PC it looks like this:

C:\Users\jcber\.eclair\testnet\
C:\Users\jcber\.eclair\eclair.conf
C:\Users\jcber\.eclair\eclair.log
C:\Users\jcber\.eclair\seed.dat

The eclair.conf file layout that you see above is what was installed when running the executable in Windows, so maybe I will work to clean that up into the flattened format, which seems cleaner.

One other note, in my .eclair installation folder there is also a folder called testnet (but not mainnet), and inside it contains eclair.sqlite and network.sqlite. I don't know if that is a factor, but thought it was interesting that there was no mainnet folder. Perhaps that doesn't matter?

**Comment by sstone** [comment]
@jcbereznay can you contact us on [gitter](https://gitter.im/ACINQ/eclair) ?

**Comment by sstone** [comment]
Closing because we try to restrict github to strictly technical issues. [gitter](https://gitter.im/ACINQ/eclair) is a better option for open questions, troubleshooting configuration issues and support.
