### ISSUE TITLE
Authentication failed using Strike 

### ISSUE THREAD

**Issue by lightningnetworkstores** [ACINQ/eclair#611]
I went to [Strike's website](https://strike.acinq.co) and following the API reference to create a charge but it keeps failing:

I copy pasted the example curl command on the command line, replaced the API key but I get a 401 error.  I generated three new API keys, tried them and nothing. Added and removed the ":" after the key and nothing. Sometimes I am prompted "Enter host password for user 'sk_KDkc4QQcPGT8Vhbu7SaDKFKNQqYSA':" and I enter the password of my account in "strike.acinq.co" and it fails... Please tell me what I am doing wrong. Command pasted below:

curl https://api.dev.strike.acinq.co/api/v1/charges -u sk_KDkc4QQcPGT8Vhbu7SaDKFKNQqYSA -d amount=42000 -d currency="btc" -d description="Blockaccino"

**Comment by dpad85** [comment]
Hi, this is not the right place for support for Strike, this github should only be used to report technical issues with eclair. I edited your message to remove your secret key (you must keep it private), but anyway you should regenerate a new one in Strike (https://strike.acinq.co/dashboard/account/apikeys).

Thanks! Closing this.

**Comment by dpad85** [comment]
For any issues with Strike, the right step is to contact us on strike@acinq.co. Thank you!
