### ISSUE TITLE
Eclair does not enforce "Their dust is higher than our reserve" rule on channel opening but LND does

### ISSUE THREAD

**Issue by btcontract** [ACINQ/eclair#613]
Discovered this while trying to open a `250000 SAT` channel using a wallet where local `dustLimit` is set to `5460 SAT` and channel reserve is set to 2% which would be `5000 SAT`. Remote Eclair based nodes accept it while LND return an `Error from remote peer: channel reserve of 5000 sat is too small, min is 5460 sat`.

This rule is described here: https://github.com/ElementsProject/lightning/commit/83f83f7685437c722bd3dcc3d42fd328c51574ef

**Comment by sstone** [comment]
Thanks @btcontract, working on a PR that will be ready very soon
