### ISSUE TITLE
Send API dangerous and timeout does not mean a payment failed.

### ISSUE THREAD

**Issue by n1bor** [ACINQ/eclair#615]
Seen examples of payments hanging for 4.5 hours before failing:

> 05:18:39.879 INFO  akka://default/user/$j/payment-initiator/$4 f.a.eclair.payment.PaymentLifecycle - route found: attempt=2/5 route=02ad6fb8d693dc1e4569bcedefadf5f72a931ae027dc0f0c544b34c1c6f3b9a02b-02d539692f55b6d61847dc432bb78166bf52318e80e6b33733bb75f76645656e27 channels=7f96a0003370000->803ed0006250001

> 09:54:44.878 INFO  akka://default/user/$j/payment-initiator/$4 f.a.eclair.payment.PaymentLifecycle - received an error message from local, trying to use a different channel (failure=channel is unavailable (offline or closing))

So do we need another call to poll the API to check if timed out payments have now failed or succeeded?

And actually in the lightning spec once we try to send a payment we can only be sure it has failed once the htlc is rolled back in our commit. So staying open for hours/days is a possibility that could be common?

**Comment by n1bor** [comment]
And do we not need to store PaymentLifecycle state in the database? As if we restart the node with pending HTLC payments will be hard to track if they were then paid of failed.

**Comment by n1bor** [comment]
PR #619 fixes issue.
Not perfect as not logged to database. But better than nothing. Just need to check for pending sends before restarting node.

**Comment by n1bor** [comment]
@pm47 @sstone @btcontract 

Just documenting what I need as not sure current implementation of #694 is going to meet it.


I as a developer of an external application using Eclair to send payments I need a simple API that:

1. Sends payments that pay/fail immediately.
2. Sends payments that hang for hours/days and are:
2.1. Recoverable over restarts of my application.
2.2. Recoverable over restarts of Eclair
2.3. And then pay successfully.
2.4. And then fail.
3. To be able to do this without any understanding of Lightning implementation details - e.g. HTLC's etc..

I need this so I can develop reliable applications that behave predictably and do not double pay or never pay a customer of my application.

This would be simple enough if I had one API call to do the send which if completes quickly returns status and detail immediately. Then a second API call that allowed me to periodically poll sends that hang and returns the same. I could then track paid/failed/hung status easily.

\
\
I think the issues with the current implementation are just around the payments that hang and timeout on the send API call.
If the application was down for a period of time and you are then recovering the sentinfo API call in #694 does not help. It returns an error if a payment is pending - so you then need to query the correct channel to see if it is there - if not you can conclude it has failed/timed out.

I think that either the PaymentInitiator should have a backing database to track status of each send (paid/failed/pending/not-exist) or the sentinfo API should manage the call to the channel to find the status rather than expecting the developer to understand all these complexities.

Happy to push a PR with either approach on top of #694 or follow another approach if someone has a better idea.

**Comment by btcontract** [comment]
What about the following approach:

- send-and-forget a `send` API call, do not rely on it's output.
- listen for websocket events permanently to catch failed and successful payments.
- on websocket or app restart first call `channels` and extract all pending payments, then call `sentpaymentinfo`/`receivedpaymentinfo` for finalized payments. If a certain payment can't be found anywhere it means it was failed.

**Comment by btcontract** [comment]
`channels` call is a bit costly, although it does runtime computations only it queries all available channels and produces a lot of Json output so it better be called once and not per each payment someone wants to check.

I may be wrong about this but looks like it's better to combine "`channels` once, then `sentpaymentinfo`/`receivedpaymentinfo` per each payment" or `checkpayment` can be modified to accept many payment hashes at once and call `channels` once internally.

**Comment by n1bor** [comment]
My other idea was to change PaymentInitiator to:
 
Maintain map of “paymenthash” -> State (pending/paid/failed).
On startup get list of channels from register. Then get list of pending payments from each channel and populate map - so is always aware of all pending payments by then subscribing to eventstream for updates from PaymentLifecycle.
Add message GetSentPaymentStatus that returns Option[State] with the state of the payment.
 
Change service.scala so:
Update sentinfo asks PaymentInitiator for paymenthash status if it is not in auditDB.
  
Update AuditDb to add a FailedSentPayment table that tracks failed payments. And add a getSentStatus that unions across the sentpayments and failedsentpayments so return correct status.

This way sentinfo will always return one of payed/failed/pending. And if not there is a bug somewhere.

Happy to pr this once your pr is merged... if everyone agrees..

**Comment by juscamarena** [comment]
Seems this should be closed as the new payment api live.
