### ISSUE TITLE
WAIT_FOR_FUNDING_CONFIRMED and Transaction Id is invalid

### ISSUE THREAD

**Issue by yuyaogawa** [ACINQ/eclair#617]
When I tried to open a channel, it showed WAIT_FOR_FUNDING_CONFIRMED and it past a few days since then. When I checked the transaction by opening in explorer, I got this
`{"error": "Transaction 8acd8b5d6f95fb7f2dae9ab4e3fa2b67b35f0e5350c1bd6cd09190cba64a4acc not found."}`

It seems to me that the funding transaction wasn't broadcast. However, the wallet showed the channel is waiting for the confirmations. I want to know the cause and how to resolve this.

Eclair Installed version: 0.3.1
This is what I got for technical information from the eclair wallet.
`RES_GETINFO(033613d280de1eba995c7545e93caf76cfba41bef88c2d6732a67ce06c168b3acb,cc4a4aa6cb9091d06cbdc150530e5fb3672bfae3b49aae2d7ffb956f5d8bcd8a,WAIT_FOR_FUNDING_CONFIRMED,DATA_WAIT_FOR_FUNDING_CONFIRMED(Commitments(LocalParams(030e65863caf4232d05f435b20135c7d6e133bcee1e1c7f28006af53c19bc29e3f,m/1990222943'/601420960/587130134/1464290005',546,1000000000,1000,1,144,30,true,a914a06a7b4d785d2aa15a491e1e637321a76c32a94a87,,88),RemoteParams(033613d280de1eba995c7545e93caf76cfba41bef88c2d6732a67ce06c168b3acb,546,18446744073709551615,1000,0,144,483,0370f98b4b73f00539ec26274e63ea0a31a77f37b2889c27033db1a0f856c9c740,02a7bf353310cf6855601350d038397ed96aa0853cbc5be7388b2020b9a8ede64e,03aee99028ba96eec172790e4e7fcd8332a820b300b2958f635341dc0133638571,03aa7eaf07b63992e28bcffa37230778d03c633a3dd0c04f3854f34c507317a164,031c8858f7c9e84e216e54a107dc3c5fd4c2c858dfec9bf7d7bb4632f3bb4e8500,,08),0,LocalCommit(0,CommitmentSpec(Set(),768,100000000,0),PublishableTxs(CommitTx(InputInfo(OutPoint(cc4a4aa6cb9091d06cbdc150530e5fb3672bfae3b49aae2d7ffb956f5d8bcd8a,0),TxOut(Satoshi(100000),00200f8bfd58c87b504aa04be2c226874f13b20b8e50045ba4dff857de3e5c516828),5221034d96d0ade382a610b4fbc26c864d1324f42a335dc062254de98e1ff745172d13210370f98b4b73f00539ec26274e63ea0a31a77f37b2889c27033db1a0f856c9c74052ae),02000000000101cc4a4aa6cb9091d06cbdc150530e5fb3672bfae3b49aae2d7ffb956f5d8bcd8a00000000004f0cfc80017484010000000000220020072f93e46c90d7f474d835512befbc93eea0751234d55e3493e2deb3c7dac4720400483045022100d6f9b99ac22bbd8b78aadefcea526d64d705fff5a98e331443296332ce05c92f022068acf6139796200f9472615c49048f36761cfe05fac5a098cf7d74022d11de9e01473044022038d05ae45b095e9087c1ab111b07b570a546702af0c2de8ec12643016f865c38022076f702de381239fb7b240efb1ab4fa5d00d60eb39e13f8f9aeaefcacc4c4a30501475221034d96d0ade382a610b4fbc26c864d1324f42a335dc062254de98e1ff745172d13210370f98b4b73f00539ec26274e63ea0a31a77f37b2889c27033db1a0f856c9c74052aefdb84520),List())),RemoteCommit(0,CommitmentSpec(Set(),768,0,100000000),10add935b3669af71b21217f0b0a6992f6e09edba1f4b1ec5429d85dd7f73f1b,02047e45c9798e7087a518b8ab3318bf74440496941b0ad3b1bc1c1ad50b1c8948),LocalChanges(List(),List(),List()),RemoteChanges(List(),List(),List()),0,0,Map(),Right(02e1ba44194f375a65e58265b1c51bb852e011eef7d5d7af629f7476eec9ccbe51),InputInfo(OutPoint(cc4a4aa6cb9091d06cbdc150530e5fb3672bfae3b49aae2d7ffb956f5d8bcd8a,0),TxOut(Satoshi(100000),00200f8bfd58c87b504aa04be2c226874f13b20b8e50045ba4dff857de3e5c516828),5221034d96d0ade382a610b4fbc26c864d1324f42a335dc062254de98e1ff745172d13210370f98b4b73f00539ec26274e63ea0a31a77f37b2889c27033db1a0f856c9c74052ae),ShaChain(lastIndex = None),cc4a4aa6cb9091d06cbdc150530e5fb3672bfae3b49aae2d7ffb956f5d8bcd8a),None,Left(FundingCreated(d2c5273310880b0581f5f65df0bcb92d6d7221217ee26208b0790c832c8b7146,cc4a4aa6cb9091d06cbdc150530e5fb3672bfae3b49aae2d7ffb956f5d8bcd8a,0,3045022100de5ffe96000df6b24d1fade536e738df08a52afbad0c9d18718d07f43be0f53602203a2ea63fd4fdf0e4ef7ee88b3facdb816af835c322b1862b4ce1bf0c7078062601))))
`

**Comment by pm47** [comment]
What version of eclair wallet are you using? Does the tx appear in the transaction history? If so, can you click on it and try to rebroadcast it ?

**Comment by yuyaogawa** [comment]
@pm47 
Eclair Installed version: 0.3.1
No, the tx didn't appear in the transaction history.

**Comment by yuyaogawa** [comment]
Sorry, my issue should go to https://github.com/ACINQ/eclair-wallet/issues/ So I close this issue
