### ISSUE TITLE
Are we actually sending ChannelUpdate every 7 days?

### ISSUE THREAD

**Issue by n1bor** [ACINQ/eclair#621]
Do we not need a "forwarder ! channelUpdate" after this line?
https://github.com/ACINQ/eclair/blob/a85ba9ceef9dd68150237ab0f2a86672182a6a73/eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala#L817

As currently I can not see how the update would get published?

**Comment by pm47** [comment]
Yes, it happens here: https://github.com/ACINQ/eclair/blob/a85ba9ceef9dd68150237ab0f2a86672182a6a73/eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala#L1452-L1462

**Comment by n1bor** [comment]
But that only gets triggered when we transition from one state to another (is in onTransition call).

According to the akka docs:
https://doc.akka.io/docs/akka/2.5/fsm.html
>stay using store(d.copy(channelUpdate = channelUpdate))

stay does not trigger a call to onTransition. Would have to be goto.

Just think when I was developing #621 I had to call 
>forwarder ! d.channelUpdate

to get it to work. Although I could have been confused by the GUI issues I had too!

Obviously only an issue if you can keep the node up for 7 days without needing to patch it!
