### ISSUE TITLE
eclair-cli help requires password

### ISSUE THREAD

**Issue by Christewart** [ACINQ/eclair#622]
Is this intentional or can this be fixed? I'm trying to just use the help command and I am being prompted for a password

```
$ ./eclair-cli help
Usage: eclair-cli [OPTION]... [COMMAND]
Client for an eclair node.

With COMMAND is one of the command listed by eclair-cli help.

  -p <password>         api's password
  -a <address>          Override the api URL with <address>
  -v                    Outputs full json returned by the API

Examples:
  eclair-cli -a localhost:1234 peers     list the peers
  eclair-cli close 006fb...              closes the channel with id 006fb...

Note: Uses the json-rpc api exposed by the node on localhost:8080. Make sure the api is enabled.
Full documentation at: <https://github.com/ACINQ/eclair>

Available commands:

Enter host password for user 'eclair-cli':
```

**Comment by Christewart** [comment]
The behavior I was expecting is that it would show all of the rpc commands initially. It currently only shows all of the RPC commands after I enter in my password.

**Comment by dpad85** [comment]
Yes it's a bit confusing, but this is a way of not hardcoding the list of available rpc commands in the `eclair-cli` file itself. 

`eclair-cli` is not bundled with the releases, users have to download the file themselves, and it's probably not kept up to date with the latest version. So the trick is to directly call the API to get the list of the available commands. And for that you need the API password.
