### ISSUE TITLE
network.sqlite is killing my HDD

### ISSUE THREAD

**Issue by peername** [ACINQ/eclair#623]
It is not a good idea to store all the network information on a disk. Especially in a Sqlite database. The file is overwritten on each new channel / node. My hard drive does not stop writing.

Consider keeping this information in memory. Sqlite supports ":memory:" dsn.

Another option is to use:

PRAGMA synchronous = OFF
PRAGMA journal_mode = MEMORY

for network.sqlite only. The content of this file is not critical.

**Comment by n1bor** [comment]
Wonder if related to #624?
