### ISSUE TITLE
Installed with .conf files for eclair and bitcoin but cannot connect

### ISSUE THREAD

**Issue by d4amenace** [ACINQ/eclair#625]
I am running bitcoin core 0.16.0 and have installed the following conf file:

testnet=0
server=1
rpcuser=foo
rpcpassword=bar
txindex=1
zmqpubrawblock=tcp://127.0.0.1:29000
zmqpubrawtx=tcp://127.0.0.1:29000
addresstype=p2sh-segwit
rpcssl=1

I am running eclair with the following conf file in .eclair:

eclair.chain=mainnet
eclair.bitcoind.rpcport=8332
eclair.bitcoind.rpcuser=foo
eclair.bitcoind.rpcpassword=bar

I have opened the port 9735 on my firewall for UDP and TCP but I still get the error message:

"Could not connect to Bitcoin Core using JSON-RPC"

any ideas?

**Comment by sstone** [comment]
Hi, we use github for strictly technical issues and bug reports, for more general questions and support please go to our [gitter](https://gitter.im/ACINQ/eclair) instead.

**Comment by d4amenace** [comment]
@sstone Sorry about that......LN is so new that there aren't many sites online with forums for Eclair and I had no idea where to turn.

@Christewart WOW...Thanks bro. I'm no coder and I would have never figured this out!  That worked perfectly!

**Comment by d4amenace** [comment]
@Christewart I have gotten as far as setting up eclair on windows desktop for sending and receiving using bitcoin core 0.16 . Once I fund my first channel, am I a full node and the capacity is the channel amount? Or what else would I need to do to "be" a node? And once I am a node, is my capacity the amount of all available channels or some designate channel?
