### ISSUE TITLE
Payment is fulfilled by payee but is still pending

### ISSUE THREAD

**Issue by btcontract** [ACINQ/eclair#628]
I have a situation: https://github.com/btcontract/lnwallet/issues/55 where a user claims that payment has been fulfilled by payee (satoshis place) but it seems like BLW client which he uses has not got a preimage back. 

His only channel is with ACINQ node, would it be possible to check that ACINQ has not got a preimage either to exclude a bug either in BLW or Eclair?

BLW/Eclair short channel id: `579426135262625792`
Payment hash: `d88d9a8b0f64deb8d9b6e31f84ac37a86ff3e8e35687b64dc145ca8bb25d0175`

**Comment by pm47** [comment]
We routed this payment to yalls, and we never received a fulfill back.

So it seems that the bug is either in yalls, in satoshis.place, or some node in between...

**Comment by btcontract** [comment]
Should be either yalls or satoshis place then, I'll try to sort this out in slack.
Thanks!
