### ISSUE TITLE
Prevent eclair from forceclosing [feature request]

### ISSUE THREAD

**Issue by mautematico** [ACINQ/eclair#629]
100% of the channels closed on my side had been forceclosed; most times by random anoying bugs like 

`peer sent unknown error` or `peer sent fee missmatch error`, etcetera.

What do you think about a configurable parameter to instruct eclair how to face cases like these?
Most of this errors seem to be temporal, and a forceclose feels _too much_ and anoying. It is even worse when, at the end, forceclosing due to temporal errors results in money loss.

**Comment by pm47** [comment]
> What do you think about a configurable parameter to instruct eclair how to face cases like these?

> Most of this errors seem to be temporal, and a forceclose feels too much and anoying.

Eclair is just enforcing the spec ([BOLT 1](https://github.com/lightningnetwork/lightning-rfc/blob/master/01-messaging.md#the-error-message)):
```
The receiving node:
  - upon receiving `error`:
    - MUST fail the channel referred to by the error message, if that channel is with the sending node.
```



Those errors are annoying, but are not necessarily bugs (e.g. `fee mismatch`) and are not necessary on eclair's side (e.g. `peer sent unknown error`). They mostly are interop issues, are being worked on, and just ignoring them won't get us anywhere.

> It is even worse when, at the end, forceclosing due to temporal errors results in money loss.

Can you be more specific? That should not be the case and we are not aware of any bugs related to this.

**Comment by sstone** [comment]
Closing because this is not an implementation issue but rather a protocol issue. We will try and make the next version less strict , and if possible move onchain fee management out of the LN protocol which should fix the `fee rate mismatch` issue.
