### ISSUE TITLE
how can I get a balance?

### ISSUE THREAD

**Issue by takaya-imai** [ACINQ/eclair#636]
I checked commands of json rpc but there is no command like "getbalance".
https://github.com/ACINQ/eclair/blob/master/eclair-core/src/main/scala/fr/acinq/eclair/api/Service.scala

How can I get a balance?

**Comment by araspitzu** [comment]
Hi takaya-imai, 

I think you can use the rpc command "channel" passing the **id** of the channel you want to inspect. From the response you can lookup the following fields:

to_local balance of channel: "result.data.commitments.localCommit.spec.toLocalMsat"
to_remote balance of channel: "result.data.commitments.localCommit.spec.toRemoteMsat"

You can iterate this process over all your channels, also don't forget to keep in account the "localChanges", if there is any change pending your "to_local/to_remote" balance might be inaccurate at  that  moment.

**Comment by sstone** [comment]
If what you need is your onchain balance, then you have to query your bitcoin node: eclair does not embed a wallet but instead uses your bitcoin wallet (through rpc calls).

**Comment by pm47** [comment]
By combining `eclair-cli` and `jq` you can do pretty much anything you want. That said we are missing a more verbose `channels` method (with the same output as the `channel` method) to make that even easier.

**Comment by takaya-imai** [comment]
@araspitzu @sstone @pm47 
thanks a lot.

I need my onchain balance. I mistook eclair has an embedded wallet.

**Comment by takaya-imai** [comment]
@pm47 I realized that I can use `eclair-cli` recently. I was using `curl` to connect json rpc for a long time.
