### ISSUE TITLE
Payments with a fresh started Eclair-Wallet sometimes takes a long time to complete

### ISSUE THREAD

**Issue by sezaru** [ACINQ/eclair#644]
Hello,

First of all, I'm  not sure if I should post this issue in this repository or in the eclair-wallet one, I choose this one since it seems the problem is in the `eclair-core` side.

Sometimes, when I try to do a payment with the Eclair Wallet right after I do a fresh open of it (to be more specific it happens more when I leave the wallet app closed for some hours) the payment will take a long time (30s ~ 1 min) to complete, after that, the next payment will be super fast as expected.

Also sometimes, instead of succeeding after the 30s ~ 1min wait, it will simply fail instead of completing it, scanning the qrcode again will always pay it correctly and super fast.

This issue seems to happen with my local nodes (I have one with LND and one with Eclair) and with public ones too, also some of my friends can reproduce it too.

I'm not so sure if the root cause is a synchronization issue or some other reason, but I was able to reproduce it in an emulator one time trying to pay a coffee from Starblocks, so I'm attaching the log bellow (I removed the android log noise from it, if you want the full log you can get it here: [logcat.log](https://github.com/ACINQ/eclair/files/2135070/logcat.log)

```
06-24 18:50:44.718  3899  4037 I SendPayment: sending 1500000 msat for invoice lntb15u1pdnq8lapp5mzmaedzg50uh69vshrtsmy07ygpw4zypjxjutjcgdus9hrjez4ksdq4xysyymr0vd4kzcmrd9hx7cqp2r3r40jsu07e824qhw04q64nmv7yav0vkhq50rx4r4auxpt8r52hq2jtlp02wms437xsvnwtw3rcl9wfnxm4j5ryzw9y27q767efshygq5qzalq
06-24 18:50:44.749  3899  3899 D Home Activity: Home.onResume done
06-24 18:50:44.768  3899  3899 I chatty  : uid=10080(fr.acinq.eclair.wallet.dev) identical 1 line
06-24 18:50:44.777  3899  3899 D Home Activity: Home.onResume done
06-24 18:50:44.893  3899  3926 D EGL_emulation: eglMakeCurrent: 0xacafa540: ver 2 0 (tinfo 0xaca8eec0)
06-24 18:50:44.954  3899  3910 I zygote  : NativeAlloc concurrent copying GC freed 251311(6MB) AllocSpace objects, 1(36KB) LOS objects, 27% free, 15MB/21MB, paused 838us total 141.357ms
06-24 18:50:44.991  3899  3926 D EGL_emulation: eglMakeCurrent: 0xacafa540: ver 2 0 (tinfo 0xaca8eec0)
06-24 18:50:45.050  3899  3926 D EGL_emulation: eglMakeCurrent: 0xacafa540: ver 2 0 (tinfo 0xaca8eec0)
06-24 18:50:45.052  3899  3926 D OpenGLRenderer: endAllActiveAnimators on 0x90d06100 (RippleDrawable) with handle 0xaca9c970
06-24 18:50:45.067  3899  3926 D EGL_emulation: eglMakeCurrent: 0xacafa540: ver 2 0 (tinfo 0xaca8eec0)
06-24 18:50:45.277  3899  3921 I f.a.e.r.Router: INFO   - finding a route 025427d1e9b406e889d499f43c7a7be57e03c003b1b1b2f78f8f1e25a7bd59ce07->035b55e3e08538afeef6ff9804e3830293eec1c4a6a9570f1e96a478dad1c86fed with assistedChannels= ignoreNodes= ignoreChannels= excludedChannels=
06-24 18:50:45.285  3899  3986 I f.a.e.p.PaymentLifecycle: INFO   - route found: attempt=1/10 route=03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134->035b55e3e08538afeef6ff9804e3830293eec1c4a6a9570f1e96a478dad1c86fed channels=143a3300005b0000->13a8030000fe0000
06-24 18:50:45.391  3899  3921 I DBHelper: update payment to pending with status=INIT
06-24 18:51:15.645  3899  3990 I a.a.DeadLetterActorRef: INFO   - Message [fr.acinq.eclair.payment.PaymentLifecycle$PaymentSucceeded] from Actor[akka://system/user/$j/payment-initiator/$a#2128235348] to Actor[akka://system/deadLetters] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings ‘akka.log-dead-letters’ and ‘akka.log-dead-letters-during-shutdown’.
```

As can be seem from the log, I started at `18:50:44.718` the payment, at `18:50:45.391` the payment was added to the DB and at `18:51:15.645` I received the DeadLetter message about the PaymentSuccess, pretty much exactly 30 seconds after the initial request, which seems to be the timeout of the actor.

Right after the DeadLetter, the wallet showed the payment succeeded activity, so I'm not sure if this DeadLetter was consumed correctly or the actor retried the reply.

I hope this is enough information to help the debug, but I can try to gather more logs of it happening if you want

**Comment by sstone** [comment]
Thanks! It's a borderline core/wallet issue but it is still better to open it on eclair-wallet, it would be easier to find for other users and our mobile app uses a modified version of our core router. If we need to change the core libraries we would open a new issue and link to it.
When a node that has been offline reconnects to its peers, it first needs to synchronize its routing table, and it may slow down our router which may not be able to produce a response in time, especially if it is missing a lot of data (here it was missing 1000 channels). We are also working on this, and also on improving our embedded wallet startup time and providing better user feedback.

**Comment by pm47** [comment]
This has been fixed (or at least should be largely improved) with Eclair Wallet 0.3.10, released today.
