### ISSUE TITLE
No additional block added when taking final expiry from payment request

### ISSUE THREAD

**Issue by btcontract** [ACINQ/eclair#651]
`c.finalCltvExpiry.toInt` in https://github.com/ACINQ/eclair/blob/master/eclair-core/src/main/scala/fr/acinq/eclair/payment/PaymentLifecycle.scala#L54 eventually comes from either a hardcoded `7 + 1` value or from the one taken from a payment request. 

In the latter case there is no `+ 1` part, does this mean a latter case is vulnerable to `Channel.MIN_CLTV_EXPIRY + 1 to not have our htlc fail when a new block has just been found`?

**Comment by pm47** [comment]
I think it might be...
