### ISSUE TITLE
Rate limit annoncement signatures

### ISSUE THREAD

**Issue by ysangkok** [ACINQ/eclair#662]
Testing Electrum with Eclair I got into a situation where Eclair would resend announcement signatures in an endless loop.

Full logs: https://sr.ht/7b2w.log (3.3 MB)

**Comment by ysangkok** [comment]
Mostly likely Eclair just answers announcement signatures always, and Electrum does the same...

**Comment by pm47** [comment]
Eclair doesn't answer to an `announcement_signature` the first time it receives it, but after that it always responds with an `announcement_signature`. This is obviously not perfect (hence the `TODO` below), but what causes the loop here is that Electrum *always* answers with an `announcement_signature`:

https://github.com/ACINQ/eclair/blob/fe82641e92e073a47f4bb59dae0c13b2d9f4dfe4/eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala#L785-L814

**Comment by pm47** [comment]
We should probably use the logic added with #705 to handle this.

**Comment by ysangkok** [comment]
Closing this since I havn't used Eclair recently so I don't know whether it is still a bug.
