### ISSUE TITLE
Excessive calls to getrawtransaction

### ISSUE THREAD

**Issue by n1bor** [ACINQ/eclair#664]
Since about 12th July my Eclair instance has started making calls to this constantly. Current queue in 10k!

I thought it was slow disks could not keep up so moved onto SSD but still too many requests.

Anyone else seeing this? If not will turn on router logging and see why so many! As my current logging does not explain why there are so many

`
07:02:54.162 DEBUG akka://default/user/batching-client f.a.e.b.bitcoind.rpc.BatchingClient - sending 50 request(s): getrawtransaction=50 (queue=5977)
07:02:54.474 DEBUG akka://default/user/batching-client f.a.e.b.bitcoind.rpc.BatchingClient - sending 50 request(s): getrawtransaction=50 (queue=5927)
07:02:54.974 DEBUG akka://default/user/batching-client f.a.e.b.bitcoind.rpc.BatchingClient - sending 50 request(s): getrawtransaction=50 (queue=5877)
07:02:55.614 DEBUG akka://default/user/batching-client f.a.e.b.bitcoind.rpc.BatchingClient - sending 50 request(s): getblock=1 getrawtransaction=49 (queue=5827)
07:02:57.265 DEBUG akka://default/user/batching-client f.a.e.b.bitcoind.rpc.BatchingClient - sending 50 request(s): getrawtransaction=50 (queue=5777)
07:02:57.658 DEBUG akka://default/user/batching-client f.a.e.b.bitcoind.rpc.BatchingClient - sending 50 request(s): getrawtransaction=50 (queue=7490)
07:02:57.978 DEBUG akka://default/user/batching-client f.a.e.b.bitcoind.rpc.BatchingClient - sending 50 request(s): getrawtransaction=50 (queue=7440)
07:02:58.275 DEBUG akka://default/user/batching-client f.a.e.b.bitcoind.rpc.BatchingClient - sending 50 request(s): getrawtransaction=50 (queue=7390)
07:02:58.842 DEBUG akka://default/user/batching-client f.a.e.b.bitcoind.rpc.BatchingClient - sending 50 request(s): getrawtransaction=50 (queue=7340)
07:02:59.262 DEBUG akka://default/user/batching-client f.a.e.b.bitcoind.rpc.BatchingClient - sending 50 request(s): getrawtransaction=50 (queue=7290)
07:02:59.714 DEBUG akka://default/user/batching-client f.a.e.b.bitcoind.rpc.BatchingClient - sending 50 request(s): getrawtransaction=50 (queue=7240)
07:03:00.144 DEBUG akka://default/user/batching-client f.a.e.b.bitcoind.rpc.BatchingClient - sending 50 request(s): getrawtransaction=50 (queue=7190)
`

**Comment by n1bor** [comment]
After a lot of confusion think I have tracked issue down.
Looks like on the 12th Mempool was quite large. So then if the WatchSpent gets triggered and calls:
`client.getMempool().map{`
That will create 10,000+ calls to getrawtransaction. Which could be an issue.

But what is really confusing me now is that is it is still doing it but not seeing a lot of calls to getmempool

**Comment by n1bor** [comment]
Arh no it is lookForSpendingTx

This was triggered a few times - wonder if I have some bug....

And now it is recursively searching the whole blockchain tx by tx!

`
21:40:47.254 WARN  akka://default/user/$b/watcher f.a.e.blockchain.bitcoind.ZmqWatcher - 258170f889da708e90b69133a5fda557449f7f2a61e91c90213bfb8b9804f34a:0 has already been spent, spending tx not in the mempool, looking in the blockchain...
21:40:50.288 WARN  akka://default/user/$b/watcher f.a.e.blockchain.bitcoind.ZmqWatcher - db279fcfdd786285e218264397cbfa01588ebf4b7ce4da3bc084dbf8a1caef36:1 has already been spent, spending tx not in the mempool, looking in the blockchain...
21:40:50.622 WARN  akka://default/user/$b/watcher f.a.e.blockchain.bitcoind.ZmqWatcher - 7d1dc2e1bcc01aab0630ac3839a3290b468b3c4b2234960ebbae5ad6a4d1f5d5:1 has already been spent, spending tx not in the mempool, looking in the blockchain...
21:40:52.267 WARN  akka://default/user/$b/watcher f.a.e.blockchain.bitcoind.ZmqWatcher - 4e6cb086b6c1eda9571e2b72accec118a14ee0363044fe1ddf6899a85d5a6c62:0 has already been spent, spending tx not in the mempool, looking in the blockchain...
21:40:54.005 WARN  akka://default/user/$b/watcher f.a.e.blockchain.bitcoind.ZmqWatcher - cf17aec64164a54600ba452051a746a5c3589e3b5cc75e9bcb5b259156ef30ef:1 has already been spent, spending tx not in the mempool, looking in the blockchain...
21:40:55.956 WARN  akka://default/user/$b/watcher f.a.e.blockchain.bitcoind.ZmqWatcher - 1831b07bd07aa0e293bad5608be5389f619fa7a7fcbf8dc4d40f50420655c737:0 has already been spent, spending tx not in the mempool, looking in the blockchain...
21:40:58.472 WARN  akka://default/user/$b/watcher f.a.e.blockchain.bitcoind.ZmqWatcher - bfa2ec3e43f1ed5ed9fb858e4e49638771848c47e1f7661f10f4422375b5dadd:0 has already been spent, spending tx not in the mempool, looking in the blockchain...
21:41:15.769 WARN  akka://default/user/$b/watcher f.a.e.blockchain.bitcoind.ZmqWatcher - 306339f919b32ff6eeaecbf25dbe5481ce060a92e41a05b09e7e77f43e47e502:0 has already been spent, spending tx not in the mempool, looking in the blockchain...
21:41:43.206 WARN  akka://default/user/$b/watcher f.a.e.blockchain.bitcoind.ZmqWatcher - cd77a6a70d199b496ffce9db48d9005167f9a206531f6bc35562d55c4170828c:1 has already been spent, spending tx not in the mempool, looking in the blockchain...
21:41:52.632 WARN  akka://default/user/$b/watcher f.a.e.blockchain.bitcoind.ZmqWatcher - f5b033870d2fe3250fd93b7c4ebefa618558af944507b6e907c82fde0b03ac68:0 has already been spent, spending tx not in the mempool, looking in the blockchain...
21:41:55.511 WARN  akka://default/user/$b/watcher f.a.e.blockchain.bitcoind.ZmqWatcher - 5d572cff91f994ad828312705b76849671428f23f2385a2c071449c604eca9be:0 has already been spent, spending tx not in the mempool, looking in the blockchain...
21:42:07.101 WARN  akka://default/user/$b/watcher f.a.e.blockchain.bitcoind.ZmqWatcher - 239e490e71958131cce4c0d5b7f6cfe928e3da7a78f26844ff1fa0e6ae52f035:0 has already been spent, spending tx not in the mempool, looking in the blockchain...
`

**Comment by n1bor** [comment]
So I think what happened was that mempool got big.
I had slow disks (are cold storage on Amazon AWS). It must have got behind.
I did nothing for a few days. Then restarted - which was a bad thing as now restarted the search...

Then tried various things to find issue. Then restarted again yesterday and upgraded disks to SSD's.

I can now see it is asking for trades from 17th July 532216 - so it is getting there. But concerned it is going to have to do this 12 times! (10 day x 12 searches x 200k tx/day = 24m calls) And getting 11m a day. So hopefully will fix itself by tomorrow...

**Comment by n1bor** [comment]
Fix I think would be to re-write lookForSpendingTx so that instead of calling getrawtransaction iteratively on each Tx just to call getblock with verbosity of 2. This returns all the tx details in 1 rpc call and as importantly 1 index seach and one disk seek. Should be 100+ times faster.

Other agree? If so will submit patch.

**Comment by sstone** [comment]
I think you're right, nice! but `getblock` with a verbosity of 0 should be even lighter on bitcoind (it would return the raw block which we can parse with `Block.read()`) ?
