### ISSUE TITLE
Transaction Log dissappears after close.....

### ISSUE THREAD

**Issue by d4amenace** [ACINQ/eclair#675]
Looking ahead, businesses will need to see these transaction logs for receipting purposes.  Perhaps their could be some option to have text files of transactions saved.

**Comment by sstone** [comment]
What do you mean ? Eclair logs (located in the eclair data directory, which defaults to ~/.eclair) for a specific channels are not removed when that channel is closed.

**Comment by d4amenace** [comment]
Isn't that log of every single operation and executable that the program operates? It will be very difficult (if it is) to use it for accounting purposes or some sort of "programmed call" to a script so that receipts can be automatically created with connecting transaction confirmation proof.

**Comment by viaj3ro** [comment]
Yeah, I'm missing the same feature! I'd like to be able to see a history of all my payments (sent, received, relayed) from the very beginning. (maybe with an option to clear the history but have it saved in a specific activity log.

**Comment by sstone** [comment]
We now have a simple audit database (see https://github.com/ACINQ/eclair/pull/654) which will be in the next release. It's already been merged on master so you can use it if you build eclair.

**Comment by sstone** [comment]
The audit database and API is now part of the released version of eclair. The `audit` API call will return a list of all sent, relayed and received payments.
