### ISSUE TITLE
Channel stuck in CLOSING

### ISSUE THREAD

**Issue by gaminn** [ACINQ/eclair#676]
My channel:
e81a35ecf1aa7d0f0f9537da711b3d767fd4499a2f9dba0312960c6142e79735
funding tx id: 3597e742610c961203ba9d2f9a49d47f763d1b71da37950f0f7daaf1ec351ae8
remote node id: 0217890e3aad8d35bc054f43acc00084b25229ecff0ab68debd82883ad65ee8266 (1ML.com node ALPHA)

was opened and funded but then closed (I don't know why but it wasn't me who initiated the closing) and now it is stuck in closing state for 10 hours without balance being released back to my wallet.

Using Eclair v0.2-beta5 and Bitcoin Core v0.16.1 on Windows 10.

Can you please help?

**Comment by sstone** [comment]
When a channel is closed you need to wait (typically 144 blocks) before you get your money back, you still need to wait a few hours. The logs will tell you why the channel was closed.

**Comment by gaminn** [comment]
OK, that's all, thanks, Sorry for spaming here with this sort of problem.

**Comment by gaminn** [comment]
I noticed one more thing - the closing transaction has amount of 247217 sat.  But my balance in that channel is 249744 sat. What happened with that appro 2500 sat?

**Comment by sstone** [comment]
No problem, It's not always easy to tell if it's a support issue or a bug so (or even both). The closing transaction needs to pay onchain fees, that's were the missing satoshis went (with a fee rate of about 5 sat/byte which is not bad).

**Comment by gaminn** [comment]
This is the closing transaction: https://www.blockchain.com/btc/tx/b3a6174d59b92a3cca99e2756211198613673690d2e8a393b771436e9301775b

As you can see input of this transaction was 247981 sat, fee 764 and I received 247217 sat. But my balance when the channel closed was 249744. So still some satoshis missing. Where are they?

**Comment by sstone** [comment]
It is because your channel balance includes money that will be used to pay onchain fees: we displayed a balance of 249744 satoshis, but when the channel was closed some of it was used to pay onchain fee for the closing transaction.
