### ISSUE TITLE
You cannot change the port 

### ISSUE THREAD

**Issue by d4amenace** [ACINQ/eclair#678]
Hello, I was trying to run eclair for windows on 2 computers connected through the same modem.  I quickly realized that I could only open port 9735 to a single computer and not both on my modem.  I figured I would change the eclair port in the conf file and that should do the trick.  No go.  I changed it in the file but when it started up it still said 9735 every time. (Must be hard-coded).  So now I cannot have more than one eclair running in my home......not cool.

**Comment by sstone** [comment]
You run run multiple instance of eclair on windows, with different parameters (see https://github.com/ACINQ/eclair#java-environment-variables): use different data directories, each with its own `eclair.conf` file:
```
java -Declair.datadir=MY_DATA_DIR -jar eclair-node-gui-0.2-beta5-8aa51f4.jar
```

**Comment by d4amenace** [comment]
That may be true when running multiple instances on the same computer, but I can't forward ports to more than one computer.

And too, even when I have placed:

Eclair.port=9736

It still shows port 9735 on the terminal and apparently reads through it still.

**Comment by sstone** [comment]
The configuration key for the LN port is `eclair.server.port`. If you want several LN nodes you have to configure and open a different port for each one of them.

**Comment by d4amenace** [comment]
That worked. Simple mistake on my part. Thanks.

**Comment by sstone** [comment]
No problem.
