### ISSUE TITLE
[GUI] fatal error: javafx/application/Application

### ISSUE THREAD

**Issue by Frederic94500** [ACINQ/eclair#681]
Hello!

When I run the lastest release of eclair in my raspberry pi, I got a fatal error... And no GUI and force quit eclair.

`ERROR fr.acinq.eclair.JavafxBoot$   - fatal error: javafx/application/Application`

**Comment by sstone** [comment]
Hi! We use github for stricly technical issues, please ask support questions on https://gitter.im/ACINQ/eclair instead.  This is probably a JDK mismatch. Thanks!

**Comment by pvyhnal-generalbytes** [comment]
On ubuntu / mint linux I had to `$ sudo apt-get install openjfx`
