### ISSUE TITLE
Channel opening fee rate adjustment have no effect

### ISSUE THREAD

**Issue by viaj3ro** [ACINQ/eclair#688]
using the latest beta (v0.2-beta5) and the default fee rate for opening a channel seems to be 12 sat/b

when I change that setting to pay more (like 25 s/b) the generated transaction pays the exact same fee as with 12 s/b

it seems like the fee rate can't be changed.

**Comment by sstone** [comment]
Yes, It was fixed with #658 which will be in the next release.

**Comment by viaj3ro** [comment]
cool! how about the closing channel fee rate? will it be possible to adjust in that release as well?
