### ISSUE TITLE
GUI is confusing. Easy to accidentally close/force close the wrong channel

### ISSUE THREAD

**Issue by viaj3ro** [ACINQ/eclair#690]
I accidentally closed the wrong channel more than once due to the blue lines making it look as if the close/force close button belongs to the channel above and not below.

It would help if the different channels are separated in a way such that there is no ambiguity about which channel belongs to which button.

**Comment by STAWKEYE** [comment]
I agree completely here - but I do still like the visual of the "fill bars". As a suggestion what about keeping the bars but alternate shadings of the background similar to those alternating dark/light shades of green, blue, or grey on ledger style spreadsheets? (Like what you get with "format as table" in Excel for example)

**Comment by YaroslavYrm** [comment]
IMO, easiest improvement is to move blue bar to the top of channel cell. In this way it will look like separator.

**Comment by viaj3ro** [comment]
Just closed the wrong channel AGAIN :x 

This time it is really annoying since the accidentally closed channel was a very old, well funded, well used and well balanced one. Exactly the kind you REALLY want to keep open :(

Please fix this GUI issue. IMHO dropping the balance bar to the bottom would be the best but moving it to the top like @YaroslavYrm is suggesting would work as well.

anything but the status quo, basically...

**Comment by dpad85** [comment]
Commit https://github.com/ACINQ/eclair/commit/2be2d38b952b4799428167ecf3a4cce60deb7169 adds a confirmation window when clicking on the `close` button. The confirmation dialog now contains some details about the channel as proposed by @viaj3ro.

The channel UI was also reworked, the channel's balance bar should not be confusing anymore: [preview](https://i.imgur.com/GkM6O3L.png).

**Comment by viaj3ro** [comment]
looks good to me. Is the remote node ID and funder (yes/no) missing though? If yes, I'd suggest to re-add it. Otherwise it would be really difficult to not get lost once you open more than 2 or 3 channels.

**Comment by dpad85** [comment]
The peer node id is displayed in bold characters at the top of the channel panel, I've switched its position with the channel id, it makes more sense that way. Good point with the funder boolean, I've put it back.
