### ISSUE TITLE
Custom fee confusing

### ISSUE THREAD

**Issue by molxyz** [ACINQ/eclair#692]
On Eclair mobile (Testnet) I found out how on-chain transaction fees can be changed by pressing on the fee number (which in this case it's number 3 for sat/byte).  However, this is a bit confusing as I had to play around with it to figure it out.  Could you create a button for `CUSTOM` so it can be more visible? 

Also, my phone shows the `PAY` and `CANCEL`  buttons are not positioned correctly.  A screenshot is attached to this issue.

This is Eclair mobile version 0.3.7 Testnet.

https://i.imgur.com/CQa0J4Y.png

EDIT:  I found that these buttons show up okay on Android version 7.1.1, this issue is on Android version 7.0.

**Comment by dpad85** [comment]
Hi, could you recreate this issue on the dedicated eclair-wallet repository?

https://github.com/ACINQ/eclair-wallet/issues

Thanks!

**Comment by molxyz** [comment]
@dpad85  Done.  Sorry about that.
