### ISSUE TITLE
in-flight htlcs hold too much value

### ISSUE THREAD

**Issue by fmgolde** [ACINQ/eclair#725]
Hi,

I'm using _eclair-node-gui-0.2-beta6-3fc5da0.jar_ on REGTEST, and I'm not able to send a 20 mBTC payment. This is the error I'm getting:

_2 attempts:_
_- (local) in-flight htlcs hold too much value: maximum=1000000000 actual=2000201000_
_- (local) in-flight htlcs hold too much value: maximum=1000000000 actual=2000201000_

I set this property on the _eclair.conf_ file to fix it, but it's not working out:

_eclair.max-htlc-value-in-flight-msat=10000000000_

I don't see anything weird at eclair.log

Any ideas? Thank you.

**Comment by sstone** [comment]
If I set `max-htlc-value-in-flight-msat` to 10000000000 then I can send a 20 mBTC payment. 
In the error message you have the max amount is set to 1000000000 msat = 1000000 sat = 10 mBTC.
Did you set `max-htlc-value-in-flight-msat` on the sending node or the receiving node ?

**Comment by fmgolde** [comment]
I set _max-htlc-value-in-flight-msat_ on the 3 nodes that I have. Anyway, today I've closed all the channels and opened new ones, and this is working fine now, so I'm no longer able to reproduce the issue. Thanks for the help.
