### ISSUE TITLE
Routing issue: Repeatedly tries failed nodes

### ISSUE THREAD

**Issue by STAWKEYE** [ACINQ/eclair#729]
When trying to make a BTC LN payment to a specific merchant, the routing always goes through rompert.com (and fails there). I had a sufficient payment channel with rompert, as did the merchant. They later added a well funded ACINQ node, which is likely also well connected to rompert. I finally created a direct payment channel to merchant on my Eclair beta 6 node.
Each of these scenarios resulted in the payment routing from my mobile eclair wallet to my main (eclair beta 6) LN node, at which point it always tries my rompert channel repeatedly until failure. It still tried rompert exclusively even after I created my direct channel.
After many experiments the only payment that was successful was one sent using the main LN node directly from eclair beta 6 (not the eclair mobile wallet). In this case it used my direct channel to merchant. While that may make it seem like it's a mobile wallet issue, I saw the previous payments pass into my main node and so I suspect it is more of a routing issue. The final payment that worked bypassed routing entirely. Below please find the log of one of the failed routing attempts.
[LOG](https://pastebin.com/raw/ctgAcBXy)

**Comment by pm47** [comment]
> It still tried rompert exclusively even after I created my direct channel.

When you create a channel, it is typically usable as soon as the funding tx has 3 blocks confirmation to *send* payments, but will only be announced on the network after 6 blocks (and thus be usable to *relay* payments). So between 3 and 6 blocks, you would have been able to send payments from your desktop node, but not from your mobile through your desktop node, because Eclair Wallet wouldn't have heard of the channel yet. Do you think this is what could have happened?

**Comment by STAWKEYE** [comment]
While the large channel between my node and rompert was more than a day old, there is a chance the dedicated channel I opened with the merchant was in-between 3 and 6 confirmations; I'm not sure. As luck would have it, the merchant closed the channel for whatever reason this morning and so I can't re-create the test.
I just completed a successful $0.05 test payment with them using Éclair mobile wallet, without the dedicated channel. Payment hash is 159c9467b1e4d80a8386d886c566ce1281f583ca690e4e0c97dccd81d3bc28e0
Given that a $0.05 payment routed through perfectly when a $25 payment couldn’t, I no longer think this is a bug and it’s probably caused by either your theory of “3<n<6 confirmations” or a merchant who’s payment channels are not as well funded as they claimed. You can probably close this one out and chalk it up to user error or network capacity depending on the above.
Thanks for all the help thus far.

**Comment by STAWKEYE** [comment]
Update: From the merchant (WearsMyLiberty) who uses a c-lightning node, "there was some issue between c-lightning and Eclair that caused channels we had with Eclair nodes to close, including ACINQ and your node." While that's obviously not descriptive enough for troubleshooting, I thought I'd pass it on that c-lightning and Eclair may not play nice together at all times.

**Comment by sstone** [comment]
It could be a fee rate issue: nodes will reject fees that they think are too high/too low and close the channel, and it will happen more often with c-lightning than with lnd or eclair (not saying that it was the problem but it is one of the most common cause of channels getting closed)

**Comment by pm47** [comment]
Closing this as the main issue was solved.

The update doesn't have enough details to figure out what happened, but @sstone gave the most probable explanation. Fees disagreements have been largely improved during the past months, and this is still a hot topic at the spec level. Next iteration of the spec may remove the issue altogether.
