### ISSUE TITLE
Not working with latest version of Bitcoin Core

### ISSUE THREAD

**Issue by InternetofTrust** [ACINQ/eclair#730]
I've updated to the latest version of Bitcoin core v0.17.0 (64-bit) but I still get the following error: 
Error: assertion failed: Eclair requires Bitcoin Core 0.16.0 or higher.

**Comment by pm47** [comment]
See #682

**Comment by sstone** [comment]
Bitcoin v0.17.0 included a breaking API change ( `signarawtransaction`) and a few changes in behaviour. A simple change to the way we check that the bitcoin node we connect to meets our requirements (currently 0.16.3 or above) will be added very soon and will allow users to run 0.16.3 or 0.17.0 (with an extra compatibility option for now).

**Comment by sstone** [comment]
The first step is to change our version check and document how to run Bitcoin Core 0.17.0 and re-enable the deprecated RPC call. This will be completed very soon and we'll release a version of eclair that people can run with 0.17.0

But we will also need to change how we use Bitcoin Core's RPC API, and make sure that eclair works with both 0.16.3 and 0.17.0 , and run our integration tests against 0.17.0. This will be done in another PR that reuses #682

**Comment by sstone** [comment]
We've just released [Eclair v0.2-beta7](https://github.com/ACINQ/eclair/releases/tag/v0.2-beta7) which will work with Bitcoin Core v0.17.0 if you enable the deprecated `signrawtransaction` RPC call (check our [README](https://github.com/ACINQ/eclair#configuring-bitcoin-core)).

**Comment by InternetofTrust** [comment]
Working again! Thanks for the fast response and work!
