### ISSUE TITLE
Allow configuring different ZMQ block and tx URLS

### ISSUE THREAD

**Issue by ysangkok** [ACINQ/eclair#733]
Since LND since 0.5 does not allow using the same port for tx and blocks, and I am updating cdeckers lightning-integration to support it, I noticed that I can't configure Eclair to use different ports. This means bitcoind has to be configured differently for lnd and eclair, which is unfortunate.

It seems to me the easiest solution would be to offer in Eclair the possibility of having different URLs for these two services.

Thank you for your time.

**Comment by sstone** [comment]
On one hand it feels a bit strange to do something because of a change in lnd, but on the other hand bitcoind uses different zmq options for blocks and txs, and it would not be a breaking change, so it's a reasonable request.
