### ISSUE TITLE
Stuck at "WAIT_FOR_FUNDING_CONFIRMED" status

### ISSUE THREAD

**Issue by Flekoun** [ACINQ/eclair#734]
Just want to let you know that I have issue being suck at : "WAIT_FOR_FUNDING_CONFIRMED" when trying to open any channel.

-I have fully synced 0.17.0 Bitcoin qt node
-configured according to the instructions to cooperate with Eclair
-I have installed Eclair v0.2-beta7
-configured according to the instruction to cooperate with Bitcoin qt

When I create a new channel ( tried already 3 of them, funded them with 0.001 BTC) outgoing  transaction correctly shows in Bitcoin qt and channel with "WAIT_FOR_FUNDING_CONFIRMED" status is shown in Eclair. However even after 20 confirmations the "WAIT_FOR_FUNDING_CONFIRMED" stays. I can see that the transaction to fund the channel is correctly recorded on Bitcoin Blockchain but Eclair for some reason does not know about it?

Thanks

EDIT: I am trying this on Mainnet

**Comment by sstone** [comment]
Can you please share your `eclair.log` (using pastebin) ?

**Comment by Flekoun** [comment]
It is too large but here are few lines, they are mostly the same anyway:
https://pastebin.com/JpHYa6JG

**Comment by sstone** [comment]
`Blockchain transactions are still in the process of being indexed`

Are you sure that you bitcoin node is fully synced ?

**Comment by Flekoun** [comment]
Yes, you are right, Bitcoin Core was still indexing, mistake was on my side. Now it is working and I can open channels. Sorry for this false issue. Thanks for your support guys! Keep your great work going!

**Comment by sstone** [comment]
Thanks for the feedback! We're already checking that `bitcoind` is "ready" when we start eclair but this test is not thorough enough and could be improved, I will open a issue for that.

**Comment by DerHuette** [comment]
I made the same mistake, opening a channel while bitcoin core is still indexing. Since I do that on a z83 mini pc, indexing may take days or weeks. After a few hours I hit 'force close'. Now eclair is stuck at 'Closing'.
Will those bitcoins ever come back? Do I have to wait with the eclair program open?
Thanx in advance!

**Comment by napbtc** [comment]
I'm also being stuck at  "WAIT_FOR_FUNDING_CONFIRMED" while trying to open my two first channels. I'm new to LN. Any info on what I should do? Thanks in advance for any help offered.

**Comment by sstone** [comment]
@napbtc if possible please avoid adding comments to closed issues and open new ones instead. When you do, provide the requested information (at least which version of which software, logs if applicable), and before you do check existing issues and resolutions. 
In this case, was your bitcoin node ready or was is still reindexing ? If you're not sure you can ask at https://gitter.im/ACINQ/eclair but logs should be explicit
