### ISSUE TITLE
channel stuck closing

### ISSUE THREAD

**Issue by nybe** [ACINQ/eclair#741]
Chanel is stuck in CLOSING mode for a few days now... was waiting for .005 BTC to be returned.

info: https://1ml.com/channel/600404817146216448

I am way too much of a noob to know what to do and was hoping y'all could help... thanks

**Comment by nybe** [comment]
this issue has been resolved... thanks!

**Comment by sstone** [comment]
When your node unilaterally closes a channel and publishes its current commitment transaction, there is a delay (usually 144 blocks i.e. one day) before this transaction can be spent an returned to your wallet. Until then it will show as CLOSING.
