### ISSUE TITLE
Constantly getting this: Payment failed - (remote) payment expiry doesn't match the value in the onion

### ISSUE THREAD

**Issue by viaj3ro** [ACINQ/eclair#758]
I usually have a direct channel to the receiver but still have to be lucky to get my payment through. It usually fails with the above error. 

Log: https://pastebin.com/LKbjyvGz

Latest eclair (beta 8) latest core (0.17.0)

**Comment by pm47** [comment]
This looks fine to me, I don't see why yalls rejects those payments.

@alexbosworth any chance you can tell us why e.g. `payment_hash`=`18fcfe7151cba3e970ef46455d087a13e5b769e4a58f07dcac992053520e9af3` got rejected with a `final_incorrect_cltv_expiry`. This error should be sent when the `cltv_expiry` of the last htlc doesn't match the `outgoing_cltv_value` in the onion, which is always the case in our code AFAICT.

**Comment by alexbosworth** [comment]
It looks like that invoice was settled successfully on my end at `2018-11-16T12:48:44.000Z`

Was it a temporary error? There are issues when the chain heights of both clients are out of sync

**Comment by pm47** [comment]
> It looks like that invoice was settled successfully on my end at 2018-11-16T12:48:44.000Z
> Was it a temporary error? 

Yes, user says he keeps retrying the payment until it succeeds. I was hoping some more details on why your node wasn't happy during the previous tries.

> There are issues when the chain heights of both clients are out of sync

Sure, but this particular error shouldn't be related to chain sync issues: it should only be sent if the onion is malformed (see [BOLT4](https://github.com/lightningnetwork/lightning-rfc/blob/master/04-onion-routing.md#failure-messages)), which I believe wasn't the case.

**Comment by viaj3ro** [comment]
I wasn't able to successfully pay the invoice. I tried 2-3 times and gave up.

I get that same error a lot. Not just with Y'alls but also with bitrefill and also with lightningslotmachine and satoshis place, I believe.

**Comment by viaj3ro** [comment]
another try, another failure with the same error message as always:

> (remote) payment expiry doesn't match the value in the onion

https://pastebin.com/TxD9nSn2

why am I always getting these?

**Comment by pm47** [comment]
Is your Bitcoin Core always on, or do you turn it on right before making a LN payment? Is it fully in sync when you attempt to use eclair?

**Comment by viaj3ro** [comment]
jip, always on and always fully synced.

**Comment by viaj3ro** [comment]
OK, I found a workaround: I have to restart eclair to be able to send payments. once it runs for a while sometimes I get the error, sometimes not.

**Comment by pm47** [comment]
So it turns out that LND returns `FinalIncorrectCltvExpiry` but they mean `FinalExpiryTooSoon` (see https://github.com/lightningnetwork/lnd/issues/2227). Let's wait for them to fix that and get back to this then.

**Comment by viaj3ro** [comment]
seems like it got fixed: https://github.com/lightningnetwork/lnd/pull/2335

so problem solved as soon as it is deployed or do you need to do a fix in eclair as well?

**Comment by t-bast** [comment]
@viaj3ro I believe you're not experiencing this issue anymore so I'm closing it.
Feel free to re-open if needed.
