### ISSUE TITLE
ACINQ does not send channel updates originating from node 038df0bd2fad1bfe42d177f18ea5e33543e2b855ef369d06bd94b81d2c87187c82

### ISSUE THREAD

**Issue by btcontract** [ACINQ/eclair#759]
When sending out routing info ACINQ node does not send channel updates which originate from https://1ml.com/node/038df0bd2fad1bfe42d177f18ea5e33543e2b855ef369d06bd94b81d2c87187c82, only channel updates from it's peers so that node can't currently be used for routing of outgoing HTLCs.

Seems like ACINQ considers `ChannelUpdate`s from `ghostofsatoshi` to be invalid, perhaps related to https://github.com/ACINQ/eclair/issues/751? `ghostofsatoshi` is a c-lightning node which runs at https://ask.for-bitcoin.com/

**Comment by pm47** [comment]
This is probably related to #751. In order not to cause too many channels
closing and give people time to update, we have temporarily stopped
relaying channel_updates that have the new field defined. I'll revert that
tomorrow and everything should be back to normal.

**Comment by pm47** [comment]
Should be fixed now, please reopen if not
