### ISSUE TITLE
Eclair allows payments of the same invoice multiple times

### ISSUE THREAD

**Issue by drmoore718** [ACINQ/eclair#777]
I run an LND node and had a user who is running Eclair v0.2-beta8 Win 10 tell me he paid an invoice twice, but was not credited with the amount for the second payment.  Aside from the issues with LND and my server that caused the balance problem, I think that the Eclair client and LN clients in general should prevent users from paying an invoice multiple times.  LND, for example, currently does prevent users from paying the same invoice multiple times.  Interested to hear your thoughts.

**Comment by pm47** [comment]
The bug is really on the receiver's side: e.g. there is no way to prevent a user from paying the same invoice from two different wallets. Only the receiver can do that.

We could add a safeguard feature on the sender's side, but that wouldn't solve the core issue.

**Comment by juscamarena** [comment]
I don't think any of our cases have been paying from different wallets but from one eclair wallet, but yes I agree receiver shouldn't accept multiple payments after already being settled.

**Comment by juscamarena** [comment]
I don't think any of our cases have been paying from different wallets but from one eclair wallet, but yes I agree receiver shouldn't accept multiple payments after already being settled.

Although, not accepting it from another wallet a privacy leak showing invoice was paid?

Guess if the invoice is public who cares at that point.

**Comment by t-bast** [comment]
As summarized, this is a receiver bug. I believe that all implementations should have fixed that bug by now so I'm closing this issue.
If this problem comes back, feel free to re-open.
