### ISSUE TITLE
Error: Payment amount is not valid

### ISSUE THREAD

**Issue by Kixunil** [ACINQ/eclair#785]
On chain payment is impossible due to "invalid" amount, while I see no reason for invalidity of the amount (wallet has larger balance and there are exactly 8 decimal places).

Expected behaviour: The on chain payment is sent after clicking "Pay"

What actually happened: When clicking Pay, the wallet refuses to send the transaction with error message "Payment amount is not valid."

I tried these steps three times and I hit the bug every time:

1. Make sure you have enough coins in the wallet (0.9 in my case)
2. Make a QR code in the form bitcoin:2addr?amount=0.00036185
3. Scan the QR code with testnet wallet (not tested on mainnet)
4. Click Pay

Testnet version 0.3.13 from Google Play

Android 5.0.2
HTC SDK 6.55

**Comment by dpad85** [comment]
Thanks for reporting this issue. I'm moving it to the correct repository (this is the eclair for server repository). 

See https://github.com/ACINQ/eclair-wallet/issues/137
