### ISSUE TITLE
Open channel ordering

### ISSUE THREAD

**Issue by STAWKEYE** [ACINQ/eclair#787]
I'm not sure what ordering criteria is used to display the open payment channels (it appears random and changes upon restarts) but having some sort options would be nice as a low priority GUI improvement.

Nice examples that would be helpful:
Descending order of capacity
Descending order of Your Balance
Grouping identical remote node ID's together (if 2 nodes open channels to each other)

**Comment by dpad85** [comment]
There is no ordering in the local channels list in the UI. Your examples are great, we could add logical grouping by channel ID, and ordering by capacity.

**Comment by viaj3ro** [comment]
would it be possible to show channel activity as well? like number of relayed transactions and then be possible to sort by that as well?

Channel age would be very useful as well.

**Comment by STAWKEYE** [comment]
To add to that - really just a way of seeing which of your channels aren't pulling their weight. With many channels, there could be a few that are almost never online or useful, and you wouldn't really know.

**Comment by t-bast** [comment]
Closing this issue as the demo UI has been deprecated in [v0.4](https://github.com/ACINQ/eclair/releases/tag/v0.4).
PRs to improve the demo UI are still accepted, but we won't track any feature requests.
