### ISSUE TITLE
Should this line read 8332 ?

### ISSUE THREAD

**Issue by STAWKEYE** [ACINQ/eclair#789]
https://github.com/ACINQ/eclair/blob/255c280bd0315af4f718240e802687f6a1967b70/eclair-core/src/main/resources/reference.conf#L22

I'm no dev and so I'm going purely by the fact that 18332 vs 8332 looks like a typo. Please disregard if I'm in error.

**Comment by sstone** [comment]
18332 is the correct RPC port on testnet. We use github strictly for technical issues, general questions are better asked on our [gitter](https://gitter.im/ACINQ/eclair)
