### ISSUE TITLE
Improper use of ZMQ opts

### ISSUE THREAD

**Issue by torkelrogstad** [ACINQ/eclair#796]
In a couple of places it's implied that `eclair.bitcoind.zmq` is a valid configuration option for Eclair. Looking at the code, I see that the only options that are actually read in [`Setup.scala`](https://github.com/ACINQ/eclair/blob/ff588b578fc3d047ad385207ab7ef117c5181d7d/eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala#L191) are `zmqblock` and `zmqtx`. 

Places I've found references to `eclair.bitcoind.zmq`: 
* [Wiki page](https://github.com/ACINQ/eclair/wiki/Configure) on config
* [`BitcoinCoreWalletSpec.scala`](https://github.com/ACINQ/eclair/blob/2de7c6b07d558b614cabf8c77f77d7aab5f607e4/eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoinCoreWalletSpec.scala)
* [`ExtendedBitcoinClientSpec.scala`](https://github.com/ACINQ/eclair//blob/master/eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/ExtendedBitcoinClientSpec.scala)
* [`BitcoinCoreFeeProvider.scala`](https://github.com/ACINQ/eclair//blob/master/eclair-core/src/test/scala/fr/acinq/eclair/blockchain/fee/BitcoinCoreFeeProviderSpec.scala)

**Comment by t-bast** [comment]
I just checked the wiki and readme, and this has been fixed.
Feel free to re-open if you spot an inconsistency.
