### ISSUE TITLE
Certain characters in the Bitcoin RPC password break eclair.

### ISSUE THREAD

**Issue by dscotese** [ACINQ/eclair#800]
Close eclair and your bitcoin node.
Change your Bitcoin rpc password by inserting a comma anywhere inside of it, both in the bitcoin.conf file and in eclair.conf.
Start your bitcoin node and wait for it to be fully synchronized.
Start eclair.
Note the message.

If Bitcoin is silently failing to honor my comma-containing password, then eclair should state that commas are not supported in the rpc password.  If bitcoin accepts the comma-containing password, then eclair should also accept it.

A message reporting that a comma may not follow the key 'X' where X is the string following the first comma in the rpc password.

100%.  See steps above.

0.2-beta8

Windows 10, I have not JDK, so the one eclair 0.2-beta8 provides.
 Nope

**Comment by araspitzu** [comment]
Can you reproduce the issue if you have your rpc password in eclair.conf enclosed in double quotes?

**Comment by araspitzu** [comment]
We use the typesafe config which uses the [HOCON syntax](https://github.com/lightbend/config/blob/master/HOCON.md) it does support commas in the fields but they have to be enclosed in double quotes.

**Comment by araspitzu** [comment]
PS: sure you can restart eclair without closing your existing channels.

**Comment by dscotese** [comment]
Since a comma-including password in the bitcoin.conf file does NOT break bitcoin core (granted, it's an implementation-specific detail, but it is the most widely accepted implementation of what is now known as "bitcoin"), perhaps a comment in the docs... Uhh... if there are any... explaining that bitcoin-core allows conf file settings that break HOCON parsers would be helpful.  Maybe eclair documentation exists somewhere and I can go update it.  Hmm...

**Comment by araspitzu** [comment]
I don't think we need to update the doc, if you look [here](https://github.com/ACINQ/eclair#configuring-eclair) we specifically say that 'Quotes are not required unless the value contains special characters' (like a comma) and in the reference configuration file we provide a dummy password *enclosed* in double quotes to clear any doubt.
