### ISSUE TITLE
Electrum: publishing funding transactions sometimes fails silently

### ISSUE THREAD

**Issue by sstone** [ACINQ/eclair#804]
In rare instances, when our Electrum wallet published a funding transaction, the Electrum server it is connected to replies that the transaction has been published correctly, but it has not: the transaction was not published, and the corresponding channel will remain stuck in `WAITING_FOR_FUNDING_CONFIRMED` state.

See https://github.com/ACINQ/eclair-mobile/issues/86 and #714

**Comment by redstorm1** [comment]
I am currently affected by this with opening a channel to the Eclair node., the funding TX has not been broadcast and does not show up in block explorer. 

Testnet. Eclair mobile 4.1

**Comment by pm47** [comment]
Following 70397962b6f5eee017d932c7d9124011e91f650f, the corresponding channel should eventually be cleaned up, instead of being stuck in state `CLOSING` forever. Can you confirm this is the case?

**Comment by t-bast** [comment]
Closing as #714 should have fixed this.
Feel free to re-open if needed.
