### ISSUE TITLE
stuck closing (two channels to same remote node)

### ISSUE THREAD

**Issue by Heebron** [ACINQ/eclair#812]
I have two channels open to the same remote node. Both have been stuck in the closing state for several days now.  Upon eclair startup, I see the following when grepping against the remote node ID:

> fgrep 028dbfccd6d1a77b8b87959efaaf7cfb3627d164ee693c27b24771e6e4c4e46c45 *.log
> 2019-01-08 05:59:48,807 INFO  f.a.e.channel.Channel  n:028dbfccd6d1a77b8b87959efaaf7cfb3627d164ee693c27b24771e6e4c4e46c45 c:0000000000000000000000000000000000000000000000000000000000000000 - restoring channel channelId=e7de2fb1abad61d675b3a231aa480332c32fb69c2f994d2beaabfa8f988175f2
> 2019-01-08 05:59:48,808 INFO  f.a.e.channel.Channel  n:028dbfccd6d1a77b8b87959efaaf7cfb3627d164ee693c27b24771e6e4c4e46c45 c:0000000000000000000000000000000000000000000000000000000000000000 - restoring channel channelId=aa5cd3bfac57fc7f1810fbb02caa1465904fe354a7d94b426e40cf81a2515a3e
> 2019-01-08 05:59:48,809 INFO  f.a.e.channel.Channel  n:028dbfccd6d1a77b8b87959efaaf7cfb3627d164ee693c27b24771e6e4c4e46c45 c:0000000000000000000000000000000000000000000000000000000000000000 - funding tx has already been spent and spending tx reached mindepth, no need to put back the watch-spent
> 2019-01-08 05:59:48,810 INFO  f.a.e.channel.Channel  n:028dbfccd6d1a77b8b87959efaaf7cfb3627d164ee693c27b24771e6e4c4e46c45 c:0000000000000000000000000000000000000000000000000000000000000000 - funding tx has already been spent and spending tx reached mindepth, no need to put back the watch-spent
> 2019-01-08 05:59:48,810 INFO  f.a.e.gui.GUIUpdater  - new channel: Actor[akka://eclair-node-gui/user/$j/switchboard/peer-028dbfccd6d1a77b8b87959efaaf7cfb3627d164ee693c27b24771e6e4c4e46c45/$b#1377035189]
> 2019-01-08 05:59:48,814 INFO  f.a.e.channel.Channel  n:028dbfccd6d1a77b8b87959efaaf7cfb3627d164ee693c27b24771e6e4c4e46c45 c:0000000000000000000000000000000000000000000000000000000000000000 - publishing txid=7978f0b9c550d96d4d844c516c12527c7510c16d0b86a5a099610030e219a950
> 2019-01-08 05:59:48,814 INFO  f.a.e.channel.Channel  n:028dbfccd6d1a77b8b87959efaaf7cfb3627d164ee693c27b24771e6e4c4e46c45 c:0000000000000000000000000000000000000000000000000000000000000000 - publishing txid=530ccdb593daa301193e5c11a6de6fb09e706e336927b0d59db99eca47adea31
> 2019-01-08 05:59:48,814 INFO  f.a.e.channel.Channel  n:028dbfccd6d1a77b8b87959efaaf7cfb3627d164ee693c27b24771e6e4c4e46c45 c:0000000000000000000000000000000000000000000000000000000000000000 - no need to republish txid=bf8872ce26c067130af825f2dc532ec15233e525cde2b451de75ff33f37993ab, it has already been confirmed
> 2019-01-08 05:59:48,815 INFO  f.a.e.channel.Channel  n:028dbfccd6d1a77b8b87959efaaf7cfb3627d164ee693c27b24771e6e4c4e46c45 c:0000000000000000000000000000000000000000000000000000000000000000 - no need to republish txid=8e7dee8057d1d2e5fdbe8fb6feaa1fd69262a7d9799dae80155402761b9dfbe8, it has already been confirmed
> 2019-01-08 05:59:48,817 INFO  f.a.e.channel.Channel  n:028dbfccd6d1a77b8b87959efaaf7cfb3627d164ee693c27b24771e6e4c4e46c45 c:0000000000000000000000000000000000000000000000000000000000000000 - no need to watch txid=bf8872ce26c067130af825f2dc532ec15233e525cde2b451de75ff33f37993ab, it has already been confirmed
> 2019-01-08 05:59:48,817 INFO  f.a.e.channel.Channel  n:028dbfccd6d1a77b8b87959efaaf7cfb3627d164ee693c27b24771e6e4c4e46c45 c:0000000000000000000000000000000000000000000000000000000000000000 - no need to watch txid=8e7dee8057d1d2e5fdbe8fb6feaa1fd69262a7d9799dae80155402761b9dfbe8, it has already been confirmed
> 2019-01-08 05:59:48,898 INFO  f.a.e.gui.GUIUpdater  - new channel: Actor[akka://eclair-node-gui/user/$j/switchboard/peer-028dbfccd6d1a77b8b87959efaaf7cfb3627d164ee693c27b24771e6e4c4e46c45/$a#-353394429]
> 

I see that two txs are published when eclair starts:
7978f0b9c550d96d4d844c516c12527c7510c16d0b86a5a099610030e219a950
530ccdb593daa301193e5c11a6de6fb09e706e336927b0d59db99eca47adea31

I am guessing that these are the transactions that need to be incorporated into the blockchain to finish the closing process. However, I do not see either of the transactions in the mempool (from blockchain) awaiting inclusion in a block. Is this because the fee is too low and blockchain is not picking up the transactions? Or, is there some other problem.

**Comment by pm47** [comment]
I see you greped on `028dbfccd6d1a77b8b87959efaaf7cfb3627d164ee693c27b24771e6e4c4e46c45`. Can you attach the whole log starting from "restoring channel", minus maybe the `Router` logs?

**Comment by t-bast** [comment]
We identified a bug months ago that resulted in what you were seeing.
This has been fixed in new releases so I'm closing this issue.
Feel free to re-open if you experience this issue with the latest release.
