### ISSUE TITLE
`FeeInsufficient` parsing failure

### ISSUE THREAD

**Issue by btcontract** [ACINQ/eclair#814]
This was discovered in BLW but when tested in Eclair the result is the same. When trying to send a payment with insufficient fees thought Bitrefill it responds with `FeeInsufficient` but it can't be parsed.

Here's a test:
```scala
test("FeeInsufficient from LND") {
    val error2 = BinaryData("6c875509763f988036d49b1cf82c8902f649b7fa37e7a04a9f873cca607aa833ab6be92551870eeb17154b6aff9c0ef3b1452b72509440e5abfe1934100faf784d23195c4c5ab0e569b1406015884b72a72f1031e4cc488beffc290cc567270f966a98d97ebab99d3f5dcc1c91db77fccce4a7112238ca8c2033f2ebed80978c5aa253cc20fc3ad5cbfe83af2d28cd7882ccd46418b22626dfb6377d6df90c63469932b221c0857ea17145649d4bee4181ee45ff753cb9d64224b1802c047b78da1de6d08fefc947e76b6d73a9093a5258c48d60b41f29bc583545bbb0470281a4000114352fd75218ce55b7ac0dcec77773ea90ec363e133865421a71162bbb3b564f1332ebb8752b7fbbddce04e1b134c0ccbb758a5f5dba1535d8c62640445ea87801")
    val secrets2: Seq[(BinaryData, PublicKey)] = Seq(
      (BinaryData("36e9162edf4fc284c8a31895ad4db1ce41120aa5458accff89e7976246d571c0"), PublicKey("030c3f19d742ca294a55c00376b3b355c3c90d61c6b6b39554dbc7ac19b141c14f")),
      (BinaryData("25384d3fec114e9fc6c74c979f7a350f08f7c36c8465997f434dfddc43c3cc5f"), PublicKey("03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f")),
      (BinaryData("ca998e8e96ffa6f0e9c759f24966b2fec6087578be01d50ccd42e0784fe0042e"), PublicKey("03e50492eab4107a773141bb419e107bda3de3d55652e6e1a41225f06a0bbf2d56")))
    assert(parseErrorPacket(error2, secrets2).isSuccess) // fails
  }
```

If I modify `FailureMessage.scala` the following way:

```scala
val channelUpdateChoice = choice(channelUpdateCodecWithType, channelUpdateCodec)
val channelUpdateWithLengthCodec = variableSizeBytes(uint16, channelUpdateChoice)

val failureMessageCodec = discriminated[FailureMessage].by(uint16)
    .typecase(PERM | 1, provide(InvalidRealm))
    .typecase(NODE | 2, provide(TemporaryNodeFailure))
    .typecase(PERM | 2, provide(PermanentNodeFailure))
    .typecase(PERM | NODE | 3, provide(RequiredNodeFeatureMissing))
    .typecase(BADONION | PERM | 4, sha256Codec.as[InvalidOnionVersion])
    .typecase(BADONION | PERM | 5, sha256Codec.as[InvalidOnionHmac])
    .typecase(BADONION | PERM | 6, sha256Codec.as[InvalidOnionKey])
    .typecase(UPDATE | 7, (("channelUpdate" | channelUpdateWithLengthCodec)).as[TemporaryChannelFailure])
    .typecase(PERM | 8, provide(PermanentChannelFailure))
    .typecase(PERM | 9, provide(RequiredChannelFeatureMissing))
    .typecase(PERM | 10, provide(UnknownNextPeer))
    .typecase(UPDATE | 11, (("amountMsat" | uint64) :: ("channelUpdate" | channelUpdateChoice)).as[AmountBelowMinimum])
    .typecase(UPDATE | 12, (("amountMsat" | uint64) :: ("channelUpdate" | channelUpdateChoice)).as[FeeInsufficient])
    .typecase(UPDATE | 13, (("expiry" | uint32) :: ("channelUpdate" | channelUpdateChoice)).as[IncorrectCltvExpiry])
    .typecase(UPDATE | 14, (("channelUpdate" | channelUpdateWithLengthCodec)).as[ExpiryTooSoon])
    .typecase(UPDATE | 20, (("messageFlags" | byte) :: ("channelFlags" | byte) :: ("channelUpdate" | channelUpdateChoice)).as[ChannelDisabled])
    .typecase(PERM | 15, provide(UnknownPaymentHash))
    .typecase(PERM | 16, provide(IncorrectPaymentAmount))
    .typecase(17, provide(FinalExpiryTooSoon))
    .typecase(18, (("expiry" | uint32)).as[FinalIncorrectCltvExpiry])
    .typecase(19, (("amountMsat" | uint64)).as[FinalIncorrectHtlcAmount])
    .typecase(21, provide(ExpiryTooFar))
```

then test above works (as well as all other tests). Basically I replace `channelUpdateWithLengthCodec` with `channelUpdateChoice` everywhere except `TemporaryChannelFailure` and `ExpiryTooSoon`.

Could be this happening due to `widenIntToLong` effects inside of `variableSizeBytes` codec?

**Comment by btcontract** [comment]
Update: changing codecs works in a sense that overall result is a `Success` but parsed `ChannelUpdate` values are wrong: `ChannelUpdate(3046022100fffd82d2c0ee5f9ad0e25c5c70706972a142c8db4638f44d263c5371e7cae9cc022100f67e02c94b79ce8478bed54fc697e81de291740e327547105eadb8bd810d955d01,0f726fe28c0ab6f1b372c1a6a246ae63f74f931e8365e15a089c68d619000000,8x2907x2907,23606,76, channelFlags = -28, cltvExpiryDelta = 0, htlcMinimumMsat = 40532396646334464, feeBaseMsat = 65536, feeProportionalMillionths = 65536000, htlcMaximumMsat = None)`

**Comment by btcontract** [comment]
Should I move this to LND?

**Comment by pm47** [comment]
Yes I think so

**Comment by Roasbeef** [comment]
When we encode, we don't have the type byte, as the length is more flexible. However, we _do_ [decode in a compatibility mode that tries to see if the type byte is there, and otherwise we parse it as normal](https://github.com/lightningnetwork/lnd/blob/master/lnwire/onion_error.go#L486).

**Comment by pm47** [comment]
@Roasbeef main issue isn't the type byte here, but the `length` which seems wrong.

**Comment by Roasbeef** [comment]
Ahh, I see what y'all mean now. Atm we use the "max accepted size for that message", which when accounting for the optional fields and padding, can be up to the main `brontide` message size. In our parsing we more or less ignore the length field, and instead just read the channel update as if it were on the wire, this is why it's gone unnoticed on our end. Will fix this! Thanks for the report!
