### ISSUE TITLE
Feature request: export data from any tab as CSV file.

### ISSUE THREAD

**Issue by dscotese** [ACINQ/eclair#816]
This is a feature request and the specification follows with some indication how important each item is:

1. Under Tools, add a new menu item, "Export as CSV."  This is how users access the feature, so it isn't that important.  It just seems like the right place.
2. When ExportAsCSV is invoked, the following happens:
2.1. A dialog pops up to ask for the _location_ of the CSV file (essential).  It could also allow the user to specify a filename (not recommended) or, even better, a prefix (recommended) for the filename.  If it specifies a prefix, then the rest of the filename could reflect the name of the tab, [PREFIX]local-channels.csv, [PREFIX]all-nodes.csv, [PREFIX]all-channels.csv, or [PREFIX]activity.csv.  I recommend that a filename NOT be entered by the user so that the filename will reflect the tab name.
2.2. The current tab (Local channels, All Nodes, All Channels, or Activity) is written out to the CSV file named as described in 2.1 with each element of the tab as a separate value (in quotes if necessary, or maybe ALWAYS in quotes).
2.3 The folder location for the target csv file is saved (maybe in the conf file?) so that it can be used as the default if the feature is used again. This is not that important, just handy, and nice.  The same goes for the prefix, if that part of the feature is implemented.

**Comment by t-bast** [comment]
Closing this issue as the demo UI has been deprecated in [v0.4](https://github.com/ACINQ/eclair/releases/tag/v0.4).
PRs to improve the demo UI are still accepted, but we won't track any feature requests.
