### ISSUE TITLE
Feature Request - Show channels in Relay tab

### ISSUE THREAD

**Issue by dscotese** [ACINQ/eclair#818]
It would be handy to see the "from" and "to" node IDs in the Relay section of the Activity tab.  This also rewards the node owner by showing that the nodes to which they connected were used, and may prompt them to open a channel (back to the "from" node) if they haven't already.  In the case where the "to" node is a service, it will encourage the node owner to explore that service.

**Comment by viaj3ro** [comment]
Yes please! and also in the received and sent tab!

**Comment by A-Force** [comment]
Yes, i feel that i would want to close the channels that don't relay often, and put that capital into areas where i see a lot of activity. But with the current Activity tab i only see that something happened, i have no idea which of my channels actually had the activity, and which of them have been idle for weeks.

**Comment by t-bast** [comment]
Closing this issue as the demo UI has been deprecated in [v0.4](https://github.com/ACINQ/eclair/releases/tag/v0.4).
PRs to improve the demo UI are still accepted, but we won't track any feature requests.
