### ISSUE TITLE
Feature request: show payment history in GUI even after a restart. At least optional.

### ISSUE THREAD

**Issue by viaj3ro** [ACINQ/eclair#824]
I really miss my payments history! Many others probably miss it as well. 

Logs are no help. At least as long as there is only one log for everything! Would be very helpful if there were 5 separate logs for sent, received, relayed, failed and everything else. Each in its own folder.

**Comment by n1bor** [comment]
You can get this using the audit api:
eclaic-cli -p password -a address audit
https://github.com/ACINQ/eclair/blob/master/eclair-core/eclair-cli

And should be easy to add to GUI (although have learnt any change to a GUI is never easy!) as data is now all there in the auditdb.

**Comment by pshep** [comment]
On top of this, can the fees be made decimal aligned? Changing the unit to Sats, or even mSats would also be helpful.

**Comment by t-bast** [comment]
Closing this issue as the demo UI has been deprecated in [v0.4](https://github.com/ACINQ/eclair/releases/tag/v0.4).
PRs to improve the demo UI are still accepted, but we won't track any feature requests.
