### ISSUE TITLE
BTC Core not running/fullysynched

### ISSUE THREAD

**Issue by STAWKEYE** [ACINQ/eclair#833]
If Eclair is started without BTC core running (or with it running but not yet fully synced) an error popup is displayed with only an option to CLOSE not just the popup, but Eclair entirely. This is often an issue if my PC is restarted, because I have BTC Core running on startup, as well as Eclair. I've added an arbitrary 20 minute delay to Eclair's startup, however for various reasons or connectivity issues this does not always work.

Ideally I propose Eclair to wait in a holding pattern automatically, closing the popup and loading independently whenever BTC Core is fully synced. I imagine the majority of LN Node operators have a hands-off approach and aren't always around to acknowledge the popup manually.

If this is not possible or desired, my second proposal is to just add a second button to the popup indicating that you've fixed the BTC Core issue and Eclair can continue loading instead of kicking out fully. [https://i.imgur.com/MWdl5MP.png]

**Comment by sstone** [comment]
Eclair will not work if it cannot connect to a bitcoin node, and it that node is not synchronized it will not work properly.  Stopping in that case is the sane thing to do (and I'm pretty sure that most apps that rely on Bitcoin Core, including LN nodes, will not start if Bitcoin Core is not running as well).
