### ISSUE TITLE
Eclair fails a payment on getting `FeeInsufficient` instead of retrying it with updated fees

### ISSUE THREAD

**Issue by btcontract** [ACINQ/eclair#839]
The same as https://github.com/lightningnetwork/lnd/issues/2540, details are here: https://github.com/btcontract/lnwallet/issues/123

This is tested on wallet `0.3.17` and node `0.2beta9`.

**Comment by btcontract** [comment]
Not sure whether this was considered before and if this is the reason `FeeInsufficient` is not retried currently, but routing node may advertise cheap fees yet send `FeeInsufficient` with much higher fees on actual payment attempt. If wallet blindly retries with new rates then user may overpay substantially on large amounts even with hard-coded fee limits in place.

**Comment by t-bast** [comment]
@btcontract is this still an issue? It feels to me that the current behavior should be to raise fees (unless we reach the configured limit) on such errors.

**Comment by t-bast** [comment]
Closing this issue, seems to be fixed. Feel free to re-open if needed.
