### ISSUE TITLE
beta 9 still not going direct route and having major issues sending transactions while relaying just fine

### ISSUE THREAD

**Issue by viaj3ro** [ACINQ/eclair#845]
was trying to pay an invoice from lightningconductor.net yesterday and even though my node is extremely well connected by now (~100 channels with mostly 0.1-0.16 BTC capacity each) I wasn't able to get the payment through. Gave up after 50-100 tries and opened a direct channel which was confirmed in block 560829 31.1.2019, 01:09:40 MEZ last night. Tried sending again this morning. Still no luck, just lot's of different error messages: https://imgur.com/a/7TIaxGh

After maybe 50 tries I gave up and gave it another shot just now. This time it went through but only on the third attempt, when my node finally selected the direct path. Logs: https://pastebin.com/YfwgW5EG

Meanwhile my node was relaying lots of transactions: https://imgur.com/a/sL84mJH

So it seems to be working fine. Any explanation why it's next to impossible to get a payment through without having a direct channel (besides routing and channel quality being really bad. But is it really that bad)? And anything I can do to make it select the direct channel if one exists already?

Btw, I still get this issue A LOT: #758

**Comment by araspitzu** [comment]
The beta9 includes some tweaks in the router that *randomize* the route selection, without any fear this happens over the 3 cheapest routes so you won't be overpaying. This explain why the direct channel was not selected in the first attempt and I'm afraid to tell you that you cannot disable the route randomization for the time being, it will be possible in the future releases. Still i don't fully understand why you're meeting such problems when sending funds, if you want further investigation please provide the full logs for an unsuccessful attempt (or series of attempt).

**Comment by viaj3ro** [comment]
OK, tried again. Exact same transaction to lightningconductor.net. Direct channel (560829x2056x1) is online but I can't get anything through. gave up after 30-50 attempts:

https://pastebin.com/SNU3ngES

**Comment by araspitzu** [comment]
So your difficulty in sending payments seems to be caused by a few factors:

- Poor routing causes to not always use a direct channel if there is one to the target.
- If the payment fails with a failure in the target node and the error type is NOT permanent eclair SHOULD retry, note that this is suggested by the [spec](https://github.com/lightningnetwork/lightning-rfc/blob/master/04-onion-routing.md#failure-messages) since `final_incorrect_cltv_expiry` is transient. 

Other factors include the possibility that your node is slightly out of sync OR some node along the route still has bug https://github.com/lightningnetwork/lnd/issues/2227. I'll follow up on the first two issues and hopefully the situation improves!

**Comment by kravens** [comment]
I'm having a similar issue, have a direct connection with the receiver, but still get a remote channel error?
5 attempts:
- (remote) channel 560526x1783x0 is currently unavailable
- (remote) channel 549618x485x0 is currently unavailable
- (remote) channel 556928x172x1 is currently unavailable
- (remote) channel 556924x1195x1 is currently unavailable
- (remote) processing node does not know the next peer in the route

**Comment by araspitzu** [comment]
Alright now with #850 you will always select the direct channel if there is one, #851 instead makes the randomization optional so it's deterministic and easier to debug. I'm still not sure how to fix #847 as this issue arise when sender and receiver are out-of-sync (don't agree on what is the latest block), automatically retrying is not going to fix the issue and i would expect the payment to fail again.
