### ISSUE TITLE
Eclair fails the payment even if the error it receives is non permanent

### ISSUE THREAD

**Issue by araspitzu** [ACINQ/eclair#847]
When issuing a payment the nodes along the route can return us errors, in case we receive a `final_incorrect_cltv_expiry` we should retry (the error is defined non permanent by the [spec](https://github.com/lightningnetwork/lightning-rfc/blob/master/04-onion-routing.md#failure-messages)) . Instead eclair fails the payment with no additional retries.

**Comment by t-bast** [comment]
We are now retrying (up to `maxAttempts`) in case of `final_incorrect_cltv_expiry` or `final_incorrect_payment_amount`, I think this is enough so closing for now.
