### ISSUE TITLE
Node 1 (and 2) Base Fee is not sorted as a number.

### ISSUE THREAD

**Issue by dscotese** [ACINQ/eclair#849]
In the [All Channels] tab, you can click the column headers to sort by that column.  When you do this for Node 1 Base Fee, the item 0.00000006958 is between 0.00000005 and 0.00000006 even though it's larger than both.  It should NOT be between them in any case.

The same problem occurs for Node 2 Base Fee, where 0.000000004 is between 0.000000005 and 0.0000000049, even though it's smaller than both.

I expect 0.00000006 to be between the other two whenever the last column header clicked is "Node 1 Base Fee."

As described above:
![image](https://user-images.githubusercontent.com/1767796/52171237-3a246580-270e-11e9-950b-678dc20b07de.png)

This issue can be reproduced with perfect reliability.

It's v0.2-beta9.

Windows 10, and I believe eclair on Windows uses its own JDK.  If not, I'm not sure how to tell.  You should put a text block in the About box to be copied into issues to answer this question (and possibly some other?)

The sorting is consistent, but it's also wrong.  I don't really understand what's wrong with it.  Under Node 1 Base fee, 6958 is between what is effectively 5000 and 6000 (I'm guessing that this is because these latter two don't have the three trailing zeroes), but under Node 2 Base Fee, what is 40 (without the trailing zero) is between 50 (without a trailing zero) and 49.

eclair.chain=mainnet
eclair.bitcoind.rpcport=8332
eclair.bitcoind.rpcuser=notplato
eclair.bitcoind.rpcpassword=
eclair.node-alias="Scotese Lightning node"
eclair.node-color=d818f0
eclair.fee-base-msat=3
eclair.fee-proportional-millionths=1
eclair.server.public-ips.0=76.174.129.203

**Comment by t-bast** [comment]
Closing this issue as the demo UI has been deprecated in [v0.4](https://github.com/ACINQ/eclair/releases/tag/v0.4).
PRs to improve the demo UI are still accepted, but we won't track any feature requests.
