### ISSUE TITLE
Payment successful, but used same channel twice: channels=561997x807x1->553315x816x0->553315x816x0->556630x1706x0->561177x842x1

### ISSUE THREAD

**Issue by viaj3ro** [ACINQ/eclair#855]
So the payment was successful on the first attempt but going back and forth through the same channel doesn't seem to make too much sense:

561997x807x1->553315x816x0->553315x816x0->556630x1706x0->561177x842x1

second and third payment went this route but first failed, second worked:
561997x807x1->553315x816x0->553314x374x0

fourth one successfully went this way again:
561997x807x1->553315x816x0->553315x816x0->556630x1706x0->561177x842x1

Not really an issue, since the payment was successful but the algo should probably not aim for such a complicated route.

full logs: https://pastebin.com/jTnMn8C5

**Comment by sstone** [comment]
Closed by #857
