### ISSUE TITLE
Mismatch in configuration key

### ISSUE THREAD

**Issue by pm47** [ACINQ/eclair#858]
In reference.conf we have `eclair.router.path-finding.max-fee-pct`
In NodeParam.scala: `router.path-finding.route-max-fee-pct`
In IntegrationSpec: `eclair.router.path-finding.route-max-fee-pct` (not sure why we needed to override the value here?)

**Comment by n1bor** [comment]
Arh - was wondering why I was getting:
fatal error: No configuration setting found for key 'router.path-finding.route-max-fee-pct'
errors - was thinking my config could not find the reference.conf!
Now I notice the miss-match!

**Comment by araspitzu** [comment]
This has slipped in the code through 4291bef, I'll make a fix asap. It also introduced a backward incompatible change in the conf @n1bor .

**Comment by pm47** [comment]
Fixed with 94c1c36252c0869f453aaf9f822cb77dc8ae9850
