### ISSUE TITLE
Eclair forcibly closed channels keep in "CLOSING" state after few days

### ISSUE THREAD

**Issue by LordWigo** [ACINQ/eclair#859]
I have closed two channels. One was opened and funded about a month ago but offline because NODE on other side went offline and send request from other NODE to my NODE. I was closing this request as well so the second node in "CLOSING" state was never funded.
However as you can see on attachment after few days and restarts Eclair/BTC core is not able to close those channels and assign funds back from the first channel which was funded over one month.

OS Windows 2016
Eclair is v0.2-Beta9 (when problem starts it was Beta8)
Bitcoin Core is v0.17.1 (64 bit)

Latest Eclair log:  https://pastebin.com/embed_iframe/5nwgWnuY

Bitcoin.conf:
server=1
txindex=1
addresstype=p2sh-segwit
deprecatedrpc=signrawtransaction
rpcuser=xxxxxxx
rpcpassword=xxxxxx
zmqpubrawblock=tcp://127.0.0.1:29000
zmqpubrawtx=tcp://127.0.0.1:29000

Eclair.conf:
eclair.chain=mainnet
eclair.server.public-ips = ["178.143.xx.xxx"]
eclair.server.port=9735
eclair.bitcoind.rpcport=8332
eclair.bitcoind.rpcuser=xxxxx
eclair.bitcoind.rpcpassword=xxxxx
eclair.node-alias=xxxxx

Open new channels is not issue.
I need to get back assigned funds, remove CLOSING channels and open new channels.

Thank you

![image](https://user-images.githubusercontent.com/45817801/52621381-6aef6200-2ea7-11e9-9b2b-aa67c741ec15.png)

**Comment by pm47** [comment]
This is probably normal, it depends what the refund timeout is (can be up to two weeks).

This info isn't yet available in the gui, so if you wish to know for sure, you need to enable the api and use the `channel` calls.

**Comment by LordWigo** [comment]
Is there any guide to help me enable API and check it?

**Comment by LordWigo** [comment]
OK transaction has been now closed...It can take up to one week until transaction is CLOSED :-O

**Comment by pm47** [comment]
The refund delay is also the time that you have to react in case of cheating attempts. With that in mind, 7 days is quite reasonable (actually, the delay *you* have to wait is to give time to your counterparty in case you try to cheat, but you get the point).

Note that there is no delay for cooperative closes.
