### ISSUE TITLE
Backup feature design

### ISSUE THREAD

**Issue by dscotese** [ACINQ/eclair#865]
There is currently no backup function.  Backups can cause problems if the node performs certain functions after a backup and before the previously backed-up state is restored.  It seems that a useful implementation of backup would be to allow the user to specify a second location (could even be a remote server, perhaps over http or whatever) where all writes to the eclair.sqlite DB would also be written, as soon as they are finished being written to the local file.

The simple implementation says: "This backup feature places a realtime copy of the database of your channels and their states into a second location so that if the storage device for your ~/.eclair folder gets corrupted, you can safely restore the back to a replacement device.  We recommend that you have a separate disk drive or other storage device available and enter a path to it for the backup here: ____________"

Then it runs two eclair.sqlite databases.

**Comment by kravens** [comment]
I've succesfully recovered my node by copying the databases from .eclair dir (actually the entire .eclair folder) from a crashed OS disc to a fresh installed OS. 
So you could use something like https://owncloud.org/, where you add the .eclair dir to be synced to your self managed cloud backup.

**Comment by pm47** [comment]
The proper way to backup eclair is indeed to copy `.eclair` dir (actually `seed.dat` and `eclair.sqlite`), but this suffers from some corner cases and needs to be improved. Not saying that we should do exactly what @dscotese is proposing, but there is indeed room for improvement.

**Comment by t-bast** [comment]
Closing this issue; the current backup mechanism is enough for most nodes, and the coming postgresql support will provide a more enterprise-y backup mechanism.
