### ISSUE TITLE
eclair shutting itself down for no reason

### ISSUE THREAD

**Issue by viaj3ro** [ACINQ/eclair#866]
Don't know if it's crashing or whatever, but it's the second time it wasn't running anymore when I checked on it. 

Logs: https://pastebin.com/W5LVN4Tb

**Comment by araspitzu** [comment]
The error is quite clear here: **GC overhead limit exceeded**, citing the official java doc on that: "This exception is typically thrown because the amount of live data barely fits into the Java heap having little free space for new allocations". To put it simply either there is a memory leak in eclair or your host doesn't have enough resources. What are the spec of your machine? Which version of java are you running? Which version of eclair?

**Comment by viaj3ro** [comment]
I was running the node on a Core i5 M520@2.4GHz with 4GB RAM with 8GB fixed size swap file on a Crucial MX500

eclair v0.2 beta 9
No java

after it crashed again 2 days ago (can't find that one in the logs anymore), I tried fetching the network db from scratch again and decided to just give it as much time as it needs. Didn't end well either unfortunately:  https://pastebin.com/U15mc8MP

**Comment by n1bor** [comment]
I am running on a 4Gig AWS vm. And I think it is having issues with 1Gig of RAM - this is the default (1/4 of physical) unless you set -Xmx=2G or similar.
But not sure if my issues were due to a patch I was running that added some monitoring.
Also have 280 channels which uses more RAM.

**Comment by viaj3ro** [comment]
How exactly can I give eclair more RAM?

couldn't find anything here: https://github.com/ACINQ/eclair/blob/master/eclair-core/src/main/resources/reference.conf

**Comment by araspitzu** [comment]
Do you still have issues with running eclair? Note that if you're running the '.exe' for windows you use an embedded version of java, JRE8. The specs you mentioned should be well enough to run eclair.

**Comment by viaj3ro** [comment]
no more crashes since I'm below 125 channels.

**Comment by pm47** [comment]
> How exactly can I give eclair more RAM?

This is not a support forum but an issue tracker, a simple look at the logs and a google search would easily have given you an answer. Again please respect the developer's time and do a minimum of work on your side. At least post see first on gitter if someone can help.
