### ISSUE TITLE
accidentally but successfully paid an invoice twice 

### ISSUE THREAD

**Issue by viaj3ro** [ACINQ/eclair#869]
same issue as #777

in my case it was a copy paste mistake and only 6300 sats but still, this shouldn't be possible.

logs: https://pastebin.com/7ijR6737

**Comment by araspitzu** [comment]
Please don't open issues twice for the same problem, #777 is already clear enough.

**Comment by viaj3ro** [comment]
well, it seemed like nobody paid attention to issue #777 since it was just hearsay without logs and anything. Does replying to an old issue get it back on the radar? Thought it wouldn't...

**Comment by pm47** [comment]
@viaj3ro the only thing that opening duplicate issues will lead to is you getting banned from posting. Please respect the maintainer's time.

**Comment by viaj3ro** [comment]
my apologies. didn't mean to steal anyones time. still very much new to all things github and simply thought it's an important/severe bug since it can quickly lead to significant amounts of money lost.
