### ISSUE TITLE
Feature request: optional confirmation prompt when closing eclair

### ISSUE THREAD

**Issue by viaj3ro** [ACINQ/eclair#870]
I know, many programs use this annoyingly but in eclairs case it would really be useful. Could just include a "Don't ask again" checkbox, so anyone who doesn't want it can instantly disable it. 

Or have it turned off by default and only provide the option via settings or config.

**Comment by pshep** [comment]
Would be nice to minimise to notification area too, like bitcoin core.

**Comment by pm47** [comment]
@dpad85 should we do this? Eclair GUI will start much faster with the next release, which is I believe the real issue there.

**Comment by viaj3ro** [comment]
faster starting GUI certainly helps. But the issue is also the missing transaction & relay history and the missing labels after restart. Optimal would be neither of those gets lost due to restart. Then the confirmation prompt would be a bonus but still helpful.

**Comment by t-bast** [comment]
Closing this issue as the demo UI has been deprecated in [v0.4](https://github.com/ACINQ/eclair/releases/tag/v0.4).
PRs to improve the demo UI are still accepted, but we won't track any feature requests.
