### ISSUE TITLE
Eclair on VM (Azure)

### ISSUE THREAD

**Issue by Marcolry** [ACINQ/eclair#878]
Hi,

I opened 3 channels stated WAIT_FOR_FUNDING_CONFIRMED for more than 24 hours now.
I'm on a D8v3 on Azure, with Bitcore 0.17 and ACINQ 0.8

=> I can't add simple connection nor channel. I'm alone on my node, I can't see the other nodes, and can't be seen on 1ml...

What is the issue? Everything worked until I made a Simple Connection or Opened Channel.

Thanks

**Comment by pm47** [comment]
What is the funding txid of those channels?

**Comment by pm47** [comment]
Actually, closing this. Please read the issue template before posting:

> Please do not open issues for support requests or questions about Lightning or Eclair: use our gitter at https://gitter.im/ACINQ/eclair instead.
Please check that there is not already a similar issue before opening a new one.

**Comment by Marcolry** [comment]
F txid : ffa5b52ce7545bcda07409f30ab2f828feac3087a56a1870559bdb882e6a5e5f

Log for the simple connection : 
Validation failure for shortChannelId=8807300036c0000 reason=No such mempool transaction. 

Blockchain transactions are still in the process of being indexed. Use gettransaction for wallet transactions. (code: -5)
