### ISSUE TITLE
Force Close

### ISSUE THREAD

**Issue by tritonrec** [ACINQ/eclair#880]
Good day. I had a problem with the return of funds when closing the node. After the node was created, the money was immediately written off, but even after a day, it was still not open. Since after a day the node did not start, I clicked force close. Two days have passed, but the money has not returned to the account. Please, tell me how to deal with this problem? What can I do to solve it?
If you need additional data, tell me what and I will provide them.

**Comment by pm47** [comment]
The way bitcoin works there is no guarantee when your funding tx will confirm, depending on the mempool. Force closing implies a delay before funds get returned to your wallet, which may be anywhere up to 2 week depending on what node you are connected to.

Also this is not the place for support, please go to our https://gitter.im/ACINQ/eclair instead.
