### ISSUE TITLE
send buffer overrun, closing connection

### ISSUE THREAD

**Issue by btcontract** [ACINQ/eclair#889]
I'm trying to connect to 3 different instances of Eclair (one of them is ACINQ), my client opens a connection with `localFeatures = "0a"` (full initial routing sync) and awaits for incoming messages. Instead of sending gossip remote peer closes a connection, when looking at remote peer log I see these messages: 

> 2019-03-10 09:26:40,959 INFO  f.acinq.eclair.io.Server  - connected to /95.135.211.188:34802
> 2019-03-10 09:26:41,063 INFO  f.a.e.io.Authenticator  n:023c8da93bd1f673fd93af174dd094d66bab2c2d87ed88bf71935ee2532ad3cdca - connection authenticated with 023c8da93bd1f673fd93af174dd094d66bab2c2d87ed88bf71935ee2532ad3cdca@95.135.211.188:34802 direction=incoming
> 2019-03-10 09:26:41,149 INFO  fr.acinq.eclair.io.Peer  n:023c8da93bd1f673fd93af174dd094d66bab2c2d87ed88bf71935ee2532ad3cdca - 023c8da93bd1f673fd93af174dd094d66bab2c2d87ed88bf71935ee2532ad3cdca has features: initialRoutingSync=true channelRangeQueriesOptional=false channelRangeQueriesMandatory=false
> 2019-03-10 09:26:41,149 INFO  f.a.eclair.router.Router  - getting valid announcements for Actor[akka://eclair-node/user/$i/switchboard/peer-023c8da93bd1f673fd93af174dd094d66bab2c2d87ed88bf71935ee2532ad3cdca#1074654018]
> 2019-03-10 09:26:41,149 INFO  fr.acinq.eclair.io.Peer  n:023c8da93bd1f673fd93af174dd094d66bab2c2d87ed88bf71935ee2532ad3cdca - sending all announcements to 023c8da93bd1f673fd93af174dd094d66bab2c2d87ed88bf71935ee2532ad3cdca
> 2019-03-10 09:26:41,193 INFO  fr.acinq.eclair.io.Peer  n:023c8da93bd1f673fd93af174dd094d66bab2c2d87ed88bf71935ee2532ad3cdca - sent all announcements to 023c8da93bd1f673fd93af174dd094d66bab2c2d87ed88bf71935ee2532ad3cdca: channels=34393 updates=68303 nodes=3789
> 2019-03-10 09:26:58,108 INFO  fr.acinq.eclair.io.Peer  n:03e15ea0a606eb256353f89cad029a1e4cd6030bef156989bde36d7a161cf29699 - sent announcements to 03e15ea0a606eb256353f89cad029a1e4cd6030bef156989bde36d7a161cf29699: channels=0 updates=18 nodes=0
> 2019-03-10 09:26:58,108 INFO  fr.acinq.eclair.io.Peer  n:023c8da93bd1f673fd93af174dd094d66bab2c2d87ed88bf71935ee2532ad3cdca - sent announcements to 023c8da93bd1f673fd93af174dd094d66bab2c2d87ed88bf71935ee2532ad3cdca: channels=0 updates=18 nodes=0
> 2019-03-10 09:27:00,611 WARN  f.a.e.c.TransportHandler  n:023c8da93bd1f673fd93af174dd094d66bab2c2d87ed88bf71935ee2532ad3cdca - send buffer overrun, closing connection
> 2019-03-10 09:27:00,612 INFO  fr.acinq.eclair.io.Peer  n:023c8da93bd1f673fd93af174dd094d66bab2c2d87ed88bf71935ee2532ad3cdca - lost connection to 023c8da93bd1f673fd93af174dd094d66bab2c2d87ed88bf71935ee2532ad3cdca

This does not happen when I try to connect to LND based nodes.

**Comment by btcontract** [comment]
As a quick fix, raising `MAX_BUFFERED` to `200000L` does the job.

**Comment by pm47** [comment]
Indeed the number of `node_announcement`+`channel_announcement`+`channel_update` has recently become higher than `100000`, hence the issue. Not sure yet what the proper way to address this is; of course in thee meantime we could just increase the size of the buffer as a workaround.

**Comment by t-bast** [comment]
Closing this stale issue. Gossip management needs to be improved at the spec level, meanwhile bandwidth usage may indeed be an issue sometimes.
