### ISSUE TITLE
Java version crashes under Win10 32bit

### ISSUE THREAD

**Issue by velgard1** [ACINQ/eclair#891]
Hi,

I tried to get Eclair running for quite a while and since I haven't found my issue covered I decided to sign up on Github now...
 
I run an Intel Compute Stick with a 32bit Win10 and 2GB of RAM. It's only use is to run Bitcoin Core and Eclair and the system is clean besides that.
First I wanted to use the Windows installer for Eclair, but stangely it wouldn't run. I also could not install the recommended Java because itseems to be only availabe in 64bit and so I used the standard JRE from Oracle.

The issue is that as soon as I connect to the network it's running for about two days before crashing without any notification.
When I start it afterwards it will continue to run for some time and then crash again.

I found out that it will work again after deleting the file which contains all channels and nodes information, but this solution is quite unsatisfying.
Afterwards I tried to change some things in the Eclair config file, but it didn't help and since I found no good documentation if / what might be helpful I'm stuck now.

Would be great if someone has an helpful idea.

**Comment by araspitzu** [comment]
Hi, actually we don't support running eclair on windows 32 bits. Also 2GB for running both eclair and bitcoind is _barely_ enough, if you are willing to dig deeper you should look for the java-generated files from the crash (it's a different log than eclair.log) and if the error is due to memory problems then you should see something like `java.lang.OutOfMemoryError`.

**Comment by velgard1** [comment]
Hi, thanks for the tip. As a result I tied to increase the Java heap size from 256MB to 512MB (after checking the current situation with JDK) and the first look is quite promising - didn't crash over night and the CPU load seems to be lower.

**Comment by araspitzu** [comment]
Closing as this is not supported.

**Comment by velgard1** [comment]
For others that have the same issue:
At first it was only running longer, but still crashing from time to time.
Since version 0.3 it's running fine without parameters!
