### ISSUE TITLE
WAIT_FOR_FUNDING_CONFIRMED

### ISSUE THREAD

**Issue by DawBin** [ACINQ/eclair#892]
After my most recent of several tries I seem to be stuck in this state again: WAIT_FOR_FUNDING_CONFIRMED

The only available option is "force close".

1. Bitcoin node "up to date"
2. My ECLAIR LOG: 

https://www.dropbox.com/s/960yasuw7kro48c/eclair.log?dl=0

**Comment by pm47** [comment]
Not a proper bug description
