### ISSUE TITLE
Feature Request: Reread conf file using menu item.

### ISSUE THREAD

**Issue by dscotese** [ACINQ/eclair#897]
I have a SPV ("lite") lightning wallet on my mobile (Android). I wanted to open a channel to my desktop eclair node, but I got an error suggesting I need max-to-local-delay-blocks=2016 in my eclair.conf file, so I just added it, but I continue getting the same error. I shut down eclair and restarted it, and now I am able to create the channel.  Apparently, the `max-to-local-delay-blocks` setting can only be changed between restarts of eclair.

There may be some conf file settings that are used during initialization and therefore ought to be mentioned as NOT AFFECTED by this feature (should it be implemented).  If identifying that list of settings is too much work, please let me know and I'll consider working on it.

If I remember correctly, the settings `fee-base-msat` and `fee-proportional-millionths` can be updated on the fly, and new channels will use the new values.  As described above, this is not true for `max-to-local-delay-blocks` which means when you want to change it, you have to shut down, lose your history  of sends, receives, and relays, and then restart again.  Apparently, it defaults to 2000, so anyone who wants to make their node available to an SPV wallet - lite wallet standard is for the max delay to be 2016 - would have to change it.

**Comment by t-bast** [comment]
Closing this issue as the demo UI has been deprecated in [v0.4](https://github.com/ACINQ/eclair/releases/tag/v0.4).
PRs to improve the demo UI are still accepted, but we won't track any feature requests.
