### ISSUE TITLE
What does it mean for a node to be "enabled" with regard to a channel?

### ISSUE THREAD

**Issue by dscotese** [ACINQ/eclair#913]
I guess this is a documentation bug, but maybe it isn't...

On my "Channels" tab, I clicked the "Node 1" column header and I see my channels with nodes that have larger Pubkeys. Some of them have black arrows pointing both ways and some have a black arrow one way and a grey one the other way. This indicates whether or not each node is "enabled." How does eclair determine which nodes are enabled and which are not? Whatever it's doing is WEIRD because some of my channels say my node is enabled and some say it's disabled.

**Comment by sstone** [comment]
See https://github.com/ACINQ/eclair/wiki/FAQ#what-does-it-mean-for-a-channel-to-be-enabled-or-disabled-
