### ISSUE TITLE
LN wallet on LN full node: Receive failure

### ISSUE THREAD

**Issue by wdey** [ACINQ/eclair#937]
I can send from LN wallet on LN full node, but receive fails with "receiver not have not enough inbound capacity", which is not true.
Q. Does the LN wallet support recieve and send, or only send ?

**Comment by sstone** [comment]
We use github for technical issue only, which should be clear in the form that is displayed when you create an issue. For support/general questions please go to [gitter](https://gitter.im/ACINQ/eclair) instead and provide more details (including at least which version of which app you're using).
