### ISSUE TITLE
Unable to check if timed out sent payment was paid from new API.

### ISSUE THREAD

**Issue by n1bor** [ACINQ/eclair#939]
Looking at the new API I can check if a requested payment has been received.
But there is no way to check if a sent payment has actually timed out or payed the other node from the API.

Seem to be 3 options:
1) Add index on audit db so we can check if a payment request was paid.
2) Add state to the paymentInitiator (ideally db backed) like the LocalPaymentHandler has and let the API query that.
3) I could request from API with a very wide time window and filter through all the results - but that does not feel very efficient.

Which approach is preferred? If 1 or 2 will prepare a PR for it...

**Comment by araspitzu** [comment]
There is a work in progress PR #885 that allows a fine-grained [tracking](https://github.com/ACINQ/eclair/pull/885#issuecomment-478918386) of outgoing payments.
