### ISSUE TITLE
Windows version eclair-gui node (cli) command line

### ISSUE THREAD

**Issue by bitcoincelebi** [ACINQ/eclair#945]
Is there a way to use eclair-cli command line in windows?
I need it but can't find it

**Comment by dpad85** [comment]
Hello,

Yes it is possible. I've added a section in the wiki with instructions for Windows users, because there are a few things you'll have to install first.

https://github.com/ACINQ/eclair/wiki/Usage#windows-user

**Comment by dpad85** [comment]
Closing this issue.

Please note that for support you can join our Gitter chat [here](https://gitter.im/ACINQ/eclair).
