### ISSUE TITLE
[Suggestion] Identify Eclair to Electrum servers

### ISSUE THREAD

**Issue by whizz** [ACINQ/eclair#947]
Eclair connects to Electrum servers, but it identifies itself same as Electrum wallet as part of the server.version() RPC call here:
https://github.com/ACINQ/eclair/blob/288aa75305ba0004c63df00223b08c17c214ea02/eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumClient.scala#L338

 
Electrum already implemented a change, where it identifies itself as "electrum/$VERSION'. See https://github.com/spesmilo/electrum/issues/5246. 

I think eclair should also adopt this scheme and send 'eclair/$VERSION'.

**Comment by t-bast** [comment]
As mentioned in the issue you link, I think identifying ourselves as a normal electrum wallet is much better than explicitly saying we are an eclair node. We don't want servers filtering out requests because they're coming from lightning nodes.
