### ISSUE TITLE
JavaFX not found when running on OpenJDK 8

### ISSUE THREAD

**Issue by bitcoinamerica** [ACINQ/eclair#959]
Suddenly i'm getting this error: fatal error: javafx/application/Application
Not sure what changed on my system..
been trying all day to git it to work even rebuilt server from scratch

**Comment by bitcoinamerica** [comment]
still having the same problem
my server has been running for 4 month,s and i'm very familiar with how everything works. iv been running the latest versions of ubuntu-18.04.1-desktop-amd64, Bitcoin Core 0.17.1, and Eclair v0.2-beta9. java-8 & openjfx all this from a fresh install. but Eclair v0.2-beta9 opens with fatal error: javafx/application/Application
i only have openjdk-8-jre-headless & openjfx installed checking with java -version
bitcoin install fine and opens my node and .conf file as expected
i launch launch eclair from terminal or a .Desktop using 
java -Xmx1G -Declair.datadir=/mnt/SSD/eclair/data -jar /mnt/SSD/eclair/core/eclair-node-gui-0.2-beta9-eb0e45a.jar
all my files are in the correct location iv tride using no -Xmx1G and using the default datadir my removing the -Declair.datadir=
i run a PC with 
i3 processor dual 3.0h
8G of RAM
150G HDD for OS
1T SSD for blockchain and eclair Data

I NEED Help!!

**Comment by pm47** [comment]
As a temporary workaround, you can launch Eclair in headless mode since the
issue seems to be related to javafx. To do this use eclair-node*.jar
instead of eclair-node-gui*.jar.

**Comment by bitcoinamerica** [comment]
yes i was aware of headless mode and it dose work.
We just needed to know if this openJfx problem is on Your end or Our end.
From my understanding the Problem roots from Eclair
 I hope to see the Gui up and running again soon, its hard to teach friend and family & people who want "IN" on how to use a terminal. iv been using eclair in my OS build to give people a free and easy way to run and start there own node. check it out at https://bitcoinamerica.github.io/LNOS/

**Comment by sstone** [comment]
This is not a problem on our end, but a issue with all apps that use JavaFX which is included with Oracle JDK8, but not with OpenJDK 8.
The simplest fix is to reinstall Oracle JDK8, which is fine for personal use. 
Our next release will target JDK11 and will include JavaFX libraries.

**Comment by bitcoinamerica** [comment]
Reinstalling "Oracle" JDK8 can not be done
I found this problem
-Oracle Java (JDK) 8 Installer PPA (DISCONTINUED) 
-The Oracle JDK License has changed for releases starting April 16, 2019.
I mite be wrong on this but i thank we are stuck until  the eclair java11 release,
Unless your one of the lucky few that installed "Oracle JDK8" before April 16, 2019

**Comment by sstone** [comment]
Of course you can still install Oracle JDK 8. The warning you posted just means that the additional PPA you configured to get it is (temporarily ?) discontinued (see https://launchpad.net/~webupd8team/+archive/ubuntu/java). You can just get it directly from Oracle.
