### ISSUE TITLE
Dust limit in `makeRemoteTxs`

### ISSUE THREAD

**Issue by btcontract** [ACINQ/eclair#97]
I might be missing some tiny detail once again but it seems there's a bug here: https://github.com/ACINQ/eclair/blob/master/eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala#L493  

Instead of `localParams.dustLimitSatoshis` a `remoteParams.dustLimitSatoshis` should be used since otherwise there might be disparity in number of sent/received timeout and success transactions.  

Sending outgoing HTLC was resulting in "htlc sig count mismatch" error here: https://github.com/ACINQ/eclair/blob/master/eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala#L401 when my client had `dustLimitSatoshis = 100000` while Eclair had it set to 542. Changing `localParams` to `remoteParams` fixed an issue.

**Comment by pm47** [comment]
Nice catch! Sorry for the delay, I'll fix this asap
