### ISSUE TITLE
How to change "ChainHash mismatch"?

### ISSUE THREAD

**Issue by mraksoll4** [ACINQ/eclair#973]
![ddddddddddccc111](https://user-images.githubusercontent.com/32709596/56865537-0dfc4600-69d8-11e9-8767-4ebd719b8f3c.jpg)

i try to use eclair with litecoin , from where this setting calculate?
i reserch all code and there notting /and try find at google , there notting info how its work
i try dissable there but its not work.
![ec222211](https://user-images.githubusercontent.com/32709596/56865586-8236e980-69d8-11e9-9c46-318b7df1dffc.jpg)

**Comment by araspitzu** [comment]
Sorry but litecoin is not supported.

**Comment by mraksoll4** [comment]
i ask  where is the settings of genesis chain, i make it support , there is not differents , transaction logic the same.  I only cannot find this where is this , how it calculate.
