### ISSUE TITLE
Flapping Channels - is this the cause of 5k update per minute?

### ISSUE THREAD

**Issue by n1bor** [ACINQ/eclair#978]
My node is sending 5k Channel Update per minute.
On https://github.com/lightningnetwork/lightning-rfc/pull/584
@pm47 said this was due to flapping channels on my node.

Counting the number of ChannelReestablish messages today there are 639 (in and out).
I have 187 connected nodes so would expect this to have created 120k updates (one to each peer for each up). It is 8pm so that means over 20 hrs this averages out at 100 per minute (or 200 if one for down too?).

So this only accounts for 2-4% of the total number of update I sent.

So where do the other 96% come from?

I am tracking this here now:
https://lightningconductor.net/grafana/d/I_ji_ezZk/diagnostics?orgId=1&fullscreen&panelId=4&from=now-24h&to=now

**Comment by pm47** [comment]
I was assuming flapping channels could be the cause, I can be wrong.

How exactly do you get the number of created `channel_update`? Where in the code do you measure it?

**Comment by n1bor** [comment]
I am just using logstash/grok to parse the log fine for this string:

%{DATA:time} %{DATA:loglevel} %{GREEDYDATA:message} channels=%{NUMBER:channels} updates=%{NUMBER:updates} nodes=%{NUMBER:nodes}

And the updates is summed per minute.

Double checked by manually grep/awk out of log and match grafana.

This is an example of a row I am parsing in log.
20:53:18.539 INFO  akka://eclair-node/user/$k/switchboard/peer-02e9046555a9665145b0dbd7f135744598418df7d61d3660659641886ef1274844 fr.acinq.eclair.io.Peer - sent announcements to 02e9046555a9665145b0dbd7f135744598418df7d61d3660659641886ef1274844: channels=0 updates=33 nodes=0

**Comment by pm47** [comment]
> %{DATA:time} %{DATA:loglevel} %{GREEDYDATA:message} channels=%{NUMBER:channels} updates=%{NUMBER:updates} nodes=%{NUMBER:nodes}

Ok. Those are not updates *created* by your nodes, the vast majority  is updates from the network and *relayed* by your node. Also, you have to divide by the number of peers to get unique updates. So that's 30 updates per minutes which is about right. I mean it's very chatty (~1 update per channel per day) but that's what we observe on the network currently.
