### ISSUE TITLE
Eclair (v0.2-beta9) not compatible with Bitcoin Core v0.18

### ISSUE THREAD

**Issue by pshep** [ACINQ/eclair#979]
The following error message is displayed when opening a channel:

> signrawtransaction was removed in v0.18.
> Clients should transition to using signrawtransactionwithkey and signrawtransactionwithwallet (code: -32)

**Comment by vix184** [comment]
I have the same problem I went back to v0.17.1 while waiting

**Comment by viaj3ro** [comment]
add deprecatedrpc=signrawtransaction in bitcoin.conf

**Comment by vix184** [comment]
that's the problem ... deprecatedrpc=signrawtransaction does not work on version 0.18

**Comment by viaj3ro** [comment]
it works for me. just updated to v0.18 and eclair beta9 is running just fine

**Comment by vix184** [comment]
Yes it works, except when you try to open a channel ... Have you tried to open a channel since you switched to v0.18?

**Comment by sstone** [comment]
Eclair v0.2-beta9 will work with Bitcoin Core 0.16 and 0.17, but not with 0.18.
Starting with the next release, Eclair will work with 0.17 and 0.18 but not with older versions.
