### ISSUE TITLE
Route not found when sending thorugh "Moon"

### ISSUE THREAD

**Issue by SimoneAdt** [ACINQ/eclair#986]
I'm getting every time the same error "route not found" when trying to send through "Moon" extension node (02d23fa6794d8fd056c757f3c8f4877782138dafffedc831fc570cab572620dc61@54.224.118.176:9735).

How can i solve it? I'm new from LN and i think may i left something behind that i need to configure.

I have a Samsung Galaxy S7 with Oreo 8.1.

**Comment by sstone** [comment]
Wrong repository, you want https://github.com/ACINQ/eclair-mobile instead.
You will need to add mode details:

- which version of the mobile app are you using ?
- who are you trying to pay and how did you get the invoice ?
