### ISSUE TITLE
A question about the 'target' directory

### ISSUE THREAD

**Issue by trueptolemy** [ACINQ/eclair#993]
Hi!
When l read the code about [lightning-integration](https://github.com/cdecker/lightning-integration), I find this in `Makefile`:
`cp src/eclair/eclair-node/target/eclair-node-*-$(shell git --git-dir=src/eclair/.git rev-parse HEAD | cut -b 1-7).jar bin/eclair.jar`
I'm confused with the '`target`' directory...In fact, after `git clone`, I can't find it...
I konw I can put the .jar file into `bin` directly for lightning-integration, but the 'target' confused me...

**Comment by araspitzu** [comment]
The target directory is created by the build tool maven `mvn` and contains the output of the build process, which is the `.jar` artifact. In order to build eclair and "find" the target folder you can follow the instructions [here](https://github.com/ACINQ/eclair/blob/master/BUILD.md)

**Comment by trueptolemy** [comment]
@araspitzu  Thanks a lot!
