### ISSUE TITLE
Configuration File  

### ISSUE THREAD

**Issue by luvarado** [ACINQ/eclair#997]
I need an updated configuration file parameters to enter into eclair and bitcoin conf.   

I expected it to run like usual. 

![image](https://user-images.githubusercontent.com/25749489/57558015-c5cb1500-7341-11e9-9c98-3bac2e449a99.png)

I have tried every configuration that I could possibly find. Gitter could not supply a config, only older incompatible ones.   

 eclair-node-gui-0.3-a5debcd.jar

windows 10

Using Bitcoin Core V 0.18.0

**Comment by sstone** [comment]
We use github strictly for technical issues, please go to https://gitter.im/ACINQ/eclair for support and/or general questions.
