### ISSUE TITLE
Documentation, IP address change #471 #125

### ISSUE THREAD

**Issue by wdey** [ACINQ/eclair#999]
I understand that Eclair does not follow peer IP changes. ok fair, you just cut off a high % of users ; like myself.
After months where my node was happily running, IP changed, and everything is down.
Is there a **documentation / recipe**, how to fix that quickly, I am specially interested in Windows.
How can a software become enterprise class without coping with such a case.

**Comment by pm47** [comment]
Short answer: use tor, only advertise a tor address and only connect to other nodes using their tor address. It will solve your problem and is better for your privacy.

> I understand that Eclair does not follow peer IP changes.

It isn't quite as simple as that. When changing IP your ISP will disconnect/reconnect you and then for each peer, depending on who originally initiated the connection:
- if it was an outgoing connection: your node will reconnect automatically
- if it was an incoming connection: each of your peers will try to reconnect to your node using your previous IP and will fail. Problem is that (a) it isn't easy to trustlessly detect your new IP address, and (b) even if you advertise your new ip on the network it is up to the peer to use that new address.

I don't know about (a) but I think we should do (b) (even if that wouldn't change anything in your scenario).

> After months where my node was happily running, IP changed, and everything is down.

That would only be the case if all your connections were incoming. Maybe you are exaggerating a little bit? Anyway glad to hear that your node is super stable, didn't expect less :-)

> How can a software become enterprise class without coping with such a case.

Enterprise servers have static ips.

**Comment by wdey** [comment]
I had outgoing connections, but unfortunately upgraded btc core to 0.18.0. then I did a downgraded to 0.17.1. 
The fact that my IP address has changed can be seen, that with 1ml.com my LN node "wdey" misses IP address.
Since then I tried everything without luck to bring back Eclair, receiving always the same error message: could not bind to port 9735.

2019-05-11 22:17:22,389 INFO  a.e.slf4j.Slf4jLogger  - Slf4jLogger started
2019-05-11 22:17:22,416 INFO  fr.acinq.eclair.Setup  - hello!
2019-05-11 22:17:22,417 INFO  fr.acinq.eclair.Setup  - version=0.2-beta9 commit=eb0e45a8b127cb4d86580dfb649ac4c2b14e32a7
2019-05-11 22:17:22,419 INFO  fr.acinq.eclair.Setup  - datadir=C:\Users\wdey\.eclair
2019-05-11 22:17:22,555 INFO  o.b.Secp256k1Context  - couldn't find secp256k1 library, defaulting to spongycastle
2019-05-11 22:17:41,723 ERROR f.a.e.gui.FxPreloader  - fr.acinq.eclair.TCPBindException: could not bind to port 9735
	at fr.acinq.eclair.PortChecker$.checkAvailable(PortChecker.scala:36)
	at fr.acinq.eclair.Setup.<init>(Setup.scala:81)
	at fr.acinq.eclair.gui.FxApp$$anon$2.run(FxApp.scala:87)
	at java.lang.Thread.run(Thread.java:748)

With this configuration, the system was properly running 1 month !
 
eclair.conf

eclair.chain=mainnet
eclair.bitcoind.rpcport=8332
eclair.bitcoind.rpcuser=<uu>
eclair.bitcoind.rpcpassword=<pw>
eclair.node-alias=<wdey>

bitcoin.conf

server=1
txindex=1
addresstype=p2sh-segwit
deprecatedrpc=signrawtransaction
rpcuser=<uu>
rpcpassword=<pw>
rpcport=9735
zmqpubrawblock=tcp://127.0.0.1:29000
zmqpubrawtx=tcp://127.0.0.1:29000

Open TCP ports
Scanning 169.95.62.188.dynamic.wline.res.cust.swisscom.ch (188.62.95.169) [65535 ports]
Discovered open port 80/tcp on 188.62.95.169
Discovered open port 8883/tcp on 188.62.95.169
Discovered open port 9735/tcp on 188.62.95.169
Discovered open port 7547/tcp on 188.62.95.169

Any help / advice is appreciated !

PS. even Enterprise servers sometimes have to change their IP (the middle age of IBM apps with hard coded IP are history).

**Comment by pm47** [comment]
> The fact that my IP address has changed can be seen: 1ml my LN node "wdey" misses IP address.

That's not how it works. 1ML doesn't know your ip because you didn't advertise it. To do so you need to add this to your `eclair.conf`:
```
eclair.server.public-ips=["1.2.3.4"] // you can also enter a dynamic dns here but it will only be resolved at startup
``` 

> fr.acinq.eclair.TCPBindException: could not bind to port 9735

This indicates that you already have an instance of eclair running (or that another application is using port 9735). 

I would advise to:
1) find what application is using port 9735 and kill it
2) upgrade to bitcoin core 0.18
3) upgrade to eclair 0.3 (which is compatible with bitcoin core 0.18 and much faster than 0.2-beta9)

**Comment by wdey** [comment]
Thanks ! where can I find the Windows .exe for Eclair 0.3 ?

**Comment by pm47** [comment]
>  where can I find the Windows .exe for Eclair 0.3 ?

See https://github.com/ACINQ/eclair/wiki/Executable-Eclair-on-Windows.
